### ISSUE TITLE
'Your changes will not be saved' alert window when trying to reload a web page

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#16100] opened 2020-02-21 10:51 UTC
### Describe the bug
'Your changes will not be saved' alert window when trying to reload web page. The cause of this issue are https://github.com/eclipse/che-theia/pull/634 changes

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Start workspace from any devfile.
2. Try to reload web page.

### Expected behavior
The page was reloaded

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![screencast-che-eclipse-che 10 33 177 124 nip io-2020 02 21-12_34_51](https://user-images.githubusercontent.com/7760565/75027923-07c7e080-54a8-11ea-86c2-2fc8dae4e149.gif)

### Installation method
   - [ ] chectl 
   - [x] che-operator
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by rhopp** [comment] 2020-02-21 15:01
@SkorikSergey This is not a bug and the tests needs to be adapted, right?

**Comment by vzhukovskii** [comment] 2020-02-21 15:11
@rhopp yes, seems, that tests have to be aligned to the new behavior.

**Comment by vzhukovskii** [comment] 2020-02-21 15:14
@SkorikSergey another question, what other tests do you have, that fail and where do they exist?

As far as I saw, Happy Path scenario passed successfully:

<img width="815" alt="Configure application confirmExit to always as default by vzhukovskii · Pull Request #634 · eclipse:che-theia 2020-02-21 17-12-44" src="https://user-images.githubusercontent.com/1968177/75046345-91d67000-54cd-11ea-8e2c-40b034839345.png">

**Comment by SkorikSergey** [comment] 2020-02-21 15:16
HappyPath doesn't reload page.

**Comment by rhopp** [comment] 2020-02-21 15:17
@vzhukovskii This failure is happenig in the legacy java-selenium suite. 
We still have some tests there... They run as PR check on eclipse/che repo and right now, they are kind of "hidden" - We have a task in the current sprint to improve the reporting from this job.

**Comment by SkorikSergey** [comment] 2020-02-21 15:22
This issue (https://github.com/eclipse/che/issues/13580) is about closing only terminal tab not browser tab. For now if type Ctrl + w in terminal and click `Leave` button browser tab will be closed.

**Comment by vzhukovskii** [comment] 2020-02-21 15:28
Theia handles `Cmd/Ctrl+W` only for tab close, we can't modify this behavior for handling only some part, e.g. terminal tab, or editor tab. We just can intercept this hotkey and prevent browser tab closing.  (As this hotkey is reserved in browsers). So that's why there was added overridden configuration item to preferences that asks user whether he wants to close tab or not.

**Comment by rhopp** [comment] 2020-02-24 14:59
IMHO this behavior change is "UX downgrade". In my opinion, the confirmation should appear only when data loss is at place (aka. some editor is not saved).

Anyway... Until this gets sorted, @SkorikSergey we can put back the previous behavior by setting this in user preferences before actually running the test (the same way, that @Ohrimenko1988 is doing this for example for setting the terminal type to `dom`)

**Comment by Katka92** [comment] 2020-02-25 09:41
This issue is a root cause of failures for nightly tests with the nightly image. I assume @SkorikSergey is fixing that in Java tests, so I will do that for typescript ones.

**Comment by amisevsk** [comment] 2020-02-25 21:13
@rhopp As a user of Che, "ctrl-w to close your whole IDE" was maybe my least favorite thing about Theia :). When typing in a terminal, ctrl-w is one of the hardest habits to break.

**Closed as completed** 2020-03-02 14:10 UTC
Labels: kind/bug, severity/P1, area/qe
