### ISSUE TITLE
Allow "memoryRequest" property in dockerimage components of the devfile

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#17540] opened 2020-07-31 08:56 UTC
### Is your enhancement related to a problem? Please describe.
`memoryLimit` is recently added into plugins and K8S/OS components, but missing for dockerimage type components in the devfile. Need to allow it there as well.

![image](https://user-images.githubusercontent.com/1651062/89018668-e1468500-d324-11ea-8ac7-a26bc8896495.png)

**Comment by sunix** [comment] 2020-09-10 15:56
@l0rd ok to move that one to p1 ?
In some kubernetes installation (in my case GCP), scheduling a pod in a node is based on memoryRequest and not memoryLimit. The problem is when user is consuming memory in a pod, for instance Quarkus native compilation and that memory goes above the node memory capacity ... kubernetes will reschedule it ... the workspace is being restarted and the compilation task is interrupted.
User needs to provide proper memoryRequest value to a container (or workspace?) so that GCP could reschedule it in a node where it has enough resources available and avoid issue.

**Comment by sparkoo** [comment] 2020-12-11 12:12
fixed by https://github.com/eclipse/che/pull/18592

**Closed as completed by sparkoo** 2020-12-11 12:12 UTC
Labels: kind/enhancement, severity/P2
