### ISSUE TITLE
504 error in console log for https://static.developers.redhat.com/che/theia_artifacts/che.ef3d47205e5a211a8f1d.js

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#14040] opened 2019-07-26 09:48 UTC
### Describe the bug

when starting a workspace, there is this error in log:

```
cdn-support.ab201a793446d0881e74.js:1 HEAD https://static.developers.redhat.com/che/theia_artifacts/che.ef3d47205e5a211a8f1d.js 504
url @ cdn-support.ab201a793446d0881e74.js:1
(anonymous) @ cdn-support.ab201a793446d0881e74.js:1
buildScripts @ cdn-support.ab201a793446d0881e74.js:1
(anonymous) @ ?uid=385034:9
```

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

Che-Theia@4ef1d89 using Theia@4ef1d89

### Steps to reproduce

Start a workspace

### Expected behavior

no error in console log.
Either there shouldn't be ac all to this resource in this case or the request should be in success

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

noticed no functional issue

**Comment by rhopp** [comment] 2019-07-26 14:19
@apupier Yeah.. I've noticed this error also today. But to my knowledge, this is not affecting functionality, right?
Triaging as 7.x. If you disagree, please speak up ;-)

**Comment by rhopp** [comment] 2019-07-26 14:24
Reevaluating my triage result ;-)
Seems we have 3 open issues with common denominator. 
I'll close this one as a duplicate of https://github.com/eclipse/che/issues/14039

**Closed as completed** 2019-07-26 14:24 UTC
Labels: kind/bug, severity/P2, status/duplicate
