### ISSUE TITLE
Cannot start workspace with Openshift storage class mode with WaitForFirstConsumer value

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#14670] opened 2019-09-26 09:52 UTC
### Describe the bug
When default **StorageClass** is configured to have `volumeBindingMode` set to `WaitForFirstConsumer`, workspaces do not start. 

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Consume a factory by "https://[your path to Che]f?url=https://raw.githubusercontent.com/redhat-developer-demos/guru-night/master/quarkus-tutorial/devfile.yaml url".

### Expected behavior
The factory consumed properly with creation a workspace.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift 4.1.16 (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![screenshot-Wait_loading_workspace_and_get_time](https://user-images.githubusercontent.com/7760565/65678532-25f5f580-e05c-11e9-97d0-f5a0eaea274d.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
Codeready issue - https://issues.jboss.org/browse/CRW-294.

**Comment by sleshchenko** [comment] 2019-09-26 10:41
Just to extend context a bit: previously it used to work, but after some upgrading of OpenShift version, OS starts to propagate events with `FailedScheduling` if `WaitForFirstConsumer` is used. The second workspace start - works just fine and If Che would wait a couple of seconds - PVC would be mounted successfully. 
So, the easiest solution here is to remove `FailedScheduling` from the [default unrecoverable events list](https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L409).
It was initially added for some issue on OSIO, so if we just remove it - some workspaces may exceed workspace timeout instead of early failure.
Maybe OSIO case should be investigated more and event message should be concreted instead of catching all `FailedScheduling`, like `FailedScheduling: no available node is found`(<-just an example)

cc @ibuziuk

**Comment by tsmaeder** [comment] 2019-09-26 14:04
@SkorikSergey not quite sure how to classify this: is "waitForFirstUser" something we need? Or can we just declare that an invalid configuration for Che?

**Comment by dmytro-ndp** [comment] 2019-09-26 14:22
@tsmaeder: `WaitForFirstConsumer` is the mode of StorageClass of OpenShift, not Che itself.
Che can only work around such a mode - don't fail start of workspace immediately, but wait for PV be ready to use carefully.

**Comment by tsmaeder** [comment] 2019-09-27 07:18
@dmytro-ndp that is not the question: can we document that "WaitForFirstConsumer" is not a supported setting for running Che, or do we need to support this setting?

**Comment by dmytro-ndp** [comment] 2019-09-27 07:23
"WaitForFirstConsumer" is default setting of OpenShift 4.x on AWS. Looks like it's usual mode for instances on AWS, Azure, ... So we need to support it.

**Comment by sleshchenko** [comment] 2019-11-01 09:24
Can not reproduce on OpenShift 4.2. Seems there was an issue in OpenShift4.0, OpenShift4.1. Closing this issue as not actual.
Feel free to reopen it or create a new one if the same behavior happens on OpenShift greater than 4.2

**Closed as completed by sleshchenko** 2019-11-01 09:24 UTC
Labels: kind/bug, severity/P1
