### ISSUE TITLE
Language server's hover dublication after stop/start of workspace

### ISSUE THREAD

**Issue by gorshkov-leonid** [eclipse-che/che#10406] opened 2018-07-12 15:28 UTC
### Description and reproduce steps
1) create php project 
2) create php file
3) cause hover message
AR=ER: some hover
3) stop workspace in separate tab
4) start workspace in tab with opened project (baluun at the top of page)
5) cause hover message
ER: same hover 
AR: hover is dublicated

**Che Version:**    
6.6.0

![duplex_hover](https://user-images.githubusercontent.com/2270831/42643253-c03c95b2-8609-11e8-80e6-cfaf3ad8f087.gif)

**Comment by eivantsov** [comment] 2018-07-13 05:35
@gorshkov-leonid thanks for reporting it. However, I will close it as a duplicate of https://github.com/eclipse/che/issues/10065

**Closed as completed by eivantsov** 2018-07-13 05:35 UTC
Labels: kind/question
