### ISSUE TITLE
Access to workspace freezes when loading moderately big maven project

### ISSUE THREAD

**Issue by KakashiMamun** [eclipse-che/che#3115] opened 2016-11-18 02:59 UTC
[Access to workspace freeze when loading moderately big maven project]

**Reproduction Steps:**

1. Create a workspace with Java-maven stack.
2.Import medium or big java maven project with several module and module inside module.
3.While connected to the workspace try to connect with incognito window/another pc in the same network.

**Expected behavior:**
Should connect to the worksapce and being able to modify code.

[Describe expected behavior here]
When 2nd or 3rd person connects to the workspace he/she should be able to load the page and open file to edit. 

**Observed behavior:**
Page starts "Reading project structure..." and freezes.
[Describe observed behavior here]
When second or 3rd person logs in the page stops responding. Even starts lagging for the 1st person also. 

**Che version:**    [5.0.0-M5]   
**OS and version:** [Ubuntu 14.04]   
**Docker version:** [1.12.3]   
**Che install:**    [Docker container, codenvy/che-server:latest but local assembly. built on 5.0.0-M5]   

**Additional information:**
The issue occurs only for maven project. other types of project shows "Reading project structure.." but doesn't freeze. only incase of maven and medium or big project it freezes.

* Problem started happening recently, didn't happen in an older version of Che: [Yes/No]
I haven't tested older versions. 
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
Every time. may be some time it freeze for 30s-1min... sometimes for 20mins

**Comment by TylerJewell** [comment] 2016-11-18 03:21
Can you try upgrading to M7?  We had some issues that affected performance due to our file system watchers that I believe were solved in m7.  This issue sounds similar to that.

**Comment by KakashiMamun** [comment] 2016-11-18 03:27
M7 has new config for docker launcher right ? I couldn't find the new config. i tried M7 and codenvy/che-server failed. can you help me finding the right setting for M7 codenvy/che-server

**Comment by TylerJewell** [comment] 2016-11-18 03:32
This is the latest syntax.
https://eclipse-che.readme.io/docs/usage-docker-server

**Comment by KakashiMamun** [comment] 2016-11-18 03:33
thanks

**Comment by patricknazar** [comment] 2016-12-13 07:53
I experience this issue too using M8. It's hard to reproduce, it just seems to be a constant thing that prevents me from doing any real work... sadly :( I am using boot2docker with Virtualbox on windows if that helps. I notice it happens a lot during npm install/composer install/bower install/possibly .git file changes. How does the system react to files in the project changing?

**Comment by TylerJewell** [comment] 2016-12-13 14:19
@slemeur - is this related to the popup issue that we are working on now?  If yes, then we can reproduce it.  If it's not, then we may need to ask for some diagnostic time on @patricknazar machine to see if we can diagnose the root cause.

@dkuleshov - FYI.

@patricknazar - the system has file system watchers inside of the container that monitor for file changes. It's supposed to make the system super fast, but there are edge cases that we have to account for at times.

**Comment by JamesDrummond** [comment] 2016-12-13 15:45
This could be related to https://github.com/codenvy/codenvy/issues/1249

**Comment by TylerJewell** [comment] 2016-12-21 23:24
@KakashiMamun - FYI - this comment and merge should solve the issue.
https://github.com/codenvy/codenvy/issues/1249#issuecomment-268671220

**Comment by bmicklea** [comment] 2016-12-26 14:26
@KakashiMamun I am closing this issue as the merged change fixes it.

**Closed as completed by bmicklea** 2016-12-26 14:26 UTC
Labels: kind/bug, severity/blocker, sprint/next
