### ISSUE TITLE
All PR job fo che-plugin-registry are failing due to ".ci/cico-plugin-registry-pr-test.sh: No such file or directory"

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#16471] opened 2020-03-27 13:01 UTC
### Describe the bug

PR job has always failed: https://ci.centos.org/job/devtools-che-plugin-registry-pr-check/

master seems fine https://ci.centos.org/job/devtools-che-plugin-registry-build-master/329/console

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Expected behavior

a working PR job

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by JPinkney** [comment] 2020-03-27 18:22
It's because https://github.com/eclipse/che-plugin-registry/pull/418 hasn't been merged yet so every PR will fail with `/bin/bash: .ci/cico-plugin-registry-pr-test.sh cannot be found`.

The PR is blocked by https://github.com/eclipse/che/issues/15797#issuecomment-602772879

**Comment by ericwill** [comment] 2020-07-29 15:38
This is a known issue, we're working on it. I'm going to close it as a dupe of #15797

**Closed as completed by ericwill** 2020-07-29 15:38 UTC
Labels: kind/bug, severity/P1, area/plugin-registry
