### ISSUE TITLE
Health checker fails to retrieve machine token for test server state

### ISSUE THREAD

**Issue by akorneta** [eclipse-che/che#6900] opened 2017-10-23 10:01 UTC
The original problem was found while selenium tests run.   At a certain moment, the wsmaster checks the agent servers state and do a request with keycloak token instead of a machine, and get 403 error. For more information take look logs:
[catalina.log](https://gist.github.com/akorneta/cc06fb0dacf513ea1b48e630392c7b9e)
[access.log](https://gist.github.com/akorneta/95a70b90c1b6159e9c8359e9a747f2dc)

**Comment by mshaposhnik** [comment] 2017-11-13 13:52
For me it looks like we have an keycloak token expired in the EnvironmentContext right after workspace being started. How could it happen? Was that an multi-thread test environment ?

**Comment by benoitf** [comment] 2017-11-13 14:57
it's in Che5 or Che6  or both ?

**Comment by mshaposhnik** [comment] 2017-11-13 14:58
Che5

**Comment by mshaposhnik** [comment] 2017-11-14 09:12
As far as it not reproducible in Che6, we're closing it.

**Closed as completed by mshaposhnik** 2017-11-14 09:12 UTC
Labels: kind/bug
