### ISSUE TITLE
'Plugins' list is absent in IDE in CHE

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#18211] opened 2020-10-27 12:24 UTC
### Describe the bug
* **Plugins** list is absent in IDE
* This bug was reproduced on CHE deployed on OCP , and wasn't checked on K8s, I assume a result will be the same
* It still worked on 7.19.2, but it seems from 7.20.0, it has been broken

### Che version

 - [x] nightly

### Steps to reproduce

1.  Install CHE using _chectl_:
```
./chectl/bin/chectl server:start --installer=operator --platform=openshift -n <my-project>
```
2. Start workspace
3. In IDE select **Plugins** (Go to **View** -> **Plugins**)

### Expected behavior
* The **Plugins** list should be present in IDE
![che-7-19-2-plugins-list](https://user-images.githubusercontent.com/5408906/97299434-9b368a00-185d-11eb-886d-278bda780145.png)

### Runtime
   - [x] Openshift
```
[ashmaraiev@localhost tmp]$ oc version
Client Version: 4.5.2
Server Version: 4.6.0-rc.4
```

### Screenshots
* **Che 7.20.0**
![che-7-20-plugins-list](https://user-images.githubusercontent.com/5408906/97300344-fd43bf00-185e-11eb-8285-35a61991e8ca.png)

* **Che nightly**
![che-nightly-plugins-list](https://user-images.githubusercontent.com/5408906/97300427-206e6e80-185f-11eb-815e-2b91dc0b289f.png)

### Logs
Che-Theia logs:
```
2020-10-27 15:18:25.423 root INFO Cannot access the registry Params: TypeError: Cannot read property 'getCertificateAuthority' of undefined
    at ChePluginServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-plugin-service.js:140:74)
    at step (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-plugin-service.js:42:23)
    at Object.next (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-plugin-service.js:23:53)
    at /home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-plugin-service.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-plugin-service.js:13:12)
    at ChePluginServiceImpl.getAxiosInstance (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-plugin-service.js:136:16)
    at ChePluginServiceImpl.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-plugin-service.js:367:55)
    at step (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-plugin-service.js:42:23)
    at Object.next (/home/theia/node_modules/@eclipse-che/theia-plugin-ext/lib/node/che-plugin-service.js:23:53)
2020-10-27 15:18:25.558 root INFO Unable to read plugin registry Params: https://plugin-registry-update-crw-operatorhub-tls-no-oauth.apps.ocp45.crw-qe.com/v3/plugins/
```

### Installation method
   - [x] chectl
```
* chectl/7.20.0 linux-x64 node-v10.22.1
* chectl/0.0.20201022-next.2bbd800 linux-x64 node-v10.22.1
```

**Comment by nickboldt** [comment] 2020-10-27 12:56
Fix for this needs to be backported to 7.20.x ASAP since this regression is not ideal for CRW 2.5.

**Comment by dmytro-ndp** [comment] 2020-10-27 12:59
@oshmarai: could you, please say if it's about common problem, or Single Host Che specific?

**Comment by RomanNikitenko** [comment] 2020-10-27 14:15
it's common problem
I can reproduce it on https://che.openshift.io using 7.20 version of the editor.
It works well for 7.19 version.

**Comment by artaleks9** [comment] 2020-10-27 14:55
It's a common problem Che..not only 'single-host'

**Comment by artaleks9** [comment] 2020-10-27 14:55
And I've already checked it for Che'single-host' - got the same problem:
![che-single-host-nightly-plugins-list](https://user-images.githubusercontent.com/5408906/97319108-3be47400-1875-11eb-87df-7f68e06f9056.png)

**Comment by azatsarynnyy** [comment] 2020-10-27 17:16
the patch for 7.21 https://github.com/eclipse/che-theia/pull/894
backported to 7.20 https://github.com/eclipse/che-theia/pull/895

**Comment by artaleks9** [comment] 2020-10-29 10:55
Unfortunately this bug was reproduced on 'nigtly-che' which was installed this morning on OCP 4.6:
```
2020-10-29 10:33:55.805 root INFO Cannot access the registry Params: Error: ENOENT: no such file or directory, scandir '/public-certs'
2020-10-29 10:33:55.987 root INFO Unable to read plugin registry Params: https://plugin-registry-nightly-che.apps.ocp46.crw-qe.com/v3/plugins/
```

![che-nightly-plugins-list](https://user-images.githubusercontent.com/5408906/97559336-f85d4780-19e5-11eb-9899-91f61a06e1c5.png)

**Comment by azatsarynnyy** [comment] 2020-10-29 11:45
Thanks for checking it @artaleks9 :+1: 

The second patch for 7.21.x https://github.com/eclipse/che-theia/pull/897 and a backport to 7.20.x https://github.com/eclipse/che-theia/pull/898
Both have been already merged.

**Closed as completed** 2020-10-29 11:45 UTC
Labels: kind/bug, severity/P1, area/editor/theia, area/che-server

**Comment by artaleks9** [comment] 2020-10-29 12:05
You're welcome, thanks for quick fix.
