### ISSUE TITLE
Cannot access che.openshift.io 

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#17153] opened 2020-06-15 07:32 UTC
### Describe the bug
I logged into che.openshift.io (using that exact string in Firefox) and was not able to access the dashboard.

### Che version
openshift.io as of now

### Steps to reproduce
1. Open Firefox
2. enter "che.openshift.io" in the address bar, hit return
3. Observe: you get redirected to the red hat subscription log-in page
4. Enter your credentials (correct, since copied from a password store)
5. You get redirected to "https://che.openshift.io/dashboard/"
6. Observe: the dasboard is not displayed, instead a page saysing "[object Object]"

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
Firefox on Windows

### Eclipse Che Logs
Browser log says:
```
Can't GET "/api". Error:  
Object { status: 401, response: "{\"errors\":[{\"code\":\"unauthorized_error\",\"detail\":\"oauth2: cannot fetch token: 400 Bad Request\\nResponse: {\\\"error\\\":\\\"invalid_grant\\\",\\\"error_description\\\":\\\"Code not valid\\\"}\",\"status\":\"401\",\"title\":\"Unauthorized error\"}]}\n" }
app-852e1d423a.js:319781:17
    <anonymous> app-852e1d423a.js:319781
uncaught exception: Object
```

**Comment by tsmaeder** [comment] 2020-06-15 07:33
![cannotlogin](https://user-images.githubusercontent.com/13163770/84629836-42d4a080-aeeb-11ea-998a-e1381a11672e.png)

**Comment by benoitf** [comment] 2020-06-15 07:36
looks like a dup of https://github.com/eclipse/che/issues/16719

**Comment by sleshchenko** [comment] 2020-06-15 07:40
I've created a separate issue for a dashboard to display better message https://github.com/eclipse/che/issues/17154

**Comment by tsmaeder** [comment] 2020-06-15 07:42
@benoitf the browser log looks different.

**Comment by tsmaeder** [comment] 2020-06-16 07:28
A bit of an update: this morning, access is working in a private window, but not in my main window.

**Comment by azatsarynnyy** [comment] 2020-06-16 08:22
I have the same error but in Chrome.
Works well in FF and in Chrome Incognito.

**Comment by ibuziuk** [comment] 2020-06-16 08:50
@azatsarynnyy @tsmaeder any pointers to specific logs or the only thingy is this 401 response during the token fetching?

**Comment by ibuziuk** [comment] 2020-06-16 11:08
@xcoulon @alexeykazakov will you be able to follow up on the recent sso updates which might result in  ```oauth2: cannot fetch token: 400 Bad Request Response:{"error":"invalid_grant","error_description":"Code not valid"}``` ?

**Comment by azatsarynnyy** [comment] 2020-06-16 12:23
> @azatsarynnyy @tsmaeder any pointers to specific logs or the only thingy is this 401 response during the token fetching?

@ibuziuk I have the following message in Chrome's console:
`VM55:627 Refused to get unsafe header "WWW-Authenticate"`
Nothing more that may look suspicious.

**Comment by azatsarynnyy** [comment] 2020-06-16 20:57
I can't reproduce it anymore after upgrading Chrome to the latest minor release :shrug: 
Everything works well now.

**Comment by tsmaeder** [comment] 2020-06-17 07:32
As of this morning, I can again log into che.openshif.io in the main window with not changes of my setup.

**Comment by ibuziuk** [comment] 2020-06-18 11:21
Closing. will follow up internally on the sso outage / issues reasoning

**Closed as completed by ibuziuk** 2020-06-18 11:21 UTC
Labels: kind/bug, severity/P1, area/hosted-che
