### ISSUE TITLE
Emitter memory leak related problems 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19200] opened 2021-03-03 18:24 UTC
### Describe the bug

The bug was reported in the Eclipse Che mattermost channel.

Che user detected a lot of logs in the browser console, also it's impossible to run a task 

<details>
<Summary>The logs:</Summary>

```
WARN Possible Emitter memory leak detected. 196 listeners added. Use event.maxListeners to increase the limit (175). MOST frequent listener (120):
logger-protocol.ts:112 root WARN     at e.onDidRunOperation (https://routenss68q01-rnikiten-che.apps.che-dev.x6e0.p1.openshiftapps.com/theia.0211f3f21f574190b0b7.js:1:3450082
 
```
 
```
WARN Possible Emitter memory leak detected. 203 listeners added. Use event.maxListeners to increase the limit (175). MOST frequent listener (127):
root WARN     at e.onDidChangeFileSystemProviderCapabilities (https://routenss68q01-rnikiten-che.apps.che-dev.x6e0.p1.openshiftapps.com/theia.0211f3f21f574190b0b7.js:1:3450082
```

```
ERROR Child node 'file-change-tree-root' does not belong to this 'file-change-tree-root' tree.
```

</details>

I checked it using a workspace from `Angular` stack and faced with the state when:
- nodes in the `Explorer` view are loading few seconds
- `My workspace` panel is empty
- opening a file takes few seconds

then the IDE goes to `offline` mode. Refreshing a page fixes the issue

### Additional info from the user:

I made some changes in che-theia removing
```
  "vscode-git": "https://open-vsx.org/api/vscode/git/1.49.3/file/vscode.git-1.49.3.vsix",
  "vscode-github": "https://open-vsx.org/api/vscode/github/1.50.1/file/vscode.github-1.50.1.vsix"
```
and
```
plugins/github-auth-plugin
```

now both issues disappeared, the `file-change-tree-root` and also `Possible Emitter memory leak detected` and the tasks are working well. 

 
### Che version

 - [ ] latest
 - [x] nightly
 - [x] other: 7.26.1
 
### Steps to reproduce
1. Start a workspace using `Angular` devfile from dashboard. 
2. Try to do simple actions - like opening a file, expand packages in the `Explorer` view.
 
### Runtime
dogfooding instance
  
### Screenshots

![memory_leak_angular](https://user-images.githubusercontent.com/5676062/109853299-6f3d7200-7c5e-11eb-8fae-bcdf8b4f6e34.png)

**Comment by azatsarynnyy** [comment] 2021-03-04 07:55
need to check it once the https://github.com/eclipse-theia/theia/pull/9045 is merged

**Comment by ericwill** [comment] 2021-03-04 20:55
cc @vinokurig please check it after eclipse-theia/theia#9045 is merged

**Comment by vinokurig** [comment] 2021-03-17 08:08
I am closing it because it is not reproducible after https://github.com/eclipse-theia/theia/pull/9045 is merged. Although there are some `root ERROR Child node 'file-change-tree-root' does not belong to this 'file-change-tree-root' tree.` console errors, there is another issue opened for that: https://github.com/eclipse-theia/theia/issues/7953

**Closed as completed by vinokurig** 2021-03-17 08:08 UTC
Labels: kind/bug, severity/P1, area/editor/theia
