### ISSUE TITLE
Some factories in multi thread launching can not clone a project properly

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#6440] opened 2017-09-26 12:19 UTC
**Reproduction Steps:** this reproduce in the selenium tests under multithread mode (3 or more threads) by DirectUrlFactoryWithRootFolder:
![img1](https://user-images.githubusercontent.com/1640058/30859811-d219bf8c-a2cd-11e7-9a1f-7234619a7512.png)

**OS and version:**    Fedora 25.0, chrome browser, nightly servers (SaaS, Onprem)

**Comment by dmytro-ndp** [comment] 2017-09-27 08:59
The problem is project source can't be cloned because of invalid origin, according to the message on log console of IDE.

**Comment by dmytro-ndp** [comment] 2017-11-03 15:18
Fresh test failure [org.eclipse.che.selenium.factory.CheckFactoryWithUntilPolicyTest.checkFactoryAcceptingWithUntilPolicy](https://ci.codenvycorp.com/view/qa/job/che-integration-tests-che6/64/testReport/org.eclipse.che.selenium.factory/CheckFactoryWithUntilPolicyTest/checkFactoryAcceptingWithUntilPolicy/
):
```
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.pageobject.ProjectExplorer.waitProjectExplorer(ProjectExplorer.java:159)
	at org.eclipse.che.selenium.factory.CheckFactoryWithUntilPolicyTest.checkFactoryAcceptingWithUntilPolicy(CheckFactoryWithUntilPolicyTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"id","selector":"gwt-debug-projectTree"}
```

**Comment by tolusha** [comment] 2017-12-11 12:48
More logs needed.

**Comment by dmytro-ndp** [comment] 2017-12-11 12:53
Which kind of logs do you need?

**Comment by tolusha** [comment] 2017-12-11 13:36
master/agent logs

**Comment by dmytro-ndp** [comment] 2017-12-11 14:03
it's hard to obtain agent's logs so as workspace is being removed just after the failure of test

**Comment by SkorikSergey** [comment] 2019-07-04 13:10
Not relevant anymore. Closing.

**Closed as completed by SkorikSergey** 2019-07-04 13:10 UTC
Labels: kind/bug, severity/P2, e2e-test/failure
