### ISSUE TITLE
Plugin host throws exception at startup

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#18455] opened 2020-11-25 10:12 UTC
### Describe the bug
When I switch to the "next" version of che-theia in any workspace and enable a plugin like "typescript", for example, the output of the "extension host (xxxx) log" show and exception at startup:

```
ERROR:Error: Cannot find module '@eclipse-che/theia-plugin-ext/lib/plugin/node/che-api-node-provider.js'
Require stack:
- /remote-endpoint/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js
- /remote-endpoint/node_modules/@eclipse-che/theia-remote/lib/node/plugin-remote-init.js
- /remote-endpoint/node_modules/@eclipse-che/theia-remote/lib/node/plugin-remote.js
```

### Che version

 happens on che.openshift.io, and a local install of che with nightly on docker-desktop

### Steps to reproduce

Switch to che-theia:next in any workspace and enable at least one che plugin.

### Runtime
   - [x] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: che.openshift.io

**Comment by tolusha** [comment] 2020-11-25 14:13
@tsmaeder 
Is it just the error or plugins don't work either?

**Comment by ericwill** [comment] 2020-11-25 18:26
A duplicate of #17601, perhaps?

**Comment by tsmaeder** [comment] 2020-11-26 09:20
@ericwill no, and error with a reason and a stack trace would show up in the log even now.

**Comment by tsmaeder** [comment] 2020-11-26 09:27
@tolusha I don't know, but if che-api-provider.js cannot be loaded, potentially all che-related API would not be available.

**Comment by tsmaeder** [comment] 2020-11-26 14:57
I suspect this is als what is causing https://github.com/eclipse/che/issues/17609

**Closed as completed** 2020-12-08 08:59 UTC
Labels: kind/bug, severity/P2, area/editor/theia
