### ISSUE TITLE
vscode-****: reason = 'Completed', exit code = 0, message = 'null'"

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#17618] opened 2020-08-11 17:40 UTC
### Describe the bug

Default Python Stack. First run was the default theia-ide. Stopped the workspace, and toggled code-server on. 

Workspace fails with:

```
Error: Failed to run the workspace: "The following containers have terminated:
vscode-pythonh8z: reason = 'Completed', exit code = 0, message = 'null'"

```

![image](https://user-images.githubusercontent.com/4656027/89927098-6eae9280-dbcb-11ea-9107-83565084c09f.png)

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

7.17.0. I assume its latest since I deployed it today (8/11/2020) with `bash <(curl -sL  https://www.eclipse.org/che/chectl/)`

### Steps to reproduce

1. Fresh install of Ubuntu 20.04 LTS with microk8s selected while installing.

2. apt update, upgrade, autoremove, clean, reboot

3. Install helm and kubectl for package managers. [helm instructions](https://helm.sh/docs/intro/install/#through-package-managers) [kubectl instructions](https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-using-native-package-management)

4. chectl and enable microk8s ingress storage

5. 
```cd $HOME
mkdir .kube
cd .kube
microk8s config > config 
```

6. `chectl server:start -a helm -p microk8s` and import certificate.

7. Select the provided python 3.7 workplace. Wait for successful start.

8. Stop and go to Workplaces -> Created python 3.7 workplace from step 7 ->  Editors -> code-server. Save. Open

9. Error here. 
### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: (please specify) Microk8s `installed:          v1.18.6 `

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [x] Windows: client
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: Server is Ubuntu

### Eclipse Che Logs

[events.txt](https://github.com/eclipse/che/files/5058426/events.txt)

### Additional context

Changing the editor back to the default theia does boot up.

**Comment by l0rd** [comment] 2020-08-12 11:08
@gnoejuan this looks like a duplicate of https://github.com/eclipse/che/issues/17378

**Comment by l0rd** [comment] 2020-08-12 11:11
@gnoejuan I am closing this issue since we already have an issue about fixing the code-server editor. Feel free to re-open or add information to #17378.

**Closed as completed by l0rd** 2020-08-12 11:11 UTC
Labels: kind/bug, status/duplicate, area/plugins
