### ISSUE TITLE
Unable to run Junit tests in Eclipse Che - Right click and run does not work

### ISSUE THREAD

**Issue by desaiRahulS** [eclipse-che/che#17818] opened 2020-09-09 20:22 UTC
### Describe the bug
I would like to right click on a Junit test and run which does nothing as it expects a main method.
I noticed that VS Code Java Test Runner plugin is missing in eclipse che 7.18.0.
Also I did not see any plugin supporting test in the list of available plugins

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create a new workspace with a Java Spring Boot sample project which has a unit test
2. Right click on the unit test and click run
3. You should get an error on the lines "main method is missing"
4. Click View -> Test, which should open an empty pane on the left side

### Expected behavior

Right click on the Junit test and clicking run should execute the unit test in Java

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
          Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"1da71a35d52fa82847fd61c3db20c4f95d283977", GitTreeState:"clean", BuildDate:"2020-07-15T21:59:26Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl

     * provide a full command that was used to deploy Eclipse Che (including the output)
        Followed the steps documented here - https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-microsoft-azure/

     * provide an output of `chectl version` command
       chectl/7.18.0 linux-x64 node-v10.22.0
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [x] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs

N/A

### Additional context

As a workaround I am running "mvn clean test" but it would be truly helpful to understand why right click on Junit and run does not work.
Similar issue as described here - https://stackoverflow.com/questions/59208921/debug-java-test-in-eclipse-che

**Comment by ericwill** [comment] 2020-09-09 20:25
Should be fixed by https://github.com/eclipse/che-plugin-registry/pull/602

**Comment by ericwill** [comment] 2020-09-09 20:26
Duplicate of https://github.com/eclipse/che/issues/14871

**Closed as completed by ericwill** 2020-09-09 20:26 UTC
Labels: kind/bug

**Comment by desaiRahulS** [comment] 2020-09-09 20:28
My apologies, as I missed the original issue being tracked. Thanks

**Comment by ericwill** [comment] 2020-09-09 20:32
> My apologies, as I missed the original issue being tracked. Thanks

No apologies needed!
