### ISSUE TITLE
Create custom commands on custom Project Type creation

### ISSUE THREAD

**Issue by kvandenhoute** [eclipse-che/che#9033] opened 2018-03-06 16:33 UTC
### Description
I'm creating a plugin for Eclipse Che 6.1. It's a custom Project Type. I can't seem to figure out how to add a custom Command on creation of my Project Type. The goal is to create some custom run commands, and some deploy commands without having to add them manually or include them in the Stack.
I started with code from the che-plugin-json sample, and in the file _[plugin-myjson-server/src/main/java/it/pkg/generator/JsonExampleCreateProjectHandler.java](https://github.com/che-samples/che-plugin-json/blob/master/plugins/plugin-myjson/plugin-myjson-server/src/main/java/it/pkg/generator/JsonExampleCreateProjectHandler.java)_ I basicly want the onCreate to become something like this:
```
...
  @Override
  public void onCreateProject(
      String projectPath, Map<String, AttributeValue> attributes, Map<String, String> options)
      throws ConflictException, ServerException {
        ...
       List<CommandImpl> commands = ...; //get the commands from somewhere
       commands.add(new CommandImpl(name,commandLine,typeId));
       ....
  }
...
```

**OS and version:**    
Ubuntu - Eclipse Che 6.1.1

**Comment by eivantsov** [comment] 2018-03-10 01:06
@azatsarynnyy @vparfonov can you suggest anything?

**Comment by vparfonov** [comment] 2018-03-15 07:33
@Farleon 
Hello, I think you can do something like this: 

```
@Override
  public void onCreateProject(
      String projectPath, Map<String, AttributeValue> attributes, Map<String, String> options)
      throws ConflictException, ServerException {
        ...
       List<CommandImpl> commands = ...; //get the commands from somewhere
       commands.add(new CommandImpl(name,commandLine,typeId));
       RegisteredProject project = projectManager.get(projectPath).get();
       Map<String, List<String>> attributes = config.getAttributes();

   //adding commands to the project attributes 
    List<String> attrValue = new ArrayList<>(attributes.size());
    for (CommandImpl command : commands) {
      CommandDto commandDto =
          dtoFactory
              .createDto(CommandDto.class)
              .withName(command.getName())
              .withType(command.getType())
              .withCommandLine(command.getCommandLine())
              .withAttributes(command.getAttributes());
              attrValue.add(dtoFactory.toJson(commandDto));
    }

    attributes.put(COMMANDS_ATTRIBUTE_NAME, attrValue);
   //save new project configuration
    NewProjectConfigImpl projectConfig =
          new NewProjectConfigImpl(
              project.getPath(),
              project.getType(),
              project.getMixins(),
              project.getName(),
              project.getDescription(),
              attributes,
              project.getSource());

      projectManager.update(projectConfig);
    

```

**Comment by Farleon** [comment] 2018-03-15 14:29
Thank you, it pointed me in the right direction but i'm not just quite there yet.
Right now I have this, going from your code.

```
  @Inject private FsManager fsManager;
  private final ProjectManager projectManager;
  protected static final DtoFactory dtoFactory = DtoFactory.getInstance();

  @Inject
  public JujuCreateProjectHandler(ProjectManager pm) {
    this.projectManager = pm;
  }
  @Override
  public void onCreateProject(
      String projectPath, Map<String, AttributeValue> attributes, Map<String, String> options)
      throws ConflictException, ServerException {
...
// adding commands to the project attributes
    List<String> attrValue = new ArrayList<>(attributes.size());
    // Create test command
    HashMap<String, String> commandAttributes = new HashMap<>();
    commandAttributes.put("goal", "Run");
    commandAttributes.put("previewUrl", "");
    CommandImpl command = new CommandImpl("test123", "echo hello", "custom", commandAttributes);

    // Convert command
    CommandDto commandDto =
        dtoFactory
            .createDto(CommandDto.class)
            .withName(command.getName())
            .withType(command.getType())
            .withCommandLine(command.getCommandLine())
            .withAttributes(command.getAttributes());

    // add command to attrvalue
    attrValue.add(dtoFactory.toJson(commandDto));

    // Save attributes in new attributesList, the attributes in parameter is of type Map<String,
    // AttributeValue> and is empty anyway
    Map<String, List<String>> attributesList = new HashMap<>();
    attributesList.put("commands", attrValue);

    // Get the new project
    RegisteredProject project = (projectManager.get(projectPath)).get();

    try {
      System.out.println("Read project: " + project);

      // save new project configuration
      NewProjectConfigImpl projectConfig =
          new NewProjectConfigImpl(
              project.getPath(),
              project.getType(),
              project.getMixins(),
              project.getName(),
              project.getDescription(),
              attributesList,
              null,
              project.getSource());

      System.out.println("Projectconfig name: " + projectConfig.getName());
      System.out.println("Projectconfig attributes: " + projectConfig.getAttributes());

      // update project
      projectManager.update(projectConfig);

      for (RegisteredProject rpp : projectManager.getAll()) {
        System.out.println(rpp.getName());
        System.out.println(rpp.getAttributes());
      }

    } catch (Exception e) {
      e.printStackTrace();
    }

```
This  code generates this output

> Read project: _org.eclipse.che.api.project.server.impl.RegisteredProject@5a05164c_
> Projectconfig name: _/testProject_
> Projectconfig attributes: _{commands=[{"commandLine":"echo hello","name":"test123","attributes":{"goal":"Run","previewUrl":""},"type":"custom"}]}_
> **The output of all projectnames with their attributes**
> che-wizard-sample-shared
> {}
> che-wizard-sample-server
> {}
> JEWizard
> {vcs.provider.name=[git], git.current.head.name=[master], commands=[{"commandLine":"cd /home/user/tomcat8/bin\n export SERVER_PORT=8080\n export JPDA_ADDRESS=9000\n ./catalina.sh jpda run", "name":"Tomcat8-IDE Start", "attributes":{"goal":"Run", "previewUrl":""}, "type":"custom"}, {"commandLine":"cd /home/user/traefik && ./traefik", "name":"Traefik Start", "attributes":{"goal":"Run", "previewUrl":""}, "type":"custom"}, ...(more run commands)], git.repository.remotes=[https://github.com/Farleon/JEWizard.git]}
> che-wizard-sample-ide
> {}
> /testProject
> {commands=[{"commandLine":"echo hello","name":"test123","attributes":{"goal":"Run","previewUrl":""},"type":"custom"}]}
> 

The JEWizard is the main project, which has my run commands. These are also shown in the workspace
![image](https://user-images.githubusercontent.com/6653186/37468220-a2a92ef2-2862-11e8-987d-bfa5889b59e3.png)

The testProject was the project I tried creating commands for onCreate of the project. The commands are added to the project but they are not shown in the workspace. They are neither in the commands palette, I can't find them visually. 
Any tips for that?

**Comment by eivantsov** [comment] 2018-03-15 14:37
@Farleon can you see this command in wokspace config? `api/workspace/$workspace-id?`

**Comment by Farleon** [comment] 2018-03-16 19:20
It also does not appear there
![image](https://user-images.githubusercontent.com/6653186/37540483-649ab568-2957-11e8-831b-3b3eb885280c.png)

The 4 commands in the config, are the ones I put there manually.

**Comment by Farleon** [comment] 2018-03-23 23:31
Any other suggestions?

**Comment by Farleon** [comment] 2018-04-05 22:26
I worked around it by using the swagger api from within my function. This obviously is not ideal, so I tried looking in the swagger code which uses the WorkspaceManager.

```
    WorkspaceImpl workspace = workspaceManager.getWorkspace(id);
    workspace.getConfig().getCommands().add(new CommandImpl(newCommand));
```

The problem is I already tried using this, and when I inject the workspacemanager the IDE wont start.
So for now i'll keep it this way. If anyone knows how to properly inject, please be so kind te let me know.

**Comment by eivantsov** [comment] 2018-04-24 09:13
Closing the issue as the problem seems to have been solved or a workaround is found.

**Closed as completed by eivantsov** 2018-04-24 09:13 UTC
Labels: kind/question
