### ISSUE TITLE
New workspace isn't displayed in workspace list

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#20707] opened 2021-10-29 09:15 UTC
### Describe the bug

If create a new workspace from another tab or cli, dashboard doesn't show it in the workspaces list, however it is present in sidebar.

### Che version

next (development version)

### Steps to reproduce

1. Create a workspace
2. Open another tab with dashboard, create and start another workspace
3. Close second tab and return to the first one

### Expected behavior

New workspace is shown in the workspaces list too

### Runtime

OpenShift

### Screenshots

![Screenshot from 2021-10-27 17-13-55](https://user-images.githubusercontent.com/15607393/139390268-e2c165d6-7b15-4fb5-b36c-9853463ef0f6.png)

### Installation method

chectl/next

### Environment

Linux

### Additional context

- DevWorkspace engine was used
- The issue is 100% reproducible on my side
- After the page refresh, everything works as expected

**Comment by akurinnoy** [comment] 2022-03-10 14:47
I can't reproduce this issue either on the minikube or the dogfooding cluster. I believe it was fixed in one of the previous pull requests.

<details>
<summary>Screencast</summary>


https://user-images.githubusercontent.com/16220722/157685524-591a752d-b072-4f03-9101-f133730bba0d.mov

</details>

**Closed as completed by akurinnoy** 2022-03-10 14:47 UTC
Labels: kind/bug, sprint/current, severity/P1, area/dashboard
