### ISSUE TITLE
When CRW Operator is installed in OpenShift, there should be a CRW link in the App Launcher

### ISSUE THREAD

**Issue by serenamarie125** [eclipse-che/che#17159] opened 2020-06-15 21:28 UTC
# Bug Description
On a OCP 4.4.6 cluster with CRW 2.1.1 Operator installed, there is no CRW link in the Application Launcher.

Additional Notes:
Configured to use TLS
CRW2 was initially installed, and has been updated to CRW2.1.1 

Note that the cluster is owned by Veer - I can reach out for additional details if needed

### Expected behavior
When CRW Operator is installed in OpenShift, there should be a CRW link in the OpenShift Application Launcher.

Mario mentioned this is tested, but I'm wondering if the issue could be due to the fact that this isn't a fresh operator install, but an update?

### Screenshots
This screenshot is showing that the Eclipse Che link is present, but the CRW is not.

![image (67)](https://user-images.githubusercontent.com/12504403/84707905-83eda480-af2d-11ea-919b-3029143a1eb8.png)

**Comment by l0rd** [comment] 2020-06-15 23:31
@serenamarie125 have you deployed Eclipse Che (beyond CRW) on that cluster?

**Comment by l0rd** [comment] 2020-06-15 23:33
cc @skabashnyuk @sparkoo

**Comment by serenamarie125** [comment] 2020-06-16 01:45
@VeerMuchandi can you provide more info here?  Thanks!

**Comment by sparkoo** [comment] 2020-06-16 05:46
@serenamarie125 @l0rd From code I can't see why it should not work. Name of the ConsoleLink object is determined by env variable `CONSOLE_LINK_NAME` during installation and I see this variable set to different value for Che and CRW. So it should be possible to install Che and CRW beside. I haven't test it though.

Logs from both operators, preferably with debug level, might help.

**Comment by VeerMuchandi** [comment] 2020-06-16 19:49
@sparkoo I have both CRW and Che running on the same cluster. Is there something I should do to test `CONSOLE_LINK_NAME`?

**Comment by VeerMuchandi** [comment] 2020-06-16 19:56
BTW, CRW 2 was deployed in Dec 2019 on my cluster and it has been upgrading since then. Could this be the reason why ConsoleLink is not created?

**Comment by sparkoo** [comment] 2020-06-17 09:54
@VeerMuchandi `CONSOLE_LINK_NAME` is variable in `che/crw-operator` deployment, so you can look there.

> BTW, CRW 2 was deployed in Dec 2019 on my cluster and it has been upgrading since then. Could this be the reason why ConsoleLink is not created?

yes, it can. I'll verify and try to reproduce that. Currently I'm trying to reproduce with latest versions.

**Comment by sparkoo** [comment] 2020-06-17 09:54
@VeerMuchandi btw do you see anything related to consolelink in crw-operator log? search for `ConsoleLink` and `Console link`

**Comment by sparkoo** [comment] 2020-06-17 13:38
@VeerMuchandi how did you install your CRW (chectl, operator hub)? Can you please take a look what codeready-operator image and tag you have? Can you please post here your `codeready-operator` deployment (`oc get deployment codeready-operator -o yaml -n workspaces`) ?

**Comment by VeerMuchandi** [comment] 2020-06-17 13:53
I installed this operator from operator hub.  Here is the deployment http://pastebin.test.redhat.com/876139

**Comment by VeerMuchandi** [comment] 2020-06-17 13:58
@sparkoo I don't see anything in operator logs for ConsoleLink. But I see some other errors. Here are the logs http://pastebin.test.redhat.com/876144

**Comment by sparkoo** [comment] 2020-06-17 14:44
@VeerMuchandi @serenamarie125  I see the issue now. Before this patch https://github.com/eclipse/che-operator/pull/247/files we've had `ConsoleLink` name de-facto hardcoded to be named `che`. We've changed only display name and image url into CRW ones. This patch comes into che-operator after latest crw-operator release. So indeed, this clashes with ConsoleLink from your Che installation. Actually, everytime reconcile loop is run it should update the `ConsoleLink` as well, so you might see some back-and-forth (Che <> CRW) changes of this `ConsoleLink`.

It should be fixed with next CRW release, assuming that crw-operator updates properly env variables in deployment. I'm not very familiar with this update process (?? @nickboldt @mmorhun @tolusha )

I see few ways how to workaround this now:
 - If you want to have the ConsoleLink for CRW now, you can create it manually. Next CRW update would create same object. This does not fix potential changes on your current ConsoleLink, as both operators would still try to use `che` ConsoleLink.
```
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: workspaces
spec:
  applicationMenu:
    imageURL: >-
      https://<crw-url>/dashboard/assets/branding/loader.svg
    section: Red Hat Applications
  href: >-
    https://<crw-url>
  location: ApplicationMenu
  text: CodeReady Workspaces
```
 - assuming you have latest version of Che, you may change the `CONSOLE_LINK_NAME` env in che-operator deployment, so it would use different name. Be aware that after CRW update, you will have 3 `ConsoleLinks`, so you will have to handle this manually.


Let me know if it helps and if you need any further assistance with this issue.

**Comment by sparkoo** [comment] 2020-06-17 16:43
closing this issue as it is already fixed in che-operator and will be in next crw-operator. Suggested workaround worked.

**Closed as completed by sparkoo** 2020-06-17 16:43 UTC
Labels: kind/bug, status/analyzing, area/che-operator
