### ISSUE TITLE
Dashboard plugins list should show one entry for each plugin, with a dropdown to select version.

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#13566] opened 2019-06-18 15:20 UTC
### Description
As the plugin registry grows, the list of available plugins in the dashboard is becoming unweildy. For instance, there are four entries for "Language Support for Java(TM)" -- versions `0.38.0`, `0.43.0`, `0.45.0`, and `latest`. Instead it would be nice if there was one "Language Support for Java(TM)" with a way of selecting version used, with a default to `latest`.

### Reproduction Steps
1. Create workspace
2. Go to plugins tab of workspace config

**Comment by gorkem** [comment] 2019-07-20 17:01
@l0rd @slemeur Can you please prioritize this.

**Comment by amisevsk** [comment] 2019-07-20 20:27
FWIW I think @jpinkney has already put a bit of work into this on the side.

**Comment by JPinkney** [comment] 2019-07-20 22:44
Yeah, I've got it to the point where it only needs a day or two of work to finish before making a PR

**Comment by JPinkney** [comment] 2019-07-22 02:58
I've just opened a PR for this. Here's a quick demo: https://www.youtube.com/watch?v=WkrbTsrjuBk

**Comment by l0rd** [comment] 2019-07-22 08:27
This is a big improvement for the UX. I am only worried about regressions but if @ashumilova and @rhopp are ok +1 to add it to 7.0.0.

And this issue is similar to https://github.com/eclipse/che/issues/13913

**Comment by l0rd** [comment] 2019-08-21 08:38
Closing this issue since it has been fixed by https://github.com/eclipse/che/pull/13942

**Closed as completed by l0rd** 2019-08-21 08:38 UTC
Labels: kind/enhancement, status/analyzing
