### ISSUE TITLE
Better failure model when PVC fails during workspace creation

### ISSUE THREAD

**Issue by dneary** [eclipse-che/che#9946] opened 2018-06-05 21:39 UTC
When starting a new workspace, if the PVC fails on the underlying infrastructure (OpenShift), for whatever reason, there is no immediate feedback to the user. The workspace loader spins, the mount is retried and re-fails, until the operation times out (60s), and returns a generic error message ("Workspace failed to start". There are "Failed to mount PV" errors reports in the OpenShift pod events for the workspace, but this information does not seem to propagate back up to Che.

I believe that we should be able to detect that a PVC failed when creating the workspace, and then inform the user that there was a problem allocating storage for the workspace.

**Comment by eivantsov** [comment] 2018-06-06 04:52
@dneary are you certain you use the latest Che? According to https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L358 Failed Mount should be considered an an unrecoverable event and it should be displayed in the IDE and server logs (not sure about server logs though)

**Comment by dneary** [comment] 2018-06-06 15:16
It's a recent deployment. It says "Che 6.7.0-SNAPSHOT".

An easy way to reproduce this using NFS is to define a PV without a valid NFS share - the NFS mount fails, resulting in the PVC claim failing, and it takes ~60s for this to propagate to the user.

**Comment by eivantsov** [comment] 2018-06-06 15:19
What exact error do you see in the IDE?

**Comment by dneary** [comment] 2018-06-06 15:41
Well, I fixed it... will need to re-break it to see.

**Comment by dneary** [comment] 2018-06-06 15:56
In the OpenShift workspace pod events, I see:

> 11:50:09 AM | Warning | Failed Mount | MountVolume.SetUp  failed for volume "nfs-pv16" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for  /var/lib/origin/openshift.local.volumes/pods/23c9eba3-69a1-11e8-9a4b-c03fd56fd023/volumes/kubernetes.io~nfs/nfs-pv16  --scope -- mount -t nfs  dn2.desklab.eng.bos.redhat.com:/home/dneary/nfsroot/pv16  /var/lib/origin/openshift.local.volumes/pods/23c9eba3-69a1-11e8-9a4b-c03fd56fd023/volumes/kubernetes.io~nfs/nfs-pv16 Output: Running scope as unit run-9587.scope.…         
> -- | -- | -- | --
> 11:49:37 AM | Warning | Failed Mount | MountVolume.SetUp  failed for volume "nfs-pv16" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for  /var/lib/origin/openshift.local.volumes/pods/23c9eba3-69a1-11e8-9a4b-c03fd56fd023/volumes/kubernetes.io~nfs/nfs-pv16  --scope -- mount -t nfs  dn2.desklab.eng.bos.redhat.com:/home/dneary/nfsroot/pv16  /var/lib/origin/openshift.local.volumes/pods/23c9eba3-69a1-11e8-9a4b-c03fd56fd023/volumes/kubernetes.io~nfs/nfs-pv16 Output: Running scope as unit run-7911.scope.…          > 11:49:21 AM | Warning | Failed Mount | MountVolume.SetUp  failed for volume "nfs-pv16" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for  /var/lib/origin/openshift.local.volumes/pods/23c9eba3-69a1-11e8-9a4b-c03fd56fd023/volumes/kubernetes.io~nfs/nfs-pv16  --scope -- mount -t nfs  dn2.desklab.eng.bos.redhat.com:/home/dneary/nfsroot/pv16  /var/lib/origin/openshift.local.volumes/pods/23c9eba3-69a1-11e8-9a4b-c03fd56fd023/volumes/kubernetes.io~nfs/nfs-pv16 Output: Running scope as unit run-6962.scope.…          > 11:49:13 AM | Warning | Failed Mount | MountVolume.SetUp  failed for volume "nfs-pv16" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for  /var/lib/origin/openshift.local.volumes/pods/23c9eba3-69a1-11e8-9a4b-c03fd56fd023/volumes/kubernetes.io~nfs/nfs-pv16  --scope -- mount -t nfs  dn2.desklab.eng.bos.redhat.com:/home/dneary/nfsroot/pv16  /var/lib/origin/openshift.local.volumes/pods/23c9eba3-69a1-11e8-9a4b-c03fd56fd023/volumes/kubernetes.io~nfs/nfs-pv16 Output: Running scope as unit run-6514.scope.…          > 11:49:09 AM | Warning | Failed Mount | MountVolume.SetUp  failed for volume "nfs-pv16" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for  /var/lib/origin/openshift.local.volumes/pods/23c9eba3-69a1-11e8-9a4b-c03fd56fd023/volumes/kubernetes.io~nfs/nfs-pv16  --scope -- mount -t nfs  dn2.desklab.eng.bos.redhat.com:/home/dneary/nfsroot/pv16  /var/lib/origin/openshift.local.volumes/pods/23c9eba3-69a1-11e8-9a4b-c03fd56fd023/volumes/kubernetes.io~nfs/nfs-pv16 Output: Running scope as unit run-6186.scope.…          > 11:49:06 AM | Warning | Failed Mount | MountVolume.SetUp  failed for volume "nfs-pv16" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for  /var/lib/origin/openshift.local.volumes/pods/23c9eba3-69a1-11e8-9a4b-c03fd56fd023/volumes/kubernetes.io~nfs/nfs-pv16  --scope -- mount -t nfs  dn2.desklab.eng.bos.redhat.com:/home/dneary/nfsroot/pv16  /var/lib/origin/openshift.local.volumes/pods/23c9eba3-69a1-11e8-9a4b-c03fd56fd023/volumes/kubernetes.io~nfs/nfs-pv16 Output: Running scope as unit run-6168.scope.…          > 11:49:05 AM | Warning | Failed Mount | MountVolume.SetUp  failed for volume "nfs-pv16" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for  /var/lib/origin/openshift.local.volumes/pods/23c9eba3-69a1-11e8-9a4b-c03fd56fd023/volumes/kubernetes.io~nfs/nfs-pv16  --scope -- mount -t nfs  dn2.desklab.eng.bos.redhat.com:/home/dneary/nfsroot/pv16  /var/lib/origin/openshift.local.volumes/pods/23c9eba3-69a1-11e8-9a4b-c03fd56fd023/volumes/kubernetes.io~nfs/nfs-pv16 Output: Running scope as unit run-5983.scope.…          > 11:49:05 AM | Warning | Failed Mount | MountVolume.SetUp  failed for volume "nfs-pv16" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for  /var/lib/origin/openshift.local.volumes/pods/23c9eba3-69a1-11e8-9a4b-c03fd56fd023/volumes/kubernetes.io~nfs/nfs-pv16  --scope -- mount -t nfs  dn2.desklab.eng.bos.redhat.com:/home/dneary/nfsroot/pv16  /var/lib/origin/openshift.local.volumes/pods/23c9eba3-69a1-11e8-9a4b-c03fd56fd023/volumes/kubernetes.io~nfs/nfs-pv16 Output: Running scope as unit run-5964.scope.…          > 11:49:04 AM | Normal | Successful Mount Volume | MountVolume.SetUp succeeded for volume "default-token-gsz9s"
> 11:49:04 AM | Normal | Scheduled | Successfully assigned workspace43qwimdrbmpkthlv.dockerimage to dn2.desklab.eng.bos.redhat.com

In Che, I see the attached when I open the workspace (still not timed out, 2' later):
![screenshot from 2018-06-06 11-54-14](https://user-images.githubusercontent.com/467525/41050121-7b9c218e-6980-11e8-9ed6-9af4e99e3501.png)

The Che dashboard shows the pulsing icon beside the workspace, no error message.

**Comment by dneary** [comment] 2018-06-06 16:03
When if failed, there was an ephemeral message, I didn't get the exact wording before it disappeared, but it was along the lines of "Failed: The workspace  reached timeout".

I see the following messages in the Che deployment log on OpenShift: 

> 2018-06-06 15:49:04,390[nio-8080-exec-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 314]   - Starting workspace 'developer/python-sieve' with id 'workspace43qwimdrbmpkthlv' by user 'developer'
> 018-06-06 15:57:04,671[aceSharedPool-2] [WARN ] [.i.k.KubernetesInternalRuntime 179] - Failed to start Kubernetes runtime of workspace workspace43qwimdrbmpkthlv. Cause: Waiting for Kubernetes environment 'default' of the workspace'workspace43qwimdrbmpkthlv' reached timeout
> 2018-06-06 15:57:04,927[aceSharedPool-2] [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 375] - Workspace 'developer:python-sieve' with id 'workspace43qwimdrbmpkthlv' start failed





 
--

**Comment by eivantsov** [comment] 2018-06-07 12:41
@ibuziuk @sleshchenko do you guys think it's because it is not an error but a warning in OpenShift events? I cannot reproduce. I tried deleting all PVs and starting a workspace, and I get an en event from OpenShift in the IDE and server logs

**Comment by sleshchenko** [comment] 2018-06-07 13:27
We don't have filtering by event type, I suppose the reason can be in `fieldPath`. [Here](https://github.com/eclipse/che/blob/59393928bc33c1fff9602a6cd31d2f32475d21ca/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesPods.java#L321
) we filter all events that are not related to containers. And in this case, it may be Pod related but not container and `fieldPath` may be NULL.

**Comment by ibuziuk** [comment] 2018-06-07 15:54
@dneary could you please provide steps to reproduce ?

**Comment by eivantsov** [comment] 2018-06-07 16:01
@ibuziuk I haven't tried it today but tried before. Deploy Che, then remove all PVs in your minishift and attempt to start a workspace.

**Comment by ibuziuk** [comment] 2018-06-07 16:06
@eivantsov but you wrote that you cannot reproduce, or I'm missing smth ?

**Comment by eivantsov** [comment] 2018-06-07 16:14
I used to test unrecoverable events like this before. Maybe smth has changed

**Comment by eivantsov** [comment] 2018-06-19 10:47
@ibuziuk somehow, Che does not catch such events.

I deleted all PVs in my local cluster and attempted to run a workspace.

1. After a few mins I see this in pod events:
![image](https://user-images.githubusercontent.com/5337267/41592793-7a38e246-73c6-11e8-9d7d-03c57d46ef84.png)
2. Che server keep waiting and eventually spits out:

```

2018-06-19 10:37:52,097[nio-8080-exec-8]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 459]    - Workspace 'che/nopvavailable' with id 'workspacelmu49sl3gspm4hg8' created by user 'che'
--
  | 2018-06-19 10:37:56,380[nio-8080-exec-3]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 329]   - Starting workspace 'che/nopvavailable' with id 'workspacelmu49sl3gspm4hg8' by user 'che'
  | 2018-06-19 10:45:57,682[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 192]  - Failed to start Kubernetes runtime of workspace workspacelmu49sl3gspm4hg8. Cause: null
  | 2018-06-19 10:45:57,974[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 390]   - Workspace 'che:nopvavailable' with id 'workspacelmu49sl3gspm4hg8' start failed
  | 2018-06-19 10:45:57,978[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceRuntimes 400]   - null
  | org.eclipse.che.api.workspace.server.spi.InternalInfrastructureException: null
  | at org.eclipse.che.workspace.infrastructure.kubernetes.StartSynchronizer.getStartFailureNow(StartSynchronizer.java:274)
  | at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:187)
  | at org.eclipse.che.api.workspace.server.spi.InternalRuntime.start(InternalRuntime.java:145)
  | at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartRuntimeTask.run(WorkspaceRuntimes.java:366)
  | at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:37)
  | at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.util.concurrent.TimeoutException: null
  | at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
  | at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
  | at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.waitMachines(KubernetesInternalRuntime.java:252)
  | at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.internalStart(KubernetesInternalRuntime.java:184)
  | ... 7 common frames omitted
  | 2018-06-19 10:45:58,005[aceSharedPool-0]  [WARN ] [o.e.c.a.w.s.WorkspaceManager 423]    - Cannot set error status of the workspace workspacelmu49sl3gspm4hg8. Error is: null
```

**Comment by mmclanerh** [comment] 2018-06-21 23:31
would it be possible to spin the workspace up via a deployment config object or by storing a template and running performing a process|create from that template? this would give you startup state, retries, etc, and abstract from having to directly manage a pod.. but rather, just gather state/status from the dc.

this also gives you some control around timeouts (giving up if things are not sane after a period) as well as concurrency control (strategy.type = recreate), so that no 2 pods concurrent attempt to mount the same pvc.

**Comment by ibuziuk** [comment] 2018-06-22 13:24
@mmclanerh yeah, it is planned to use dc instead of bare pods for openshift infra  - https://github.com/eclipse/che/pull/10021

**Comment by ibuziuk** [comment] 2018-06-25 11:51
@eivantsov PR is ready to be merged - https://github.com/eclipse/che/pull/10155
tested on minishift by deleting of all pvs:

![image](https://user-images.githubusercontent.com/1461122/41848654-6ed9757a-787e-11e8-9388-6ae3ef5e20e9.png)

would it be possible to have  a few negative testing scenarios with QE

**Comment by eivantsov** [comment] 2018-06-25 11:54
@vkuznyetsov can you take care of it in the next sprint?

@ibuziuk what OS version have you tested? Does it make sense to try 3.10RC or 3.11 nightly?

**Comment by ibuziuk** [comment] 2018-06-25 12:12
have tested against the following minishift:

```
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
etcd 3.2.1
```

> Does it make sense to try 3.10RC or 3.11 nightly
the more tests, the better ;-)
but here the problem is that we do not have particular test metrics with supported openshift / k8s versions che should be running against. So, currently I assume (might be wrong here) that it is expected that che would work against any 3.x master version.

**Comment by ibuziuk** [comment] 2018-06-26 11:43
Tested on the latest minishift version:

> minishift v1.20.0+53c500a
> openshift v3.9.0+71543b2-33
> kubernetes v1.9.1+a0ce1bc657
> etcd 3.2.16

![image](https://user-images.githubusercontent.com/1461122/41909076-5dc368ea-7946-11e8-9615-37ddc6290e19.png)

**Comment by eivantsov** [comment] 2018-07-25 13:08
Should be fixed by https://github.com/eclipse/che/issues/10295

**Comment by sleshchenko** [comment] 2018-08-31 09:13
@eivantsov #10295 is closed, should this issue be closed as well?

**Comment by eivantsov** [comment] 2018-08-31 09:19
@sleshchenko good idea, maybe after checking it. Also, I do think it is a good idea to write some negative QE tests to make sure we don;t lose this feature.

**Comment by eivantsov** [comment] 2018-09-03 05:58
Closing as fixed:

![image](https://user-images.githubusercontent.com/5337267/44969819-7da85700-af57-11e8-84fb-f4afbc794f28.png)

**Closed as completed by eivantsov** 2018-09-03 05:58 UTC
Labels: kind/bug, status/in-progress, sprint/current, severity/P1
