### ISSUE TITLE
Sync changes to local git config with user Che git config

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#13959] opened 2019-07-22 13:55 UTC
### Describe the bug

Git commit command requires committer name and email in the git config. Each time when the workspace restarts, git  commit asks for committer name and email, even if it was set before restart.
### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Set Git committer name and email: 
```
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```
2. Perform git commit from terminal or from the SCM Tab => committed successfully.
3. Restart workspace
4. Perform git commit.
**WRONG** Error occurs: 
```
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <root@workspace2qrbunxmaiupc1vw.che-dev-5c99c9c745-kz6sq>) not allowed
``` 

### Expected behavior

Git commit should be successful, if the user data is set once.
### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by l0rd** [comment] 2019-07-22 18:14
@vinokurig this looks like a duplicate of https://github.com/eclipse/che/issues/13874. Please re-open if you think that's not the case.

**Comment by vzhukovskii** [comment] 2019-07-29 13:53
Reopen this issue, because it doesn't duplicate #13874. This issue needs to find the way to store `~/.gitconfig`, when workspace restarts.

**Comment by nickboldt** [comment] 2019-07-31 20:52
I see this was added to 7.1 then moved to 7.x. Maybe we split the difference and set it to 7.2 or 7.3?

**Comment by l0rd** [comment] 2019-08-02 10:55
@vzhukovskii what I understand is:
- #13874 is about adding git config to the user preferences and use it to generate workspaces git config
- #13959 (this issue) is about syncing eventual manual changes of a user in the git config of a workspace with the user preferences

So #13874 is a pre-requisite of this issue and even a P1. While this issue for me is not a major issue and I would keep 7.x

**Comment by vzhukovskii** [comment] 2019-08-02 11:40
@l0rd yes, you're right, #13874 has higher priority.

**Closed as completed** 2019-09-13 14:53 UTC
Labels: kind/bug, area/editor/theia
