### ISSUE TITLE
Move tests from java selenium framework to typescript framework

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#18376] opened 2020-11-16 08:23 UTC
### Is your task related to a problem? Please describe.
Move tests from java selenium framework to typescript framework.
- [ ] **Dashboad**
- [ ] **Factory**
- [ ] **Hotupdate**
- [ ] **Workspaces**

**Comment by rhopp** [comment] 2020-12-09 09:30
- Factory - some work has been started here: https://github.com/eclipse/che/blob/master/tests/e2e/tests/e2e/FactoryUrl.spec.ts  this could be just extended
- Dashboard - this should be made deprecated by move to dashboard-next and proper testing in there (+ e2e integration suite implemented as part of https://github.com/eclipse/che/issues/18391
- Workspaces 
  - Timeout tests are already implemented (@Katka92 can you point us where?)
- Rolling update
 - If I get it correctly, these are kind of "resilience" tests. Would be interested whether we could implement this in a way, that the same set of tests will be used for both "update" (between che versions) and "restart" (where che-server pod gets killed). I think this would required bit more thought into it, but it's not that urgent IMO (as we are already testing some upgrade scenarios)

**Comment by Katka92** [comment] 2020-12-09 10:17
So, the idling test is ready in the test-harness repo [1], but the job for it is not in place yet. The issue is here: https://github.com/eclipse/che/issues/18029 
As it is a new job, we didn't want to add that to "old" Jenkins, but there are no Che installation jobs on the new one - which is a requirement for the idling test - it doesn't include installation & setup of Che itself. Once the installation jobs are in place I can work on a job for idling or I can at least help with it.

[1] https://github.com/che-incubator/che-test-harness/pull/9

**Comment by rhopp** [comment] 2021-03-01 12:19
Factory is covered, other stuff has followup issues. Closing.

**Closed as completed by rhopp** 2021-03-01 12:19 UTC
Labels: kind/epic, kind/task, severity/P2, area/qe
