### ISSUE TITLE
Two terminal tabs appearing when workspace first loads

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#2324] opened 2016-09-03 23:14 UTC
Using tagged 4.7.0 release. 
Docker for Windows
Windows 10
Create a workspace and when IDE first opens, getting two tabs for the terminal.

**Comment by tolusha** [comment] 2016-09-04 06:46
If terminals work it can't be blocker.

**Comment by riuvshin** [comment] 2016-09-05 11:19
it seems it is duplicate of https://github.com/eclipse/che/issues/2249

**Closed as completed** 2016-09-05 14:59 UTC
Labels: kind/bug, severity/blocker
