### ISSUE TITLE
Quarkus welcome page gets shown again and again

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17994] opened 2020-09-30 08:21 UTC
### Describe the bug

When Quarkus VS Code extension is started a welcome page is automatically opened. 

![image](https://user-images.githubusercontent.com/606959/94660124-92f23a00-0305-11eb-9d21-6317e85029a8.png)

At the very bottom of that page a checkbox allow to opt out.

![image](https://user-images.githubusercontent.com/606959/94660236-b5845300-0305-11eb-9dae-05ef405f6be6.png)

But even if I uncheck "Show welcome page when using Quarkus Tools" the welcome page will be shown next time I restart the Che workspace.

### Che version

che.osio

### Steps to reproduce

- Start the Quarkus Tools stack on che.osio. 
- Open a Java file and wait for the "Quarkus Tools for Eclipse Che" welcome page to open.
- Uncheck "Show welcome page when using Quarkus Tools"
- Restart the Che workpace and observe that the "Quarkus Tools for Eclipse Che" welcome page to opens again.

### Expected behavior

1. The welcome page should not be opened when restarting the workspace.
2. The welcome page should not be opened even when creating a new workspace that have the Quarkus Tools.
3. There should be some space between the checkbox "Show welcome page when using Quarkus Tools" and the line above in the Quarkus welcome page.

**Comment by ericwill** [comment] 2020-09-30 13:49
Might be related to https://github.com/eclipse/che/issues/16352 ?

**Comment by vitaliy-guliy** [comment] 2020-10-20 13:23
Clicking on the checkbox is not handled, because there is no necessary javascript injected in webview frame. The problem is because quarkus extension is running in sidecar, and for that extensions we have an issue with loading resources into webviews https://github.com/eclipse/che/issues/16870

![Screenshot from 2020-10-20 16-17-38](https://user-images.githubusercontent.com/1655894/96592016-99664700-12f0-11eb-8edc-2f6fb215ec90.png)

**Comment by vzhukovs** [comment] 2020-12-21 21:07
Checked this use case in che-theia master. Issue seems is not reproducible anymore.

**Comment by ericwill** [comment] 2021-01-04 21:31
> Checked this use case in che-theia master. Issue seems is not reproducible anymore.

Thanks for checking, closing the ticket now.

**Closed as completed by ericwill** 2021-01-04 21:31 UTC
Labels: kind/bug, severity/P2, area/plugins, area/editors
