### ISSUE TITLE
Workspace Container Issues

### ISSUE THREAD

**Issue by magbj** [eclipse-che/che#10370] opened 2018-07-10 18:39 UTC
### Description

I have successfully been able to deploy Che, create users and workspaces. Specific things are failing within the container when I start it up though. I tried to spin up eclipse/ubuntu_python:latest, and things stops at this:

![eclipseche_ws_api](https://user-images.githubusercontent.com/6413432/42529673-2359778c-844d-11e8-8b4a-4286fd9bfb66.PNG)

The container is still functional though, and I can use it and log into it. Going through the different logs and checking running processes, it looks like exec_agent, terminal, ws_agent and ssh (added it on in config) have all started successfully. However, pyls (Python Language Server), did not. I was able to start it after the fact though via the terminal, and it seems to work through the IDE.

Looking through the catalina.out for the ws-agent, everything seems normal though.

When I was debugging this, it would have been helpful to be able to do SSH connectivity from a desktop SSH client. Is that possible with the setup that I have, using Kubernetes and Nginx Ingress Controller?

Thanks!

### Reproduction Steps

Deployed into AWS in a private subnet (1 AZ/subnet), running on top of AWS EKS/Kubernetes
ELB for incoming traffic. HTTP for now, will do SSL termination on Nginx.
Using Nginx Ingress Controller (0.16.2). 
Keycloak version: 3.4.3.Final
Eclipse Che version: 6.8.0-SNAPSHOT
Created a storage class for EBS/GP2
All ports/IPs are accessible within private subnet

**Diagnostics:** 

```
pulling image "eclipse/ubuntu_python:latest"
Successfully pulled image "eclipse/ubuntu_python:latest"
Created container
Started container
Exec Agent binary is downloaded remotely
2018/07/10 17:15:19 Exec-agent configuration
2018/07/10 17:15:19   Server
2018/07/10 17:15:19     - Address: :4412
2018/07/10 17:15:19     - Base path: ''
2018/07/10 17:15:19   Authentication
2018/07/10 17:15:19     - Enabled: true
2018/07/10 17:15:19     - Tokens expiration timeout: 10m
2018/07/10 17:15:19   Workspace master server
2018/07/10 17:15:19     - API endpoint: http://che-cde-che.cde.nonprd.aws.example.com/api
2018/07/10 17:15:19   Process executor
2018/07/10 17:15:19     - Logs dir: /workspace_logs/exec-agent
2018/07/10 17:15:19 
2018/07/10 17:15:19 ⇩ Registered HTTPRoutes:
 
2018/07/10 17:15:19 Process Routes:
2018/07/10 17:15:19 ✓ Start Process ........................... POST   /process
2018/07/10 17:15:19 ✓ Get Process ............................. GET    /process/:pid
2018/07/10 17:15:19 ✓ Kill Process ............................ DELETE /process/:pid
2018/07/10 17:15:19 ✓ Get Process Logs ........................ GET    /process/:pid/logs
2018/07/10 17:15:19 ✓ Get Processes ........................... GET    /process
2018/07/10 17:15:19 
2018/07/10 17:15:19 Exec-Agent WebSocket routes:
2018/07/10 17:15:19 ✓ Connect to Exec-Agent(websocket) ........ GET    /connect
2018/07/10 17:15:19 
2018/07/10 17:15:19 Exec-Agent liveness route:
2018/07/10 17:15:19 ✓ Check Exec-Agent liveness ............... GET    /liveness
2018/07/10 17:15:19 
2018/07/10 17:15:19 ⇩ Registered RPCRoutes:
 
2018/07/10 17:15:19 Process Routes:
2018/07/10 17:15:19 ✓ process.start
2018/07/10 17:15:19 ✓ process.kill
2018/07/10 17:15:19 ✓ process.unsubscribe
2018/07/10 17:15:19 ✓ process.subscribe
2018/07/10 17:15:19 ✓ process.updateSubscriber
2018/07/10 17:15:19 ✓ process.getLogs
2018/07/10 17:15:19 ✓ process.getProcess
2018/07/10 17:15:19 ✓ process.getProcesses
Terminal Agent binary is downloaded remotely
2018/07/10 17:15:22 Terminal-agent configuration
2018/07/10 17:15:22     - Address: :4411
2018/07/10 17:15:22     - Base path: ''
2018/07/10 17:15:22   Server
2018/07/10 17:15:22   Terminal
2018/07/10 17:15:22     - Slave command: ''
2018/07/10 17:15:22     - Activity tracking enabled: false
2018/07/10 17:15:22   Authentication
2018/07/10 17:15:22     - Enabled: true
2018/07/10 17:15:22     - Tokens expiration timeout: 10m
2018/07/10 17:15:22   Workspace master server
2018/07/10 17:15:22     - API endpoint: http://che-cde-che.cde.nonprd.aws.example.com/api
2018/07/10 17:15:22 
2018/07/10 17:15:22 ⇩ Registered HTTPRoutes:
 
2018/07/10 17:15:22 Terminal routes:
2018/07/10 17:15:22 ✓ Connect to pty(websocket) ............... GET    /pty
2018/07/10 17:15:22 
2018/07/10 17:15:22 Terminal-Agent liveness route:
2018/07/10 17:15:22 ✓ Check Terminal-Agent liveness ........... GET    /liveness
2018/07/10 17:15:22 
Workspace Agent will be downloaded from Workspace Master
Listening for transport dt_socket at address: 4403
2018-07-10 17:15:26,862[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.5.23
2018-07-10 17:15:26,864[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.5.23.0
2018-07-10 17:15:26,864[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Sep 28 2017 10:30:11 UTC
2018-07-10 17:15:26,865[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            4.14.42-61.37.amzn2.x86_64
2018-07-10 17:15:26,865[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
2018-07-10 17:15:26,865[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
2018-07-10 17:15:26,865[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
2018-07-10 17:15:26,865[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11
2018-07-10 17:15:26,866[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
2018-07-10 17:15:26,866[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/che/ws-agent
2018-07-10 17:15:26,866[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/che/ws-agent
2018-07-10 17:15:26,866[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/che/ws-agent/conf/logging.properties
2018-07-10 17:15:26,866[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
2018-07-10 17:15:26,867[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:MaxRAM=600m
2018-07-10 17:15:26,867[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:MaxRAMFraction=1
2018-07-10 17:15:26,867[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+UseParallelGC
2018-07-10 17:15:26,867[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:MinHeapFreeRatio=10
2018-07-10 17:15:26,867[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:MaxHeapFreeRatio=20
2018-07-10 17:15:26,868[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:GCTimeRatio=4
2018-07-10 17:15:26,868[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:AdaptiveSizePolicyWeight=90
2018-07-10 17:15:26,868[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dsun.zip.disableMemoryMapping=true
2018-07-10 17:15:26,868[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms50m
2018-07-10 17:15:26,868[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dfile.encoding=UTF8
2018-07-10 17:15:26,868[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.security.egd=file:/dev/./urandom
2018-07-10 17:15:26,869[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/workspace_logs/ws-agent
2018-07-10 17:15:26,869[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.level=INFO
2018-07-10 17:15:26,869[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djuli-logback.configurationFile=file:/home/user/che/ws-agent/conf/tomcat-logger.xml
2018-07-10 17:15:26,869[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
2018-07-10 17:15:26,869[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
2018-07-10 17:15:26,869[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=4403,server=y,suspend=n
2018-07-10 17:15:26,870[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
2018-07-10 17:15:26,870[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
2018-07-10 17:15:26,870[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
2018-07-10 17:15:26,870[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/home/user/che/ws-agent/conf/
2018-07-10 17:15:26,870[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/che/ws-agent
2018-07-10 17:15:26,870[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/che/ws-agent
2018-07-10 17:15:26,871[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/che/ws-agent/temp
2018-07-10 17:15:26,918[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 573]  - Initializing ProtocolHandler ["http-nio-4401"]
2018-07-10 17:15:26,928[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 67]   - Using a shared selector for servlet write/read
2018-07-10 17:15:26,930[main]             [INFO ] [o.a.catalina.startup.Catalina 632]   - Initialization processed in 255 ms
2018-07-10 17:15:26,982[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 336]  - The JMX Remote Listener has configured the registry on port [32002] and the server on port [32102] for the [Platform] server
2018-07-10 17:15:26,983[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.5.23
2018-07-10 17:15:26,983[main]             [INFO ] [o.a.c.core.StandardService 416]      - Starting service [Catalina]
2018-07-10 17:15:27,097[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/che/ws-agent/webapps/ROOT.war]
2018/07/10 17:15:29 Start new terminal.
2018-07-10 17:15:30,162[ost-startStop-1]  [INFO ] [i.WorkspaceProjectSynchronizer 65]   - Workspace ID: workspaceobh2jm2tkufskwcd
2018-07-10 17:15:30,165[ost-startStop-1]  [INFO ] [i.WorkspaceProjectSynchronizer 66]   - API Endpoint: http://che-cde-che.cde.nonprd.aws.example.com/api
2018-07-10 17:15:30,379[rcherInitThread]  [INFO ] [o.e.c.a.s.s.i.LuceneSearcher 158]    - Initial indexing complete after 2 msec 
Tue Jul 10 17:15:30 UTC 2018 - [localhost-startStop-1] Product-specified preferences called before plugin is started
2018-07-10 17:15:30,888[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/che/ws-agent/webapps/ROOT.war] has finished in [3,791] ms
2018-07-10 17:15:30,894[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 632]  - Starting ProtocolHandler ["http-nio-4401"]
2018-07-10 17:15:30,929[main]             [INFO ] [o.a.catalina.startup.Catalina 683]   - Server startup in 3998 ms
```

It seems to be receiving traffic as expected:
```
10.223.53.80 - - [10/Jul/2018:17:15:31 +0000] "GET /api/?token=eyJhbGciOiJSUzUxMiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIn0.eyJ3c2lkIjoid29ya3NwYWNlb2JoMmptMnRrdWZza3djZCIsInVpZCI6IjY1YjYwN2JhLWFiODYtNDI1My04ZWU3
LTUzOWIxMDA4ZWY5OCIsInVuYW1lIjoibWJqb3JrbWFuIiwianRpIjoiNmEwNGViY2UtNWZhNC00OTFiLWFhNTAtZDc4YzFhZGM4OWQxIn0.SCRXskeJXzAzQATiQ6eLGyq-blis2B7hmaeC2Tb5ly6PujEepysgsk0rBfywL61crZ3bo77jCY1EKaSocJ8O9aCfE3RDedM
ZbSWMsMsvLYvF_WdDUvjXLKxkCAIagd9dHsjDNz53Z-LXnixkS8g0ynJkoOYSQ0nC1TkuOAKciEw5uS4XyYMHvPz5wJFYBDAvAOIfh4C-VHNETf-EnzAyWmWuW5Bb4RrCSLoE6tVbGMoKaHKqbUbre3Lh6O-hymK7mrOL7_l39i8WRhpEeXSeYYaDjwLZlKt5k-nBUKm3BE
WMozbKji5LcjCTtiz856ZFOrc9wQSztFjHOf-ATpnEIA HTTP/1.1" 200 -
10.223.53.80 - - [10/Jul/2018:17:15:34 +0000] "GET /api/?token=eyJhbGciOiJSUzUxMiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIn0.eyJ3c2lkIjoid29ya3NwYWNlb2JoMmptMnRrdWZza3djZCIsInVpZCI6IjY1YjYwN2JhLWFiODYtNDI1My04ZWU3
LTUzOWIxMDA4ZWY5OCIsInVuYW1lIjoibWJqb3JrbWFuIiwianRpIjoiNmEwNGViY2UtNWZhNC00OTFiLWFhNTAtZDc4YzFhZGM4OWQxIn0.SCRXskeJXzAzQATiQ6eLGyq-blis2B7hmaeC2Tb5ly6PujEepysgsk0rBfywL61crZ3bo77jCY1EKaSocJ8O9aCfE3RDedM
ZbSWMsMsvLYvF_WdDUvjXLKxkCAIagd9dHsjDNz53Z-LXnixkS8g0ynJkoOYSQ0nC1TkuOAKciEw5uS4XyYMHvPz5wJFYBDAvAOIfh4C-VHNETf-EnzAyWmWuW5Bb4RrCSLoE6tVbGMoKaHKqbUbre3Lh6O-hymK7mrOL7_l39i8WRhpEeXSeYYaDjwLZlKt5k-nBUKm3BE
WMozbKji5LcjCTtiz856ZFOrc9wQSztFjHOf-ATpnEIA HTTP/1.1" 200 -
10.223.53.80 - - [10/Jul/2018:17:15:34 +0000] "OPTIONS /api/project-type HTTP/1.1" 200 -
10.223.53.80 - - [10/Jul/2018:17:15:34 +0000] "OPTIONS /api/java/compiler-settings/all HTTP/1.1" 200 -
10.223.53.80 - - [10/Jul/2018:17:15:34 +0000] "GET /wsagent?token=eyJhbGciOiJSUzUxMiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIn0.eyJ3c2lkIjoid29ya3NwYWNlb2JoMmptMnRrdWZza3djZCIsInVpZCI6IjY1YjYwN2JhLWFiODYtNDI1My04Z
WU3LTUzOWIxMDA4ZWY5OCIsInVuYW1lIjoibWJqb3JrbWFuIiwianRpIjoiNmEwNGViY2UtNWZhNC00OTFiLWFhNTAtZDc4YzFhZGM4OWQxIn0.SCRXskeJXzAzQATiQ6eLGyq-blis2B7hmaeC2Tb5ly6PujEepysgsk0rBfywL61crZ3bo77jCY1EKaSocJ8O9aCfE3RD
edMZbSWMsMsvLYvF_WdDUvjXLKxkCAIagd9dHsjDNz53Z-LXnixkS8g0ynJkoOYSQ0nC1TkuOAKciEw5uS4XyYMHvPz5wJFYBDAvAOIfh4C-VHNETf-EnzAyWmWuW5Bb4RrCSLoE6tVbGMoKaHKqbUbre3Lh6O-hymK7mrOL7_l39i8WRhpEeXSeYYaDjwLZlKt5k-nBUKm
3BEWMozbKji5LcjCTtiz856ZFOrc9wQSztFjHOf-ATpnEIA&clientId=605674731 HTTP/1.1" 101 -
10.223.53.80 - - [10/Jul/2018:17:15:34 +0000] "GET /api/java/compiler-settings/all HTTP/1.1" 200 -
10.223.53.80 - - [10/Jul/2018:17:15:34 +0000] "GET /api/project-type HTTP/1.1" 200 -
10.223.53.80 - - [10/Jul/2018:17:15:34 +0000] "OPTIONS /api/project HTTP/1.1" 200 -
10.223.53.80 - - [10/Jul/2018:17:15:34 +0000] "GET /api/project HTTP/1.1" 200 -
10.223.53.80 - - [10/Jul/2018:17:15:35 +0000] "OPTIONS /api/app/state?userId=65b607ba-ab86-4253-8ee7-539b1008ef98 HTTP/1.1" 200 -
10.223.53.80 - - [10/Jul/2018:17:15:35 +0000] "GET /api/app/state?userId=65b607ba-ab86-4253-8ee7-539b1008ef98 HTTP/1.1" 200 -
10.223.53.80 - - [10/Jul/2018:17:15:44 +0000] "GET /api/liveness HTTP/1.1" 200 -
10.223.53.80 - - [10/Jul/2018:17:15:54 +0000] "GET /api/liveness HTTP/1.1" 200 -
10.223.53.80 - - [10/Jul/2018:17:16:04 +0000] "GET /api/liveness HTTP/1.1" 200 -
```

**Comment by eivantsov** [comment] 2018-07-11 06:16
@magbj can you consistently reproduce the issue with Python Language server?

As to SSHing into the pod, it looks like a k8s question rather than Che question. My question is: can you sping up a pod on k8s, run sshd there, put your public key to ~/.ssh/authorized_keys and ssh into it using ingress endpoint? I have never tried that.

Perhaps you can follow https://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/

**Comment by magbj** [comment] 2018-07-11 22:34
@eivantsov It always happens on that image, but I am not sure it is the Python Language server. It seems like the ws_agent never reports back as being successful.

Interestingly, I started to use a custom image based on Centos with Python installed. It always succeeds. I never see this problem on that one. 

For the SSH, it might be more of a k8s issue, but I also need to have a way to discover that a workspace has been created, the pod used for that workspace, and get the exposed port for that pod.

**Comment by magbj** [comment] 2018-07-20 20:29
@eivantsov Since switching to my own image, I have not seen the issue with the workspace not starting.

I was able to create a k8s service outside Che to connect via SSH. I have been experimenting with doing it with Kubernetes yaml as part of the recipe as well, and it does seem to work if I only create one instance of my workspace, but not multiple. With this in the recipe (as a string in content):

```
kind: List
items:
-
 kind: Service
 apiVersion: v1
 metadata:
  name: my-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
    service.beta.kubernetes.io/aws-load-balancer-internal: enabled
 spec:
  selector:
    name: workspace
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
-
  apiVersion: v1
  kind: Pod
  metadata:
    name: app
    annotations:
      org.eclipse.che.container.workspace.machine_name: xxxx-machine
  spec:
    containers:
      -
        image: xxxxxx.dkr.ecr.us-east-1.amazonaws.com/xxxx:latest
        name: workspace
        ports:
         -
          containerPort: 22
          protocol: TCP

```

I am getting this:
```
kubectl describe service my-service --namespace cde-che
Name:                     my-service
Namespace:                cde-che
Labels:                   che.workspace_id=workspaceg2txdqnoyyju5vcd
Annotations:              service.beta.kubernetes.io/aws-load-balancer-backend-protocol=tcp
                          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout=3600
                          service.beta.kubernetes.io/aws-load-balancer-internal=enabled
Selector:                 che.workspace_id=workspaceg2txdqnoyyju5vcd,name=workspace
Type:                     LoadBalancer
IP:                       172.20.82.115
LoadBalancer Ingress:     internal-xxxx.us-east-1.elb.amazonaws.com
Port:                     <unset>  22/TCP
TargetPort:               22/TCP
NodePort:                 <unset>  30616/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     31825
Events:
  Type    Reason                Age   From                Message
  ----    ------                ----  ----                -------
  Normal  EnsuringLoadBalancer  3m    service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   3m    service-controller  Ensured load balancer

```

It seems like the name for the service needs to be made unique as well. Just like it is done for the pod already.

**Comment by eivantsov** [comment] 2018-09-10 10:56
@magbj closing this issue. Feel free to create a new one with your `service` question. thanks

**Closed as completed by eivantsov** 2018-09-10 10:56 UTC
Labels: kind/question
