### ISSUE TITLE
Running shell tasks don't execute from tasks panel on the right

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#17202] opened 2020-06-20 02:12 UTC
### Describe the bug

Since 7.14.1 and 7.14.3, this bug has started to be observed. Configured shell tasks don't run from the right panel. I can only run them via top menu >> terminal >> run tasks >> select my shell task.

### Che version

 - [X] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [X] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [X] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [X] other: please specify

**Comment by ibuziuk** [comment] 2020-06-22 14:34
@SDAdham seems to work for me on Hosted Che (7.14.2). Is it 7.14.3 specific?


![Peek 2020-06-22 16-33](https://user-images.githubusercontent.com/1461122/85299913-2e257900-b4a6-11ea-87f2-83b09887281c.gif)

Could you please provide browser info and steps to reproduce?

**Comment by azatsarynnyy** [comment] 2020-06-22 14:59
probably, it should be already fixed by the recently merged PR https://github.com/eclipse/che-theia/pull/739

**Comment by ibuziuk** [comment] 2020-06-22 15:00
yeah, but if the issue is in 7.14.x might a critical one for the product cc: @nickboldt @rhopp

**Comment by azatsarynnyy** [comment] 2020-06-22 15:01
cc @tsmaeder @ericwill

**Comment by tsmaeder** [comment] 2020-06-22 15:30
This has been broken for about 2 weeks at least: the use of source and scope has been fixed upstream and our use of it did not match.

**Comment by tsmaeder** [comment] 2020-06-22 15:31
Not sure if it's critical: the workaround is just to use "Run Task..."

**Comment by SDAdham** [comment] 2020-06-24 08:08
@ibuziuk  This issue was noticed to be happening since Since 7.14.1 and 7.14.3, I haven't tried 7.14.2.

@tsmaeder : Agreed that run task works as a workaround and I hope that this doesn't break cuz if this one breaks too, then there will be no other workarounds too.

**Comment by nickboldt** [comment] 2020-06-26 01:58
7.14.2 ~= 7.14.1 -- iirc there were no changes between builds. It was a release done by the prod team to practice doing releases and further the cause of seamless automation.

If this is a problem in 7.15.0, please keep complaining so it will be prioritized for a fix in 7.16.x / CRW 2.3.

**Comment by SDAdham** [comment] 2020-06-26 11:49
@nickboldt : when is 7.15.0 is going to be released?

**Comment by SDAdham** [comment] 2020-07-01 12:59
@nickboldt / @ibuziuk the issue is still persisting but new behaviour:
In the terminal view, it comes up. But that's incorrect because it should ask for inputs first. But it looks like it does skip asking for input and shows the terminal straight away and when it does, it fails on the first command that doesn't make sense:
First command:
```
sleep 2 && if [ ! -d \"data\" ]; then mkdir data && chmod 777 data; fi && echo ... rest of the command...
```
Output:
```
mkdir: cannot create directory 'data': File exists
```
which doesn't make sense.

So in short, 2 issues:

* It doesn't ask for input
* Incorrect command processing

**Comment by tsmaeder** [comment] 2020-07-24 07:50
Two things:

1. I did not notice originally that the issue talks about "shell" tasks. The "My Workspace" panel only shows and executes commands of type "che". This is the intended behaviour. Even executing che tasks was broken at one time, hence my comment above.
2. Could you provide the relevant part of your devfile? I don't really know how to reproduce this from the info given. For example, why should the IDE ask for input?
3. Did you try the command you're executing in a terminal in the Theia container?

**Comment by RomanNikitenko** [comment] 2020-07-30 08:24
@SDAdham 
Could you provide more details: https://github.com/eclipse/che/issues/17202#issuecomment-663393871

**Comment by RomanNikitenko** [comment] 2020-10-02 09:09
@SDAdham 
> Configured shell tasks don't run from the right panel. I can only run them via top menu >> terminal >> run tasks >> select my shell task.

According to [the documentation](https://www.eclipse.org/che/docs/che-7/end-user-guide/defining-custom-commands-for-che-theia/#che-theia-task-types_defining-custom-commands-for-che-theia) it's expected behavior:

> Tasks of type che, also known as exec commands, can be executed from the Terminal→Run Task menu or by selecting them in the My Workspace panel. Other tasks are only available from Terminal→Run Task. 
 
I'm closing the issue. Please feel free to reopen this one if you have more questions.

**Closed as completed by RomanNikitenko** 2020-10-02 09:09 UTC
Labels: kind/bug, severity/P1, area/plugins
