### ISSUE TITLE
Maven dependencies are download each time the workspace is getting restarted

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13603] opened 2019-06-21 06:51 UTC
### Description
Start a workspace, wait for dependencies to be loaded, stop the workspace and restart it.
- Dependencies are reloaded by the Java LS

### Reproduction Steps
Start a workspace, wait for dependencies to be loaded, stop the workspace and restart it.
- Dependencies are reloaded by the Java LS

**OS and version:** 
Che 7 RC 2

**Comment by sleshchenko** [comment] 2019-06-21 10:21
If you type `mvn clean install` in maven container - then dependencies will be downloaded after each restart of workspace, and it iis caused by lack of user information in `/etc/passwd`, to fix it it is needed to build custom image and make maven container - openshift compatible where `/etc/passwd` will be writable and entrypoint will fill in user name if needed. More see https://github.com/eclipse/che/pull/13561

As about Java LS - it may be caused by the same issue OR volume for storing resolved dependencies may be missed @tolusha Can you comment?

**Comment by tsmaeder** [comment] 2019-09-10 11:45
The devfile [here](https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-maven/devfile.yaml) does not contain a persistent volume for ~/.m2. Need to mount the "m2" volume to the java plugin home dir.

**Comment by tsmaeder** [comment] 2019-09-10 11:46
Let's also check all other devfiles and fix as appropriate.

**Comment by amisevsk** [comment] 2019-09-10 14:58
@tsmaeder Is this something that should be fixed in the devfiles or in the plugin meta.yaml itself?

**Comment by tsmaeder** [comment] 2019-09-24 07:43
Blocked by https://github.com/eclipse/che/issues/14634

**Comment by tsmaeder** [comment] 2019-10-02 07:51
I think it makes sense to mount the volume in the plugin meta.yml, becuase we want this for all java tooling sidecars.

**Comment by tsmaeder** [comment] 2019-10-02 07:55
@svor as a first step, let's put this into the 0.50 version of the Java plugins when you create it.

**Closed as completed** 2019-10-07 14:51 UTC
Labels: kind/bug, severity/P1
