### ISSUE TITLE
After updating CheCluster CR Che is in an inconsistent state

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#14111] opened 2019-08-02 16:30 UTC
### Describe the bug

When creating a Che server though the Operator with the default settings (which now also includes deploying embedded registries), and then enabling TLS, the Che server is broken:
- Openshift OAuth login is broken since Openshift `OAuthClient` confirguation is not updated with the new `https`-based redirect URL
- The devfile list and plugin brokering are broken since the routes of the embedded registries are not upgraded to TLS.

Additionally, a problem related to `CheCluster` update logic break the correct use of `devfileRegistryUrl` and `pluginRegistryUrl` values, so that only the default registry URLs (those on `openshift.io`) can be used when external registries have been set in the custom resource at creation time.

### Che version
 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

- TLS-related error:
  - Create a Che Cluster with default settings with the Operator
  - Enable TLS and self-signed certificates in a second steps

- Registry related error:
  - Create a `CheCluster` resource with `externalDevfileRegistry` set to true and `externalDevfileUrl` set to a custom URL
  - The started Che server will use the `che-devfile-registry.openshift.io` URL for the devfile registry instead of your custom URL

### Expected behavior

- Changing the `CheCluster` custom resource to enable TLS and self-signed certificates should behave correctly, especially knowing that enabling TLS can be done from the OperatorHub UI through a switch. 
- External plugin registry URL should taken into account.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by l0rd** [comment] 2019-08-02 17:44
I am adding the `7.0.0` because it's valuable and the PR already been created but @nickboldt please verify that the PR doesn't have regressions risks.

**Comment by slemeur** [comment] 2019-08-06 17:32
@nickboldt could you reference the PR of this issue?

**Comment by nickboldt** [comment] 2019-08-06 19:03
It's linked above, @slemeur but here you go: https://github.com/eclipse/che-operator/pull/63

**Comment by ibuziuk** [comment] 2019-08-14 13:13
@nickboldt @davidfestal can we close this one?

**Comment by davidfestal** [comment] 2019-08-14 13:17
Yes

**Closed as completed** 2019-08-20 13:18 UTC
Labels: severity/P2, area/che-operator
