### ISSUE TITLE
Dogfooding instance fails to start workspace

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#20052] opened 2021-06-30 14:30 UTC
### Describe the bug
The dogfooding instance fails to start the following devfile with a timeout:

<details>

```yaml
apiVersion: 1.0.0
metadata:
  name: linklessbuild2
projects:
  - name: theia
    source:
      startPoint: master
      location: 'https://github.com/eclipse-theia/theia'
      type: git
  - name: vscode-test-extension
    source:
      startPoint: master
      location: 'https://github.com/RomanNikitenko/vscode-test-extension.git'
      type: git
    clonePath: test/vscode-test-extension
  - name: che-theia
    source:
      startPoint: master
      location: 'https://github.com/eclipse-che/che-theia'
      type: git
components:
  - id: ms-vscode/node-debug2/latest
    type: chePlugin
    alias: node-debug
  - mountSources: true
    endpoints:
      - attributes:
          protocol: http
          public: 'true'
        name: theia-dev-flow
        port: 3010
    memoryLimit: 5Gi
    type: dockerimage
    alias: che-dev
    image: 'quay.io/eclipse/che-theia-dev:next'
    env:
      - value: 2504;
        name: THEIA_PLUGIN_ENDPOINT_DISCOVERY_PORT
  - mountSources: true
    memoryLimit: 1Gi
    type: dockerimage
    alias: plugin-host
    image: 'quay.io/eclipse/che-theia-dev:next'
    env:
      - value: 2504;
        name: THEIA_PLUGIN_ENDPOINT_DISCOVERY_PORT
      - value: 'local-dir:///projects/plugins1/'
        name: THEIA_PLUGINS
      - value: /projects/java-11-openjdk
        name: JAVA_HOME
  - id: eclipse/che-theia/next
    memoryLimit: 2048Mi
    registryUrl: 'https://eclipse-che.github.io/che-plugin-registry/main/v3/'
    type: cheEditor
  - id: redhat/java11/latest
    type: chePlugin
  - id: che-incubator/typescript/latest
    memoryLimit: 2Gi
    type: chePlugin
  - id: timonwong/shellcheck/latest
    type: chePlugin
```

</details>

### Che version

 - [ ] dogfooding instance at https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/

### Steps to reproduce

Make the new workspace with the devfile above.

### Expected behavior
The workspace should run.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by benoitf** [comment] 2021-06-30 15:30
![Screenshot 2021-06-30 at 17 28 43](https://user-images.githubusercontent.com/436777/123988907-b1867e00-d9c8-11eb-910f-e6100b5aa216.png)

anyway I tried your devfile and it's starting. But you're referring to master branch that has been renamed to main (leading an error when opening the IDE)

**Comment by tsmaeder** [comment] 2021-07-01 07:32
> But you're referring to master branch that has been renamed to main

@benoitf main vs. master is a red herring: my problem happens a long time before the IDE ever opens.

**Comment by tsmaeder** [comment] 2021-07-01 07:32
Also, looks like Che to me 🤷 

![Capture](https://user-images.githubusercontent.com/13163770/124084481-4f249080-da4f-11eb-888a-330fa74cc211.PNG)

**Comment by l0rd** [comment] 2021-07-01 12:49
@tsmaeder since the same devfile on the same cluster  works for others, your problem should be related to a particular configuration of your account or to some objects that are in the namespace and are using resources. I think it would be useful if you could provide your namespace OpenShift events when you start the workspace.

@ibuziuk do you know if we are showing a specific error when there are not enough resources to start the workspace (CPU/RAM/PVs) or if a PV fails to get attached. Or are we just failing for timeout?

@sleshchenko I think that the new dashboard is providing less details about errors, is there something that comes to your mind here? Something @tsmaeder can do to get more information on the nature of the error.

**Comment by sleshchenko** [comment] 2021-07-02 07:09
I have created an issue to improve the situation with devworkspaces: Dashboard should expose workspace related events in output https://github.com/eclipse/che/issues/20066

But then I checked and see it's devfile v1. So, a new dashboard provides as many details as the previous one used to provide.
@tsmaeder any info in output?

**Comment by sleshchenko** [comment] 2021-07-02 07:17
I see two issues:

1. Workspace pod can't be created due

> docker pull quay.io/eclipse/che-machine-exec@sha256:916929bb252f1bff813327e3bffa3641c4f79fcde802f00349aa4cb644826fe9
Error response from daemon: manifest for quay.io/eclipse/che-machine-exec@sha256:916929bb252f1bff813327e3bffa3641c4f79fcde802f00349aa4cb644826fe9 not found: manifest unknown: manifest unknown

2. Mkdir pod hangs due:

> the mkdir-pod says "Unable to attach or mount volumes: unmounted volumes=[claim-che-workspace], unattached volumes=[default-token-tvnln claim-che-workspace]: timed out waiting for the condition"

**Comment by benoitf** [comment] 2021-07-02 07:49
@sleshchenko I don't see how you could reference the issue 'workspace pod could not pull che-machine-exec'

as the devfile specified in the issue is:
```yaml
  - id: eclipse/che-theia/next
    memoryLimit: 2048Mi
    registryUrl: 'https://eclipse-che.github.io/che-plugin-registry/main/v3/'
```

then it doesn't fetch definition from the current registry but from an external location which has no sha256

**Comment by tsmaeder** [comment] 2021-07-02 08:08
>  I don't see how you could reference the issue 'workspace pod could not pull che-machine-exec'

I clicked on the wrong one (the original). As far as that is concerned, are all "next" tags not working? What do I need to fix in my devfiles?

**Comment by sleshchenko** [comment] 2021-07-02 10:34
So, mkdir pod hangs(related to some old workspace) and prevents other pods from starting due they use the same PVC. It may happen to happen due different reasons, so probably Che Server should make sure no other pods use workspace PVC before creating a new deployment.

But after I solved the issue with mkdir, the workspace deployment can not be started due artifacts plugin broker:
> 2021/07/02 10:27:59 Couldn't connect to endpoint 'wss://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/api/websocket', due to error 'websocket: bad handshake'

@tsmaeder please try to restart workspace now.

**Comment by sleshchenko** [comment] 2021-07-02 11:16
well, I filtered all the pods and there are a lot of hangs workspaces pods, their types:
- mkdir: Unable to attach or mount volumes: unmounted volumes=[claim-che-workspace], unattached volumes=[claim-che-workspace default-token-vpjtx]: timed out waiting for the condition
- rm: Unable to attach or mount volumes: unmounted volumes=[claim-che-workspace], unattached volumes=[claim-che-workspace default-token-vpjtx]: timed out waiting for the condition
- workspace: 2021/07/02 10:27:59 Couldn't connect to endpoint 'wss://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/api/websocket', due to error 'websocket: bad handshake'

**Comment by sleshchenko** [comment] 2021-07-05 14:01
One really interesting namespace
![Screenshot_20210705_165958](https://user-images.githubusercontent.com/5887312/124482974-862dd580-ddb2-11eb-80c8-d3a8e5d20818.png)

So, Che Server probably should better take care of all pods in the namespaces but not only the current workspace one.

**Comment by tsmaeder** [comment] 2021-07-06 09:11
This morning, workspace startup fails when running the plugin broker with the following log:

```
2021/07/06 09:08:36 Broker configuration
2021/07/06 09:08:36   Push endpoint: wss://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/api/websocket
2021/07/06 09:08:36   Auth enabled: true
2021/07/06 09:08:36   Runtime ID:
2021/07/06 09:08:36     Workspace: workspaceg4ig0zobvwy5fg79
2021/07/06 09:08:36     Environment: default
2021/07/06 09:08:36     OwnerId: 6df74fb6-7cc7-43e5-9bb7-4a524c8abf29
2021/07/06 09:08:36   CA bundle certificates path /public-certs
2021/07/06 09:08:36 Couldn't connect to endpoint 'wss://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/api/websocket', due to error 'websocket: bad handshake'
```

No extra pods are present.

**Comment by tsmaeder** [comment] 2021-07-07 07:11
Raising this one to "blocker" status, as it's preventing me 100% from working on che-theia.

**Comment by sleshchenko** [comment] 2021-07-07 14:28
I'll take a look bad handshake issue but ATM it has extra pod:
![Screenshot_20210707_172801](https://user-images.githubusercontent.com/5887312/124777245-bc9d5900-df48-11eb-8bb4-b7bbb5e1a105.png)

**Comment by sleshchenko** [comment] 2021-07-07 15:01
> 2021/07/06 09:08:36 Couldn't connect to endpoint 'wss://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/api/websocket', due to error 'websocket: bad handshake'

I don't have any good idea for that different than an infrastructure issue.
The same plugin broker image, the same configuration works for me but does not work for the other 4 people.

**Comment by ibuziuk** [comment] 2021-07-08 07:14
> Raising this one to "blocker" status, as it's preventing me 100% from working on che-theia.

Why this issue is reported as a blocker? Is it the only instance that can be used for the theia development? 
Just for the record, I can start a workspace from the description without any issues after changing the branch to 'main'
@tsmaeder are you still facing https://github.com/eclipse/che/issues/20052#issuecomment-874596603 ?

**Comment by tsmaeder** [comment] 2021-07-08 08:31
@ibuziuk using the dogfooding instance is the _recommended_ way to work. Some time ago, I was running Che myself on my local machine (docker desktop) and when I frequently ran into trouble with my installation (and tried to get help with fixing them), I was told in no uncertain terms to use the dogfooding instance instead.
I don't care how we achieve this, but I _need_ a stable environment to do my daily work that does not break every other week. I think the _best_ way to achieve this would be to mandate _everyone_ to use Che to develop Che, that way we would immediately detect serious problems. 
This is a blocker because I've been able to run a che-theia dev workspace exactly one day out of the last week. That's one of the definitions of "blocker" explicitly mentioned in the wiki. I might face a problem today or I may not. But unless we actually find and fix the problem, how do we know it's not coming back tomorrow?

**Comment by ibuziuk** [comment] 2021-07-08 09:36
@tsmaeder well, I believe you should have a backup up options based on crc / minikube to do the everyday job if for some reason the other instance is not available. There could be outages on the infrastructure OSD level, that we can not control. 

Anyway, are you still facing the https://github.com/eclipse/che/issues/20052#issuecomment-875679752 ?

**Comment by tsmaeder** [comment] 2021-07-08 09:56
I was able to start the workspace that failed yesterday. Did we fix anything or is it just random?

**Comment by ibuziuk** [comment] 2021-07-08 12:16
> Did we fix anything or is it just random?

Nothing, but removal of the stale mkdir / rm pods from the namespace (this can be performed by a user, admin rights are not required)

**Comment by tsmaeder** [comment] 2021-07-08 12:21
No stale mkdir pods were present in my namespace yesterday when I had the failure mentioned here (https://github.com/eclipse/che/issues/20052#issuecomment-874596603) yesterday (I checked in the openshift console). I doubt that this is the problem. Looks still random to me 🤷 .

**Comment by ibuziuk** [comment] 2021-07-12 11:29
@tsmaeder do you mind closing the issue if not reproducible ?

**Comment by tsmaeder** [comment] 2021-07-12 12:07
I'm not sure, did we

* understand what the problem was?
* improve error reporting to have a better understanding next time the problem happens?
* fix the code or procedures so it doesn't happen again?

Any of those would make me happy. Otherwise, I think we should wait a couple of weeks before concluding the problem went away.

**Comment by ibuziuk** [comment] 2021-07-26 09:53
@tsmaeder 2 weeks since the last comment. Are you still able to reproduce or the issue can be closed?

**Comment by tsmaeder** [comment] 2021-07-26 13:46
Today, I get a different error message on the exact same workspace:

```
Failed to run the workspace: "Failure executing: POST at: https://172.30.0.1/apis/route.openshift.io/v1/namespaces/tsmaeder-che/routes. Message: Route.route.openshift.io "route0pv47qmr" is invalid: spec.host: Invalid value: "route2bwva3.": host must conform to DNS 952 subdomain conventions. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.host, message=Invalid value: "route2bwva3.": host must conform to DNS 952 subdomain conventions, reason=FieldValueInvalid, additionalProperties={})], group=route.openshift.io, kind=Route, name=route0pv47qmr, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Route.route.openshift.io "route0pv47qmr" is invalid: spec.host: Invalid value: "route2bwva3.": host must conform to DNS 952 subdomain conventions, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={})."
```

**Comment by svor** [comment] 2021-07-28 09:32
Have the same problem:
![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2021 07 28-12_29_33](https://user-images.githubusercontent.com/1271546/127299118-ff57a9c5-92b4-4e6b-a68a-478e506dfbc6.png)

@ibuziuk any idea what is wrong?

**Comment by ibuziuk** [comment] 2021-07-28 09:59
this DNS 952 subdomain issue is not infrastructure relate. It has been already reported as part of https://github.com/eclipse/che/issues/20072

**Comment by svor** [comment] 2021-07-28 10:26
@ibuziuk thanks. So, it looks like we don't have a workaround to avoid that and it means that dogfooding instance can not be used for daily work right now which is kind of blocker if you don't have a local cluster.

**Comment by ibuziuk** [comment] 2021-08-06 08:50
DevWorkspace has been disabled. Closing

**Comment by tsmaeder** [comment] 2021-08-06 14:10
I just tried to start a workspace on the dogfooding instance and I'm still getting the dns 952 message: 

> Failed to run the workspace: "Failure executing: POST at: https://172.30.0.1/apis/route.openshift.io/v1/namespaces/tsmaeder-che/routes. Message: Route.route.openshift.io "routempmf80tc" is invalid: spec.host: Invalid value: "routenlis6s.": host must conform to DNS 952 subdomain conventions. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.host, message=Invalid value: "routenlis6s.": host must conform to DNS 952 subdomain conventions, reason=FieldValueInvalid, additionalProperties={})], group=route.openshift.io, kind=Route, name=routempmf80tc, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Route.route.openshift.io "routempmf80tc" is invalid: spec.host: Invalid value: "routenlis6s.": host must conform to DNS 952 subdomain conventions, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={})."

**Comment by ibuziuk** [comment] 2021-08-09 07:45
@tsmaeder which workspace / devfile are you using?

**Comment by tsmaeder** [comment] 2021-08-09 08:13
Still the same as the one in the description.

**Comment by ibuziuk** [comment] 2021-08-09 08:52
Fixed by removing `CHE_INFRA_OPENSHIFT_ROUTE_HOST_DOMAIN__SUFFIX: ` from CR
operator set it incorrectly after enabling / disabling DevWrorkspace - https://github.com/eclipse/che/issues/20274

**Closed as completed by ibuziuk** 2021-08-09 08:52 UTC
Labels: kind/bug, severity/blocker, status/info-needed, area/hosted-che
