### ISSUE TITLE
Happy path tests failed on 'Add debug configuration options'

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#15586] opened 2019-12-28 11:05 UTC
### Describe the bug
Happy path E2E tests failed on Singleuser/Multiuse Eclipse Che deployed to minikube 1.11 on step "**Add debug configuration options**":
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/1541/
<details>
 <summary>Test log</summary>
 <pre>
    ✓ Check content of the launched application (1718ms)
        ▼ TopMenu.selectOption "Debug"
        ▼ TopMenu.clickOnTopMenuButton "Debug"
        ▼ Ide.closeAllNotifications
        ▼ TopMenu.clickOnSubmenuItem "Open Configurations"
        ▼ Editor.waitEditorAvailable "launch.json"
        ▼ Editor.waitTab "launch.json"
        ▼ Editor.waitEditorOpened "launch.json"
        ▼ Editor.selectTab "launch.json"
        ▼ Ide.closeAllNotifications
        ▼ Editor.waitTab "launch.json"
        ▼ Editor.clickOnTab "launch.json"
        ▼ Ide.closeAllNotifications
        ▼ Editor.waitTabFocused "launch.json"
    ✓ Open debug configuration file (2695ms)
        ▼ Editor.moveCursorToLineAndChar title: "launch.json" line: "11" char: "7"
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.performKeyCombination title: "launch.json" text: ""
        ▼ Editor.clickOnSuggestion "Java: Launch Program in Current File"
        ▼ Editor.waitTabWithUnsavedStatus "launch.json"
    1) Add debug configuration options

  23 passing (13m)
  1 pending
  1 failing

  1) Validation of debug functionality
       Add debug configuration options:
     TimeoutError: Waiting for element to be located By(xpath, //div[text()='launch.json']/parent::li[contains(@class, 'theia-mod-dirty')])
Wait timed out after 300010ms
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at asyncRun (/tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2927:27)
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:668:7
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
 </pre>
</details>

### Screenshot
![screenshot-Add_debug_configuration_options](https://user-images.githubusercontent.com/1197777/71542725-7db13f00-2972-11ea-9bce-ad20a4b27633.png)

### Screencast
https://youtu.be/Zk424t-nozI

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
https://github.com/eclipse/che/blob/master/tests/e2e/tests/e2e_happy_path/HappyPath.spec.ts

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.11
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl:next with helm installer
   - [x] che-operator:nightly
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: CRW CCI

### Additional context
There is possible fix available https://github.com/eclipse/che/pull/15353
The issue isn't reproduced on Multiuser Eclipse Che installed by chectl:next with operator installer.

**Comment by tolusha** [comment] 2020-01-02 07:31
@dmytro-ndp 
The video is private.

**Comment by dmytro-ndp** [comment] 2020-01-02 09:29
@tolusha: thanks for notice. Access has been fixed.

**Comment by tolusha** [comment] 2020-01-09 07:33
The first things I would like to know if this issue is reproducible on the pure Theia.

**Comment by tsmaeder** [comment] 2020-01-09 09:37
It looks like we have autosave of editors on per default now. The test is waiting for the launch.json to be "dirty", but autosave might already have executed by the time the check for "dirty" is done. 
Not sure why the test is checking for "dirty", though: it seems to me this is just trying to set up some precondition, which i suspect is that launch.json is saved and contains the proper content.

**Comment by rhopp** [comment] 2020-01-09 11:23
@tsmaeder I'm reworking this right now to not edit launch.json in the test itself, but include it in the devfile directly instead.

**Comment by rhopp** [comment] 2020-01-15 08:31
Resolved by https://github.com/eclipse/che/pull/15643

**Closed as completed by rhopp** 2020-01-15 08:31 UTC
Labels: kind/bug, severity/blocker
