### ISSUE TITLE
Pull request panel distracts

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#7304] opened 2017-11-10 12:57 UTC
### Description
Sometimes appearing and disappearing of pull request panel is not comfortable:
- After IDE loading, clicking on a project causes appearance of the panel. In most cases it is useless and uses editor's space.
- If two (or more) projects are added into workspace and some of them aren't under git, changing selection in project explorer between them or even tabs in editor causes the panel appearance and disappearance. And a user has no ability to alter or turn off such annoying behaviour. If someone have to work with two projects, where one of them isn't project under git - it's a disaster.

### Reproduction Steps
1. Open a workspace
2. Select a project under git in project explorer

Screencast:
![pull-request-panel](https://user-images.githubusercontent.com/15607393/32659408-4e8b313c-c627-11e7-9610-03d7a1407d11.gif)

- [ ] Once it closed don't show it again until page is refreshed
- [ ] If panel is opened and the current project isn't a git project then some massage should be dipslayed

**Comment by vinokurig** [comment] 2017-11-10 13:19
The problem is not in the pull-request panel, it happens because when the right part has no panels to show and when selection is set to Git project pull request panel is added to part and it appears. Also when selection is set to project without Git, pull request panel disappears from part and the part hides. The problem is in the part's behavior.

**Comment by vparfonov** [comment] 2017-11-10 13:57
I think show PullRequest panel just because project under Git control is not good idea. User should to decide code is ready for PR, then make PR.

**Comment by sunix** [comment] 2017-11-10 15:10
Honestly I don't feel this is annoying in real life (real life means when using Che every day with real projects):

1. In real life, you work 100% of your time with the same Git provider. The screenshot shows "fake" project, these kind of behavior of a feature should be commented for real use case.
2. It's good to show the panel so people know that it exists, closing it once should close by default for this project.
3. maybe if you don't use this feature, we should have an option to hide the panel in the preferences. But please do not disable it by default :) ... at least this should be discuss in a more global discussion on how it can work well with the new git panel (maybe adding a button "Create a PR").

To me, this issue is not priority at all and would prefer to see git panel improvements rather than this one.
Thanks

**Comment by skabashnyuk** [comment] 2017-11-10 20:08
Why don't we reinvent a wheel and do like IntelliJ is doing?
To have some state for opened panel(1) and hidden (2)
<img width="1280" alt="2017-11-10 22 06 13 2" src="https://user-images.githubusercontent.com/1614429/32676523-9e28be9e-c663-11e7-8189-ae9638ee49ba.png">

**Comment by AndrienkoAleksandr** [comment] 2017-11-11 13:12
I totally agree with @skabashnyuk . "show/hide panel button" should exist. I know main argument to remove them it's a saving more space. But I don't think we should throw away such important and usefull conception. I usually always used "show/hide" button panel feature. And It was very usefull and easy to use. It was nice user experience for me. With current mechanism showing panel I spend more time to find and show or hide some panels. I need look on a lot icons and think what should I click to get expected result. And I need click more than one button. I think classic way to show/hide panels was better. Desktop Eclipse and IntelliJ use this way. But any way  it's only mine own opinion and user experience.

**Comment by bmicklea** [comment] 2017-11-11 15:29
The PR panel is a differentiator, we need to highlight it for people. However once it’s closed it should stay closed. Having a preference to set whether it’s open on project load (default) or closed on project load is fine.

**Comment by skabashnyuk** [comment] 2017-11-11 15:50
@bmicklea  what would be an action to bring it back?

**Comment by bmicklea** [comment] 2017-11-11 19:59
It would be closed but still there on the right - you’d just click it to open.  Or am I misunderstanding the question?

**Comment by skabashnyuk** [comment] 2017-11-11 20:05
> It would be closed but still there on the right

That is a good question. I don't know.

**Comment by bmicklea** [comment] 2017-11-11 20:06
Yes - were not removIng it, just keeping it closed once it’s closed.

-- 

Brad Micklea // Developer Tools // 416.707.0792

**Comment by sunix** [comment] 2017-11-17 09:46
but there is nothing to do ... it already keeping closed once it's closed

**Comment by sunix** [comment] 2017-11-17 09:49
Could we just close this issue because it is not an issue in my opinion

**Comment by sunix** [comment] 2017-11-17 10:13
OK
cannot reproduce with 2 git projects (close panel, switch project, panel is still closed)
can reproduce with 1 git project and 1 non git project ( close panel, switch project, switch project, panel reopens)

Then in real life I personally never have project not managed by git ... even for my svn project I use git-svn. I would prefer to see git panel improvements rather than this one. But this is my opinion.

**Comment by skabashnyuk** [comment] 2017-11-21 07:08
It's really distracting. Example
I have 1 project managed by git. Each time I start workspace I see this panel and close it. 
What is the point of this behavior? I don't need it after workspace start. But when I will need it I have to restart my workspace?

I think the goal of this issue is to find the proper way of hiding closing this panel.
For example like this https://github.com/eclipse/che/issues/7304#issuecomment-343573433

@sunix @slemeur or you think this is a right behavior?

**Comment by AndrienkoAleksandr** [comment] 2017-11-21 07:56
@skabashnyuk You need do three steps:
1. Click on the panels icon:
![clickonpanelbuttons](https://user-images.githubusercontent.com/6873095/33060435-e01670ae-cea0-11e7-94c6-fc4cd44c08e0.png)
2. In the list icons find left panel icon (icons are small so it's not easy...):
![screenwithpanelsicon](https://user-images.githubusercontent.com/6873095/33060477-06e1713e-cea1-11e7-8626-3cb0868d744c.png)
3. Click on the found icon(icon is small and click is not easy too..):
![foundiconpng](https://user-images.githubusercontent.com/6873095/33060499-1f7199ea-cea1-11e7-8a46-3ce1343eee3e.png)
4. And finally you will see pull request panel:
![pullrequestpanel](https://user-images.githubusercontent.com/6873095/33060530-3715eab0-cea1-11e7-811e-fee6612af1c2.png)
Show/hide button was much easier: only ONE CLICK.

**Comment by skabashnyuk** [comment] 2017-11-21 08:05
Wow that is so obvious and innovative approach to show pull request panel. Don't understand how I've missed it.

**Comment by slemeur** [comment] 2017-11-21 08:50
The pull request panel is not supposed to be displayed all the time. It's a one time action that user should be able to call from:
- A menu item (in this case, the user will need to use his mouse)
- using the command palette (in this case, the user will not have to leave the keyboard)

Once the pull request proceed, user will likely hide the panel and get the editor maximize.

**Comment by slemeur** [comment] 2017-11-21 08:52
Linking to https://github.com/eclipse/che/issues/4993

**Comment by sunix** [comment] 2017-11-22 11:02
@skabashnyuk in real life I don't restart a workspace all the time. But maybe we are missing layout preferences ... that's all. For instance each time I start a workspace I minimise the Dashboard pane. When I have a panel layout settings and restart the workspace or open another workspace, I would like Che to use the same previous layout.
To reopen the PR panel, why not having a button like the dashboard pane ?

**Closed as completed** 2017-12-07 08:56 UTC
Labels: kind/task

**Comment by slemeur** [comment] 2017-12-20 13:32
Linking to #7975
