### ISSUE TITLE
Cannot create a new stack in OCP

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#9648] opened 2018-05-08 09:38 UTC
**Reproduction Steps:**
1. Open **Stacks** list from the **Dashboard**.
2. Click on the **Add Stack** button.
3. Type stack name and click the **Save** button.

**Expected result:**
The new stack created.

**Actual result:** 
Creating failed. There is "**Infrastructure not found for type: compose**" error notification.

**OS and version:**
Che 6.5.0-SNAPSHOT; Chrome 65.0; Fedora 25

**Additional information:**
![selection_256](https://user-images.githubusercontent.com/7760565/39749883-75970220-52bc-11e8-8adf-325d32f63a53.png)

![nimbus-record-video-2018-05-08-12-21-16](https://user-images.githubusercontent.com/7760565/39749791-3bfbd1b2-52bc-11e8-9d84-33c80ea49885.gif)

**Comment by eivantsov** [comment] 2018-05-08 11:59
Duplicate of https://github.com/eclipse/che/issues/9523

**Closed as completed** 2018-05-08 12:23 UTC
Labels: kind/bug, status/in-progress, severity/P1
