### ISSUE TITLE
Adapt Che Theia to use VSCode builtins instead of deprecated Theia extensions

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#15770] opened 2020-01-21 16:17 UTC
### Is your task related to a problem? Please describe.

In Theia upstream, several extensions are deprecated and going to be removed soon, see https://github.com/eclipse-theia/theia/pull/6933
VS Code built-in extensions are used instead, see https://github.com/eclipse-theia/theia/pull/6883

### Describe the solution you'd like

We need to adapt Che Theia to exclude the deprecated extensions and include the corresponding VS Code builtins instead.

### Additional context

`@theia/cli` provides `download:plugins` script to fetch the VS Code plugins.
For the details, see:
- the CHANGELOG https://github.com/eclipse-theia/theia/pull/6883/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR12-R15
- example `package.json` https://github.com/eclipse-theia/theia/pull/6883/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R74

**Comment by gattytto** [comment] 2020-01-21 18:42
https://github.com/eclipse/che/issues/14759 this seems to be a builtins sprint tho I think there's yet another one made by @tsmaeder

**Comment by tolusha** [comment] 2020-01-22 07:58
@azatsarynnyy 
As @gattytto noticed, the work is almost done https://github.com/eclipse/che-theia/pull/572

**Comment by azatsarynnyy** [comment] 2020-01-22 09:29
@tolusha do you think we should have yet another mechanism of installing VS Code built-in extensions apart from the one provided by Theia upstream?

I understand that there's work on Che Theia generator that is in progress. And it has been started before it was added to Theia. But what's the point of introducing and supporting our own mechanism while very similar one is already supported upstream? We could just rely on it after slightly adapting Che Theia build.
Maybe I just misunderstood something... :slightly_smiling_face: 

@benoitf WDYT?

**Comment by tsmaeder** [comment] 2020-01-22 09:33
Duplicate of https://github.com/eclipse/che/issues/14759. Please discuss issues with the current PR over there.

**Comment by benoitf** [comment] 2020-01-22 09:57
@azatsarynnyy Anatolii's PR is a base to start but of course we should use now the upstream download-script to grab plug-ins (and how we specify the list of plug-ins in package.json file) (through the assembly template)

**Comment by benoitf** [comment] 2020-01-22 09:58
moving to https://github.com/eclipse/che/issues/14759

**Closed as completed by benoitf** 2020-01-22 09:58 UTC
Labels: kind/task, severity/P1, area/editor/theia
