### ISSUE TITLE
Dashboard isn't loaded

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#18930] opened 2021-02-01 07:59 UTC
### Describe the bug
Dashboard isn't loaded

### Che version

 - [x] nightly

### Steps to reproduce
1. Deploy Eclipse Che nightly
2. Open Dashboard 

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Screenshots
![Screenshot from 2021-02-01 09-58-17](https://user-images.githubusercontent.com/1640675/106430139-0fdc1e80-6474-11eb-89ab-a5aab23d8034.png)

### Installation method
   - [x] chectl
     * `chectl server:deploy --platform minikube`

### Environment
   - [x] my computer
       - [x] Linux

**Comment by RomanNikitenko** [comment] 2021-02-01 08:24
Looks like it's duplicate https://github.com/eclipse/che/issues/18929

**Comment by sleshchenko** [comment] 2021-02-01 08:45
Seems it's related to fact that v3/plugins starts return htmls instead of index.json

![Screenshot_20210201_104416](https://user-images.githubusercontent.com/5887312/106434611-77956800-647a-11eb-87f0-4792aefd107d.png)

Investigating more

**Comment by sleshchenko** [comment] 2021-02-01 08:54
`.htaccess` is not propagated into plugin-registry container anymore.

```bash
bash-5.0# ls -la
total 232
drwxr-xr-x 49 root root  4096 Jan 29 14:12 .
drwxr-xr-x  6 root root  4096 Jan 29 14:12 ..
drwxr-xr-x  3 root root  4096 Jan 29 14:12 atlassian
drwxr-xr-x  3 root root  4096 Jan 29 14:12 bazelbuild
drwxr-xr-x  3 root root  4096 Jan 29 14:12 bmewburn
drwxr-xr-x  6 root root  4096 Jan 29 14:12 broadcommfd
drwxr-xr-x  3 root root  4096 Jan 29 14:12 castwide
drwxr-xr-x  3 root root  4096 Jan 29 14:12 cdr
drwxr-xr-x  5 root root  4096 Jan 29 14:12 che-incubator
drwxr-xr-x  3 root root  4096 Jan 29 14:12 containers
drwxr-xr-x  4 root root  4096 Jan 29 14:12 dart-code
drwxr-xr-x  3 root root  4096 Jan 29 14:12 dbaeumer
drwxr-xr-x  3 root root  4096 Jan 29 14:12 dirigiblelabs
drwxr-xr-x  3 root root  4096 Jan 29 14:12 donjayamanne
drwxr-xr-x  4 root root  4096 Jan 29 14:12 eamodio
drwxr-xr-x  5 root root  4096 Jan 29 14:12 eclipse
drwxr-xr-x  3 root root  4096 Jan 29 14:12 eclipse-cdt
drwxr-xr-x  3 root root  4096 Jan 29 14:12 errata-ai
drwxr-xr-x  3 root root  4096 Jan 29 14:12 esbenp
drwxr-xr-x  4 root root  4096 Jan 29 14:12 felixfbecker
drwxr-xr-x  3 root root  4096 Jan 29 14:12 gattytto
drwxr-xr-x  3 root root  4096 Jan 29 14:12 github
drwxr-xr-x  3 root root  4096 Jan 29 14:12 golang
drwxr-xr-x  4 root root  4096 Jan 29 14:12 haskell
-rw-r--r--  1 root root 33022 Jan 29 14:12 index.json
drwxr-xr-x  3 root root  4096 Jan 29 14:12 joaompinto
drwxr-xr-x  3 root root  4096 Jan 29 14:12 lfs
drwxr-xr-x  4 root root  4096 Jan 29 14:12 mads-hartmann
drwxr-xr-x  3 root root  4096 Jan 29 14:12 microprofile-community
drwxr-xr-x  3 root root  4096 Jan 29 14:12 microshed
drwxr-xr-x  3 root root  4096 Jan 29 14:12 moby
drwxr-xr-x  3 root root  4096 Jan 29 14:12 ms-kubernetes-tools
drwxr-xr-x  3 root root  4096 Jan 29 14:12 ms-python
drwxr-xr-x  4 root root  4096 Jan 29 14:12 ms-vscode
drwxr-xr-x  3 root root  4096 Jan 29 14:12 octref
drwxr-xr-x  5 root root  4096 Jan 29 14:12 pizzafactory
drwxr-xr-x 22 root root  4096 Jan 29 14:12 redhat
drwxr-xr-x  4 root root  4096 Jan 29 14:12 redhat-developer
drwxr-xr-x  3 root root  4096 Jan 29 14:12 rogalmic
drwxr-xr-x  3 root root  4096 Jan 29 14:12 rust-lang
drwxr-xr-x  3 root root  4096 Jan 29 14:12 scalameta
drwxr-xr-x  3 root root  4096 Jan 29 14:12 sdkbox
drwxr-xr-x  3 root root  4096 Jan 29 14:12 sonarsource
drwxr-xr-x  3 root root  4096 Jan 29 14:12 timonwong
drwxr-xr-x  3 root root  4096 Jan 29 14:12 vscode
drwxr-xr-x  3 root root  4096 Jan 29 14:12 vscodevim
drwxr-xr-x  3 root root  4096 Jan 29 14:12 vuejs
drwxr-xr-x  4 root root  4096 Jan 29 14:12 ws-skeleton
drwxr-xr-x  3 root root  4096 Jan 29 14:12 zowe
drwxr-xr-x  4 root root  4096 Jan 29 14:12 zxh404
```

I'm not 100% sure but I assume it may be caused by https://github.com/eclipse/che-plugin-registry/pull/815

@benoitf Could you take a look?

**Comment by sleshchenko** [comment] 2021-02-01 09:47
P.S. There is a dedicated issue for dashboard not to fail if something is wrong in a component https://github.com/eclipse/che/issues/18758

**Comment by sleshchenko** [comment] 2021-02-01 11:04
Should be fixed by https://github.com/eclipse/che-plugin-registry/pull/820

**Closed as completed by sleshchenko** 2021-02-01 11:04 UTC
Labels: kind/bug, area/plugin-registry, area/dashboard
