### ISSUE TITLE
Dashboard tear down server attributes after change port or protocol on the server page

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#12212] opened 2018-12-17 15:04 UTC
### Description
1. Create new workspace with help 'java' stack.
2. Open workspace config on the user dashboard.
3. In the workspace config add server attributes to the server `codeserver`:
FROM
```
 "codeserver": {
              "port": "9876",
              "protocol": "http"
            },
```
TO: 
```
 "codeserver": {
              "attributes": {
                "key": "value"
              },
              "port": "9876",
              "protocol": "http"
            },
```

4. Save workspace config by 'Save Button'.
5. Open 'Servers' page on the user dashboard.
6. Edit server `codeserver` for dev-machine: change port to 9877 and save changes.
7. Go to the workspace config on the user dashboard.
Actual result: port was changed for  server `codeserver`, but user dashboard tear down previous server attributes.
Expected result: user dashboard should save new port value and doesn't tear down previous server attributes:
```
 "codeserver": {
              "attributes": {
                     "key": "value"
             },
              "port": "9877",
              "protocol": "http"
            }
```

**OS and version:** 
minikube version: v0.30.0

**Comment by gorkem** [comment] 2019-08-23 23:14
@AndrienkoAleksandr Is this still valid?

**Comment by azatsarynnyy** [comment] 2020-02-07 16:32
closing it as the issue is related to Che 6

**Closed as completed by azatsarynnyy** 2020-02-07 16:32 UTC
Labels: kind/bug
