### ISSUE TITLE
Installation documentation of Eclipse Che on Docker Desktop

### ISSUE THREAD

**Issue by amoldhondse** [eclipse-che/che#18692] opened 2020-12-23 12:08 UTC
Not able to find documentation for running eclipse che on Docker Desktop on Mac ?
Link on this is not working - 
https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-docker-desktop/

**Comment by AndrienkoAleksandr** [comment] 2020-12-23 12:59
Sorry, Could you share more details: logs, errors ?

**Comment by amoldhondse** [comment] 2020-12-23 13:08
The above link is broken ? can you share the link or instructions - eclipse che on Docker Desktop on Mac ?

**Comment by AndrienkoAleksandr** [comment] 2020-12-23 14:12
https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-docker-desktop/#_adding_certificates_to_google_chrome_and_safari_on_macos

**Comment by AndrienkoAleksandr** [comment] 2020-12-23 14:14
Strange https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-docker-desktop/ this link is working for me. Maybe some network issue...

**Comment by amoldhondse** [comment] 2020-12-23 16:12
lick on below link and it gives error for initial setup
**Running Eclipse Che on Kubernetes using Docker Desktop on macOS or Windows.** it redirects to https://che.eclipseprojects.io/

**Comment by AndrienkoAleksandr** [comment] 2020-12-23 16:51
Ok, I asked Eclipse web master to take a look.

**Comment by AndrienkoAleksandr** [comment] 2020-12-23 16:56
@boczkowska Sorry, I think it should work... But, could you check, please, that link https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-docker-desktop/ is working in the che-docs source code.

**Comment by amoldhondse** [comment] 2020-12-24 01:50
@AndrienkoAleksandr The internal link is the problem as mentioned before where I believe the instructions regarding Running eclipse che on Desktop docker is specified,is there a alternate documentation regarding this configuration that I can use.

**Comment by themr0c** [comment] 2020-12-24 06:39
In the page  https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-docker-desktop/, the link "See Running Eclipse Che on Kubernetes using Docker Desktop on macOS or Windows." to the blog https://che.eclipseprojects.io/ is currently broken, because the blog is broken. This is a duplicate of the following issue: https://github.com/eclipse/che/issues/18606

**Closed as completed by themr0c** 2020-12-24 06:39 UTC
Labels: kind/question, area/doc
