### ISSUE TITLE
Authentication flow doesn't work

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#18791] opened 2021-01-13 10:41 UTC
### Describe the bug

Authentication popup cant reach the keycloak API.
### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. In the dashboard create a workspace.
2. Go to the projects tab and click `Add Project` button.
3. Chose `GitHub` and click the `Connect your GitHub account` button.

See: A popup with unavailable address is shown:
![Screenshot from 2021-01-13 12-02-57](https://user-images.githubusercontent.com/7668752/104441350-36f1af80-559c-11eb-8f3f-a035fbfb7019.png)

### Expected behavior

The popup should open the redirected url from keycloak.
### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by benoitf** [comment] 2021-01-13 10:56
@vinokurig as dashboard is switching over to dashboard-next maybe there is no longer this issue (if login is no longer there)
cc @sleshchenko

**Comment by vinokurig** [comment] 2021-01-13 11:06
@benoitf The issue is not related to dashboard, It can be reproduced from the workspace by signing in the GitHub pull-request plugin or other plugins that use GitHub e.g. Git or SSH plugin. I mentioned dashboard as it is the easiest way to reproduce the problem.

**Comment by tolusha** [comment] 2021-01-13 11:16
Everything should work for GitHub PR plugin
https://github.com/eclipse/che-theia/pull/953

**Comment by tolusha** [comment] 2021-01-13 11:17
I tend to think it is just a dashboard issue.

**Comment by benoitf** [comment] 2021-01-13 11:20
@vinokurig the flow you're describing in the issue is specific to the dashboard (there is no server code involved)

**Comment by sleshchenko** [comment] 2021-01-13 11:30
> as dashboard is switching over to dashboard-next maybe there is no longer this issue (if login is no longer there)

that's true. New Dashboard does not have this functionality yet. This issue will be fixed by our team only in case it's a critical for CRW.

**Comment by vinokurig** [comment] 2021-01-13 11:46
@benoitf @tolusha 
> Everything should work for GitHub PR plugin

Actually it doesn't work because the authentication request is called here: https://github.com/eclipse/che/blob/f9d8638acb0d75daf72dae1a38463768df778f54/assembly/assembly-root-war/src/main/webapp/_app/oauthLoader.js#L160-L164

**Comment by vinokurig** [comment] 2021-01-13 11:55
Even when I do the request manually with the `API` url from the `CHE_API_EXTERNAL` env variable:
```
https://che-che.192.168.99.254.nip.io/api/oauth/authenticate?oauth_provider=github&redirect_after_login=https://che-che.192.168.99.254.nip.io&scope=repo&token=<user token>
```
it doesn't work.

**Comment by vinokurig** [comment] 2021-01-13 12:14
@benoitf 
> @vinokurig the flow you're describing in the issue is specific to the dashboard (there is no server code involved)

The server side is involved because the popup calls the server API which is redirecting to an unavailable url.

**Comment by sleshchenko** [comment] 2021-01-14 08:11
Seems there is nothing Dashboard does with it. Probably it's related to https://github.com/eclipse/che/pull/18225 and somewhere internal URL is used, but publish must be.

**Closed as completed** 2021-01-18 14:37 UTC
Labels: kind/bug, severity/P1, area/install, area/che-server
