### ISSUE TITLE
Git rebase does not work in self-hosting workspace

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15162] opened 2019-11-11 12:50 UTC
This is on che.openshift.io.

I have checked out che-theia into the projects folder. When I fetch a branch from @JPinkney's fork and try a rebase, the rebase fails. The full script is below. 
The rebase of the same branch works fine on my machine.

**Comment by tsmaeder** [comment] 2019-11-11 12:51
Full interaction:

```
(theia-dev@container) (/projects) $ git clone https://github.com/eclipse/che-theia/
Cloning into 'che-theia'...
remote: Enumerating objects: 6253, done.
remote: Total 6253 (delta 0), reused 0 (delta 0), pack-reused 6253
Receiving objects: 100% (6253/6253), 3.59 MiB | 5.41 MiB/s, done.
Resolving deltas: 100% (3974/3974), done.
Checking out files: 100% (500/500), done.
(theia-dev@container) (/projects) $ git remote add josh https://github.com/JPinkney/che-theia/
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
(theia-dev@container) (/projects) $ cd che-theia/
(theia-dev@container) (/projects/che-theia) $ git remote add josh https://github.com/JPinkney/che-theia/
(theia-dev@container) (/projects/che-theia) $ git fetch josh workspace_roots_che_on_master
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Total 64 (delta 35), reused 35 (delta 35), pack-reused 29
Unpacking objects: 100% (64/64), done.
From https://github.com/JPinkney/che-theia
 * branch            workspace_roots_che_on_master -> FETCH_HEAD
 * [new branch]      workspace_roots_che_on_master -> josh/workspace_roots_che_on_master
(theia-dev@container) (/projects/che-theia) $ get checkout workspace_roots_che_on_master
bash: get: command not found
(theia-dev@container) (/projects/che-theia) $ git checkout workspace_roots_che_on_master
Checking out files: 100% (265/265), done.
Branch 'workspace_roots_che_on_master' set up to track remote branch 'workspace_roots_che_on_master' from 'josh'.
Switched to a new branch 'workspace_roots_che_on_master'
(theia-dev@container) (/projects/che-theia) $ git rebase origin/master
First, rewinding head to replay your work on top of it...
error: unable to create file dockerfiles/theia/.gitignore: File exists
error: unable to create file dockerfiles/theia/Dockerfile: File exists
error: unable to create file dockerfiles/theia/README.md: File exists
error: unable to create file dockerfiles/theia/build.sh: File exists
error: unable to create file dockerfiles/theia/e2e/Dockerfile: File exists
error: unable to create file dockerfiles/theia/e2e/src/package.json: File exists
error: unable to create file dockerfiles/theia/src/entrypoint.sh: File exists
error: unable to create file extensions/eclipse-che-theia-about/package.json: File exists
error: unable to create file extensions/eclipse-che-theia-about/scripts/generate-about-details.js: File exists
error: unable to create file extensions/eclipse-che-theia-about/src/browser/about-che-theia-dialog.ts: File exists
error: unable to create file extensions/eclipse-che-theia-dashboard/package.json: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/package.json: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/browser/che-api-provider.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/browser/che-frontend-module.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-client.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-main.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-command-contribution.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-frontend-service.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-manager.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-menu.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-view-contribution.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-widget.tsx: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/browser/style/che-plugins.css: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/node/che-backend-module.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-api-provider.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/node/che-task-service.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/src/plugin/che-task-impl.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-ext/webpack.config.js: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-remote/package.json: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-remote/src/node/hosted-plugin-remote.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-backend-module.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-remote/src/node/server-plugin-proxy-runner.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin-remote/src/node/terminal-container-aware.ts: File exists
error: unable to create file extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts: File exists
error: unable to create file extensions/eclipse-che-theia-preferences-provider-extension/package.json: File exists
error: unable to create file extensions/eclipse-che-theia-terminal/package.json: File exists
error: unable to create file extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts: File exists
error: unable to create file extensions/eclipse-che-theia-terminal/src/browser/terminal-frontend-module.ts: File exists
error: unable to create file extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts: File exists
error: unable to create file extensions/eclipse-che-theia-terminal/src/node/workspace-service-impl.ts: File exists
error: unable to create file extensions/eclipse-che-theia-user-preferences/package.json: File exists
error: unable to create file extensions/eclipse-che-theia-user-preferences/src/node/che-theia-preferences-synchronizer.ts: File exists
error: unable to create file extensions/eclipse-che-theia-user-preferences/tsconfig.json: File exists
fatal: Could not detach HEAD
```

**Comment by tolusha** [comment] 2019-11-11 13:49
> `This is on che.openshift.io.`

Do it mean it `che.openshift.io` specific?
Have you tried the same operation locally?

**Comment by tsmaeder** [comment] 2019-11-11 15:22
I have no working self-hosting setup.

**Comment by tsmaeder** [comment] 2019-11-11 15:23
I tried to "open workspace" on a different repository to make sure it's not a problem with git in che-theia. Still doesn't work.

**Comment by tsmaeder** [comment] 2019-11-11 16:11
The scenario works when I create a new workspace based on "Nodejs express web application" (node10).

**Comment by tsmaeder** [comment] 2019-11-11 16:31
Ok, I think I know what the difference is: when I turn on "persistVolumes: true" in the nodejs workspace, even the checkout fails:
```
error: unable to create file dockerfiles/remote-plugin-clang-8/Dockerfile: File exists
```
...

**Comment by tolusha** [comment] 2019-11-12 07:17
I've tested when it was set to `true` (be default) and haven't faced such a error

**Comment by benoitf** [comment] 2019-11-12 08:17
@tsmaeder could you provide devfile you were using ?

**Comment by tsmaeder** [comment] 2019-11-12 08:18
As I mentioned above, the problem reproduces with the node 10 devfile.

**Comment by tolusha** [comment] 2019-11-12 08:19
@benoitf 
Start from any node based devfile
and follow these steps:

```bash
git clone https://github.com/eclipse/che-theia/
cd che-theia/
git remote add josh https://github.com/JPinkney/che-theia/
git fetch josh workspace_roots_che_on_master
git checkout workspace_roots_che_on_master
git rebase origin/master
```

**Comment by tolusha** [comment] 2019-11-12 08:19
Make sure that `persistVolumes` is set to `true`

**Comment by benoitf** [comment] 2019-11-12 08:24
with the devfile I can know if persistent volumes are turned on or off.
With previous comments, it's not clear when it's enabled or not.

But AFAIK we can't have persistent volumes with operations doing a lot of I/O on che.openshift.io
(like cloning big projects, 'npm install' etc)

Also the issue should not be on this repository but on https://github.com/redhat-developer/rh-che

**Comment by benoitf** [comment] 2019-11-12 08:25
And AFAIK this issue exists since the beginning (this is mainly why ephemeral workspaces have been added)

**Comment by ibuziuk** [comment] 2019-11-12 17:50
This looks similar to https://github.com/redhat-developer/rh-che/issues/1047

**Comment by ibuziuk** [comment] 2019-11-12 17:52
> what's the best place for issues only specific to che.openshift.io

https://github.com/redhat-developer/rh-che/issues

**Comment by amisevsk** [comment] 2019-11-12 21:04
I can't reproduce on che.openshift.io when running a workspace in ephemeral mode (`persistVolumes: false`), which is the default for new workspaces. If you pass a devfile via factory URL, chances are it's going to include PVs, and modifying many files quickly is a known issue with Gluster (I often can do `mvn clean install` in some projects, with the same error).

**Comment by benoitf** [comment] 2019-11-13 07:36
I would close this issue as duplicate of https://github.com/redhat-developer/rh-che/issues/1047 
@tsmaeder ?

**Comment by tsmaeder** [comment] 2019-11-13 10:21
@benoitf that depends: do we have a solution that works with persistent volumes on OpenShift clusters in general? If not, this is not che.openshift.io-specific and we should have an issue for it in the main repo.

**Comment by benoitf** [comment] 2019-11-13 11:27
@tsmaeder at some point we had other PVC (but attached time was longer) and it was working as expected once workspace was started.
Also on RHPDS instances it's working AFAIK

**Comment by tsmaeder** [comment] 2019-11-13 12:46
What's RHPDS?

**Comment by benoitf** [comment] 2019-11-13 13:06
https://rhpds.redhat.com/ (Red Hat Product System) 
Like for workshop instances

**Comment by benoitf** [comment] 2019-11-14 16:10
This issue is related to che.openshift.io PVC type and it's already reported at https://github.com/redhat-developer/rh-che/issues/1047

Closing here upstream as with other PVC type it's working (OpenShift/Kubernetes, etc) so it's not related directly to Eclipse Che
Also as part of Che "performance/fast startup" there are other issues with like rsyncing project data as alternative as well (mixing ephemeral performance but still persistence)

**Closed as completed by benoitf** 2019-11-14 16:10 UTC
Labels: kind/bug

**Comment by amisevsk** [comment] 2019-11-14 19:21
To add, there's an epic that I think covers this one that @l0rd opened a few days ago: https://github.com/eclipse/che/issues/15174. I agree that this isn't a Che issue and is more a limitation of the underlying storage system being used. Ideally Che has a compatibility matrix for which storage drivers have limitations.
