### ISSUE TITLE
Add a Lombok extension to Che plugin registry.

### ISSUE THREAD

**Issue by asavin-cl** [eclipse-che/che#17767] opened 2020-09-01 16:09 UTC
As you may know, many developers use **Lombok** during writing the code.
Could you add a **Lombok extension** to Che? It will increase the usability of your product.
Link to VS Code extension:
https://marketplace.visualstudio.com/items?itemName=GabrielBB.vscode-lombok

**Comment by sparkoo** [comment] 2020-09-01 16:21
@asavin-cl are you interested in contributing it?

**Comment by gattytto** [comment] 2020-09-01 17:14
duplicate of https://github.com/eclipse/che/issues/17483

@asavin-cl we can continue on the other issue and maybe you can close this one?.

**Comment by ericwill** [comment] 2020-09-01 17:23
Closed as duplicate of #17483

**Closed as completed by ericwill** 2020-09-01 17:23 UTC
Labels: kind/enhancement
