### ISSUE TITLE
Minimal set of dashboard improvements for Che 7

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#11788] opened 2018-10-31 09:17 UTC
### Description

Here is a small list of desiderata for Che 7 regarding the dashboard:

- [x] Plugins list should be visible only if a Che 7 stack has been selected
- [x] A user should be able to set less than 500 MB for a runtime memory limit
- [x] Che 7 stacks should not appear when running on Docker infrastructure
- [x] Configuration should be saved automatically (remove SAVE button) -> moving to separate issue https://github.com/eclipse/che/issues/12136
- [x] When a user select create workspace it should also start by default

cc @slemeur @evidolob @ashumilova

**Comment by mmorhun** [comment] 2018-10-31 10:11
@l0rd I disagree with the point that we should start workspace after creation. It might be useful to change some configuration and only then start it. At least we should leave the ability to not to start it.
Also we have limitation for number of workspaces which run simultaneously and if a user creates a new workspace it might not start due to the settings which will look not so good, like error on creation.

**Comment by l0rd** [comment] 2018-10-31 10:13
@mmorhun I agree we should leave the ability not to start it right away. But the default should be to start it!

**Comment by mmorhun** [comment] 2018-10-31 10:18
@l0rd as about saving of workspace config: we cannot save invalid one, AFAIK. And if a user is in process of editing it might cause problems. To me we shouldn't show errors/success on editing (it is obvious, IMO), but on attempt to save. The problem is that we cannot predict when user finish the editing. And we should notify a user if config is invalid and what is wrong when editing is done.
So far, I see the save button the most clear way of doing it. But what we can improve, that preventing of leaving tab with unsaved configuration (the problem I run into from time to time).

**Comment by l0rd** [comment] 2018-10-31 10:38
@mmorhun what you are saying doesn't make and it looks like you haven't tried to edit a workspace since a long time :-) Try to edit the json config of a workspace, and tell me if the syntax checking is done when you are typing or when you press Save:
![image](https://user-images.githubusercontent.com/606959/47782552-c5055680-dd00-11e8-85ad-cad7b6e7f184.png)

**Comment by mmorhun** [comment] 2018-10-31 11:09
@l0rd no, I have used the editor during last few days a lot :) . I more talking about ways to improve and not about how current config editor works.
As about the error message, well, for some cases it might be useful, for example in case of copy/pasting config parts, I missed it, but while a user types it might be annoying (I do know that when I type parameter name I miss the value for now). But ok, it is easier to ignore than not to have it at all, may be we should keep it.
The thing which to me should be fixed is formatting on fly, because it may change input point on type pause (or keep caret in the position (i.e. move according to formatting)).

**Comment by mmorhun** [comment] 2018-10-31 11:10
@l0rd and yes, thanks for feedbacks ;)

**Comment by l0rd** [comment] 2018-10-31 11:14
@mmorhun I agree that current syntax checking/formatting can be annoying but I consider of higher priority the removal of the "SAVE" button.

**Comment by ashumilova** [comment] 2018-10-31 11:19
I have few questions: 
1. "Che 7 stack" - how we differ it from others? can we check attributes (editor or plugins) are set as indicator?

2. When workspace is created not from Che7 stack and we edit it - can we still leave "plugins" , cause it's made in a way to allow to switch to Che7 model without errors (installers will be removed and user notified about that). Here the idea was to promote switching to Che7 model from Che6 one.

3. About starting by default workspace on creation-> here it's meant when user clicks "Edit" or "Open in IDE"(in this case workspace is started)?

**Comment by ashumilova** [comment] 2018-10-31 11:34
About removing "SAVE". I understand about the point to autosave, but with current layouts do not really have idea how to make it consistent. Let me explain. This layout appears each time we do any edits with any object:
![screenshot from 2018-10-31 13-23-01](https://user-images.githubusercontent.com/1611939/47785067-3ef10c00-dd10-11e8-8aad-50fa436c06b2.png)
but in case of workspace it has additional option - to Apply the changes, which means workspace will be restarted. In case of autosave - first - no way to provide that and may cause misunderstandings. Maybe we should think how to improve overall flow of editing the workspace details.

**Comment by ashumilova** [comment] 2018-10-31 11:59
BTW, what button on workspace creation you meant:
- in right upper corner
or
- at the bottom on the page
![screenshot from 2018-10-31 13-43-30](https://user-images.githubusercontent.com/1611939/47786023-1cacbd80-dd13-11e8-92ae-3536fe0447dc.png)

Based on your idea to start workspace by default but still have way to change it, and avoid popup (as I understood):
![screenshot from 2018-10-31 13-46-06](https://user-images.githubusercontent.com/1611939/47786098-58478780-dd13-11e8-9987-c880266e672b.png)

we could add smth like checkbox - by default unchecked saying smth:
"I want to proceed editing the workspace"

**Comment by benoitf** [comment] 2018-10-31 12:04
about

> - [ ] Che 7 stacks should not appear when running on Docker infrastructure

maybe it could be more generic. Testing on Kubernetes we see some stacks that are not working as well due to openshift recipe, etc. So it should display only `compliant` stacks

**Comment by l0rd** [comment] 2018-10-31 14:47
@ashumilova

>  "Che 7 stack" - how we differ it from others? can we check attributes (editor or plugins) are set as indicator?

That's an excellent question and I was wondering the same thing. Checking `editor` attribute is a good idea but I don't have a strong opinion: that's an implementation detail.

> When workspace is created not from Che7 stack and we edit it - can we still leave "plugins" , cause it's made in a way to allow to switch to Che7 model without errors (installers will be removed and user notified about that). Here the idea was to promote switching to Che7 model from Che6 one.

That's fine.

> About starting by default workspace on creation-> here it's meant when user clicks "Edit" or "Open in IDE"(in this case workspace is started)?

I mean Open in IDE. I think that's what users want to do 99% of the times: select the stack, select the project and Open in IDE (not editing).

> About removing "SAVE"...

I don't want to go through a full refactoring/review of the dashboard with this issue. It's just a list of quick fixes to improve the UX. I still think that enabling autosave, removing the `SAVE` button (and and maybe just renaming `APPLY` to `RESTART`) can be done as a quick fix. But you know the details better than I do and if you think it's more complicated than that let's descope it from this list and make it a separate issue. I am fine with it. 

> what button on workspace creation you meant? 

Both. Transforming both into "Open in IDE" button.

> we could add smth like checkbox - by default unchecked saying smth:
"I want to proceed editing the workspace"

I would just invert `Create` (currently the default) and `Open in IDE` (should be the default instead):
![image](https://user-images.githubusercontent.com/606959/47795473-eb3bee00-dd22-11e8-93ac-5fb7e1343f48.png)

**Comment by l0rd** [comment] 2018-10-31 14:55
> Testing on Kubernetes we see some stacks that are not working as well due to openshift recipe, etc. 

@benoitf I think that's already the case no?

**Comment by benoitf** [comment] 2018-10-31 15:09
@l0rd ok maybe it's the Che7 stack then that is not working as expected due to the broker adding openshift recipes dynamically when we're on K8s

**Comment by l0rd** [comment] 2018-10-31 15:17
@benoitf that's weird. I have tested Che 7 stacks (merged yesterday in master) and they worked perfectly on kubernetes for me.

**Comment by benoitf** [comment] 2018-10-31 15:22
@l0rd I used 6.13.0 it might explain

**Closed as completed** 2019-01-15 12:25 UTC
Labels: kind/enhancement
