### ISSUE TITLE
Make chectl deploy Che with ssl by default

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#15325] opened 2019-11-26 15:49 UTC
### Is your task related to a problem? Please describe.
Recently, some components of Eclipse Theia were reimplemented to work only with secured connection, i.e. they work only with https protocol. After that changes we have a batch of issues on Che Theia side.

### Describe the solution you'd like
We should deploy Che with SSL by default. Chectl should take care about sertificates on its own without a batch of manual actions.
Ideally, would be great to use some free (say Let's Encrypt) service to get certificates.
Also option to provide own certificate should be present.
Would be nice to have documented the flow.

### Describe alternatives you've considered
We may start from self-signed certificates as it is the simplest solution (however chectl should do it instead of user).
Maybe we should consider a common certificate for all dev instances (it might be not really secure, but Che will work on https by default).

### Additional context
As for now to make everything work we need to do many manual steps to deploy Che with SSL. [Here](https://github.com/eclipse/che/issues/14035#issuecomment-519822676) is some instructions how one may try to do it. However, there are some other issues which makes development in local Che instance not friendly, even complicated.

**Comment by mmorhun** [comment] 2019-11-26 15:50
As for now, all webviews doesn't work on http, so to make them work one need to setup Che with SSL.

**Comment by skabashnyuk** [comment] 2019-11-26 19:36
Duplicates https://github.com/eclipse/che/issues/14742 ?

**Comment by l0rd** [comment] 2019-11-26 22:37
Yes closing as a duplicate of #14742 

As a comment about your proposal @mmorhun on the generation of certs: we cannot use let's encrypt for local dev env and other user cases, we need to generate self signed cert and a great tool to do that on kube is https://github.com/jetstack/cert-manager

**Closed as completed by l0rd** 2019-11-26 22:37 UTC
Labels: kind/task, area/chectl, status/duplicate
