### ISSUE TITLE
Space in NO_PROXY leads to failed startup

### ISSUE THREAD

**Issue by gorootde** [eclipse-che/che#8368] opened 2018-01-19 13:28 UTC
### Description
When starting Che with environment Variable `NO_PROXY` set to e.g. `localhost, *.foo.bar` you get an error message on startup. The space between the two hostnames is the reason

### Reproduction Steps

- Define -e "NO_PROXY=localhost, *.foo.bar" on che multiuser startup and startup che

**OS and version:**    
- Windows 10, Docker for Windows
- Che 5.22.1

**Diagnostics:** 
Error message in STDOUT:
 `Found custom che.properties...
Error: Could not find or load main class *.*.foo.bar'`

**Comment by riuvshin** [comment] 2018-01-22 09:36
@gorootde Thanks for the report!
Many tools do not allow different separators in no_proxy it should be a space, coma, pipe or something else. Usually what goes after separation symbol is what you expect to be in the next value but I'm not sure that you want space here.
I think we can eliminate all spaces from that ENV before using it, but do you really want to use 2 separators at the same time?

**Comment by gorootde** [comment] 2018-01-22 11:15
Maybe it is a special usecase, but I was simply reusing the proxy Configuration of my Mac. MacOS is perfectly fine with commas and an additional whitespace (so are all the other CLI tools I’ve used so far).
Che doesn’t have to support such a configuration necessarily, but it should at least fail with a defined error message.

**Comment by riuvshin** [comment] 2018-01-22 11:17
@gorootde yeah, agree. I will take a look how we can Improve that.

**Comment by riuvshin** [comment] 2018-01-22 11:52
@gorootde can you please provide whole `docker run ...` command how you running it. 
I'm not able to reproduce it by just adding `-e "NO_PROXY=localhost, *.foo.bar"`

**Comment by riuvshin** [comment] 2018-02-19 13:35
I finally reproduced this, with `-e "CHE_NO_PROXY=localhost, *.foo.bar"`

**Comment by riuvshin** [comment] 2018-02-19 14:01
So there are few issues,
1) space in any CHE ENV leads to problem where ENV will be injected with only part of the expected value, like when user doing `-e CHE_TEST="this is test"` in CHE will appear following ENV VAR `CHE_TEST=this`. This bug is already fixed https://github.com/eclipse/che/pull/8818
2) the second issue is related to the `java` configuration, we are setting `-Dhttp.nonProxyHosts=` based on what user provided in `CHE_NO_PROXY`, however using spaces in `-Dhttp.nonProxyHosts=` is not allowed that is why it fails. Here is a PR with fix https://github.com/eclipse/che/pull/8834

**Closed as completed** 2018-02-19 14:24 UTC
Labels: kind/bug, sprint/current

**Comment by riuvshin** [comment] 2018-02-19 14:27
@gorootde fixes are merged and will be available on 6.2.0 release and on nightly build
