### ISSUE TITLE
Cloning a VSTS repo feature does not work

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#1893] opened 2016-07-21 12:16 UTC
**Reproduction Steps:**
_Precondition:_ git URL from VSTS repository
1. Get a https url from VSTS repository
2. Go to the IDE and Workspace -> Import project -> select GIt
3. Paste the VSTS git repo url and click import button
**Expected behavior:** The project should be cloned. Pull/push operations should be available from the IDE
**Observed behavior:** We have next exception: _java.lang.IllegalStateException: org.eclipse.che.ide.websocket.rest.exceptions.UnauthorizedException: URL_TO_VSVS_REPO: Authentication is required but no CredentialsProvider has been registered_
### See also screenshot:

![selection_001](https://cloud.githubusercontent.com/assets/1640058/17022642/d047f1e4-4f57-11e6-8743-4b9a63cf667c.png)

**Expected behavior:** after clicking on the fires item the Compare button should be enabked
**Observed behavior:** after clicking on the fires item the Compare button still disabled
**Che version:**    4.5.0
**OS and version:** Ubuntu OS 14.0
**Docker version:** 1.11.2
**Che install:**  local bundle
**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: YES

**Comment by mshaposhnik** [comment] 2016-07-21 13:27
Pls create appropriate issue in CODENVY, but leave this one too, because fix will also affect CHE code.

**Comment by musienko-maxim** [comment] 2016-07-22 07:43
Has been added to https://github.com/codenvy/codenvy/issues/431 in CODENVY

**Comment by riuvshin** [comment] 2016-07-22 11:52
close as duplicate of https://github.com/codenvy/codenvy/issues/431

**Closed as completed by riuvshin** 2016-07-22 11:52 UTC
Labels: kind/bug, severity/blocker
