### ISSUE TITLE
Browser was freeze when running `npm install` in the console.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#6203] opened 2017-09-10 06:57 UTC
**Reproduction Steps:**

1. Setup node environment
2. Get an application contains packages.json via GitHub or somewhere.
3. Run `npm install`
4. Browser is hang up. Browser's console shows 504 error in `ws://.../connect`
   
This is not 100% reproduction.

**OS and version:**    

* Version :5.18.0-SNAPSHOT
* Revision :5231059555dc1838
* Build Time :2017-09-08 13:45:52

**Diagnostics:** 

I suspect the root cause is this NPE.
![screenshot 2017-09-10 at 15 48 44 - display 2](https://user-images.githubusercontent.com/101795/30246869-ab7db44e-9640-11e7-9e4b-f46492568969.png)

**Comment by sr229** [comment] 2017-09-10 08:27
@monaka I can't reliably reproduce this, my npm exits fine and there was no 504 reported in my end. Probably connection issues?

**Comment by monaka** [comment] 2017-09-10 08:32
I don't think the root cause is connection issue.
Traefik report like this.

```
time="2017-09-10T06:40:22Z" level=warning msg="Error dialing `172.18.0.2:4412`: dial tcp 172.18.0.2:4412: getsockopt: connection timed out" 
```

Looks the terminal service on dev-machine is down.

**Comment by monaka** [comment] 2017-09-10 08:54
I created PR #6205 to show my expectations. Frankly I've not tested that yet. Anyway this will be issue by execution timing.

**Comment by bmicklea** [comment] 2017-09-11 14:00
@eivantsov can you try and reproduce?  I can't either...

**Comment by bmicklea** [comment] 2017-09-11 14:02
@monaka thanks for the issue and associated PR - it looks like you've found a bug here and we really appreciate the PR. One of the maintainers has already commented on the PR asking you for some feedback - can't wait to see this merged!

**Comment by sr229** [comment] 2017-09-12 01:02
@monaka I was able to reproduce the NPE after some trials, so I can confirm this.

**Comment by davidwindell** [comment] 2017-09-12 08:54
We've also seen this issue quite a lot, but in our case when we copy a massive amount of files/directories from within a docker image into the workspace

**Comment by SkorikSergey** [comment] 2018-01-26 14:02
Is this still an issue?

**Comment by davidwindell** [comment] 2018-01-26 14:17
Not for us, resolved with the tree fixes last year

**Comment by bmicklea** [comment] 2018-02-05 12:31
Closing as fixed - @monaka if this is still an issue please reopen with details.

**Closed as completed by bmicklea** 2018-02-05 12:31 UTC
Labels: kind/bug, status/in-progress
