### ISSUE TITLE
.m2 dependencies are getting stored in a '?' folder in the project

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13610] opened 2019-06-21 13:00 UTC
### Description
.m2 dependencies are getting stored in a '?' folder in the project which looks extremely odd and trigger more the attention about a bug than anything else.. 

### Reproduction Steps
- Create a workspace based on the stack java-maven
- import https://github.com/spring-projects/spring-petclinic
- open a terminal and run the command ./mvnw spring-boot:run

**OS and version:**    
Che 7 RC 2

**Comment by slemeur** [comment] 2019-06-21 13:01
And then build is failing because of this error
```
[ERROR] Unknown lifecycle phase "/home/user/.m2". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
```

**Comment by slemeur** [comment] 2019-06-21 13:01
cc @tsmaeder

**Comment by sleshchenko** [comment] 2019-06-21 14:12
It is caused by lack of user information in `/etc/passwd`, to fix it it is needed to build custom image and make maven container - openshift compatible where /etc/passwd will be writable and entrypoint will fill in user name if needed. More see #13561

**Comment by tsmaeder** [comment] 2019-09-03 09:26
@sleshchenko  I suspec this is fixed now?

**Comment by amisevsk** [comment] 2019-09-03 16:58
This issue is resolved for our patched base images; the `/etc/passwd` issue is still present for community images, but that is a larger issue (most community images *will not work* with Che), so I think this issue can be closed.

**Closed as completed** 2019-09-04 11:35 UTC
Labels: kind/bug, severity/P1
