### ISSUE TITLE
Switch existing tests on k8s to use single-host

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#16904] opened 2020-05-13 07:57 UTC
### Is your task related to a problem? Please describe.
Subtask of https://github.com/eclipse/che/issues/16842.

### Describe the solution you'd like
All the tests we are currently running on k8s should run with single-host configuration

### Additional context
**Known issues** 
 - Running demo application of 'java-web-spring' doesn't work in CHE 'single-host' on k8s https://github.com/eclipse/che/issues/17783
- 'Plugins' list is absent in IDE in CHE 'single-host' on k8s https://github.com/eclipse/che/issues/17749

**Comment by rhopp** [comment] 2020-08-25 11:59
We should slightly change the focus of this issue from the pure ingress single-host to the new Traefik based single-host solution, right @l0rd ?
@skabashnyuk @sparkoo  Could you please provide us needed configuration options/steps how to try the Traefik solution once it's merged? (https://github.com/eclipse/che/pull/17557)

**Comment by skabashnyuk** [comment] 2020-08-25 12:21
@rhopp we'll let you know as soon as it would be ready.

**Comment by skabashnyuk** [comment] 2020-08-27 08:23
@rhopp  Is this issue defer from https://github.com/eclipse/che/issues/16842 ?

**Comment by artaleks9** [comment] 2020-08-28 14:47
As the issues related to start workspace were resolved and closed, I re-checked installation CHE with single-host strategy on k8s and start workspace. So devfile samples are present on dashboard and ws can be run. But there is a problem with 'Plugins' list, which is absent in IDE.
I created appropriate issue: https://github.com/eclipse/che/issues/17749

**Comment by artaleks9** [comment] 2020-09-03 22:23
Also _Happy path test_ is failed via a problem with run demo application. This bug can be reproduced on the _Java Spring Boot_ workspace, because both _Happy path test_ and sample workspace use the _Petclinic demo application_.
There was created appropriate issue: https://github.com/eclipse/che/issues/17783

**Comment by artaleks9** [comment] 2020-09-03 22:37
It seems the problem with run demo application has more general reason, because demo application of _Java Vert.x_ sample workspace also doesn't work as expected. See screenshot:
![java-web-vertx-che-single-host](https://user-images.githubusercontent.com/5408906/92180171-19267800-ee4f-11ea-8723-f263f3e22f70.png)

**Comment by artaleks9** [comment] 2020-09-10 14:16
* There are created jobs to run E2E tests on CHE 'single-host' on 'minikube':
-[MultiUser-Che-single-host--nightly-check-e2e-tests-against-k8s](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/che16904-MultiUser-Che-nightly-check-e2e-tests-against-k8s/)
-[basic-MultiUser-Che-single-host-check-e2e-tests-against-k8s](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/che16904-basic-MultiUser-Che-check-e2e-tests-against-k8s/)
* Considering the known issue with run demo application the  Happy path E2E test was reworked with a workaround.

**Closed as completed** 2020-10-13 06:34 UTC
Labels: kind/task, area/qe, new&noteworthy
