### ISSUE TITLE
I can't build theia using che-theia.

### ISSUE THREAD

**Issue by cenkce** [eclipse-che/che#16965] opened 2020-05-18 16:09 UTC
### Describe the bug
I can't build theia using che-theia.

### Steps to reproduce
1.  Clone eclipse-theia/theia
2. Install che-theia
3. Run `che-theia init`
4. And `yarn`

### Expected behavior
Should build all plugins

### Additional context
```
[compile] src/browser/che-task-main.ts(10,27): error TS6133: 'TaskInfo' is declared but its value is never read.
[compile] src/node/che-task-service.ts(42,55): error TS2345: Argument of type 'import("/Users/cenkce/Desktop/che-theia-new/theia/packages/task/lib/common/task-protocol").TaskConfiguration' is not assignable to parameter of type 'import("/Users/cenkce/Desktop/che-theia-new/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskConfiguration'.
[compile] src/node/che-task-service.ts(43,94): error TS2322: Type 'import("/Users/cenkce/Desktop/che-theia-new/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskInfo' is not assignable to type 'import("/Users/cenkce/Desktop/che-theia-new/theia/packages/task/lib/common/task-protocol").TaskInfo'.
[compile]   The types of 'config._scope' are incompatible between these types.
[compile]     Type 'string | undefined' is not assignable to type 'TaskConfigurationScope'.
[compile]       Type 'undefined' is not assignable to type 'TaskConfigurationScope'.
[compile] src/node/che-task-service.ts(47,17): error TS2322: Type 'CheTask' is not assignable to type 'Task'.
[compile]   Types of property 'fireTaskExited' are incompatible.
[compile]     Type '(event: import("/Users/cenkce/Desktop/che-theia-new/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskExitedEvent) => void' is not assignable to type '(event: import("/Users/cenkce/Desktop/che-theia-new/theia/packages/task/lib/common/task-protocol").TaskExitedEvent) => void'.
[compile] src/node/che-task-service.ts(115,56): error TS2345: Argument of type 'import("/Users/cenkce/Desktop/che-theia-new/theia/packages/task/lib/common/task-protocol").TaskInfo' is not assignable to parameter of type 'import("/Users/cenkce/Desktop/che-theia-new/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskInfo'.
[compile]   Types of property 'config' are incompatible.
[compile]     Type 'import("/Users/cenkce/Desktop/che-theia-new/theia/packages/task/lib/common/task-protocol").TaskConfiguration' is not assignable to type 'import("/Users/cenkce/Desktop/che-theia-new/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskConfiguration'.
[compile] src/node/che-task-service.ts(118,5): error TS2416: Property 'fireTaskExited' in type 'CheTask' is not assignable to the same property in base type 'Task'.
[compile]   Type '(event: import("/Users/cenkce/Desktop/che-theia-new/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskExitedEvent) => void' is not assignable to type '(event: import("/Users/cenkce/Desktop/che-theia-new/theia/packages/task/lib/common/task-protocol").TaskExitedEvent) => void'.
[compile]     Types of parameters 'event' and 'event' are incompatible.
[compile]       Type 'import("/Users/cenkce/Desktop/che-theia-new/theia/packages/task/lib/common/task-protocol").TaskExitedEvent' is not assignable to type 'import("/Users/cenkce/Desktop/che-theia-new/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskExitedEvent'.
[compile]         Types of property 'config' are incompatible.
[compile]           Type 'import("/Users/cenkce/Desktop/che-theia-new/theia/packages/task/lib/common/task-protocol").TaskConfiguration | undefined' is not assignable to type 'import("/Users/cenkce/Desktop/che-theia-new/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskConfiguration | undefined'.
[compile]             Type 'import("/Users/cenkce/Desktop/che-theia-new/theia/packages/task/lib/common/task-protocol").TaskConfiguration' is not assignable to type 'import("/Users/cenkce/Desktop/che-theia-new/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskConfiguration'.
[compile]               Types of property '_scope' are incompatible.
[compile]                 Type 'TaskConfigurationScope' is not assignable to type 'string | undefined'.
[compile]                   Type 'TaskScope.Workspace' is not assignable to type 'string | undefined'.
[compile] error Command failed with exit code 2.
[compile] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[compile] yarn compile exited with code 2
```

**Comment by tsmaeder** [comment] 2020-05-18 18:51
Che-theia does not build against Theia master at this time.

**Comment by cenkce** [comment] 2020-05-18 19:00
Ok but I can't build 0.16.0 and 0.16.1 branches as well.

**Comment by cenkce** [comment] 2020-05-27 19:46
```@eclipse-che/theia-plugin-ext: error Command failed with exit code 1.
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run build
lerna ERR! error Command failed with exit code 1.
lerna ERR! 
lerna ERR! $ concurrently -n "format,lint,compile" -c "red,green,blue" "yarn format" "yarn lint" "yarn compile" && yarn run compileWorker
lerna ERR! [lint] $ eslint --cache=true --no-error-on-unmatched-pattern=true "{src,test}/**/*.{ts,tsx}"
lerna ERR! [format] $ tsfmt -r --useTsfmt ../../configs/tsfmt.json
lerna ERR! [compile] $ tsc
lerna ERR! [lint] 
lerna ERR! [lint] /Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin-ext/src/browser/che-product-main.ts
lerna ERR! [lint]   24:16  warning  Redundant use of `await` on a return value  no-return-await
lerna ERR! [lint] 
lerna ERR! [lint] /Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin-ext/src/browser/che-sidecar-content-reader-main.ts
lerna ERR! [lint]   25:88  warning  Redundant use of `await` on a return value  no-return-await
lerna ERR! [lint] 
lerna ERR! [lint] /Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin-ext/src/browser/che-workspace-main.ts
lerna ERR! [lint]   38:16  warning  Redundant use of `await` on a return value  no-return-await
lerna ERR! [lint] 
lerna ERR! [lint] /Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin-ext/src/browser/oauth-utils.ts
lerna ERR! [lint]   68:16  warning  Redundant use of `await` on a return value  no-return-await
lerna ERR! [lint]   72:16  warning  Redundant use of `await` on a return value  no-return-await
lerna ERR! [lint] 
lerna ERR! [lint] /Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-manager.ts
lerna ERR! [lint]   201:20  warning  Redundant use of `await` on a return value  no-return-await
lerna ERR! [lint]   204:16  warning  Redundant use of `await` on a return value  no-return-await
lerna ERR! [lint] 
lerna ERR! [lint] /Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts
lerna ERR! [lint]   138:16  warning  Redundant use of `await` on a return value  no-return-await
lerna ERR! [lint] 
lerna ERR! [lint] /Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin-ext/src/plugin/che-task-impl.ts
lerna ERR! [lint]   54:20  warning  Redundant use of `await` on a return value  no-return-await
lerna ERR! [lint] 
lerna ERR! [lint] /Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin-ext/src/plugin/che-variables.ts
lerna ERR! [lint]   56:20  warning  Redundant use of `await` on a return value  no-return-await
lerna ERR! [lint] 
lerna ERR! [lint] ✖ 10 problems (0 errors, 10 warnings)
lerna ERR! [lint] 
lerna ERR! [lint] yarn lint exited with code 0
lerna ERR! [format] yarn format exited with code 0
lerna ERR! [compile] src/browser/che-frontend-module.ts(118,35): error TS2345: Argument of type 'typeof TaskConfigurationsService' is not assignable to parameter of type 'string | symbol | Newable<TaskService> | Abstract<TaskService>'.
lerna ERR! [compile]   Type 'typeof TaskConfigurationsService' is not assignable to type 'Newable<TaskService>'.
lerna ERR! [compile]     Type 'TaskConfigurationsService' is not assignable to type 'TaskService'.
lerna ERR! [compile]       Property 'runResolvedTask' is private in type 'TaskService' but not in type 'TaskConfigurationsService'.
lerna ERR! [compile] src/browser/che-task-main.ts(37,55): error TS2345: Argument of type '(event: TaskInfo) => Promise<void>' is not assignable to parameter of type '(e: TaskInfo) => any'.
lerna ERR! [compile]   Types of parameters 'event' and 'e' are incompatible.
lerna ERR! [compile]     Type 'import("/Users/cenkce/Desktop/theia-dev/theia/packages/task/lib/common/task-protocol").TaskInfo' is not assignable to type 'import("/Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskInfo'.
lerna ERR! [compile]       Types of property 'config' are incompatible.
lerna ERR! [compile]         Type 'import("/Users/cenkce/Desktop/theia-dev/theia/packages/task/lib/common/task-protocol").TaskConfiguration' is not assignable to type 'import("/Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskConfiguration'.
lerna ERR! [compile]           Types of property '_scope' are incompatible.
lerna ERR! [compile]             Type 'string | undefined' is not assignable to type 'TaskConfigurationScope'.
lerna ERR! [compile]               Type 'undefined' is not assignable to type 'TaskConfigurationScope'.
lerna ERR! [compile] src/browser/che-task-main.ts(38,52): error TS2345: Argument of type '(event: TaskExitedEvent) => Promise<void>' is not assignable to parameter of type '(e: TaskExitedEvent) => any'.
lerna ERR! [compile]   Types of parameters 'event' and 'e' are incompatible.
lerna ERR! [compile]     Type 'import("/Users/cenkce/Desktop/theia-dev/theia/packages/task/lib/common/task-protocol").TaskExitedEvent' is not assignable to type 'import("/Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskExitedEvent'.
lerna ERR! [compile]       Types of property 'config' are incompatible.
lerna ERR! [compile]         Type 'import("/Users/cenkce/Desktop/theia-dev/theia/packages/task/lib/common/task-protocol").TaskConfiguration | undefined' is not assignable to type 'import("/Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskConfiguration | undefined'.
lerna ERR! [compile]           Type 'import("/Users/cenkce/Desktop/theia-dev/theia/packages/task/lib/common/task-protocol").TaskConfiguration' is not assignable to type 'import("/Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskConfiguration'.
lerna ERR! [compile] src/browser/task-config-service.ts(22,14): error TS2415: Class 'TaskConfigurationsService' incorrectly extends base class 'TaskService'.
lerna ERR! [compile]   Property 'runResolvedTask' is private in type 'TaskService' but not in type 'TaskConfigurationsService'.
lerna ERR! [compile] src/browser/task-config-service.ts(99,13): error TS2322: Type '{ widgetOptions: { area: "bottom"; }; mode: WidgetOpenMode; taskConfig: TaskConfiguration | undefined; }' is not assignable to type 'TaskTerminalWidgetOpenerOptions'.
lerna ERR! [compile]   Object literal may only specify known properties, and 'taskConfig' does not exist in type 'TaskTerminalWidgetOpenerOptions'.
lerna ERR! [compile] src/node/che-task-service.ts(42,55): error TS2345: Argument of type 'import("/Users/cenkce/Desktop/theia-dev/theia/packages/task/lib/common/task-protocol").TaskConfiguration' is not assignable to parameter of type 'import("/Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskConfiguration'.
lerna ERR! [compile] src/node/che-task-service.ts(47,17): error TS2322: Type 'CheTask' is not assignable to type 'Task'.
lerna ERR! [compile]   Types of property 'fireTaskExited' are incompatible.
lerna ERR! [compile]     Type '(event: import("/Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskExitedEvent) => void' is not assignable to type '(event: import("/Users/cenkce/Desktop/theia-dev/theia/packages/task/lib/common/task-protocol").TaskExitedEvent) => void'.
lerna ERR! [compile] src/node/che-task-service.ts(115,56): error TS2345: Argument of type 'import("/Users/cenkce/Desktop/theia-dev/theia/packages/task/lib/common/task-protocol").TaskInfo' is not assignable to parameter of type 'import("/Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskInfo'.
lerna ERR! [compile] src/node/che-task-service.ts(118,5): error TS2416: Property 'fireTaskExited' in type 'CheTask' is not assignable to the same property in base type 'Task'.
lerna ERR! [compile]   Type '(event: import("/Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskExitedEvent) => void' is not assignable to type '(event: import("/Users/cenkce/Desktop/theia-dev/theia/packages/task/lib/common/task-protocol").TaskExitedEvent) => void'.
lerna ERR! [compile]     Types of parameters 'event' and 'event' are incompatible.
lerna ERR! [compile]       Type 'import("/Users/cenkce/Desktop/theia-dev/theia/packages/task/lib/common/task-protocol").TaskExitedEvent' is not assignable to type 'import("/Users/cenkce/Desktop/theia-dev/theia/che/che-theia/extensions/eclipse-che-theia-plugin/src/che").TaskExitedEvent'.
lerna ERR! [compile] error Command failed with exit code 2.
lerna ERR! [compile] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! [compile] yarn compile exited with code 2
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/Users/cenkce/Desktop/theia-dev/theia/node_modules/execa/index.js:236:11)
{ Error: Command failed: yarn run build
error Command failed with exit code 1.
```

**Comment by cenkce** [comment] 2020-05-27 19:49
Gives error when I build 1.0.0 tag. How can I build to the version? We've ui and backend extensions and I want to upgrade our version to 1.0.0. Which version should I use?

**Comment by RomanNikitenko** [comment] 2020-05-28 07:21
@cenkce 
I see that the errors above are caused by versions incompatibility.
Looks like current master of `che-theia`, but earlier version of `theia` are used for build.

The only way is known for me how to resolve your problem is:
- on step 3 of your steps to reproduce you could do [init from custom](https://github.com/eclipse/che-theia/blob/master/generator/README.md#custom-extension-and-plugin-set) yaml file: `che-heia init -c ./path/to/custom/che-theia-init-sources.yaml` 
- it's possible to define own [source](https://github.com/eclipse/che-theia/blob/fdf6fee29b1bc0f8aa0286a99f188fe54dcafe3c/che-theia-init-sources.yml#L2) and [checkoutTo](https://github.com/eclipse/che-theia/blob/fdf6fee29b1bc0f8aa0286a99f188fe54dcafe3c/che-theia-init-sources.yml#L25) fields
- using these fields you could manage `che-theia` assembly you prefer to use

**Comment by cenkce** [comment] 2020-05-28 08:12
@RomanNikitenko yes I remember it.  I'll try again thanks.

**Comment by cenkce** [comment] 2020-05-28 08:39
7.8.0 also gives same error. Can you specify the version of Theia in your versions? Which version is compatible with Theia 1.10?

**Comment by RomanNikitenko** [comment] 2020-05-28 10:54
@cenkce 
> 7.8.0 also gives same error. 

 `0.15.0-next.e1d08d00` version of `theia` [was used](https://github.com/eclipse/che-theia/commit/b3b6cd2e4590ca007eb128638716ca039e50c238) for `7.8.0 ` tag of `che-theia`.  

[Using 7.13.2](https://github.com/eclipse/che-theia/commit/080d57e5ef4ed465fd6de4433661ec14c3854adf) of `che-theia` and `v.1.1.0` of `theia` works for me. I think `7.13.0` should work as well. 

![versions](https://user-images.githubusercontent.com/5676062/83132813-9de45600-a0ea-11ea-8c30-b057ab789bde.gif)

**Comment by cenkce** [comment] 2020-05-28 11:03
Ok Thanks I'm trying now

**Comment by cenkce** [comment] 2020-05-28 11:15
Yes it's perfectly done

**Comment by azatsarynnyy** [comment] 2020-07-08 12:30
I'm closing it as the issue has been resolved.
Feel free to reopen if needed.

**Closed as completed by azatsarynnyy** 2020-07-08 12:30 UTC
Labels: kind/bug, severity/P1, area/editor/theia
