### ISSUE TITLE
Openshift connector and Che: openshift user should be logged automatically with the Openshift user.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#15261] opened 2019-11-20 18:35 UTC
### Is your enhancement related to a problem? Please describe.
Having 
- a workspace that use the openshift connector plugin
- a Che server running on Openshift v4.2 and OpenShift oAuth activated

When a user is opening the openshift connector panel, he is connected as his openshift user. and see (without any project)
![Selection_461](https://user-images.githubusercontent.com/650571/69267027-a0f70a80-0bcc-11ea-9142-ce34f5ef6ffb.png)

### Describe the solution you'd like

When a user is opening the openshift connector panel, he should be connected as his openshift user. and not have to login with his credential or token

**Comment by tsmaeder** [comment] 2019-11-21 15:23
Not sure I understand this one correctly: What I understand is this:
1. When opening the connector panel, the cluster that Che is running on is displayed per default
2. Your expectation is that the user is already logged into that cluster as the same user he uses to log into Che?

**Comment by tsmaeder** [comment] 2019-11-21 15:33
@sunix this seems upstream behaviour, right?

**Comment by sunix** [comment] 2019-11-21 16:56
> Not sure I understand this one correctly: What I understand is this:
> 
> 1. When opening the connector panel, the cluster that Che is running on is displayed per default
> 2. Your expectation is that the user is already logged into that cluster as the same user he uses to log into Che?

yes



> @sunix this seems upstream behaviour, right?

not an upstream issue.

**Comment by azatsarynnyy** [comment] 2019-11-26 10:24
OpenShift Connector plugin is connected to a cluster as Che service account. ATM I don't see how we can connect plugin automatically as OpenShift user.

Improving a kubeconfig injection with chectl could make the UX is a bit better. See https://github.com/eclipse/che/issues/14877

**Comment by l0rd** [comment] 2019-11-27 11:06
@azatsarynnyy a couple of comments:
1) When we inject the context using chectl the OpenShift Connector plugin will use that context (and not the workspace serviceaccount) to connect to the cluster right?
2) When Che is deployed on OpenShift in multi-user mode and OpenShift OAuth enabled we should inject the OpenShift context of the current Che user at workspace startup (no need to use chectl)

**Comment by l0rd** [comment] 2019-11-27 11:09
Hence for me #14877 and this one are distinct issues:
- [ ] Automate OpenShift context injection when OpenShift OAuth is enabled ==> this issue
- [ ] Improve Kubernetes context injection when using chectl ==> #14877 

And this issue is probably the most critical one. But if for technical reasons solving #14877 helps solve this one let's start with #14877. Does that make sense?

**Comment by azatsarynnyy** [comment] 2019-11-28 10:00
> @azatsarynnyy a couple of comments:
> 
> When we inject the context using chectl the OpenShift Connector plugin will use that context (and not the workspace serviceaccount) to connect to the cluster right?

right

> When Che is deployed on OpenShift in multi-user mode and OpenShift OAuth enabled we should inject the OpenShift context of the current Che user at workspace startup (no need to use chectl)

@l0rd where we get the OpenShift context of the current Che user in that case? Is that information stored somewhere?

**Comment by sunix** [comment] 2020-04-10 10:12
@ericwill @vinokurig any update on this one ? what is the status ?

**Comment by vinokurig** [comment] 2020-04-10 13:29
It is almost done, waiting for https://github.com/che-incubator/che-theia-openshift-auth/pull/1 and https://github.com/eclipse/che-plugin-registry/pull/419 to be reviewed

**Comment by dmytro-ndp** [comment] 2020-04-14 13:06
The issue is quite important for downstream project CRW, and it be nice to have it fixed in CRW 2.2.

**Closed as completed** 2020-04-15 07:45 UTC
Labels: kind/enhancement, status/in-progress, severity/P1
