### ISSUE TITLE
LS for default PHP stacks not working 

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#16196] opened 2020-03-02 10:58 UTC
### Describe the bug
PHP default stacks don't have any Language support. Code highlighting, error highlighting, code completion etc.

### Che version

 - [x] latest 7.9.0
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

 - Go to Workspace -> Add Worksapce
 - Create and open `PHP Symfony` workspace
 - Open file symfony-demo-application/src/Controler/BlogController.php
 - No LS features are provided.

### Expected behavior
Code should be highlighted according PHP syntax and LS features as error highlighting or code completion should work.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`) Hosted Che
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2020-03-02 11-51-35](https://user-images.githubusercontent.com/29278800/75670290-bf18e000-5c7c-11ea-995d-13fcba934988.png)

Some browser console logs errors that could be related to the problem:
![Screenshot from 2020-03-02 11-48-50](https://user-images.githubusercontent.com/29278800/75670311-c8a24800-5c7c-11ea-87b8-befd5e08eeae.png)

**Comment by ibuziuk** [comment] 2020-03-02 14:22
@tsmaeder could you please take a look?

**Comment by JPinkney** [comment] 2020-03-02 14:56
I think the problem is that when we switched to using the vscode builtins in che-theia we don't provide a PHP language configuration: https://github.com/eclipse/che-theia/blob/master/generator/src/templates/theiaPlugins.json. Since the PHP filetype is no longer be there the PHP language features won't activate when a PHP file is opened.

When I tested on the 7.10.0-SNAPSHOT and opened up BlogController.php the default language configuration is set to plain text (since PHP is missing) so there also won't be syntax colourization

Related issues:
https://github.com/eclipse-theia/theia/issues/6672
https://github.com/eclipse/che/issues/16114

**Comment by amisevsk** [comment] 2020-03-02 15:16
Can this be worked around by manually opening a file and setting its type to `php`? Does the PHP plugin depend on vscode/theia for initialization only or also for finding files?

**Comment by JPinkney** [comment] 2020-03-02 15:33
> Can this be worked around by manually opening a file and setting its type to php?

Unfortunately not, since we removed the @theia/textmate-grammers package the PHP filetype that is associated with the syntax colourization etc doesn't get added to Theia and since we don't have the vscode-builtin-php we technically don't have a "real" PHP language configuration. For some reason there is a `php` filetype that is available but I believe it's only coming from files extension type of `BlogController.php`

> Does the PHP plugin depend on vscode/theia for initialization only

I think it has to be activated by vscode/theia since [activation events](https://github.com/bmewburn/vscode-intelephense/blob/master/package.json#L22) is defined in the vscode extension

**Comment by tsmaeder** [comment] 2020-03-03 10:13
There is a PR here: https://github.com/eclipse/che-theia/pull/648 but Github doesn't autolink it.

**Comment by JPinkney** [comment] 2020-03-05 14:01
Closing as https://github.com/eclipse/che-theia/pull/648 has now been merged

**Closed as completed by JPinkney** 2020-03-05 14:01 UTC
Labels: kind/bug, severity/P1, area/languages
