### ISSUE TITLE
WebView does not work if container is specified

### ISSUE THREAD

**Issue by gorshkov-leonid** [eclipse-che/che#16988] opened 2020-05-21 12:54 UTC
I am trying to use vscode-plugin and it is not working when any container specified

### Steps to reproduce
Server: https://che.openshift.io/
1. Create any workspace
2. Add a reference to meta.yaml in devfile:
```
components:
...
  - type: chePlugin
    reference: 'https://raw.githubusercontent.com/gorshkov-leonid/trash/master/meta.yaml'
...
```
3. Restart workspace
4. Create and open file simple.uml
```
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
```
5. Press alt + d (or find command `PlantUML: Preview Current Diagram`)

**Expected Result:** web view created without errors
**Actual Result:** web view is not working and there are errors in console

### Logs
![image](https://user-images.githubusercontent.com/2270831/82560590-cd431200-9b82-11ea-912d-e78173c7d9d4.png)

### Che version
Eclipse 7.12.2 according to the label at the bottom.

And:
![image](https://user-images.githubusercontent.com/2270831/82560194-029b3000-9b82-11ea-9149-40272d6b7be1.png)
```
@eclipse-che/che-theia-hosted-plugin-manager-extension 0.0.1
@eclipse-che/theia-about 0.0.1
@eclipse-che/theia-activity-tracker 1.0.0
@eclipse-che/theia-dashboard-extension 0.0.1
@eclipse-che/theia-git-provisioner 0.0.1
@eclipse-che/theia-logging 1.0.0
@eclipse-che/theia-plugin-ext 0.0.1
@eclipse-che/theia-preferences-provider-extension 0.0.1
@eclipse-che/theia-remote 0.0.1
@eclipse-che/theia-terminal 0.0.1
@eclipse-che/theia-user-preferences-synchronizer 0.0.1
@theia/callhierarchy 1.0.0
@theia/console 1.0.0
@theia/core 1.0.0
@theia/debug 1.0.0
@theia/editor 1.0.0
@theia/file-search 1.0.0
@theia/filesystem 1.0.0
@theia/json 1.0.0
@theia/keymaps 1.0.0
@theia/languages 1.0.0
@theia/markers 1.0.0
@theia/messages 1.0.0
@theia/metrics 1.0.0
@theia/mini-browser 1.0.0
@theia/navigator 1.0.0
@theia/outline-view 1.0.0
@theia/output 1.0.0
@theia/plugin-dev 1.0.0
@theia/plugin-ext 1.0.0
@theia/plugin-ext-vscode 1.0.0
@theia/preferences 1.0.0
@theia/preview 1.0.0
@theia/process 1.0.0
@theia/scm 1.0.0
@theia/search-in-workspace 1.0.0
@theia/task 1.0.0
@theia/terminal 1.0.0
@theia/userstorage 1.0.0
@theia/variable-resolver 1.0.0
@theia/workspace 1.0.0
```

And It becomes working If I remove the container from meta.yaml. 

This example is synthetic, just to show, but I have the same problem in my server with a plugin that actually requires Java container. This plugin [yang-vscode](https://marketplace.visualstudio.com/items?itemName=typefox.yang-vscode) won't work

**Comment by gorshkov-leonid** [comment] 2020-05-21 13:38
Probably it is related to https://github.com/eclipse/che/issues/16870 but I am not sure

**Comment by rhopp** [comment] 2020-05-25 14:42
Indeed this looks like a duplicate of #16870. Closing.

**Closed as completed by rhopp** 2020-05-25 14:42 UTC
Labels: kind/bug, status/duplicate
