### ISSUE TITLE
Stabilize org.eclipse.che.plugin.dynamodule.DynaModuleListGeneratorMojoTest

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#13458] opened 2019-05-31 08:59 UTC
### Description
org.eclipse.che.plugin.dynamodule.DynaModuleListGeneratorMojoTest is quite often failing when building che (PR check build job).
Few examples:
* https://ci.codenvycorp.com/job/che-pullrequests-build/6774/#showFailuresLink
* https://ci.codenvycorp.com/job/che-pullrequests-build/6773/#showFailuresLink
* https://ci.codenvycorp.com/job/che-pullrequests-build/6772/
* https://ci.codenvycorp.com/job/che-pullrequests-build/6768/
* https://ci.codenvycorp.com/job/che-pullrequests-build/6750/

**Comment by metlos** [comment] 2019-05-31 09:05
Hi, this is temporary and caused by merging of https://github.com/eclipse/che-parent/pull/117. This is needed for https://github.com/eclipse/che/pull/13417 which will fix the tests once merged.

**Comment by rhopp** [comment] 2019-05-31 09:09
Thx for info.

**Comment by metlos** [comment] 2019-05-31 09:10
Yep, sorry for the false alarm. We didn't fully anticipate the effect the merge of the che-parent would have.

**Comment by skabashnyuk** [comment] 2019-05-31 09:41
Will be fixed by https://github.com/eclipse/che/pull/13417

**Comment by metlos** [comment] 2019-05-31 10:48
#13417 is now merged, so the tests should stabilize on the next master build. If not, please raise the alarm! :)

**Closed as completed** 2019-06-06 09:21 UTC
Labels: kind/bug, severity/blocker
