### ISSUE TITLE
Multiple issues with nodejs devfile

### ISSUE THREAD

**Issue by JPinkney** [eclipse-che/che#13806] opened 2019-07-09 16:17 UTC
### Description

While trying to dogfood Che I found multiple issues with the node devfile that makes working with it almost impossible right off the bat.

Just from the short video below I've found a few things:
- [x] Git clone location prompt shows you by default somewhere that is different than /projects
This dialog is being removed. 
- [x] Git clone gets permission denied
Looks like you're trying to clone to /. User error?
- [x] When opening up the node terminal it sets you to a location other than /projects
Which container?
- [x] Permission denied when running npm install
- [ ] yarn does not exist in the image (you can easily install it but a lot of projects I see use yarn)

https://www.youtube.com/watch?v=ep5nOJiL99w

**Diagnostics:** 

7.0.0-rc-4.0-SNAPSHOT deployed via chectl onto minikube

**Comment by slemeur** [comment] 2019-07-10 16:41
Please @tsmaeder and @tolusha give a look to this issue.
Probably related to https://github.com/eclipse/che-devfile-registry/pull/29

**Comment by JPinkney** [comment] 2019-07-10 17:21
If i'm not mistaken when I was testing it was using registry.access.redhat.com/ubi8/nodejs-10 as the image so my devfile must not have been updated. I'll try with the new one and report back.

**Comment by l0rd** [comment] 2019-07-10 21:38
cc @skabashnyuk @sparkoo @ibuziuk

**Comment by ibuziuk** [comment] 2019-07-11 07:20
I suspect that most of the issues would be fixed with https://github.com/eclipse/che-devfile-registry/tree/master/arbitrary-users-patch images - will try to check this assumption after CI setup

**Comment by tsmaeder** [comment] 2019-07-11 07:43
@ibuziuk yes, looks like it. However, the fact that yarn is IMO one of the cases where the user will have to bring their own images. Not saying we can't offer a devfile with yarn installed, but there will always be that "one more tool" some user needs that is not installed on any of the packaged devfiles.

**Comment by JPinkney** [comment] 2019-07-11 13:56
> Looks like you're trying to clone to /. User error?

I would have expected that if projects is selected in the dialog that it would clone to /projects maybe that's an user error, maybe its not, that's just what I expected. I tried double clicking on /projects and it brought me to 
![2019-07-11-092219_763x733_scrot](https://user-images.githubusercontent.com/8839537/61054484-878fb780-a3bd-11e9-81f8-f027555d233f.png) and then when I selected 'Select Repository Location' the error that came up was 
```
Git: fatal: could not create work tree dir '/schemastore': Permission denied
```
(I was test cloning https://github.com/schemaStore/schemastore)

Whats interesting is I was able to successfully clone it in other locations like theia/node_modules/@eclipse-che/api folder.


> Which container?

Its the container with alias nodejs
From the devfile:
```
type: dockerimage
image: registry.access.redhat.com/ubi8/nodejs-10
alias: nodejs
```


> However, the fact that yarn is IMO one of the cases where the user will have to bring their own images.

True, I'm just sad I have to do that myself :wink:

**Comment by tsmaeder** [comment] 2019-09-25 07:14
It all works. The fact that yarn is not installed is not a bug.

**Closed as completed by tsmaeder** 2019-09-25 07:14 UTC
Labels: kind/bug, status/analyzing

**Comment by slemeur** [comment] 2019-09-25 12:36
@tsmaeder : Could you create an enhancement issue to "yarn" by default in the default nodejs stack? Because I agree with the initial requirement, that gets pretty "standard" and a lot of projects are using it. Having it, would be beneficial to end-users.

**Comment by slemeur** [comment] 2019-10-01 07:11
ping @tsmaeder ???

**Comment by slemeur** [comment] 2019-10-01 07:13
https://github.com/eclipse/che/issues/14720
