### ISSUE TITLE
Autosave for a devfile works incorrectly

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#14348] opened 2019-08-28 11:09 UTC
### Describe the bug

Autosave for a devfile works incorrectly.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a new workspace from the devfile

```
metadata:
  name: wksp-test
apiVersion: 1.0.0
```

2. Open 'Devfile' tab

3. Simulate a case when you tried to add a new editor component but did not manage to finish in time:
- Paste the following content
```
metadata:
  name: wksp-test
apiVersion: 1.0.0
components:
  - name: theia
    type: 
```
- Wait until autosave will be triggered and an error appeared.

### Expected behavior
Devfile content is not updated until the user does not finish typing.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![Screenshot from 2019-08-28 13-53-45](https://user-images.githubusercontent.com/6310786/63850671-4b300f00-c99d-11e9-8bd9-71e2cde1062d.png)
![Screenshot from 2019-08-28 13-54-44](https://user-images.githubusercontent.com/6310786/63850687-54b97700-c99d-11e9-8006-27d5e9629480.png)
![Screenshot from 2019-08-28 13-55-49](https://user-images.githubusercontent.com/6310786/63850704-5d11b200-c99d-11e9-9039-034d0c12317d.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

I propose to add a possibility to configure autosave for devfile or turn it off.
Instead of autosave, I have a purpose to save the current state of the devfile editor(simple string) as a temporary workspace data and restore it after page reload

**Comment by AndrienkoAleksandr** [comment] 2019-08-28 11:13
+1 Really annoying bug.

**Comment by sleshchenko** [comment] 2019-08-28 11:18
Looks like error messages on the first and the second screenshots must be improved on Che Server side. @olexii4 Could you please create a separate issue?

**Comment by olexii4** [comment] 2019-08-28 13:13
@sleshchenko I have created
https://github.com/eclipse/che/issues/14350

**Comment by amisevsk** [comment] 2019-08-28 21:23
Closely related (duplicate?): https://github.com/eclipse/che/issues/13982

**Comment by tsmaeder** [comment] 2019-08-29 14:48
Duplicate of https://github.com/eclipse/che/issues/13982

**Closed as completed by tsmaeder** 2019-08-29 14:48 UTC
