### ISSUE TITLE
Dashboard duplicates panels 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19931] opened 2021-06-07 12:02 UTC
### Describe the bug

Dashboard duplicates panels at some conditions, please see a screenshot bellow.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
You can see the steps to reproduce on the video in the `Screenshots` section

1. Start a workspace
2. Wait till the workspace is stopped by timeout
3. Go to dashboard = > `Workspaces` panel.
4. Select the workspace for starting from `Recent Workspaces`
5. See at the state of the dashboard when the workspace is started. 

### Expected behavior

Dashboard doesn't duplicate panels
### Runtime
   Dogfooding instance

### Screenshots

![duplicates_panels_dashboard](https://user-images.githubusercontent.com/5676062/121012537-7bc2f080-c7a0-11eb-99a1-63f2d343626c.png)

![double_panels_dashboard](https://user-images.githubusercontent.com/5676062/121012557-82516800-c7a0-11eb-8e57-d12ccab5d689.gif)

**Comment by RomanNikitenko** [comment] 2021-06-07 12:14
It looks like the cause of the problem somehow related to switching between `Workspaces` and `Recent Workspaces` areas:

![switching_dashboard](https://user-images.githubusercontent.com/5676062/121014780-086eae00-c7a3-11eb-8f60-b10c628adb9e.gif)

**Comment by vzhukovs** [comment] 2021-06-08 12:06
![Снимок экрана 2021-06-08 в 14 58 16](https://user-images.githubusercontent.com/1968177/121181734-02dc9b00-c86b-11eb-9b45-e00c961f3401.png)

Also faced with this issue today on Dogfooding instance

**Comment by sympatheticmoose** [comment] 2021-07-14 12:01
Reproduced today on workspaces.openshift.com

**Comment by sleshchenko** [comment] 2021-07-14 15:03
So, investigated it and it's related to SingleHost(with multihost the error will be different, like 503) and it's caused by a fact that Dashboard tries to open URL from the first workspace run(Thanks @olexii4 for idea). Now it's fixed and dashboard uses the right URL.
To prevent such cases later, it's needed to make Dashboard detecting opening itself in iframe, redirect to main page and report an issue.

**Comment by sleshchenko** [comment] 2021-07-15 06:44
Fixed by https://github.com/eclipse-che/che-dashboard/pull/259

**Closed as completed by sleshchenko** 2021-07-15 06:44 UTC
Labels: kind/bug, sprint/next, severity/P1, area/dashboard
