### ISSUE TITLE
[Hosted Che] add the permissions for the end user to create secrets in the <username>-che namespace

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#17553] opened 2020-08-03 13:58 UTC
### Is your enhancement related to a problem? Please describe.
With https://github.com/eclipse/che/issues/14680, it is possible to reuse secrets to mount them in the filesystem or environment variable.
However, it is not possible to create a secret in hosted Che:

![image](https://user-images.githubusercontent.com/650571/89190700-1ca1b780-d5a2-11ea-9c7e-01da6fcf17e6.png)

executing what is describe in https://www.eclipse.org/che/docs/che-7/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/#mounting-a-secret-as-an-environment-variable-into-a-workspace-container_mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container

**Comment by ibuziuk** [comment] 2020-08-03 14:03
Going to close it as won't fix since by design users has no edit rights in the *-che namespace and  have only view rights in the namespace. Secrets can be created in the user namepsaces though

**Comment by sunix** [comment] 2020-08-03 14:55
@skabashnyuk any thoughts on how we could have it working in che.openshift.io ?

**Comment by ibuziuk** [comment] 2020-08-03 14:56
well, this is simply a permission issue, not related to che per se

**Comment by ibuziuk** [comment] 2020-08-04 14:41
Closing. Currently, a user can not have edit rights in the *-che namespace by design on Hosted Che

**Closed as completed by ibuziuk** 2020-08-04 14:41 UTC
Labels: kind/enhancement, severity/P2, area/hosted-che
