### ISSUE TITLE
IDE hangs from time to time

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#18151] opened 2020-10-21 07:59 UTC
### Describe the bug
Within dogfooding session I faced with the problem that sometimes Che hangs
Looks like it starts from project tree items hang then IDE hangs in general, finally I get  ``` Connection is closed``` error or ```Paused before potential out-of-memory``` state (see screenshots section).
Please see video: https://youtu.be/3na80JGPMdw

### Che version
I can reproduce it on dogfooding instance using fresh master of ```theia``` and ```che-theia```, so my own images.
Also I tested it for devfile from happy tests for https://github.com/eclipse/che-theia/pull/882.

### Steps to reproduce

1. Try to expand tree items a few times

### Screenshots
video: https://youtu.be/3na80JGPMdw

![connectionIsClosed](https://user-images.githubusercontent.com/5676062/96690493-6d989f00-138c-11eb-83fd-906d52e697cc.gif)

![out-of-memory](https://user-images.githubusercontent.com/5676062/96691162-3bd40800-138d-11eb-94e5-1b2d6c60d104.png)

### Environment
dogfooding instance

**Comment by RomanNikitenko** [comment] 2020-10-21 08:46
Tested for https://che.openshift.io/

![ide_hangs_cheOpenshift](https://user-images.githubusercontent.com/5676062/96696087-0cc09500-1393-11eb-8fb0-624d1b0a2e95.gif)

**Comment by RomanNikitenko** [comment] 2020-10-21 09:42
Maybe related to upstream changes https://github.com/eclipse-theia/theia/commit/fe4062e66aec9f4131a09bb0ffb6bea9544bd8a2

**Comment by vitaliy-guliy** [comment] 2020-10-21 09:44
Is it reproducible on local Che deployment?

**Comment by RomanNikitenko** [comment] 2020-10-21 09:45
@vitaliy-guliy 
I didn't check it

**Comment by RomanNikitenko** [comment] 2020-10-21 16:43
I found that commit https://github.com/eclipse-theia/theia/commit/329a3ef0ef33392aac0f2dda98c25132de56e8b0 brought breaking changes for che.

**Comment by azatsarynnyy** [comment] 2020-10-22 05:54
I'm labeling it as a blocker since it prevents us from consuming the latest upstream Theia commits with the required changes.

**Comment by tsmaeder** [comment] 2020-10-22 07:52
@azatsarynnyy +1 on this being a blocker: let's not stay off theia/master too long. 
Do we know _how_ the plugin activation changes cause this behaviour?

**Comment by RomanNikitenko** [comment] 2020-10-22 07:58
@tsmaeder 
> Do we know how the plugin activation changes cause this behaviour?

First we had suspicion that [watcher related changes](https://github.com/eclipse-theia/theia/commit/fe4062e66aec9f4131a09bb0ffb6bea9544bd8a2) brought breaking changes for che, but after investigation I detected that the behavior was broken by https://github.com/eclipse-theia/theia/commit/329a3ef0ef33392aac0f2dda98c25132de56e8b0  
I'm investigating `how the plugin activation changes cause this behaviour` right now.

**Comment by RomanNikitenko** [comment] 2020-10-22 08:52
@tsmaeder 
about your question
looks like plugin activation process like endless loop now:

First I see tons logs:
 
```
2020-10-22 08:40:46.301 root ERROR [hosted-plugin: 46] activatePlugin:  editorconfig.editorconfig 
2020-10-22 08:40:46.390 root ERROR [hosted-plugin: 46] activatePlugin:  editorconfig.editorconfig 
2020-10-22 08:40:46.476 root ERROR [hosted-plugin: 46] activatePlugin:  editorconfig.editorconfig 
2020-10-22 08:40:46.800 root ERROR [hosted-plugin: 46] activatePlugin:  editorconfig.editorconfig 
2020-10-22 08:40:47.262 root ERROR [hosted-plugin: 46] activatePlugin:  editorconfig.editorconfig 
```
then

```
2020-10-22 08:40:47.562 root INFO [hosted-plugin: 46] <--- Last few GCs --->
e [46:0x55d9dccc1020]   802260 ms: Mark-sweep 383.2 (387.9) -> 380.7 (386.7) MB, 65.9 / 0.0 ms  (+ 279.2 ms in 404 steps since start of marking, biggest step 7.0 ms, walltime since start of marking 357 ms) (average mu = 0.158, current mu = 0.035) finalize i[46:0x55d9dccc1020]   802774 ms: Mark-sweep 381.3 (386.9) -> 380.0 (385.2) MB, 4.9 / 0.0 ms  (+ 224.1 ms in 446 steps since start of marking, biggest step 7.6 ms, walltime since start of marking 366 ms) (average mu = 0.355, current mu = 0.555) finalize in

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x0b414b3c08d1 <JSObject>
    0: builtin exit frame: writeUtf8String(this=0x31ba51c8b661 <Pipe map = 0xfd504559399>,0x1bdede0004b1 <undefined>,0x24d72d61bfc9 <Very long string[17741]>,0x24d72d6198a1 <WriteWrap map = 0x3119db13c079>,0x31ba51c8b661 <Pipe map = 0xfd504559399>)

    1: _send [0x86e90326b59] [internal/child_process.js:~688] [pc=0x27ca8e042f95](this=0x2448f643fd41 <process map = 0x3119db135fe9>,0x24d72d6197d9 ... 
2020-10-22 08:40:47.562 root ERROR [hosted-plugin: 46] FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory 
2020-10-22 08:40:48.395 root ERROR [hosted-plugin: 46] IPC exited, with signal: SIGABRT, and exit code: null 
```
Pay attention on `JavaScript heap out of memory `^^

then tons logs like:

```
2020-10-22 08:40:48.407 root ERROR Error from plugin host: Channel closed 
2020-10-22 08:40:48.500 root ERROR Error from plugin host: Channel closed 
2020-10-22 08:40:48.591 root ERROR Error from plugin host: Channel closed 
2020-10-22 08:40:49.166 root ERROR Error from plugin host: Channel closed 
```

then
![crash_plugins](https://user-images.githubusercontent.com/5676062/96848349-fbdc5600-145c-11eb-8616-ef1010e35c10.png)

**Comment by tsmaeder** [comment] 2020-10-22 11:52
That makes sense: plugin activation should be a no-op after the first time, the referenced commit broke that behaviour, obviously.

**Comment by azatsarynnyy** [comment] 2020-10-24 08:04
fixed by https://github.com/eclipse/che-theia/pull/891

**Closed as completed by azatsarynnyy** 2020-10-24 08:04 UTC
Labels: kind/bug, severity/blocker, area/editor/theia
