### ISSUE TITLE
Dashboard factory enhancement

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#14338] opened 2019-08-27 11:20 UTC
### Is your enhancement related to a problem? Please describe.

In the case with CHE7 workspaces and their devfiles, which can be used instead of factories, I'm always frustrated when I see CHE factories without devfile supporting.  On the other hand - we don't have a special UI for using devfiles instead of factories.

For creating a new workspace from the devfile we need to type a special URL(for example 'http://che-che.192.168.99.100.nip.io/f?url=https://raw.githubusercontent.com/eclipse/che/master/dashboard/devfile.yaml') or create any new workspace then change devfile content.

### Describe the solution you'd like

I propose the next UI changes:
![Screenshot from 2019-08-27 12-47-32](https://user-images.githubusercontent.com/6310786/63767029-2708fb00-c8d5-11e9-9a47-10eddd2f6bf9.png)
To have special tabs for creating a new workspace from the existing workspace, local devfile or git resource(include target devfile choosing).

**Comment by olexii4** [comment] 2019-08-27 11:21
@slemeur WDYT?

**Comment by l0rd** [comment] 2019-08-27 22:55
@olexii4 isn't it a duplicate of https://github.com/eclipse/che/issues/12925?

**Comment by olexii4** [comment] 2019-08-28 09:34
@l0rd It is not a duplicate.  It is a purpose to hide factories until they will work with CHE 7 workspaces. And UI purpose which helps us to create a new workspace, based on another CHE7 workspace. Create a new workspace from the devfile(local or remote). 

Because I always do it by my hand. It is small changes but very useful for me as a CHE7 developer

**Closed as completed** 2019-09-18 09:36 UTC
Labels: kind/enhancement, status/info-needed, status/duplicate
