### ISSUE TITLE
NodeJS Web Express Application error highlighting doesn't work

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#16993] opened 2020-05-22 07:24 UTC
### Describe the bug
https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/nodejs does not have a working error highlighting.

### Che version
 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
* Start a workspace
* open nodejs-web-app/app/app.js
* wait for LS to initialize
* try to write `err` or `error_text` or random string

### Expected behavior
Erroneous text will be underlined 

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift 
```
Client Version: 4.3.5
Server Version: 4.4.4
Kubernetes Version: v1.17.1
```
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
N/A

### Installation method
   - [x] chectl
     * `chectl server:start -a operator -p openshift --self-signed-cert -n <namespace>`
     * `chectl/7.13.0 linux-x64 node-v10.20.1`
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: crw-qe.com OCP 4.4

### Eclipse Che Logs
N/A

### Additional context
N/A

**Comment by ericwill** [comment] 2020-07-09 16:12
Looks related to #15919 ?

**Comment by Katka92** [comment] 2020-07-14 11:04
Could not reproduce on latest Che 7.15.1. Closing.

**Closed as completed by Katka92** 2020-07-14 11:04 UTC
Labels: kind/bug, severity/P1, area/languages
