### ISSUE TITLE
Eclipse che can't create workspace

### ISSUE THREAD

**Issue by anthonma** [eclipse-che/che#14731] opened 2019-10-01 13:26 UTC
### Describe the bug
When I try to create a workspace I get an error saying Devfile schema validation failed. Error: (/metadata/generateName):The object must not have a property whose name is "generateName".
And in the console there are some errors shown in the screenshot below.

### Che version
 - [ ] latest
 - [ ] nightly
 - [x] other: 7.0.0-RC-2.0 Docker image

### Steps to reproduce
1. start che with 7.0.0-RC-2.0 Docker image
2. access dashboard
3. create workspace

### Expected behavior
A new workspace is created

### Runtime
 - [ ] kubernetes (include output of kubectl version)
 - [ ] Openshift (include output of oc version)
 - [ ] minikube (include output of minikube version and kubectl version)
 - [ ] minishift (include output of minishift version and oc version)
 - [ ] docker-desktop + K8S (include output of docker version and kubectl version)
 - [x] other: started with 7.0.0-RC-2.0 docker image; don't know which runtime is used here

### Screenshots
![che_dashboard_error](https://user-images.githubusercontent.com/55550413/65965384-d863f900-e45e-11e9-8314-687e71a81d72.PNG)

### Installation method
 - [ ] chectl
 - [ ] che-operator
 - [ ] minishift-addon
 - [x] I don't know

Environment
 - [ ] my computer
   - [ ] Windows
   - [ ] Linux
   - [ ] macOS
 - [ ] Cloud
   - [ ] Amazon
   - [ ] Azure
   - [ ] GCE
   - [ ]  other (please specify)
- [x] other:  Linux vm

**Comment by skabashnyuk** [comment] 2019-10-01 13:54
@anthonma thank you for this report. Can you follow the bug template?


### Describe the bug


### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce



### Expected behavior


### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots


### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

**Comment by skabashnyuk** [comment] 2019-10-01 13:57
@anthonma from what I can see you are using 7.0.0-RC-2.0 Docker image - that is an outdated way to run Che. Can you use something that is available at this moment https://www.eclipse.org/che/docs/che-7

**Comment by amisevsk** [comment] 2019-10-01 14:22
I agree that you should move away from the release candidate builds if possible. This issue in particular is caused by Che reusing the hosted Che devfile registry (which we've since moved away from). This registry is set up for a newer release of Che, which does support generateName.

**Comment by anthonma** [comment] 2019-10-01 14:24
Thank you for your fast replies. I will try the possibilities described in the link.

**Comment by l0rd** [comment] 2019-10-01 22:39
@anthonma I am closing this issue because it looks like the cause of the problem (an old version incompatible with latest devfile registry) and a solution (use a newer Che version) have been provided. Don't hesitate to re-open if your problem hasn't been solved.

**Closed as completed by l0rd** 2019-10-01 22:39 UTC
Labels: kind/question, status/info-needed
