### ISSUE TITLE
[hosted Che] CPU limitations for plugin sidecar is not applied

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#18730] opened 2021-01-05 13:43 UTC
### Describe the bug

We have an ability to limit CPU usage by setting it in plugin `meta.yaml`.
But both `cpuRequest` and `cpuLimit` for the plugin sidecar were not applied.
The problem was noticed when profiling changes provided by PR https://github.com/eclipse/che-plugin-registry/pull/774

That PR sets CPU request and CPU limitation for most of the plugins to 30 and 500 millicores.
It was tested with `cpuRequest: 0.1` and `cpuLimit: 0.5`, but got the same result. CPU in Aplications -> Pods -> Metrics stayed unchanged.

![Screenshot from 2021-01-05 15-37-08](https://user-images.githubusercontent.com/1655894/103652527-e8289200-4f6b-11eb-939e-c9ee655e77d7.png)

It seems limitation in 29(30) millicores is default `cpuRequest` value, set by infrastructure.

Tried to add the limitations by adding them to the devfile
```
  -
    type: chePlugin
    reference: https://gist.githubusercontent.com/vitaliy-guliy/b794fe6831d91964475575150a65f9ee/raw/cbaa2e3b2e37315b8eb7c5841214886c72c6b1dc/plugin.meta.yaml
    cpuRequest: 0.1
    cpuLimit: 0.4
```
Got
```
CPU: 29 millicores to 625 millicores
```

### Steps to reproduce

<details>
<summary>Devfile to test</summary>

```
---
apiVersion: 1.0.0
metadata:
  generateName: nodejs-mongo-
projects:
  -
    name: nodejs-mongodb-sample
    source:
      type: git
      location: "https://github.com/che-samples/nodejs-mongodb-sample"
components:
  -
    type: chePlugin
    reference: https://gist.githubusercontent.com/vitaliy-guliy/b794fe6831d91964475575150a65f9ee/raw/cbaa2e3b2e37315b8eb7c5841214886c72c6b1dc/plugin.meta.yaml
  - 
    type: chePlugin
    id: ms-vscode/node-debug2/latest
    registryUrl: 'https://pr-check-774-alpine-che-plugin-registry.surge.sh/v3'
    preferences:
      debug.node.useV3: false
  -
    type: dockerimage
    alias: nodejs
    image: quay.io/eclipse/che-nodejs10-ubi:nightly
    env:
      # The values below are used to set up the environment for running the application
      - name: SECRET
        value: 220fd770-c028-480d-8f95-f84353c7d55a 
      - name: NODE_ENV
        value: production
    memoryLimit: 512Mi
    endpoints:
      - name: 'nodejs'
        port: 8080
    mountSources: true

```
</details>

### Runtime
   - [x] hosted Che

**Comment by ibuziuk** [comment] 2021-01-07 09:17
Hosted Che OSO v3 clusters are snowflakes with opinionated CPU setup / overcommitment - limitCPUToMemoryPercent is set to 200, in other words CPU limit is overridden by the ClusterResourceOverride admission controller to 2 vCPU cores for every 1Gi memory - https://docs.openshift.com/container-platform/3.6/admin_guide/overcommit.html#configuring-masters-for-overcommitment

If this issue is not reproducible on OSD v4 (limits / requests are set correctly) I would treat this issue as low priority.

**Comment by ibuziuk** [comment] 2021-03-11 12:24
Closing since che.openshift.io has been deprecated in favour of workspaces.openshift.com https://www.eclipse.org/che/docs/che-7/hosted-che/hosted-che/#registering-to-hosted-che_che

**Closed as completed by ibuziuk** 2021-03-11 12:24 UTC
Labels: kind/bug, severity/P1, area/hosted-che
