### ISSUE TITLE
Sometimes cannot start a workspace on che.openshift.io from dashboard in the incognito mode

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#18335] opened 2020-11-11 10:23 UTC
### Describe the bug
Due to some reasons it is not possible to start a workspace from dashboard on che.openshift.io

### Che version
che.openshift.io

### Steps to reproduce

1. Open a new private browser window 
2. Login into your account
3. Try to start a workspace

### Expected behavior
Workspace is started as usual

### Runtime
che.openshift.io

### Screenshots
![failed to start a workspace](https://user-images.githubusercontent.com/15607393/98795587-0910b300-2413-11eb-85b3-4f4ca0a44fb7.png)

![screencast](https://user-images.githubusercontent.com/15607393/98800137-a7ebde00-2418-11eb-9591-54c59f611c01.gif)

### Installation method
N/A

### Environment
che.openshift.io

### Eclipse Che Logs
N/A

### Additional context
The issue is not 100% reproducible but happens quite often on my side.
![chromeVersion](https://user-images.githubusercontent.com/15607393/98799613-049ac900-2418-11eb-8572-391a58a1606b.png)

**Comment by tolusha** [comment] 2020-11-11 10:37
I was able to reproduce the issue.

**Comment by mmorhun** [comment] 2020-11-11 10:49
Page refresh (even without cache) doesn't help

**Comment by sleshchenko** [comment] 2020-11-11 12:03
The shared stacktraces are initialized by sso.redhat.com and static.redhat.com. I assume it's more hosted-che sso issue. @ibuziuk any ideas?

**Comment by ibuziuk** [comment] 2020-11-12 11:08
the private session requires unblocking of the cookies - https://www.eclipse.org/che/docs/che-7/hosted-che/hosted-che/#_troubleshooting

@mmorhun let me know if this helps

**Comment by mmorhun** [comment] 2020-11-12 13:45
@ibuziuk I have no extension in private Chrome window.

**Comment by mmorhun** [comment] 2020-11-12 13:51
@ibuziuk you are right, unchecking "Block third-party cookies" in private Chrome window resolved the issue. However it wasn't clear at all... Can we have some hint error message in case of such error?

**Comment by ibuziuk** [comment] 2020-11-12 14:09
@mmorhun @sleshchenko any ideas how the detection is expected to happen in the general case on the theia level?

**Comment by ibuziuk** [comment] 2020-11-17 11:54
going to close the issue, since enabling the cookies is a known documented requirment - https://www.eclipse.org/che/docs/che-7/hosted-che/hosted-che/#_troubleshooting

**Closed as completed by ibuziuk** 2020-11-17 11:54 UTC
Labels: kind/bug, severity/P1, area/hosted-che, area/editors
