### ISSUE TITLE
Dashboard is making new http requests every second (DevWorkspace mode)

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19372] opened 2021-03-23 14:07 UTC
### Describe the bug
Once my workspace is opened, I see requests every second to
`https://che-eclipse-che.apps.cluster-.../api/unsupported/k8s/apis/workspace.devfile.io/v1alpha2/namespaces/user1-che/devworkspaces`

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Create DevWorkspace with dashboard and look at http requests

### Expected behavior
websocket connection or more than one second request when the workspace is started.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

https://user-images.githubusercontent.com/436777/112159393-67337b00-8be9-11eb-937b-17dc6ecb25ad.mp4

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by sleshchenko** [comment] 2021-03-23 14:11
it's not a bug but feature.
unsupported k8s proxy does not support websockets.
it will be fixed when we switch to a new dashboard backend. I'll check if there is an issue for that.

**Comment by benoitf** [comment] 2021-03-23 14:15
one second still look 'overkill' once the workspace is started.

**Comment by sleshchenko** [comment] 2021-03-23 14:16
OK, then I agree it's a bug )

**Comment by sleshchenko** [comment] 2021-09-28 11:00
Is fixed by using websocket https://github.com/eclipse-che/che-dashboard/pull/349

**Closed as completed by sleshchenko** 2021-09-28 11:00 UTC
Labels: kind/bug, severity/P1, area/dashboard, engine/devworkspace
