### ISSUE TITLE
Adding ssh key by OAuth GitHub form does not work

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#2988] opened 2016-11-04 16:04 UTC
**Reproduction Steps:**

* Go to 'Profile'  - > 'Preferences' -> 'VSC' 
* Press button 'Generate key and upload it to GitHub'.
* Perform authorized application. 

**Expected behavior:**
The OAuth form should be closed and added ssh key.

**Observed behavior:**
The form is not closed, the ssh key is not added.

**Che version:**  5.0.0-M7  
**OS and version:**  Ubuntu 14.04  
**Docker version:** 1.12   
**Che install:**   Docker container  

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* See the attachment.
![ssh_keys_oauth](https://cloud.githubusercontent.com/assets/5408906/20012594/8f219f3a-a2b8-11e6-9d95-c729f099f0fb.gif)

**Comment by riuvshin** [comment] 2016-11-09 09:18
Removed blocker and regression. @artaleks9 if you open CHE with IP oAuth can't work because preconfigured oAuth is for localhost. 
But I think we can keep that issue and make proper error message instead of loading UD in popup.

**Comment by vinokurig** [comment] 2016-11-09 15:35
In the current logic the popup has close handler where it analyses his url all time when it's opened.
On authentication the popup goes to redirect url that he received from properties file.
If the redirect urls host is not the same as in main window, the popup will receive DOMException (http://stackoverflow.com/questions/25098021/securityerror-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame) while recognizing the url, which is ignored because the popup gets the same exception on loading gitHub authentication page (https://github.com != localhost). So thare is no way to recognize the case where ide loaded in the popup with different url with current logic.

@riuvshin I think that we can close this issue and we can create new one to think how to rework popup logic, if it is necessary.

**Comment by riuvshin** [comment] 2016-11-22 12:34
+1

**Closed as completed** 2016-11-22 12:35 UTC
Labels: kind/bug
