### ISSUE TITLE
Remove all workspace-related command from Theia File menu

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#13909] opened 2019-07-18 14:42 UTC
Theia File menu has items to open and close the workspace. But the workspace in Theia is something else that workspace in Che. In Theia it's a directory with projects.
Che works with predefined `/projects` directory which is never changed.
In that case it makes no sense to have Theia workspace related commands in file menu.
We can always load Theia and open `/projects` directory.

![workspace](https://user-images.githubusercontent.com/1655894/61466053-82aca400-a979-11e9-86d7-b0896400e0ba.png)

The solution could be to remove or hide Workspace* command from Theia File menu.
It will not confuse the user when dashboard sidebar is opened.

**Comment by rhopp** [comment] 2019-07-19 13:18
+1 for removing "workspace" references from Theia.

**Comment by benoitf** [comment] 2019-07-19 15:15
I think at F2F it was discussed that for example `close workspace` should be `stop workspace` instead

**Comment by rhopp** [comment] 2019-07-22 06:38
@benoitf Couldn't we do this in two steps? For GA, just remove these entries and for some future release bring them back with reimplemented functionality?

**Comment by tsmaeder** [comment] 2019-07-22 06:48
I'm doing this as part of changing to using projects workspace roots. See my message to che-dev 2 weeks ago. Propose to close this as a duplicate.

**Comment by l0rd** [comment] 2019-07-22 12:17
@tsmaeder duplicate of #13427 ?

**Comment by akurinnoy** [comment] 2019-07-26 10:57
@tsmaeder Hello, maybe you need some help getting rid of commands related to Theia workspaces?

**Comment by tsmaeder** [comment] 2019-07-31 11:11
Duplicate of duplicate of #13427

**Comment by vitaliy-guliy** [comment] 2019-09-06 13:19
@tsmaeder why did you close the issue? We still have a duplicate in the Theia File menu that has a different meaning.

**Comment by tsmaeder** [comment] 2019-09-09 08:58
Because this will be fixed when we move to a workspace root-based system as a fix for #13427, so this is a duplicate.

**Closed as completed by tsmaeder** 2019-09-09 08:58 UTC
Labels: kind/enhancement, status/in-progress, severity/P2, area/editor/theia
