### ISSUE TITLE
Cannot access workspace after upgrading from 7.0 to 7.1/7.2

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#14593] opened 2019-09-19 07:28 UTC
I have just upgraded our helm deployment from 7.0 to 7.1 (and latest master) and we now get a bunch of CORS/Jwtproxy errors and can't access any workspaces :(

### Screenshots
![Screenshot from 2019-09-19 08-22-30](https://user-images.githubusercontent.com/1720090/65222579-4e5b7e00-dab7-11e9-9659-0320e5c31f29.png)

### Che version
 - [x] latest
 - [x] nightly
 - [x] other: 7.1.0 and above

### Steps to reproduce
Launch any workspace.

### Expected behaviour
Be able to launch a workspace and access it via a web browser

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9", GitCommit:"3e4f6a92de5f259ef313ad876bb008897f6a98f0", GitTreeState:"clean", BuildDate:"2019-08-05T09:22:00Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

### Installation method
Helm charts via Rancher

### Environment
   - [x] my computer 
       - [x] Linux
   - [x] Cloud
       - [x] Amazon

### Additional context

The only changes from default helm chart are listed below
```
global: 
    cheWorkspacesNamespace: "che-hw4gt"
    ingressDomain: "che.che-test.XYZ.com"
    multiuser: "true"

CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP: "0"
CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_RUN__AS__USER: "0"
```

**Comment by sleshchenko** [comment] 2019-09-19 07:49
Looks like dashboard needs devfile based workspace in 7.1.0 while you have workspace config based.
Are you able to start new devfile based workspaces?

**Comment by davidwindell** [comment] 2019-09-19 11:23
@sleshchenko I've created a new workspace from the web GUI but it still won't load (same error)

**Comment by davidwindell** [comment] 2019-09-24 20:28
Any chance of any assistance with this? We are completely stuck, I've even tried creating a new helm deployment in a new namespace/new filesystem and the same errors persist

**Comment by amisevsk** [comment] 2019-09-24 20:33
Any logs on Che server? Are the websocket ports accessible from the workspace pod?

**Comment by davidwindell** [comment] 2019-09-24 20:35
Che server seems OK, as in workspace starts fine and shows as running:

```
2019-09-24 20:29:39,597[nio-8080-exec-6] [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 432] - Starting workspace 'admin/wksp-dk88' with id 'workspacexu6ell7bu0ypewlp' by user 'admin'
2019-09-24 20:30:52,891[aceSharedPool-0] [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 835] - Workspace 'admin:wksp-dk88' with id 'workspacexu6ell7bu0ypewlp' started by user 'admin'
```

Is there a CORS problem?

```
Access to XMLHttpRequest at 'http://servernssybnn8-jwtproxy-server-4401.che2.che-test.edge-servers.com/jwt/auth' from origin 'http://che-che2.che2.che-test.XYZ.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Or does the 404 error from this mean anything?

```
OPTIONS http://servernssybnn8-jwtproxy-server-4401.che2.che-test.edge-servers.com/jwt/auth 404 (Not Found)
```

**Comment by amisevsk** [comment] 2019-09-24 23:49
Hm, I'm not terribly familiar with the JWTProxy stuff.

**Comment by skabashnyuk** [comment] 2019-09-25 06:42
@davidwindell can you share workspace configuration? Is it che6 workspace(workspace config based) or che7(devfilebased)?

**Comment by davidwindell** [comment] 2019-09-25 14:20
Sure, it's just a basic PHP devfile workspace (launched from the provided stack). All workspaces have the same problem:

```
metadata:
  name: wksp-ob28
projects:
  - name: php-web-simple
    source:
      location: 'https://github.com/che-samples/web-php-simple'
      type: git
components:
  - id: redhat/php/latest
    memoryLimit: 1Gi
    type: chePlugin
  - id: redhat/php-debugger/latest
    memoryLimit: 256Mi
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: 8080/tcp
        port: 8080
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: composer
        containerPath: /home/user/.composer
      - name: symfony
        containerPath: /home/user/.symfony
    image: 'quay.io/eclipse/che-php-7:nightly'
    alias: php
apiVersion: 1.0.0
commands:
  - name: Start Apache Web Server
    actions:
      - type: exec
        command: service apache2 start
        component: php
  - name: Stop Apache Web Server
    actions:
      - type: exec
        command: service apache2 stop
        component: php
  - name: Restart Apache Web Server
    actions:
      - type: exec
        command: service apache2 restart
        component: php
  - name: Configure Apache Web Server DocumentRoot
    actions:
      - type: exec
        command: >
          if grep -q '/projects$' /etc/apache2/sites-available/000-default.conf;
          then
            sed -i 's|DocumentRoot /projects|DocumentRoot /projects/php-web-simple|' /etc/apache2/sites-available/000-default.conf
          else
            echo "DocumentRoot already configured!"
          fi
        component: php
```

**Comment by davidwindell** [comment] 2019-09-25 16:01
So I've tried deleting our entire k8s cluster and starting again. Exactly the same errors.

Is the problem because of CORS?

> Access to XMLHttpRequest at 'http://serverswr0cxfm-jwtproxy-server-4401.chehelp.che-test.XYZ.com/jwt/auth' from origin 'http://che-chehelp.chehelp.che-test.XYZ.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Has something changed on the JWTProxy (whatever that is ;) that could have affected CORS?

**Comment by amisevsk** [comment] 2019-09-25 17:57
@metlos any ideas here? Perhaps related to https://github.com/eclipse/che-jwtproxy/pull/11

**Comment by skabashnyuk** [comment] 2019-09-26 06:48
@davidwindell can you provide some additional context of this bug



### Describe the bug


### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce



### Expected behavior


### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots


### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

**Comment by davidwindell** [comment] 2019-09-26 08:49
@skabashnyuk I've filled out all the context above now, thanks

**Comment by skabashnyuk** [comment] 2019-09-26 11:49
Single host/default host mode?

**Comment by disaster37** [comment] 2019-09-26 13:54
Hi,

I think I have the same kind of behavior about cors issue after upgrading to 7.1.0.
I found that ingress created on Kubernetes for jwtproxy and for workspace seems bad.
It create ingress with path "/(.*)". Why not "/" ?

In my use case, I use multi host with multi user and no tls.

**Comment by davidwindell** [comment] 2019-09-26 14:02
I'm using the default (multi host? although only have one host for now).

**Comment by disaster37** [comment] 2019-09-26 14:25
And juste before get errors about CORS policy, I get 404 on URL http://serverxjjk9v49-jwtproxy-server-4401.che2.XXX.XXX.XXX.XXX.nip.io/jwt/auth

**Comment by skabashnyuk** [comment] 2019-09-26 14:28
@davidwindell @disaster37 can you make sure that jwt-proxy pod is running. Is there any strange event related to this pod?

**Comment by amisevsk** [comment] 2019-09-26 15:01
There's a bit of documentation about how ingress annotations work for the single host strategy: https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L488-L521, perhaps @metlos can comment

**Comment by skabashnyuk** [comment] 2019-09-26 15:06
Some output from successful jwtproxy start.

![Знімок екрана  о 17 04 05](https://user-images.githubusercontent.com/1614429/65700293-b09c1c00-e07f-11e9-8047-3a89be82ccb0.png)

```
curl -v  'http://routeen4yps6k-eclipse-che.apps-crc.testing/jwt/auth' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36' -H 'Referer: http://che-eclipse-che.apps-crc.testing/_app/loader.html?redirectUrl=http%3A%2F%2Frouteen4yps6k-eclipse-che.apps-crc.testing%2F&workspaceId=workspace0dx1f1e3d7nwdijx' -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlMGR4MWYxZTNkN253ZGlqeCJ9.eyJ3c2lkIjoid29ya3NwYWNlMGR4MWYxZTNkN253ZGlqeCIsInVpZCI6ImIwN2UzYTU4LWVkNTAtNGE2ZS1iZTE3LWZjZjQ5ZmY4YjI0MiIsImF1ZCI6IndvcmtzcGFjZTBkeDFmMWUzZDdud2RpangiLCJuYmYiOi0xLCJ1bmFtZSI6ImF555aXNzIjoid3NtYXN0ZXIiLCJleHAiOjE2MDEwNDU2MDMsImlhdCI6MTU2OTUwOTYwMywianRpIjoiYmExY2M4MWQtMGU5YS00OTU4LWFkNDktYmNhZjU2MGVmZmFlIn0.dydeY9wAnr8zXBziQaXW0oVfqmiLH7XoH0xLsamtt9LDkhUwMcIX0j2hWT-LyRJBZLq76DaYRKccY_yVuBv3OoE8-yD27trUcvrzItp_XgB_WeH8rX8n1FirSD5JCAL60jZEQKc2VCNHLgmoAV6FXdtqJnDmdfBCWODMmftKQibCQGB9pQ6uj8a5KQDZYdsDi6gtjCA0aO8P6AilrFtyMeJiEuibUP1gzQzUX585Xf5jWmkCGN1GIfurVLVBaUuVSEFknoJlmGQqO1e8BFIrVbcOS1JgPS55C6b4IrBPrDZuakc2egJ_Y97Z9znY4gHtB8RLpzsHTprF8Va5A' --compressed --insecure
*   Trying 192.168.64.59...
* TCP_NODELAY set
* Connected to routeen4yps6k-eclipse-che.apps-crc.testing (192.168.64.59) port 80 (#0)
> GET /jwt/auth HTTP/1.1
> Host: routeen4yps6k-eclipse-che.apps-crc.testing
> Accept: */*
> Accept-Encoding: deflate, gzip
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
> Referer: http://che-eclipse-che.apps-crc.testing/_app/loader.html?redirectUrl=http%3A%2F%2Frouteen4yps6k-eclipse-che.apps-crc.testing%2F&workspaceId=workspace0dx1f1e3d7nwdijx
> Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlMGR4MWYxZTNkN253ZGlqeCJ9.eyJ3c2lkIjoid29ya3NwYWNlMGR4MWYxZTNkN253ZGlqeCIsInVpZCI6ImIwN2UzYTU4LWVkNTAtNGE2ZS1iZTE3LWZjZjQ5ZmY4YjI555mF1ZCI6IndvcmtzcGFjZTBkeDFmMWUzZDdud2RpangiLCJuYmYiOi0xLCJ1bmFtZSI6ImFkbWluIiwiaXNzIjoid3NtYXN0ZXIiLCJleHAiOjE2MDEwNDU2MDMsImlhdCI6MTU2OTUwOTYwMywianRpIjoiYmExY2M4MWQtMGU5YS00OTU4LWFkNDktYmNhZjU2MGVmZmFlIn0.dydeY9wAnr8zXBziQaXW0oVfqmiLH7XoH0xLsamtt9LDkhUwMcIX0j2hWT-LyRJBZLq76DaYRKccY_yVuBv3OoE8-yD27trUcvrzItp_XgB_WeH8rX8n1FirSD5JCAL60jZEQKc2VCNHLgmoAV6FXdtqJnDmdfBCWODMmftKQibCQGB9pQ6uj8a5KQDZYdsDi6gtjCA0aO8P6AilrFtyMeJiEuibUP1gzQzUX585Xf5jWmkCGN1GIfurVLVBaUuVSEFknoJlmGQqO1e8BFIrVbcOS1J555VLMcRC6b4IrBPrDZuakc2egJ_Y97Z9znY4gHtB8RLpzsHTprF8Va5A
>
< HTTP/1.1 204 No Content
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: http://che-eclipse-che.apps-crc.testing
< Content-Type: text/plain
< Set-Cookie: access_token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlMGR4MWYxZTNkN253ZGlqeCJ9.eyJ3c2lkIjoid29ya3NwYWNlMGR4MWYxZTNkN253ZGlqeCIsInVpZCI6ImIwN2UzYTU4LWVkNTAtNGE2444iZTE3LWZjZjQ5ZmY4YjI0MiIsImF1ZCI6IndvcmtzcGFjZTBkeDFmMWUzZDdud2RpangiLCJuYmYiOi0xLCJ1bmFtZSI6ImFkbWluIiwiaXNzIjoid3NtYXN0ZXIiLCJleHAiOjE2MDEwNDU2MDMsImlhdCI6MTU2OTUwOTYwMywianRpIjoiYmExY2M4MWQtMGU5YS00OTU4LWFkNDktYmNhZjU2MGVmZmFlIn0.dydeY9wAnr8zXBziQaXW0oVfqmiLH7XoH0xLsamtt9LDkhUwMcIX0j2hWT-LyRJBZLq76DaYRKccY_yVuBv3OoE8-yD27trUcvrzItp_XgB_WeH8rX8n1FirSD5JCAL60jZEQKc2VCNHLgmoAV6FXdtqJnDmdfBCWODMmftKQibCQGB9pQ6uj8a5KQDZYdsDi6gtjCA0aO8P6AilrFtyMe555UP1gzQzUX585Xf5jWmkCGN1GIfurVLVBaUuVSEFknoJlmGQqO1e8BFIrVbcOS1JgPSB8VLMcRC6b4IrBPrDZuakc2egJ_Y97Z9znY4gHtB8RLpzsHTprF8Va5A; Path=/; HttpOnly
< Date: Thu, 26 Sep 2019 15:00:28 GMT
< Set-Cookie: 33c2e2242f83ceafe8a4a3df4f2a8dcb=84a9cdd970cea6e17226f056540ad211; path=/; HttpOnly
< Cache-control: private
<
* Connection #0 to host routeen4yps6k-eclipse-che.apps-crc.testing left intact

```

@davidwindell what type/version of ingress controller are you using?

**Comment by disaster37** [comment] 2019-09-26 17:23
There are nothink strange with jwtproxy pods that called verifier

Some logs:
```
time="2019-09-26T17:17:02Z" level=info msg="Starting reverse proxy (Listening on ':4401')"
time="2019-09-26T17:17:02Z" level=info msg="Starting reverse proxy (Listening on ':4400')"
```

I look that ingress use label `nginx.ingress.kubernetes.io/rewrite-target` but this label start to work with nginx-ingress 0.22.0. I use version 0.21.0 in my context (rancher 2.2.8 with Kubernetes 1.14.6). Maybee it's the cause of problem ?

**Comment by amisevsk** [comment] 2019-09-27 03:16
@disaster37 Yeah, this is something we likely need to document better. From the che.properties file, I see
```
For nginx ingress controller older than 0.22.0, the rewrite-target should be set to merely "/" and the path transform
to "%s" (see the the che.infra.kubernetes.ingress.path.rewrite_transform property).
```
Could you try setting env vars:
```
CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON='{"ingress.kubernetes.io/rewrite-target": "/","ingress.kubernetes.io/ssl-redirect": "false", "ingress.kubernetes.io/proxy-connect-timeout": "3600","ingress.kubernetes.io/proxy-read-timeout": "3600"}'
CHE_INFRA_KUBERNETES_INGRESS_PATH__TRANSFORM="%s"
```
on the Che server deployment and trying again? (pending confirm from @metlos that those are the correct values)

**Comment by disaster37** [comment] 2019-09-27 07:28
Hi, it's work like a charm, thanks ;)

**Comment by skabashnyuk** [comment] 2019-09-27 07:44
@davidwindell  can you test https://github.com/eclipse/che/issues/14593#issuecomment-535769427 from your side?

**Comment by davidwindell** [comment] 2019-09-27 10:47
It worked!! Thank you so much. Yes, the latest Rancher uses the nginx ingress controller v0.21 at the moment.

**Comment by skabashnyuk** [comment] 2019-09-27 11:11
@davidwindell can we close this ticket?

**Comment by skabashnyuk** [comment] 2019-09-27 11:15
@davidwindell @disaster37 I encourage you to contribute this information https://github.com/eclipse/che/issues/14593#issuecomment-535769427 to Eclipse Che docs https://github.com/eclipse/che-docs so next time users will not hit the same problem as you. Would you like me to assist you?

**Closed as completed** 2019-09-27 11:23 UTC
Labels: kind/bug, status/info-needed, severity/P2

**Comment by davidwindell** [comment] 2019-09-27 11:26
@skabashnyuk I'd be happy to do so, can you point me to the best page to list this on in the docs repo?

**Comment by skabashnyuk** [comment] 2019-09-27 11:49
@davidwindell awesome. I think https://github.com/eclipse/che-docs/blob/master/src/main/pages/che-7/overview/assembly_deploying-che-on-kubernetes-on-aws.adoc can be our starting point. We can add here section troubleshooting. WDYT?

**Comment by davidwindell** [comment] 2019-09-28 09:36
@skabashnyuk I think there is scope for a vanilla K8S guide where helm is used to deploy? I haven't used the AWS guide directly (we use Rancher).

**Comment by skabashnyuk** [comment] 2019-09-28 15:04
@davidwindell apparently we don't have it.
