### ISSUE TITLE
[Hosted che] Openshift oAuth returns invalid token

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#17020] opened 2020-05-26 11:18 UTC
Openshift oAuth provider returns invalid token for the Openshift which runs [hosted Che](https://che.openshift.io).
### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create a workpspace with [openshift connector plugin](https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/redhat/vscode-openshift-connector).
2. Start the workspace
3. See error: 
![screenshot-che openshift io-2020 05 26-13_09_12](https://user-images.githubusercontent.com/7668752/82888557-1fed4700-9f52-11ea-9615-2afbd155262b.png)
4. Open terminal for the openshift-connector sidecar
5. Execute `curl -H 'Authorization: Bearer <user token>' https://che.openshift.io/api/oauth/token?oauth_provider=openshift` and see the token
6. execute `oc get user --token <token from the request>`
7. See authorisation error.

It is strange that the oauth/token request can return a token even without specifying `oauth_provider` parameter (``curl -H 'Authorization: Bearer <user token>' https://che.openshift.io/api/oauth/token``)

### Expected behavior

The token must be valid
### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by ibuziuk** [comment] 2020-05-26 11:27
sorry, not following what is the expected behaviour? Have you seen https://github.com/eclipse/che/issues/16890 ?

**Comment by vinokurig** [comment] 2020-05-26 12:46
The expected behaviour should be a valid openshift token response from the `curl -H 'Authorization: Bearer <user token>' https://che.openshift.io/api/oauth/token?oauth_provider=openshift` request

**Comment by vinokurig** [comment] 2020-05-26 12:47
https://github.com/eclipse/che/issues/16890 needs this to login automatically

**Comment by ibuziuk** [comment] 2020-05-27 10:02
@vinokurig could you clarify how the plugin works atm? as you can see it login to the *-che namespace:

https://user-images.githubusercontent.com/1461122/81581490-1808a100-93af-11ea-9cf2-fd8a44a7f262.png

I do not understand what is expected to be done on Hosted Che end. Also see: https://github.com/eclipse/che/issues/16890#issuecomment-634037344

**Comment by vinokurig** [comment] 2020-05-27 14:36
@ibuziuk
> could you clarify how the plugin works atm? as you can see it login to the *-che namespace:

It is loged in as `system:serviceaccount:*-che:che-workspace` (`oc whoami` output) but to get access to the user's cluster:
![screenshot-che openshift io-2020 05 27-17_28_14](https://user-images.githubusercontent.com/7668752/83033453-cc592700-a03f-11ea-8746-67a9c1753789.png)
I've logged in via login and password, but to automate the login flow we need the user openshift token which can be received by the [oAuth API](https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAPI.java#L51-L54). The oauth API works nice in my local minishift assembly but https://che.openshift.io/api/oauth/token API request returns an invalid token.

**Comment by ibuziuk** [comment] 2020-06-01 14:51
@vinokurig based on the https://github.com/eclipse/che/issues/16890#issuecomment-634037344 It looks like it is not a good idea to fall back on che specific API. Also, I do not understand why if the login is failing the OpenShift connector still logs in to the *-che namespace correctly? (what login mechanism is used there?)

https://user-images.githubusercontent.com/1461122/81581490-1808a100-93af-11ea-9cf2-fd8a44a7f262.png

@ericwill wdyt about closing the issue in favor of https://github.com/eclipse/che/issues/16890 and continue the discussion in one place?

**Comment by ericwill** [comment] 2020-06-01 14:56
> @ericwill wdyt about closing the issue in favor of #16890 and continue the discussion in one place?

Yes, sure. @vinokurig let's continue the discussion in #16890

**Closed as completed by ericwill** 2020-06-01 14:56 UTC
Labels: kind/bug, severity/P1, area/hosted-che
