### ISSUE TITLE
Autosave is moving the editor cursor while typing

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18096] opened 2020-10-12 11:58 UTC
### Describe the bug
When typing, and autosave activated, the cursor is automatically moved somewhere else while typing.

My workaround is to change the autosave delay to 5000 ms or disable it to have a usable editor.

I could reproduce with

- .js files

at the moment. Have not tried with other file types yet.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

**Comment by azatsarynnyy** [comment] 2020-10-12 12:50
It looks like a duplicate of https://github.com/eclipse/che/issues/16194

**Comment by sunix** [comment] 2020-10-12 13:19
@azatsarynnyy I am not sure, I did not have any issues few days ago in the same environment

**Comment by sunix** [comment] 2020-10-12 14:24
Maybe the files in `/projects` are getting too big
```
root@workspacesuglr2l0atm0n5cs:/projects 
$ du -sh
1.8G    .
root@workspacesuglr2l0atm0n5cs:/projects 
$
```

**Comment by l0rd** [comment] 2020-10-21 22:55
I have reproduced that with the spring boot getting started.

**Comment by azatsarynnyy** [comment] 2020-11-05 17:45
I noticed that the cursor is moving only in the projects that have `.editorconfig` file included. With enabled [`trim_trailing_whitespace` feature](https://github.com/spring-projects/spring-petclinic/blob/27109010a52600eb9bf227d631fac3f81ed6ba15/.editorconfig#L12).
So, the easiest workaround is to disable `trim_trailing_whitespace` in `.editorconfig` file.

**Comment by azatsarynnyy** [comment] 2020-11-05 17:49
Another thing I'm checking in https://github.com/eclipse/che-theia/pull/912 is to exclude `EditorConfig` VS Code extension from Che Theia built-in Plug-ins and make it optional via Che Plug-in Registry.

**Closed as completed** 2020-11-05 19:24 UTC
Labels: kind/bug, severity/P1, area/editor/theia

**Comment by azatsarynnyy** [comment] 2020-11-05 19:31
Confirmed - the issue was caused by EditorConfig VS Code extension that works a bit different in Theia/Che Theia comparing to VS Code. So, I've excluded it from Che Theia built-in Plug-ins https://github.com/eclipse/che-theia/pull/912

If it will be required we can consider adding it to Che Plug-in Registry, and analyze how to change/fix the default behavior.
The issue for that is https://github.com/eclipse/che/issues/18297

**Comment by l0rd** [comment] 2020-11-05 21:43
Nice work. Thank you @azatsarynnyy
