### ISSUE TITLE
Git markers are not displayed for mounted project

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#6844] opened 2017-10-19 14:04 UTC
### Description
Git markers in editor are displayed for created/imported project, but are not displayed for mounted project
**Che version:**    
6.0.0-M1
![gitmarkersbug](https://user-images.githubusercontent.com/5676062/31774820-7f3fe3ac-b4ef-11e7-8c11-a1b092de53ab.gif)

If project doesn't have vcs provider then we have to ask a parent and so on.

**Comment by AndrienkoAleksandr** [comment] 2017-10-19 14:21
+1 The same.

**Comment by vinokurig** [comment] 2017-10-30 11:40
IInvestigation shows that it happens because `Project` object received from a file, that is located not in the root of the project, does not return any mixins. https://github.com/eclipse/che/blob/8936842508ed17fdd49341bc3ced53ef8002201b/ide/che-core-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/OrionEditorPresenter.java#L1214-L1222

**Comment by RomanNikitenko** [comment] 2017-10-30 14:15
@vinokurig Do you mean 'appContext.getRootProject().getAttribute("vcs.provider.name")' will fix the issue at this case?

**Comment by vinokurig** [comment] 2017-10-30 15:02
I guess yes, but anyway project with mixins must be returned from any file

**Comment by vinokurig** [comment] 2017-11-20 08:35
Can not reproduce the issue described in my previous comment (https://github.com/eclipse/che/issues/6844#issuecomment-340419516) in the latest version

**Comment by vinokurig** [comment] 2017-11-20 08:38
I think it should be fixed by https://github.com/eclipse/che/issues/7407

**Comment by vinokurig** [comment] 2017-11-23 14:32
It is reproduced if the project has multiple maven modules. It doesn't matter if the project is mounted or not!

**Closed as completed** 2017-12-07 09:51 UTC
Labels: kind/bug
