### ISSUE TITLE
Investigate how to report metrics from workspaces

### ISSUE THREAD

**Issue by mkuznyetsov** [eclipse-che/che#13375] opened 2019-05-21 08:47 UTC
It is needed to figure out the approach on how to collect and observe metrics from workspace agent/editor/language servers, such as "The % of workspaces projects cloned successfully" and "The % of Language Servers requests that get a successful response"

related to https://github.com/eclipse/che/issues/13270

**Comment by tsmaeder** [comment] 2019-08-14 11:41
Duplicate of Investigate Language server metrics #14017 ?

**Comment by skabashnyuk** [comment] 2019-08-14 13:38
I think they can be distinct.
https://github.com/eclipse/che/issues/14017 - can be limited to providing metrics in  Prometheus format to some endpoint.
https://github.com/eclipse/che/issues/13375 - this can be about how to collect LSP and other metrics from the workspace and deliver them to Prometheus server

**Comment by tsmaeder** [comment] 2019-08-14 14:02
So we need to wait now until this issue here is solved?

**Comment by skabashnyuk** [comment] 2019-08-14 14:06
I think you can start working https://github.com/eclipse/che/issues/14017

**Comment by tsmaeder** [comment] 2019-09-25 07:43
We're going to have metrics from theia plugins soon. Any progress on this issue?

**Comment by skabashnyuk** [comment] 2019-09-25 08:08
>Any progress on this issue?

No. No progress.
The only known to me reasonable variant is to relay on prometheus-operator. However, for hosted Che it can be a complicated dependency. 
CC @l0rd

**Comment by skabashnyuk** [comment] 2019-10-31 07:44
closing with prefer to :
-  [MVP] Collecting Che Workspace metrics in single cluster mode with Prometheus https://github.com/eclipse/che/issues/14888
-  Collecting Che Workspace metrics in multiple cluster mode with help of Prometheus Federation mechanism https://github.com/eclipse/che/issues/14889
-  Test Prometheus federation in simplified mode. https://github.com/eclipse/che/issues/15030
- Investigate alternative possibilities to reduce Prometheus's permissions required to monitor workspaces https://github.com/eclipse/che/issues/15031

**Closed as completed by skabashnyuk** 2019-10-31 07:44 UTC
Labels: kind/task, severity/P1
