### ISSUE TITLE
Devfile: Updating devfile in workspace has a mismatch between the cursor position and actual editing position

### ISSUE THREAD

**Issue by bryantson** [eclipse-che/che#14168] opened 2019-08-08 19:10 UTC
### Describe the bug

In a newly created workspace, the custom commands are modified in DEVFILE. The cursor that is pointing and the actual editing position is mismatching both from the horizontal and vertical editing perspective. 

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify
latest

### Steps to reproduce
1. Create a new workspace
2. Go back to Dashboard and click the gear icon to Configure Workspace
3. Click "Devfile" tab
4. Modify the existing lines
5. Notice that the cursor position is mismatching with the actual editing position

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: (please specify)

AWS

### Installation method
   - [ ] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

- Windows
- AWS
- Chrome Browser

**Comment by rhopp** [comment] 2019-08-09 13:37
Hi @bryantson !
Thanks for the bugreport. Could you please also provide some screenshot/screencast of the errorneous behavior?
Could you also send us which version of Chrome are you using?

I've tried that (with latest che deployed on minikube) and Google Chrome 76 and I was not experiencing any of the behavior you are describing.

**Comment by bryantson** [comment] 2019-08-12 14:43
@rhopp Thank you. Sure. Please see one screenshot showing the erroneous behavior with an appropriate comments.

<img width="1890" alt="screenshot" src="https://user-images.githubusercontent.com/5396174/62873799-9da6d580-bce5-11e9-9c0e-7ac46e9079ab.png">
I am using Google Chrome: Version 76.0.3809.100 (Official Build) (32-bit)

In addition, it will be nice to have the editing options there (Save, Undo, Redo, etc) instead of just auto-saving, but this will probably require the separate Issue request.

**Comment by sleshchenko** [comment] 2020-03-26 13:08
I believe it should not be actual anymore since we use the new monaco YAML editor merged in https://github.com/eclipse/che/pull/15067
@JPinkney @olexii4 Could you confirm my guess?

**Comment by olexii4** [comment] 2020-03-31 11:42
@sleshchenko I confirm. We have the new Monaco editor now instead of the CodeMirror. I can't reproduce this bug.

**Comment by sleshchenko** [comment] 2020-04-01 07:52
@bryantson Feel free to reopen or create a new issue if it still does not work for you on newer Che

**Closed as completed** 2020-04-01 07:51 UTC
Labels: status/info-needed, severity/P2, area/dashboard
