### ISSUE TITLE
Cannot share workspace

### ISSUE THREAD

**Issue by vseager** [eclipse-che/che#8952] opened 2018-02-28 09:47 UTC
### Description
Within any of our workspace settings, the 'Share' tab is empty, see screenshot. This happens for all users.

### Reproduction Steps
Select any workspace from the workspace dashboard and click on the 'Share' tab.

**OS and version:**
Nightly (6.2.0)

**Diagnostics:** 
Console errors:
```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
vendor-73784b1bca.js:33381 TypeError: Cannot read property 'ENTER' of undefined
    at e (app-4f97698dc6.js:3593)
    at Object.i [as invoke] (vendor-73784b1bca.js:25384)
    at d.instance (vendor-73784b1bca.js:30043)
    at g (vendor-73784b1bca.js:29160)
    at vendor-73784b1bca.js:29433
    at l (vendor-73784b1bca.js:35653)
    at vendor-73784b1bca.js:35669
    at h.$eval (vendor-73784b1bca.js:36913)
    at h.$digest (vendor-73784b1bca.js:36731)
    at h.$apply (vendor-73784b1bca.js:37021)
(anonymous) @ vendor-73784b1bca.js:33381
/api/ssh/workspace/find?name=workspace0ceszop8nwf6qlmh Failed to load resource: the server responded with a status of 404 (Not Found)
/api/workspace/namespace/outeredge Failed to load resource: the server responded with a status of 403 (Forbidden)
page.js:204 10 false false
app-f5f089f345.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

![screenshot-2018 02 28-09-36-27](https://user-images.githubusercontent.com/2035088/36780900-3c820fd8-1c6c-11e8-859d-ab45826cbdfc.png)

**Comment by davidwindell** [comment] 2018-02-28 14:36
@vseager looks like a duplicate of #8900

**Comment by skabashnyuk** [comment] 2018-03-05 07:09
closed as duplicate

**Closed as completed by skabashnyuk** 2018-03-05 07:09 UTC
