### ISSUE TITLE
Git clone with https fails

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#16362] opened 2020-03-14 22:34 UTC
### Describe the bug
Cloning using a https url from Github fails with the following error
```
Cloning into '/projects/'...
fatal: cannot exec '/default-theia-plugins/vscode-git/extension/out/askpass.sh': Permission denied
fatal: could not read Username for 'https://github.com': No such device or address
```

### Che version

 - [x] latest (7.9.1)
 - [ ] nightly
 - [ ] other: please specify

**Comment by benoitf** [comment] 2020-03-15 07:06
Seems to duplicate https://github.com/eclipse/che/issues/16084

**Comment by ibuziuk** [comment] 2020-03-16 14:37
@ericwill should we close it as a duplicate of #16084

**Comment by ericwill** [comment] 2020-03-16 14:39
Yes it's a duplicate.

**Comment by benoitf** [comment] 2020-03-16 14:41
I think priority is quite high as well

**Comment by ibuziuk** [comment] 2020-03-16 14:42
Closing in favor of #16084

**Closed as completed by ibuziuk** 2020-03-16 14:42 UTC
Labels: kind/bug, severity/P1, status/duplicate, area/plugins
