### ISSUE TITLE
Che does not start after toggling dev mode on / off from CLI

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#3351] opened 2016-12-12 12:25 UTC
Could not use own Che build 

`docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/vetal/che:/data -v /home/vetal/codenvy/projects/che:/repo eclipse/che-cli:nightly start`

```
WARNING: No swap limit support
INFO: (che cli): Loading cli...
WARN: Your local eclipse/che-cli:nightly image is older than the version on DockerHub.
WARN: Run 'docker pull eclipse/che-cli:nightly' to update your CLI.
INFO: (che cli): Checking registry for version 'nightly' images
INFO: (che config): Generating che configuration...
Notice: Compiled catalog for f30f78d9e0ce.ua.codenvy-dev.com in environment production in 0.11 seconds
Notice: Applied catalog in 0.04 seconds
INFO: (che config): Customizing docker-compose for running in a container
INFO: (che start): Preflight checks
        port 8080 (http):       [AVAILABLE] 
        port 8000 (debug):       [AVAILABLE]

INFO: (che start): Starting containers...
Couldn't find env file: /che/instance/config/che.env

**Reproduction Steps:**

1. docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/vetal/che:/data  eclipse/che-cli:nightly start`
2. build Che with own changes 
3. docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/vetal/che:/data -v /home/vetal/codenvy/projects/che:/repo eclipse/che-cli:nightly start

**Expected behavior:**
Che server should start

**Observed behavior:**
Got error: Couldn't find env file: /che/instance/config/che.env
[Describe observed behavior here]

**Che version:**    5.0.0-M9-SNAPSHOT   
**OS and version:** Ubuntu 16.04
**Docker version:**  1.12.3

**Comment by TylerJewell** [comment] 2016-12-12 12:28
Paste cli log output

**Comment by vparfonov** [comment] 2016-12-12 12:47
[cli.log.txt](https://github.com/eclipse/che/files/645933/cli.log.txt)

**Comment by TylerJewell** [comment] 2016-12-12 13:53
@vparfonov @skabashnyuk @riuvshin @benoitf - ok, I see the issue here.  So, the scenario is:
1. Start Che from CLI without dev mode
2. Restart Che with dev mode

Then there is an error.  The issue is that when using dev mode, all of the configuration files are sourced from the repository, not just the custom assembly. So if you did an init() using the Che CLI image and then turn on dev mode, we use a different set of configuration files.  

First question - do we wnat to allow this workflow?

**Comment by vparfonov** [comment] 2016-12-12 15:07
I think yes. But it least it should say something for understand problem, like "your Che dir not empty try new one"

**Comment by TylerJewell** [comment] 2016-12-12 16:24
@vparfonov - I believe that this issue was resolved in the latest fixup.  It has to do with the renaming of the volume mount from :/che to :/data.

The docker-compose-container.yml file that is generated by the old refactor was generating the old location of the env file.  I just did a new test, and it's now generating the right location.  So I believe that this issue was only temporary due to the switchover and would not occur again if you start everything from scratch.

**Closed as completed** 2016-12-13 15:17 UTC
Labels: kind/bug, severity/blocker, status/analyzing
