### ISSUE TITLE
Cursor does not return after undo operation in a big file

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#7770] opened 2017-12-07 13:37 UTC
### Reproduction Steps
Create ws. base on Eclipse Che stack. Clone the che project, checkout on che6 stack. Wait resolving dependency. Open Editor PageObject. Refactor some methods. Perform ctrl+z.
![ezgif com-video-to-gif3](https://user-images.githubusercontent.com/1640058/33718027-acb41100-db64-11e7-9481-c240c97b8d1d.gif)

**Expected result:** The cursor should return to previews position 
**Actual result:** The cursor loses position, all content becomes selected
**OS and version:**   Chrome browser, CHE 6.0.0-M3. 

**Diagnostics:**

**Comment by RomanNikitenko** [comment] 2018-01-04 11:08
The issue is relevant for case when user applies undo operation after using Refactoring rename dialog.
Fix for this case: https://github.com/eclipse/che/pull/8172
In case when user applies undo operation after renaming in linked mode (without Refactoring rename dialog, just Shift + F6) we should fix https://github.com/eclipse/che/issues/8136 at first.

**Closed as completed** 2018-01-05 12:44 UTC
Labels: kind/bug, severity/P1
