### ISSUE TITLE
Plugin installation fails from che-theia workspace

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-che/che#15006] opened 2019-10-28 16:19 UTC
I have a trial instance of openshift.io and a default workspace (Java maven). When I open the plugin view and click on "install" on any plugin, I get:
"Unable to install plugin 'redhat/php-debugger/latest'. Request addPlugin failed unexpectedly without providing any details."

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] openshift.io
   - [ ] other: please specify

**Comment by ibuziuk** [comment] 2019-11-04 19:28
Also fails for me but with a bit different flow on 7.3.1:

![Peek 2019-11-04 20-25](https://user-images.githubusercontent.com/1461122/68151242-9b00f880-ff41-11e9-8f22-30781885ba48.gif)

**Comment by ibuziuk** [comment] 2019-11-04 19:30
@evidolob any comments on that ^ ?

**Comment by skabashnyuk** [comment] 2019-11-05 15:32
Reproduced
<img width="1678" alt="Знімок екрана  о 16 32 24" src="https://user-images.githubusercontent.com/1614429/68221565-e66ee180-ffe9-11e9-9886-ecf946215d74.png">

**Comment by evidolob** [comment] 2019-11-06 07:54
che-theia use DELETE http request with `/api/workspace/{workspaceId}/runtime` URL.
When I do curl request on that URL, I got
```
Error: Failed to run the workspace: "Failure executing: POST at: https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/api/v1/namespaces/yvydolob-che/configmaps. 
Message: configmaps "workspacegyj2ynixetn1vkm2-gitconfig" already exists. Received status: 
Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=configmaps, name=workspacegyj2ynixetn1vkm2-gitconfig, retryAfterSeconds=null, uid=null, 
additionalProperties={}), kind=Status, message=configmaps "workspacegyj2ynixetn1vkm2-
gitconfig" already exists, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null,
 additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={})."
```
error on ws-loader, 
I think problem in implementation of `/api/workspace/{workspaceId}/runtime` REST service

**Comment by ibuziuk** [comment] 2019-11-06 08:19
@evidolob you execute delete and get `Failure executing: POST` ?
Also, could you please test locally (I see that you are still testing against Hosted Che)

**Comment by vitaliy-guliy** [comment] 2019-11-06 09:46
To solve the problem we need:
- [ ] fix an error when updating the devfile of running workspace (Request addPlugin failed unexpectedly)
- [ ] check workpsace status before refreshing the page (should wait until workspace status has been changed)

**Comment by vitaliy-guliy** [comment] 2019-11-06 14:28
@JonasHelming could you provide more information about your workspace? I need at least your devfile to reproduce the case and check the error when installing a plugin (addPlugin request).

I created a workspace from the following devfile but didn't get any errors.
```
metadata:
  name: che-theia-all
projects:
  - name: che-theia
    source:
      location: 'https://github.com/eclipse/che-theia.git'
      type: git
      branch: master
  - name: theia
    source:
      location: 'https://github.com/theia-ide/theia.git'
      type: git
      branch: master
components:
  - mountSources: true
    endpoints:
      - name: theia-dev-flow
        attributes:
          protocol: http
          public: 'true'
        port: 3010
    memoryLimit: 3000Mi
    type: dockerimage
    alias: che-dev
    image: 'eclipse/che-theia-dev:next'
apiVersion: 1.0.0
commands:
  - name: init ... DEV che-theia
    actions:
      - workdir: /projects/theia
        type: exec
        command: |
          che:theia init
        component: che-dev
```

**Comment by ibuziuk** [comment] 2019-11-07 10:35
@vitaliy-guliy hmm.. why do you need a devfile? steps to repro are basically:
- start any workspace
- open plugin view
- install any plugin

https://github.com/eclipse/che/issues/15006#issuecomment-549509695

This need to be tested against multiuser with tls / celf-signed-certs and workspace creation in the unique namespace

**Comment by vitaliy-guliy** [comment] 2019-11-07 10:39
@ibuziuk I cannot get an error with updating the devfile (adding a plugin component) on che.openshift.io as @JonasHelming noted

I did exactly as you wrote:
- start any workspace
- open plugin view
- install any plugin

Result: new plugin component in the devfile is appeared.

But yes, there is still a problem with restarting the workspace.

**Comment by ibuziuk** [comment] 2019-11-07 10:41
> But yes, there is still a problem with restarting the workspace.

This is the biggest issue, workspace is not stopped properly and all the workspace resources are still there (routes, deployments etc) see the error message  https://github.com/eclipse/che/issues/15006#issuecomment-550189980

**Comment by ibuziuk** [comment] 2019-11-07 10:42
@evidolob if the plugin installation issue / workspace stop + restart is not Hosted Che specific we would probably need to disable plugin installation from che-theia UI

**Comment by skabashnyuk** [comment] 2019-11-11 11:19
@ibuziuk I think at this moment we can't guarantee for sure that there is no Hosted Che specific. I believe that we need to fix this https://github.com/redhat-developer/rh-che/issues/1689 and clarify all exceptions that happened during workspace removal on Hosted Che.

**Comment by skabashnyuk** [comment] 2019-11-11 12:44
Tested upstream multi-user workspace stop with machine token on crc version: 1.1.0+95966a9 OpenShift version: 4.2.2 (embedded in binary). Everything works as expected.
<img width="1144" alt="Знімок екрана  о 13 41 00" src="https://user-images.githubusercontent.com/1614429/68588295-68975400-0489-11ea-97c2-3a9a471b2b75.png"> No issues on che server logs

**Comment by vitaliy-guliy** [comment] 2019-11-11 15:46
Cannot stop the workspace with machine token on local minishift and openshift.io.

Che server responds OK on STOP request but then, when listening workspace status via websocket, client receives the message that an error occurred when stopping the workspace.
After that when getting the workspace info, it's status is STOPPED but on the infrastructure everything is still running.

**Comment by skabashnyuk** [comment] 2019-11-11 15:50
openshift.io is another story. I was not able to reproduce in on minishift. What was your configuration on minishift? chectl, operator, OAuth?

**Comment by Katka92** [comment] 2019-11-12 07:15
Hi guys, I've tried to reproduce on Hosted Che. When I install a plugin and click the button to refresh the workspace, I got an error [1]. I've refreshed the browser window again and got a different error [2] saying that `Config maps already exist.`. I came to the console to check if the resources are really here - and there were, but in a few seconds they were deleted correctly. I refreshed again and the workspace was loaded correctly. 

[1]
![Screenshot from 2019-11-12 08-09-24](https://user-images.githubusercontent.com/29278800/68649974-35ee6980-0524-11ea-96ca-dbfdf0c43271.png)

[2]
![Screenshot from 2019-11-12 08-09-56](https://user-images.githubusercontent.com/29278800/68650073-6504db00-0524-11ea-8a65-318ef08c0b32.png)

**Comment by vitaliy-guliy** [comment] 2019-11-14 16:02
Everything's merged. Must work now.

**Closed as completed by vitaliy-guliy** 2019-11-14 16:02 UTC
Labels: kind/bug, severity/P1, area/editor/theia

**Comment by ibuziuk** [comment] 2019-11-14 17:27
@vitaliy-guliy was it cherry-picked to 7.3.x?

**Comment by ibuziuk** [comment] 2019-11-19 08:19
verified on on prod-preview running against 7.3.2 and the functionality works just fine \o/
