### ISSUE TITLE
Failed to start Kubernetes runtime of workspace. Cause: Waiting for Ingress Timeout

### ISSUE THREAD

**Issue by EriksonMurrugarra** [eclipse-che/che#8967] opened 2018-02-28 22:24 UTC
### Description
Hello.
I am following the instruction of the official documentation to get Eclipse Che deployed on my Kubernetes cluster. The YAML file I am using could be found in the following GitHub [repository](https://github.com/EriksonMurrugarra/kubernetes-che): 

As I am installing it on my local one-node kubernetes cluste**r I am not generating any Ingres**s. I don't know if this might be the issue. Changes in the original yaml file are:

**Persistent Volume - Local**
```
- apiVersion: v1                
  kind: PersistentVolume        
  metadata:                     
    name: che-volume            
  spec:                         
    storageClassName: manual    
    capacity:                   
      storage: 3Gi              
    accessModes:                
      - ReadWriteOnce           
    hostPath:                   
      path: "/apps/opt/che-vol" 
```

**Service - NodePort**
```
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: che
    name: che-host
  spec:
    type: NodePort
    ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30123
    selector:
      app: che
```

**Config Map pointing to my EC2 IP Address**
```
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: che
    name: che
  data:
    CHE_HOST: "MY_IP"
    CHE_PORT: "8080"
    CHE_API: "http://MY_IP/api"
    CHE_WEBSOCKET_ENDPOINT:  ws://MY_IP/api/websocket
    CHE_DEBUG_SERVER: "true"
    CHE_INFRASTRUCTURE_ACTIVE: kubernetes
    CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL: http://MY_IP/agent-binaries/linux_amd64/bootstrapper/bootstrapper
    CHE_INFRA_KUBERNETES_MACHINE__START__TIMEOUT__MIN: "5"
    CHE_INFRA_KUBERNETES_MASTER__URL: ""
    CHE_INFRA_KUBERNETES_OAUTH__TOKEN: ""
    CHE_INFRA_KUBERNETES_PASSWORD: ""
    CHE_INFRA_KUBERNETES_USERNAME: ""
    CHE_INFRA_KUBERNETES_NAMESPACE: "che"
```

**Ingress - Commented**

```
# - apiVersion: extensions/v1beta1
#   kind: Ingress
#   metadata:
#     name: che-ingress
#     annotations:
#       nginx.ingress.kubernetes.io/rewrite-target: /
#       nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
#       nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
#   spec:
#     rules:
#     - host: eclipse
#       http:
#         paths:
#         - backend:
#             serviceName: che-host
#             servicePort: 8080
```

**The main issue I am facing out is that everytime that I want to create a new Workspace it is not being created and the following message could be read in the eclipse/che log:**

`2018-02-28 22:02:06,574[aceSharedPool-1]  [WARN ] [.i.k.KubernetesInternalRuntime 140]  - **Failed to start Kubernetes runtime of workspace** workspaceksnejtn8xwrzvrzz. Cause: **Waiting for ingress** 'ingresstat78kuy' reached timeout`

It seems that the eclipse server is not being able to create a valid pod for the workspace.

### Reproduction Steps
I ran the following commands:

`kubectl create namespace che`
`kubectl apply -f che-kubernetes.yml --namespace=che`

**OS and version:**    
I am using a RedHat EC2 instance on AWS

**Diagnostics:** 
Logs provided below:
`Using embedded assembly...
Listening for transport dt_socket at address: 8000
2018-02-28 21:54:22,695[main]             [INFO ] [o.a.c.s.VersionLoggerListener 89]    - Server version:        Apache Tomcat/8.5.23
2018-02-28 21:54:22,698[main]             [INFO ] [o.a.c.s.VersionLoggerListener 91]    - Server built:          Sep 28 2017 10:30:11 UTC
2018-02-28 21:54:22,700[main]             [INFO ] [o.a.c.s.VersionLoggerListener 93]    - Server number:         8.5.23.0
2018-02-28 21:54:22,701[main]             [INFO ] [o.a.c.s.VersionLoggerListener 95]    - OS Name:               Linux
2018-02-28 21:54:22,704[main]             [INFO ] [o.a.c.s.VersionLoggerListener 97]    - OS Version:            3.10.0-693.11.6.el7.x86_64
2018-02-28 21:54:22,704[main]             [INFO ] [o.a.c.s.VersionLoggerListener 99]    - Architecture:          amd64
2018-02-28 21:54:22,707[main]             [INFO ] [o.a.c.s.VersionLoggerListener 101]   - Java Home:             /usr/lib/jvm/java-1.8-openjdk/jre
2018-02-28 21:54:22,708[main]             [INFO ] [o.a.c.s.VersionLoggerListener 103]   - JVM Version:           1.8.0_131-b11
2018-02-28 21:54:22,709[main]             [INFO ] [o.a.c.s.VersionLoggerListener 105]   - JVM Vendor:            Oracle Corporation
2018-02-28 21:54:22,710[main]             [INFO ] [o.a.c.s.VersionLoggerListener 107]   - CATALINA_BASE:         /home/user/eclipse-che/tomcat
2018-02-28 21:54:22,710[main]             [INFO ] [o.a.c.s.VersionLoggerListener 109]   - CATALINA_HOME:         /home/user/eclipse-che/tomcat
2018-02-28 21:54:22,712[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.config.file=/home/user/eclipse-che//tomcat/conf/logging.properties
2018-02-28 21:54:22,713[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
2018-02-28 21:54:22,713[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:MaxRAMFraction=2
2018-02-28 21:54:22,714[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+UseParallelGC
2018-02-28 21:54:22,714[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:MinHeapFreeRatio=10
2018-02-28 21:54:22,715[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:MaxHeapFreeRatio=20
2018-02-28 21:54:22,715[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:GCTimeRatio=4
2018-02-28 21:54:22,715[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:AdaptiveSizePolicyWeight=90
2018-02-28 21:54:22,716[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+UnlockExperimentalVMOptions
2018-02-28 21:54:22,716[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -XX:+UseCGroupMemoryLimitForHeap
2018-02-28 21:54:22,716[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dsun.zip.disableMemoryMapping=true
2018-02-28 21:54:22,717[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Xms20m
2018-02-28 21:54:22,717[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.docker.network=bridge
2018-02-28 21:54:22,718[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dport.http=8080
2018-02-28 21:54:22,718[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.home=/home/user/eclipse-che/
2018-02-28 21:54:22,718[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.dir=/data/logs
2018-02-28 21:54:22,719[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.logs.level=INFO
2018-02-28 21:54:22,719[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djuli-logback.configurationFile=file:/home/user/eclipse-che//tomcat/conf/tomcat-logger.xml
2018-02-28 21:54:22,719[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
2018-02-28 21:54:22,720[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
2018-02-28 21:54:22,720[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
2018-02-28 21:54:22,721[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote
2018-02-28 21:54:22,721[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.ssl=false
2018-02-28 21:54:22,722[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
2018-02-28 21:54:22,722[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dche.local.conf.dir=/etc/conf
2018-02-28 21:54:22,722[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.base=/home/user/eclipse-che//tomcat
2018-02-28 21:54:22,723[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/eclipse-che//tomcat
2018-02-28 21:54:22,723[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/eclipse-che//tomcat/temp
2018-02-28 21:54:22,849[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 573]  - Initializing ProtocolHandler ["http-nio-8080"]
2018-02-28 21:54:22,870[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 67]   - Using a shared selector for servlet write/read
2018-02-28 21:54:22,875[main]             [INFO ] [o.a.catalina.startup.Catalina 632]   - Initialization processed in 881 ms
2018-02-28 21:54:22,907[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 336]  - The JMX Remote Listener has configured the registry on port [32001] and the server on port [32101] for the [Platform] server
2018-02-28 21:54:22,907[main]             [INFO ] [o.a.c.core.StandardService 416]      - Starting service [Catalina]
2018-02-28 21:54:22,908[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.5.23
2018-02-28 21:54:24,003[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/swagger.war]
2018-02-28 21:54:24,220[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/swagger.war] has finished in [214] ms
2018-02-28 21:54:24,224[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/api.war]
2018-02-28 21:54:25,662[ost-startStop-1]  [INFO ] [.e.c.c.d.JNDIDataSourceFactory 59]   - This=org.eclipse.che.core.db.h2.H2SQLJndiDataSourceFactory@75ac5374 obj=ResourceRef[className=javax.sql.DataSource,factoryClassLocation=null,factoryClassName=org.apache.naming.factory.ResourceFactory,{type=scope,content=Shareable},{type=auth,content=Container},{type=singleton,content=true},{type=factory,content=org.eclipse.che.api.CommonJndiDataSourceFactory}] name=che Context=org.apache.naming.NamingContext@54f69a1b environment={}
2018-02-28 21:54:31,195[ost-startStop-1]  [INFO ] [o.f.c.i.d.DbSupportFactory 44]       - Database: jdbc:h2:che (H2 1.4)
2018-02-28 21:54:31,311[ost-startStop-1]  [INFO ] [o.f.c.i.util.VersionPrinter 44]      - Flyway 4.2.0 by Boxfuse
2018-02-28 21:54:31,314[ost-startStop-1]  [INFO ] [o.f.c.i.d.DbSupportFactory 44]       - Database: jdbc:h2:che (H2 1.4)
2018-02-28 21:54:31,396[ost-startStop-1]  [INFO ] [i.f.CustomSqlMigrationResolver 157]  - Searching for sql scripts in locations [classpath:che-schema]
2018-02-28 21:54:31,548[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbValidate 44]       - Successfully validated 27 migrations (execution time 00:00.140s)
2018-02-28 21:54:31,587[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Current version of schema "PUBLIC": 6.0.0.12
2018-02-28 21:54:31,591[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Schema "PUBLIC" is up to date. No migration necessary.
2018-02-28 21:54:34,388[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.terminal:1.0.0' is already in the registry.
2018-02-28 21:54:34,398[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.git-credentials:1.0.0' is already in the registry.
2018-02-28 21:54:34,409[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.ws-agent:1.0.1' is already in the registry.
2018-02-28 21:54:34,415[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.terminal:1.0.1' is already in the registry.
2018-02-28 21:54:34,419[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.ls.js-ts:1.0.1' is already in the registry.
2018-02-28 21:54:34,424[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.ws-agent:1.0.0' is already in the registry.
2018-02-28 21:54:34,427[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.ls.php:2.0.1' is already in the registry.
2018-02-28 21:54:34,432[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.ssh:1.0.0' is already in the registry.
2018-02-28 21:54:34,438[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.exec:1.0.0' is already in the registry.
2018-02-28 21:54:34,445[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.exec:1.0.1' is already in the registry.
2018-02-28 21:54:34,448[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.ls.python:1.0.3' is already in the registry.
2018-02-28 21:54:34,457[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.ws-agent:1.0.2' is already in the registry.
2018-02-28 21:54:34,469[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.unison:1.0.0' is already in the registry.
2018-02-28 21:54:34,472[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.ls.json:1.0.1' is already in the registry.
2018-02-28 21:54:34,480[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.ls.yaml:1.0.0' is already in the registry.
2018-02-28 21:54:34,488[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.ws-agent:1.0.3' is already in the registry.
2018-02-28 21:54:34,494[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.test.ls:1.0.0' is already in the registry.
2018-02-28 21:54:34,504[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.ls.csharp:1.0.1' is already in the registry.
2018-02-28 21:54:34,516[ost-startStop-1]  [INFO ] [a.i.s.i.LocalInstallerRegistry 70]   - Latest version of installer 'org.eclipse.che.ls.camel:1.0.0' is already in the registry.
2018-02-28 21:54:35,009[ost-startStop-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 113]   - Configured factories for environments: '[kubernetes, dockerimage]'
2018-02-28 21:54:35,011[ost-startStop-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 114]   - Registered infrastructure 'kubernetes'
2018-02-28 21:54:35,016[ost-startStop-1]  [WARN ] [o.e.c.a.w.s.WorkspaceRuntimes 427]   - Not recoverable infrastructure: 'kubernetes'
2018-02-28 21:54:35,522[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/api.war] has finished in [11,298] ms
2018-02-28 21:54:35,539[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/ROOT.war]
2018-02-28 21:54:37,422[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/ROOT.war] has finished in [1,883] ms
2018-02-28 21:54:37,424[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/docs.war]
2018-02-28 21:54:37,806[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/docs.war] has finished in [382] ms
2018-02-28 21:54:37,807[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/dashboard.war]
2018-02-28 21:54:38,170[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/dashboard.war] has finished in [363] ms 2018-02-28 21:54:38,178[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 632]  - Starting ProtocolHandler ["http-nio-8080"]
2018-02-28 21:54:38,198[main]             [INFO ] [o.a.catalina.startup.Catalina 683]   - Server startup in 15322 ms
2018-02-28 21:55:05,965[io-8080-exec-10]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 461]    - Workspace 'che/vestmmv' with id 'workspaceeszgxumvnnuh7nxg' created by user 'che'
2018-02-28 21:55:22,322[nio-8080-exec-3]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 228]   - Starting workspace 'che/vestmmv' with id 'workspaceeszgxumvnnuh7nxg' by user 'che'
2018-02-28 21:56:53,072[nio-8080-exec-9]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 461]    - Workspace 'che/wksp-658a' with id 'workspaceksnejtn8xwrzvrzz' created by user 'che'
2018-02-28 21:57:06,388[nio-8080-exec-6]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 228]   - Starting workspace 'che/wksp-658a' with id 'workspaceksnejtn8xwrzvrzz' by user 'che'
2018-02-28 22:00:22,798[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 140]  - Failed to start Kubernetes runtime of workspace workspaceeszgxumvnnuh7nxg. Cause: Waiting for ingress 'ingress6dajahep' reached timeout
2018-02-28 22:00:23,198[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 284]   - Workspace 'che:vestmmv' with id 'workspaceeszgxumvnnuh7nxg' start failed
2018-02-28 22:02:06,574[aceSharedPool-1]  [WARN ] [.i.k.KubernetesInternalRuntime 140]  - Failed to start Kubernetes runtime of workspace workspaceksnejtn8xwrzvrzz. Cause: Waiting for ingress 'ingresstat78kuy' reached timeout
2018-02-28 22:02:06,649[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 284]   - Workspace 'che:wksp-658a' with id 'workspaceksnejtn8xwrzvrzz' start failed`

Thank you!

**Comment by garagatyi** [comment] 2018-03-01 07:49
Is ingress controller running in your cluster? Ingress is the only implemented way of port exposure in k8s infrastructure right now. Without running ingress controller workspaces won't start. And out of the box, it should be nginx ingress controller. You can tweak the configuration to other implementation of ingress controller.

**Comment by EriksonMurrugarra** [comment] 2018-03-01 19:21
Hi, @garagatyi  Thank you for your response.

I did create a Nginx Ingress controller and I don't have the same 'Waiting for Ingress Timeout' error. But now I am facing out another error which says:

**Could not start workspace MYWORKSPACE. Reason: Waiting for pod 'workspace6ld0hpqkvq3k1t9e.dockerimage' reached timeout**

do you t think is it related to the Ingress or other stuff?


Thank you.

**Comment by garagatyi** [comment] 2018-03-03 09:22
@sleshchenko can you help with this issue. It seems that it is area contributed by you.

**Comment by sleshchenko** [comment] 2018-03-03 09:28
@EriksonMurrugarra Can you check `workspace6ld0hpqkvq3k1t9e.dockerimage` pod events on Kubernetes dashboard? It should be created in `workspace6ld0hpqkvq3k1t9e` namespace. The possible issue here is `Insufficient memory.` error. But events should show the real issue why pod is not running in time.

**Comment by czeumer** [comment] 2018-03-06 13:20
I had the same issue on AWS with ELB. The ELB does not set the IP address but "only" the  hostname. The current implementation only checks for the IP.
We have a branch that works for our setup (AWS / ELB / Cert Manger with ACME TLS)
https://github.com/autonubil/che/blob/k8s-alb/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerResolver.java#L100

**Comment by garagatyi** [comment] 2018-03-06 15:20
@sleshchenko @skabashnyuk should we change the type of the issue to bug?

**Comment by sleshchenko** [comment] 2018-03-06 15:30
@garagatyi I guess @EriksonMurrugarra now fixed his issue with ingress controller and now his issue is ```Could not start workspace MYWORKSPACE. Reason: Waiting for pod 'workspace6ld0hpqkvq3k1t9e.dockerimage' reached timeout```

Maybe it'd better create another enhancement issue to support ingress controllers that don't set IP but set hostname (AWS / ELB / Cert Manger with ACME TLS)

**Comment by eivantsov** [comment] 2018-03-26 08:36
@EriksonMurrugarra any update? The pod never started. Can you grab any relevant info from k8s events?

**Comment by EriksonMurrugarra** [comment] 2018-03-26 13:51
Hi, Thank you for the follow-up.
Yes I was able to start the pod but now I am facing another issue that after some minutes it kills the pod:

![issue](https://user-images.githubusercontent.com/21296976/37910311-d2048df4-30d2-11e8-8bbe-38ad4c17c034.png)
![popissue](https://user-images.githubusercontent.com/21296976/37910314-d4fc8318-30d2-11e8-83e7-fb626070d967.png)

**Comment by eivantsov** [comment] 2018-03-26 13:59
@EriksonMurrugarra can you reliably reproduce it? Probably client got some outdated event.

**Comment by EriksonMurrugarra** [comment] 2018-03-26 14:06
I happens every time I start a new Workspace. Maybe this is happening because of the IP address that the client is trying to establish a connection (127.0.0.1). My Server is running on another IP (10.118.130.34). 
![image](https://user-images.githubusercontent.com/21296976/37911174-f139e500-30d4-11e8-8b53-8ea835a9b758.png)

**Comment by eivantsov** [comment] 2018-03-26 14:47
@EriksonMurrugarra it should definitely be your k8s node IP.

How did you deploy Che? I don't understand where localhost IP comes from.

**Comment by EriksonMurrugarra** [comment] 2018-03-26 14:56
Hi @eivantsov,
Please find the configuration files in the following GitHub repo [https://github.com/EriksonMurrugarra/eclipse-kube](https://github.com/EriksonMurrugarra/eclipse-kube)

**Comment by eivantsov** [comment] 2018-03-26 15:00
It is not exactly as per https://github.com/eclipse/che/blob/master/deploy/kubernetes/kubectl/Deploy%20Che.md

**Comment by eivantsov** [comment] 2018-04-24 08:26
Closing due to inactivity. @EriksonMurrugarra feel free to reopen if deploy to k8s still fails for you

**Closed as completed by eivantsov** 2018-04-24 08:26 UTC
Labels: kind/question
