### ISSUE TITLE
Plugins do not work in the latest Che-Theia build (che-theia:next)

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#16021] opened 2020-02-13 10:32 UTC
### Describe the bug

It looks the latest Theia has changes that broke the plugins system.
In fact, Che-Theia tries to unpack the plugins. After unpacking, plugins are deployed but not started.
Running Che-Theia has `My Workspace` view, which is provided by plugin contribution point.

### Che version

 - [x] nightly

### Steps to reproduce
Create a workspace with next version of Che-Theia editor. 

### Expected behavior

Che-Theia with working plugins.

### Screenshots

![Screenshot from 2020-02-13 12-28-24](https://user-images.githubusercontent.com/1655894/74425696-c65a8400-4e5c-11ea-81a8-03ea91a0f381.png)

![Screenshot from 2020-02-13 12-26-48](https://user-images.githubusercontent.com/1655894/74425720-cfe3ec00-4e5c-11ea-9c94-a363634451c9.png)

![Screenshot from 2020-02-13 12-27-10](https://user-images.githubusercontent.com/1655894/74425757-e12cf880-4e5c-11ea-97b5-c6db6670b37a.png)

**Comment by RomanNikitenko** [comment] 2020-02-13 10:45
I tried locally on `minikube` to use che-theia:next and it works for me, I can not reproduce the issue

![еее](https://user-images.githubusercontent.com/5676062/74426823-bba0ee80-4e5e-11ea-913a-3b37ef462374.png)

**Comment by azatsarynnyy** [comment] 2020-02-13 11:03
It's expected behavior as `eclipse/che-theia/next` is not always compatible with the other components versions, which are 7.8.0 on https://che.openshift.io ATM

There were several PRs for different components of Che:
- Che Server https://github.com/eclipse/che/pull/15432
- Che Theia https://github.com/eclipse/che-theia/pull/591
- Che Plugin Registry https://github.com/eclipse/che-plugin-registry/pull/335

All of them were merged after 7.8.0.
`eclipse/che-theia/next` includes the changes which depend on the changes that aren't in 7.8.0 of other components. 

closing it as expected behavior

**Closed as completed by azatsarynnyy** 2020-02-13 11:03 UTC
Labels: kind/bug, severity/blocker
