### ISSUE TITLE
Error highlighting broken in several default stack

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#15919] opened 2020-02-04 11:23 UTC
### Describe the bug
Error highlighting feature is not working in several default stacks in 7.8.0.
Affected stacks:
- [x] NodeJS Express Web Application
- [x] NodeJS MongoDB Web Application
- [x] PHP Symfony
- [x] PHP with MySQL
- [x] PHP Laravel with MySQL
- [x] Rust
EDIT: added .net core stack
- [x] .NET Core

### Che version

 - [x] other:  7.8.0 on che.prod-preview.openshift.io

### Steps to reproduce

1. Go to Workspaces -> Add Workspace
2. Select one of the stacks from the description of the issue
3. Open the file and write some erroneous text to it
4. Erroneous words are not highlighted

### Expected behavior

Erroneous code should be highlighted by a red underline.

### Runtime
   - [x] other: (please specify) che.prod-preview.openshift.io

### Environment
   - [x] other: please specify che.prod-preview.openshift.io

**Comment by l0rd** [comment] 2020-02-04 23:57
@Katka92 can you provide some logs (c.f. the [doc to retrieve language servers logs](https://www.eclipse.org/che/docs/che-7/viewing-che-workspaces-logs/#viewing-logs-from-language-servers-and-debug-adapters))?

**Comment by tsmaeder** [comment] 2020-02-05 10:16
@Katka92 are the plugins starting at all? Do you get content assist, for example? I know that the node support writes progress messages to the status bar when starting up.

**Comment by tsmaeder** [comment] 2020-02-17 09:35
Everything works just fine on local crc. I suspect this is some limitation on prod-preview.

**Comment by Katka92** [comment] 2020-02-17 09:58
Hi, thank you for your answers. In some devfiles just error highlighting was not working as expected, in other devfiles also other features. Now there is a new issue for 4 days with Java Maven stack that LS seems to not work at all. https://github.com/eclipse/che/issues/16051

**Comment by Katka92** [comment] 2020-03-02 11:09
On 7.9.0 Hosted che on prod-preview error highlighting is not working for a Rust devfile, but code suggestion and completion seems to be working correctly.

**Comment by Katka92** [comment] 2020-04-27 14:33
The issue is still present for 7.12.0 tested on Hosted Che.

**Comment by ibuziuk** [comment] 2020-05-08 14:19
@ericwill could you please take a look?

**Comment by ericwill** [comment] 2020-05-08 14:33
Yes we've planned it for next sprint (184).

**Comment by ericwill** [comment] 2020-05-25 19:54
I tried today on che.openshift.io and it turns out the PHP stacks (Symfony, MySQL, and Laravel) work fine. Rust and NodeJS are still broken.

**Comment by ericwill** [comment] 2020-05-29 20:30
NodeJS with React is also broken.

**Comment by tsmaeder** [comment] 2020-06-26 12:04
Checking: 

- [x] NodeJS Express Web Application
- [x] NodeJS MongoDB Web Application
- [x] PHP Symfony
- [x] PHP with MySQL
- [x] PHP Laravel with MySQL
- [x] Rust

**Comment by tsmaeder** [comment] 2020-06-26 12:54
There seems to be an element of randomness to this: I have observed the node/mongodb workspace start the language server successfully, but most of the time, it fails.

**Comment by tsmaeder** [comment] 2020-06-26 12:57
When the LS startup failed, I was this stack trace in the typescript container log:
```
PLUGIN_HOST(1): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/che-incubator.typescript.latest.zkalzvuwgu.che-typescript-language-1.35.1.vsix/extension/out/extension)
Remote plugin in vscode-typescript5dp: promise rejection is not handled in two seconds: TypeError: vscode.workspace.onDidRenameFile is not a function
Remote plugin in vscode-typescript5dp: promise rejection stack trace: TypeError: vscode.workspace.onDidRenameFile is not a function
    at new UpdateImportsOnFileRenameHandler (/tmp/vscode-unpacked/che-incubator.typescript.latest.zkalzvuwgu.che-typescript-language-1.35.1.vsix/extension/out/features/updatePathsOnRename.js:42:41)
    at ConditionalRegistration.dependentRegistration_1.VersionDependentRegistration [as _doRegister] (/tmp/vscode-unpacked/che-incubator.typescript.latest.zkalzvuwgu.che-typescript-language-1.35.1.vsix/extension/out/features/updatePathsOnRename.js:181:128)
    at ConditionalRegistration.update (/tmp/vscode-unpacked/che-incubator.typescript.latest.zkalzvuwgu.che-typescript-language-1.35.1.vsix/extension/out/utils/dependentRegistration.js:23:42)
    at VersionDependentRegistration.update (/tmp/vscode-unpacked/che-incubator.typescript.latest.zkalzvuwgu.che-typescript-language-1.35.1.vsix/extension/out/utils/dependentRegistration.js:51:28)
    at new VersionDependentRegistration (/tmp/vscode-unpacked/che-incubator.typescript.latest.zkalzvuwgu.che-typescript-language-1.35.1.vsix/extension/out/utils/dependentRegistration.js:41:14)
    at Object.register (/tmp/vscode-unpacked/che-incubator.typescript.latest.zkalzvuwgu.che-typescript-language-1.35.1.vsix/extension/out/features/updatePathsOnRename.js:181:12)
    at TypeScriptServiceClientHost.Promise.resolve.then.then.module (/tmp/vscode-unpacked/che-incubator.typescript.latest.zkalzvuwgu.che-typescript-language-1.35.1.vsix/extension/out/typeScriptServiceClientHost.js:67:118)
```

**Comment by tsmaeder** [comment] 2020-06-26 12:58
Note the line 

```
Remote plugin in vscode-typescript5dp: promise rejection stack trace: TypeError: vscode.workspace.onDidRenameFile is not a function
```

Normally, this would indicate that the API `onDidRenameFile` is not implemented, but it is. In addition, if it wasn't implemented, startup would have to fail each time. How bizarre!

**Comment by tsmaeder** [comment] 2020-06-29 08:59
I am having trouble reproducing these failures. @Katka92 how about you? If you observe such failures, it is essential that we get the logs from the sidecar container providing the language support.

**Comment by Katka92** [comment] 2020-06-29 11:02
@tsmaeder Hello, it's quite an old issue so I'm not sure about the state from the top of my head. I'll verify and comment here in a few days.

**Comment by tsmaeder** [comment] 2020-06-29 11:32
I was able to reproduce it once, so it seems the problem is still present, but seems to be less frequent.

**Comment by Katka92** [comment] 2020-07-02 12:20
So I've tried a few times on yesterday's deployment of Che 7.16.0-SNAPSHOT and was not able to reproduce.

**Comment by Katka92** [comment] 2020-07-08 07:22
I didn't reproduce that during pre-release testing on Hosted Che 7.15.1.

**Comment by ScrewTSW** [comment] 2020-07-08 11:36
Reproduced the issue again with .NET Core stack, LS is not initialize quite often.
https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/dotnet

**Comment by tsmaeder** [comment] 2020-07-09 07:19
@ScrewTSW do you have a case that reliably reproduces the problem? Where did you reproduce it and are you doing anything special? Also, could you provide logs from the relevant containers, please?

**Comment by tsmaeder** [comment] 2020-07-09 09:10
Also: how are determining the failure? .Net needs to "restore dependencies" to work.

**Comment by tsmaeder** [comment] 2020-07-09 11:42
FWIW: can't reproduce as of this morning in openshift.io.

**Comment by ScrewTSW** [comment] 2020-07-09 11:59
> 
> 
> @ScrewTSW do you have a case that reliably reproduces the problem? Where did you reproduce it and are you doing anything special? Also, could you provide logs from the relevant containers, please?

Hello. I was able to reproduce it using .NET Core stack on prod-preview.openshift.io, account on 2a cluster, out of 5 runs it happened 4 times

**Comment by ScrewTSW** [comment] 2020-07-09 12:00
> 
> 
> Also: how are determining the failure? .Net needs to "restore dependencies" to work.

No error highlighting, suggestions, codenavigation didn't work at all

**Comment by tsmaeder** [comment] 2020-07-09 12:08
@could you grab the container logs from at least one failing run?

**Comment by Katka92** [comment] 2020-07-13 05:48
We spent some time trying to investigate the problem. At the end, we could not reproduce the issue. Closing for now.

**Comment by tsmaeder** [comment] 2020-07-16 07:59
I was able to reproduce the stack trace I found above

root ERROR [hosted-plugin: 20812] Promise rejection not handled in one second: TypeError: s.workspace.onDidRenameFile is not a function , reason: TypeError: s.workspace.onDidRenameFile is not a function
root ERROR [hosted-plugin: 20812] With stack trace: TypeError: s.workspace.onDidRenameFile is not a function
    at new m (C:\Users\thomas\code\chedev\theia\plugins\vscode-builtin-typescript-language-features\extension\dist\extension.js:53:67536)
    at s.u.VersionDependentRegistration [as _doRegister] (C:\Users\thomas\code\chedev\theia\plugins\vscode-builtin-typescript-language-features\extension\dist\extension.js:53:69739)
    at s.update (C:\Users\thomas\code\chedev\theia\plugins\vscode-builtin-typescript-language-features\extension\dist\extension.js:1:12010)
    at t.VersionDependentRegistration.update (C:\Users\thomas\code\chedev\theia\plugins\vscode-builtin-typescript-language-features\extension\dist\extension.js:1:12479)
    at new t.VersionDependentRegistration (C:\Users\thomas\code\chedev\theia\plugins\vscode-builtin-typescript-language-features\extension\dist\extension.js:1:12278)
    at Object.t.register (C:\Users\thomas\code\chedev\theia\plugins\vscode-builtin-typescript-language-features\extension\dist\extension.js:53:69685)
    at Promise.resolve.then.then.e (C:\Users\thomas\code\chedev\theia\plugins\vscode-builtin-typescript-language-features\extension\dist\extension.js:1:97526)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Katka92** [comment] 2020-07-16 08:19
@tsmaeder Hi, thank you for investigating and sharing the knowledge! Feel free to reopen the issue if you want. If you need any help, please ping us.

**Comment by tsmaeder** [comment] 2020-08-10 11:41
A new instance of the stack trace I reported has been spotted in the wild:

> hi all, before i post a bug report, i wanted to make sure i do it right and in the correct place.
>
>The TS/JS tooling keeps crashing in the latest Che (7.16.2) for us.  Stack from the container below:  Is this a bug with the plugin, che, or what?  and where should I report, or is it known?
>
>Remote plugin in vscode-typescript4xq: promise rejection is not handled in two seconds: TypeError: vscode.workspace.onDidRenameFile is not a function
>Remote plugin in vscode-typescript4xq: promise rejection stack trace: TypeError: vscode.workspace.onDidRenameFile is not a function
>    at new UpdateImportsOnFileRenameHandler (/tmp/vscode-unpacked/che-incubator.typescript.1.30.2.aaxqtsdhym.che-typescript-language.vsix/extension/out/features/updatePathsOnRename.js:31:49)
>    at ConditionalRegistration.dependentRegistration_1.VersionDependentRegistration [as _doRegister] (/tmp/vscode-unpacked/che-incubator.typescript.1.30.2.aaxqtsdhym.che-typescript-language.vsix/extension/out/features/updatePathsOnRename.js:241:103)
>    at ConditionalRegistration.update (/tmp/vscode-unpacked/che-incubator.typescript.1.30.2.aaxqtsdhym.che-typescript-language.vsix/extension/out/utils/dependentRegistration.js:23:42)
 >   at VersionDependentRegistration.update (/tmp/vscode-unpacked/che-incubator.typescript.1.30.2.aaxqtsdhym.che-typescript-language.vsix/extension/out/utils/dependentRegistration.js:51:28)
 >   at new VersionDependentRegistration (/tmp/vscode-unpacked/che-incubator.typescript.1.30.2.aaxqtsdhym.che-typescript-language.vsix/extension/out/utils/dependentRegistration.js:41:14)
 >   at Object.register (/tmp/vscode-unpacked/che-incubator.typescript.1.30.2.aaxqtsdhym.che-typescript-language.vsix/extension/out/features/updatePathsOnRename.js:241:12)
 >   at TypeScriptServiceClientHost.Promise.resolve.then.then.module (/tmp/vscode-unpacked/che-incubator.typescript.1.30.2.aaxqtsdhym.che-typescript-language.vsix/extension/out/typeScriptServiceClientHost.js:67:118)
 >   at process._tickCallback (internal/process/next_tick.js:68:7)
>Remote plugin in vscode-typescript4xq: promise rejection is not handled in two seconds: undefined>
>Remote plugin in vscode-typescript4xq: promise rejection is not handled in two seconds: TypeError: Cannot read property 'stack' of undefined
>Remote plugin in vscode-typescript4xq: promise rejection stack trace: TypeError: Cannot read property 'stack' of undefined
    at /remote-endpoint/node_modules/@eclipse-che/theia-remote/lib/node/plugin-remote.js:36:25

>19:29


>ignore the 1.30.2 version, i switched from latest to test if 1.35 was the issue.  It seemed like it was working, but eventually came back

**Comment by tsmaeder** [comment] 2020-08-10 11:47
My suspicion is that initialization of the plugin host (aka overriding the module load) and plugin activation are happening at the same time. We could test this theory by putting a breakpoint in the plugin host to simulate delay.

**Comment by tsmaeder** [comment] 2020-08-25 11:53
> root ERROR [hosted-plugin: 20812] With stack trace: TypeError: s.workspace.onDidRenameFile is not a function

Note that this is looking for "onDidRenameFile", not "onDidRenameFile**s**". The "s" was added when the api graduated from vscode-proposed.ts to vscode.ts. 
So in fact, we're looking at a version issue here: for newer version of Theia (about 4 months ago), we need a newer version of the typescript extension

**Comment by ericwill** [comment] 2021-03-17 19:49
This has been fixed now that we've updated the typescript extension, no?

**Comment by l0rd** [comment] 2021-09-20 15:24
@svor it's not clear from the description what's missing here

**Comment by svor** [comment] 2021-09-21 11:33
@l0rd The typescript extension was updated and seems we don't have `vscode.workspace.onDidRenameFile is not a function` related problem any more. 

![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2021 09 21-14_32_38](https://user-images.githubusercontent.com/1271546/134163357-967f0da6-dfd9-48d5-897c-d1ed1e1d0774.png)

I'm going to close the issue.

**Closed as completed by svor** 2021-09-21 11:33 UTC
Labels: kind/bug, severity/P1, area/plugins, area/samples
