### ISSUE TITLE
Autocomplete feature does not work in java editor

### ISSUE THREAD

**Issue by djimenezgarcia** [eclipse-che/che#11760] opened 2018-10-26 17:38 UTC
### Working on a java  project the autocomplete feature does not work in version 6.13.0
After eclipse-che upgrade from 6.12.0 to 6.13.0 autocomplete (ctrl-space) feature seems to stop working. 

### Reproduction Steps
Just open a java class or inteface,  try typing crtl+space to autocomplete some class or interface name, or a java language token like "try". Editor does nothing.

**OS and version:**   docker 17.06.2-ce with eclipse-che 6.13.0 (same bug detected in rc)

**Diagnostics:** 
This error log appears in "dev-machine" tab when entering workspace:

_**2018-10-26 17:17:19,270[estProcessor-40]  [ERROR] [oggingUncaughtExceptionHandler 32]   - Runtime exception caught in thread ServerSideRequestProcessor-40. Message: null
java.lang.NullPointerException: null at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.detectTest(JavaLanguageServerExtensionService.java:405) at org.eclipse.che.plugin.java.testing.AbstractJavaTestRunner.detectTests(AbstractJavaTestRunner.java:52) at org.eclipse.che.api.testing.server.TestingRPCService.handleTestDetection(TestingRPCService.java:102) at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.handle(RequestHandlerManager.java:351) at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:52) at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:98) at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:73) at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:224) at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.access$1000(RequestHandlerManager.java:335) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)**_

**Comment by eivantsov** [comment] 2018-10-30 07:00
@djimenezgarcia does it happen to a particular project? If so, can you share it?

**Comment by djimenezgarcia** [comment] 2018-10-30 09:09
It happens in every java project in my workspace. All of my projects use **Maven**.  Workspace type is  named **dev-machine** with image **eclipse/ubuntu_jdk8** with RAM 3GB.

I can share one of my java project but I think it won´t be useful.

One particular thing I have notice is that workspace actions take time to execute. For example, when I execute a "maven package" command, it takes 10 seconds to start. Final execution is OK, project is compiled and packaged, and jar file is generated but errors arise in "dev-,achine" tab:

_**2018-10-30 09:05:44,861[estProcessor-24]  [ERROR] [oggingUncaughtExceptionHandler 32]   - Runtime exception caught in thread ServerSideRequestProcessor-24. Message: null
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.getClasspathTree(JavaLanguageServerExtensionService.java:703)
java.lang.NullPointerException: null
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToManyHandler.access$1100(RequestHandlerManager.java:374)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToManyHandler.handle(RequestHandlerManager.java:389)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:52)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:227)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:73)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:98)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.che.api.core.jsonrpc.commons.reception.FunctionConfiguratorOneToMany.lambda$withFunction$0(FunctionConfiguratorOneToMany.java:77)
2018-10-30 09:05:54,862[estProcessor-25]  [ERROR] [oggingUncaughtExceptionHandler 32]   - Runtime exception caught in thread ServerSideRequestProcessor-25. Message: null
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.getClasspathTree(JavaLanguageServerExtensionService.java:703)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToManyHandler.handle(RequestHandlerManager.java:389)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToManyHandler.access$1100(RequestHandlerManager.java:374)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:227)
	at org.eclipse.che.api.core.jsonrpc.commons.reception.FunctionConfiguratorOneToMany.lambda$withFunction$0(FunctionConfiguratorOneToMany.java:77)
java.lang.NullPointerException: null
	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.processRequest(JsonRpcMessageReceiver.java:98)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver.lambda$receive$0(JsonRpcMessageReceiver.java:73)**_

**Comment by dickerpulli** [comment] 2018-10-30 09:19
@djimenezgarcia Why do you closed this issue? Have you found a solution?

**Comment by Ohrimenko1988** [comment] 2018-10-30 10:14
Sorry, I can't reproduce this bug. Can you provide your's steps to reproduce?
Please review my screencast:
![rrrr](https://user-images.githubusercontent.com/22724619/47711139-2b28a580-dc3d-11e8-9e6b-9f9cf10f2bb6.gif)

I have run default "java" stack with default "spring" project

**Comment by dickerpulli** [comment] 2018-10-30 10:40
I solved my issue. The problem with my workspace was that "Java language server" was not active in workspace settings "Workspace installers".

**Comment by apupier** [comment] 2018-10-30 10:44
if the "java Language Server" is not active there should not be the exception anyway

**Comment by dickerpulli** [comment] 2018-10-30 11:20
After deactivating "Java language server" the exceptions @djimenezgarcia mentioned occuring again. Maybe you can reproduce this in your workspace.

**Comment by djimenezgarcia** [comment] 2018-10-30 11:20
**dockerpulli** was alright. Issue is solved setting "Java language server" state to on. I do not remember having changed that. Maybe changed on upgrade?

**Comment by dickerpulli** [comment] 2018-10-30 11:21
I also havn't deactivated it by hand.

**Comment by apupier** [comment] 2018-10-30 11:58
have you upgraded the Che instance or created a new one?
before 6.13, there was no Java servers, Java was always activated. Since 6.13, it becomes a server, so explicit activation is required. In case of an upgrade, it means that all previous will miss Java compared to previous workspace. unless something has been done in the migration? //cc @tsmaeder

**Comment by djimenezgarcia** [comment] 2018-10-30 12:14
I upgraded from 6.12.2. So it was my fault not to know this was needed.

**Comment by skabashnyuk** [comment] 2018-12-01 15:20
Closing. Feel free to reopen this issue if you think it's still relevant for you.

**Closed as completed by skabashnyuk** 2018-12-01 15:20 UTC
Labels: kind/question

**Comment by SalimCastellanos** [comment] 2018-12-13 23:32
The some problem, i migrate from old version, and the worspace fail... i active java server and problem fixed.

**Comment by SDAdham** [comment] 2019-03-18 02:22
@SalimCastellanos : I am experiencing the same problem, can you please let me know which java server? and from where to enable the option?
