### ISSUE TITLE
Cannot deploy che-operator:7.33.0 with chectl 

### ISSUE THREAD

**Issue by dkwon17** [eclipse-che/che#20116] opened 2021-07-09 20:45 UTC
### Describe the bug

After starting `crc` and running:
```
chectl server:deploy --installer operator -p crc --che-operator-image=quay.io/eclipse/che-operator:7.33.0
```
I receive this output:
```
chectl server:deploy --installer operator -p crc --che-operator-image=quay.io/eclipse/che-operator:7.33.0
› Current Kubernetes context: 'crc-admin'
  ✔ Verify Kubernetes API...OK (it's OpenShift)
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not
  ✔ ✈️  CodeReady Containers preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if crc is installed...done.
    ✔ Verify if CodeReady Containers is running...done.
    ✔ Check OpenShift version: 4.x
    ✔ Check Kubernetes version: Unknown.
    ✔ Retrieving CodeReady Containers IP and domain for routes URLs...127.0.0.1.nip.io.
  ✔ Following Eclipse Che logs
    ✔ Start following Operator logs...done
    ✔ Start following Eclipse Che Server logs...done
    ✔ Start following PostgreSQL logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plug-in Registry logs...done
    ✔ Start following Devfile Registry logs...done
    ✔ Start following Eclipse Che Dashboard logs...done
    ✔ Start following namespace events...done
 ›   Warning: Consider using the more reliable 'OLM' installer when deploying a stable release
 ›    of Eclipse Che (--installer=olm).
  ❯ 🏃‍  Running the Eclipse Che operator
    ✔ Create Namespace (eclipse-che)...It already exists.
    ✔ Create ServiceAccount che-operator in namespace eclipse-che...done.
    ✔ Read Roles and Bindings...done.
    ✔ Creating Roles and Bindings...done.
    ✔ Create CRD checlusters.org.eclipse.che...done.
    ✔ Create backup and restore CRDs...skipped.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment che-operator in namespace eclipse-che...done.
    ❯ Operator pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✖ Starting...failed
        → Failed to start a pod, reason: Error, exitCode: 1
      Prepare Eclipse Che cluster CR
    Error: Command server:deploy failed. Error log:
    /Users/dakwon/Library/Caches/chectl/error.log.
```

Alongside this log message from the che-operator pod:
![image](https://user-images.githubusercontent.com/83611742/125132631-97d4ed00-e0d2-11eb-87b4-9b1d66e6df77.png)
```
time="2021-07-09T18:06:38Z" level=fatal msg="Failed to initialize default value: RELATED_IMAGE_internal_rest_backup_server'. Environment variable with default value was not found."
```

### Steps to reproduce
1. Run `crc start --memory=16192 --cpus=4`
2. Run `chectl server:deploy --installer operator -p crc --che-operator-image=quay.io/eclipse/che-operator:7.33.0`

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   ```
Client Version: 4.7.11
Server Version: 4.7.13
Kubernetes Version: v1.20.0+df9c838
   ```
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

### `chectl` error logs

```
2021-07-09T20:33:58.867Z Error: Command server:deploy failed. Error log: /Users/dakwon/Library/Caches/chectl/error.log.
2021-07-09T20:33:58.867Z     at newError (~/.local/share/chectl/client/7.32.2/lib/util.js:194:19)
2021-07-09T20:33:58.867Z     at Object.wrapCommandError (~/.local/share/chectl/client/7.32.2/lib/util.js:190:12)
2021-07-09T20:33:58.867Z     at Deploy.<anonymous> (~/.local/share/chectl/client/7.32.2/lib/commands/server/deploy.js:255:35)
2021-07-09T20:33:58.867Z     at Generator.throw (<anonymous>)
2021-07-09T20:33:58.867Z     at rejected (~/.local/share/chectl/client/7.32.2/node_modules/tslib/tslib.js:115:69)
2021-07-09T20:33:58.867Z     at runMicrotasks (<anonymous>)
2021-07-09T20:33:58.867Z Cause: Error: Failed to start a pod, reason: Error, exitCode: 1
2021-07-09T20:33:58.867Z     at KubeTasks.<anonymous> (~/.local/share/chectl/client/7.32.2/lib/tasks/kube.js:110:35)
2021-07-09T20:33:58.867Z     at Generator.next (<anonymous>)
2021-07-09T20:33:58.867Z     at fulfilled (~/.local/share/chectl/client/7.32.2/node_modules/tslib/tslib.js:114:62)
2021-07-09T20:33:58.867Z     at runMicrotasks (<anonymous>)
```

**Comment by flacatus** [comment] 2021-07-10 07:25
Hello @dkwon17 !
Did u update chectl? I cannot reproduce your issue in my local machine

**Comment by flacatus** [comment] 2021-07-10 08:50
```log
❯ chectl server:deploy --installer operator -p crc --che-operator-image=quay.io/eclipse/che-operator:7.33.0

› Current Kubernetes context: 'default/api-crc-testing:6443/kubeadmin'
  ✔ Verify Kubernetes API...OK (it's OpenShift)
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not
  ✔ ✈️  CodeReady Containers preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if crc is installed...done.
    ✔ Verify if CodeReady Containers is running...done.
    ✔ Check OpenShift version: 4.x
    ✔ Check Kubernetes version: Unknown.
    ✔ Retrieving CodeReady Containers IP and domain for routes URLs...192.168.130.11.nip.io.
  ✔ Following Eclipse Che logs
    ✔ Start following Operator logs...done
    ✔ Start following Eclipse Che Server logs...done
    ✔ Start following PostgreSQL logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plug-in Registry logs...done
    ✔ Start following Devfile Registry logs...done
    ✔ Start following Eclipse Che Dashboard logs...done
    ✔ Start following namespace events...done
  ✔ 🏃‍  Running the Eclipse Che operator
    ✔ Create Namespace (eclipse-che)...Done.
    ✔ Create ServiceAccount che-operator in namespace eclipse-che...done.
    ✔ Read Roles and Bindings...done.
    ✔ Creating Roles and Bindings...done.
    ✔ Create CRD checlusters.org.eclipse.che...done.
    ✔ Create backup and restore CRDs...done.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment che-operator in namespace eclipse-che...done.
    ✔ Operator pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Prepare Eclipse Che cluster CR...Done.
    ✔ Create the Custom Resource of type checlusters.org.eclipse.che in the namespace eclipse-che...done.
  ✔ ✅  Post installation checklist
    ✔ PostgreSQL pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Keycloak pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Devfile Registry pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Plug-in Registry pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Eclipse Che Dashboard pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Eclipse Che Server pod bootstrap
      ✔ Scheduling...done
      ✔ Downloading images...done
      ✔ Starting...done
    ✔ Eclipse Che status check...done
  ✔ Retrieving Keycloak admin credentials...done
  ✔ Retrieving Che self-signed CA certificate...OK
  ✔ Prepare post installation output...done
  ✔ Show important messages
    ✔ Eclipse Che 7.33.0-SNAPSHOT has been successfully deployed.
    ✔ Documentation             : https://www.eclipse.org/che/docs/
    ✔ -------------------------------------------------------------------------------
    ✔ Users Dashboard           : https://che-eclipse-che.apps-crc.testing
    ✔ -------------------------------------------------------------------------------
    ✔ Plug-in Registry          : https://plugin-registry-eclipse-che.apps-crc.testing/v3
    ✔ Devfile Registry          : https://devfile-registry-eclipse-che.apps-crc.testing
    ✔ -------------------------------------------------------------------------------
    ✔ Identity Provider URL     : https://keycloak-eclipse-che.apps-crc.testing/auth
    ✔ Identity Provider login   : "admin:lw7f6BUv6Dz5".
    ✔ -------------------------------------------------------------------------------
    ✔ [ACTION REQUIRED] Please add Che self-signed CA certificate into your browser: /tmp/cheCA.crt.
   Documentation how to add a CA certificate into a browser: https://www.eclipse.org/che/docs/che-7/end-user-guide/importing-certificates-to-browsers/
Command server:deploy has completed successfully in 09:21.

```

**Comment by dkwon17** [comment] 2021-07-11 23:03
Hello @flacatus , I updated `chectl` to the `next` channel and it is now working. Thank you!

**Comment by sleshchenko** [comment] 2021-07-12 06:34
Closing this issue assuming that there is a place for misusage when the newer/older image is used with not-compatible deployment resources.
If anyone thinks that it's still an issue - please reopen or create a new one.

**Closed as completed by sleshchenko** 2021-07-12 06:34 UTC
Labels: kind/question, area/install
