### ISSUE TITLE
OpenShift/K8S: PVC helper errors when workspaces share one PV

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#9691] opened 2018-05-14 09:05 UTC
When running Selenium tests there were lots of errors in wsmaster logs:

```
2018-05-12 09:16:57,998[er-ThreadPool-0]  [ERROR] [e.c.w.i.k.n.p.PVCSubPathHelper 146]  - Job command '%s' execution is failed.
```
These errors, however, did not affect workspaces, so everything is fine with performance.
The errors showed up when PVC strategy was changed to common, ie all workspaces used the same PV.  However, precreate subpaths env was set to false, since it's not required in 1.6+ K8S versions.

```
CHE_INFRA_KUBERNETES_PVC_STRATEGY=common
CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS=false
```

It does not look like we need PVC helper at all with the above settings.

**Comment by sleshchenko** [comment] 2018-10-02 14:47
I think it should be fixed by https://github.com/eclipse/che/commit/689e123f28bdb3ebd2575b133ad4c40a18686ff8#diff-ff922581aa816d78fb5e17a72a1c9b3bR53 because previously there was the wrong check whether a namespace is predefined. But it is needed to check if it is actually fixed.

**Comment by skabashnyuk** [comment] 2018-10-19 11:16
can't reproduce on latest selenium tests.

**Closed as completed by skabashnyuk** 2018-10-19 11:16 UTC
Labels: kind/bug, severity/P2
