### ISSUE TITLE
Python language server failed to start

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#13599] opened 2019-06-21 06:02 UTC
### Description
I am trying to start workspace with a python plugin. Once workspace is started plugin downloads binaries (see python output panel):  
```
Starting Microsoft Python language server.
##########Linting Output - pylint##########
Downloading https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-linux-x64.0.2.96.nupkg... ##########Linting Output - pylint##########
------------------------------------
Your code has been rated at 10.00/10
complete
Unpacking archive... done
```
But then in plugin container logs:
```
Error: spawn /tmp/vscode-unpacked/ms-python.python.2019.2.5433.lprfkstukm.ms-python.python-2019.2.5433.vsix/extension/languageServer.0.2.96/Microsoft.Python.LanguageServer ENOENT
There is no such file in the directory.
```
And plugin functionality is broken.

My investigations shown that `/tmp/vscode-unpacked/...` directory is cleaned up when browser is refreshed.

### Reproduction Steps

**OS and version:**    
Che-7.0.0-CR1

**Diagnostics:**

**Comment by tolusha** [comment] 2019-06-21 06:35
It seems side-car container is being restarted....

**Comment by tolusha** [comment] 2019-06-21 06:47
I can't reproduce with Che-7.0.0-CR2

**Comment by tsmaeder** [comment] 2019-06-21 09:14
@benoitf @evidolob Seems fixed with latest release, but still flagging to see if it rings a bell.

**Comment by tolusha** [comment] 2019-07-12 06:55
Plugin side-car container is being restarted.

![Screenshot from 2019-07-12 09-49-33](https://user-images.githubusercontent.com/1640675/61108388-d7888000-a48a-11e9-95ad-ba01d9aa1069.png)

```
Info Python Extension: 2019-07-12 05:28:42: Cached data exists getEnvironmentVariables, /projects
--
  | Info Python Extension: 2019-07-12 05:29:12: Get language server folder name, Class name = f, completed in 2ms, Arg 1: <Uri:/projects>, Return Value: "languageServer.0.3.20"
  | Info Python Extension: 2019-07-12 05:29:12: Cached data exists getEnvironmentVariables, /projects
  | Info Python Extension: 2019-07-12 05:29:12: Cached data exists getEnvironmentVariables, <No Resource>
  | Info Python Extension: 2019-07-12 05:29:12: Cached data exists getEnvironmentVariables, /projects
  | Info Python Extension: 2019-07-12 05:29:12: Activation Commands received undefined for shell bash
  | Info Python Extension: 2019-07-12 05:29:12: getActivatedEnvironmentVariables, Class name = b, completed in 3ms, Arg 1: <Uri:/projects>
  | Info Python Extension: 2019-07-12 05:29:12: Cached data exists getEnvironmentVariables, /projects
  | Info Python Extension: 2019-07-12 05:29:12: Get language server folder name, Class name = f, completed in 4ms, Arg 1: <Uri:/projects>, Return Value: "languageServer.0.3.20"
  | events.js:174
  | throw er; // Unhandled 'error' event
  | ^
  | Error: spawn /tmp/vscode-unpacked/ms-python.python.latest.wtisvokzlk.ms-python-release.vsix/extension/languageServer.0.3.20/Microsoft.Python.LanguageServer ENOENT
  | at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
  | at onErrorNT (internal/child_process.js:415:16)
  | at process._tickCallback (internal/process/next_tick.js:63:19)
  | Emitted 'error' event at:
  | at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
  | at onErrorNT (internal/child_process.js:415:16)
  | at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by tolusha** [comment] 2019-07-12 06:58
```
Container vscode-pythonatj
State:
Running since Jul 12, 2019 8:29:45 AM
Last State
Terminated at Jul 12, 2019 8:29:12 AM with exit code 1 (Error)
Ready:
true
Restart Count:
3
```

**Comment by tolusha** [comment] 2019-07-12 07:03
devfile:
https://github.com/eclipse/che-devfile-registry/blob/ab/asp.net/devfiles/python-django/devfile.yaml#L1

**Comment by tsmaeder** [comment] 2019-07-12 07:59
@tolusha 

1. are you sure this is the some issue you encountered earlier? Just asking because the log looks slightly different.
2. Is this reproducible 100%?
3. What platform are you running on and how do y create & run the workspace?

**Comment by tolusha** [comment] 2019-07-12 08:40
1. The error is the same
`Error: spawn /tmp/vscode-unpacked/ms-python.python.latest.wtisvokzlk.ms-python-release.vsix/extension/languageServer.0.3.20/Microsoft.Python.LanguageServer ENOENT`
2. Yes
3. minishift v1.34.0+f5db7cb

**Comment by tsmaeder** [comment] 2019-07-12 08:59
How did you use the devfile? Chectl?

**Comment by tolusha** [comment] 2019-07-12 09:30
I created workspace using swagger API

**Comment by rhopp** [comment] 2019-07-12 15:58
I've just tried to create&use workspace created by the devfile @tolusha provided on 7.0.0-rc-4.0-SNAPSHOT (on minikube)
I've had no problems... Workspace started fine, code completion works... python container is not restarting at all:
```
- containerID: docker://83de0a14f630e4626237b71c37758dad323869d1f5a082609acbe11bb5d38fad
    image: eclipse/che-remote-plugin-python-3.7.3:7.0.0-rc-3.0
    imageID: docker-pullable://eclipse/che-remote-plugin-python-3.7.3@sha256:4c4c801c248de458d23a6d26141e6bc82b030f3b29c94aed6ad271fea64acecd
    lastState: {}
    name: vscode-python0ru
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-07-12T15:49:52Z"
```

@tolusha Could you try it on minikube/k8s? I can try this on Monday on openshift, so we will at least know if it's infra related.

Putting status info-needed for now.

**Comment by tolusha** [comment] 2019-07-16 00:26
@rhopp 
It works on minikube.

**Comment by tolusha** [comment] 2019-07-22 00:53
@rhopp 
I've started experiencing this issue on minikube too.

**Comment by svor** [comment] 2019-07-22 10:59
I've tested python-django on minishift and everything works fine on my side

**Comment by svor** [comment] 2019-07-23 06:32
I tried to reproduce it again and I got this problem twice. I'd say it is still actual problem.
https://youtu.be/dcd5Q0q9nf4

**Comment by tsmaeder** [comment] 2019-07-23 07:44
So it's real: this looks like some timing issue to me: we need to do some debugging when it happens: maybe dig into the code that runs the language server? https://docs.google.com/document/d/1puk0xDWJPaVz8VeKIMmr9EhL-rMnCE-yvxezXjPV1Hs/edit#heading=h.ylbuelxcww6d does not seem to offer many options for python LS.

**Comment by tolusha** [comment] 2019-07-24 06:10
@svor can confirm.
It is impossible to reproduce the issue once I deleted and started a new che server.

**Comment by svor** [comment] 2019-07-24 06:50
I tried to reproduce this problem few times after delete/start che server and couldn't reproduce it.

**Comment by tsmaeder** [comment] 2019-09-03 09:28
@tolusha so what's teh stat on this one?

**Comment by tolusha** [comment] 2019-09-03 11:08
https://github.com/eclipse/che/issues/14074#issuecomment-520935568

**Comment by tsmaeder** [comment] 2019-09-03 11:38
So are you saying this issue is a duplicate of the other?

**Comment by tolusha** [comment] 2019-09-03 12:45
yes, I think so.

**Comment by tsmaeder** [comment] 2019-09-10 09:17
duplicate

**Closed as completed by tsmaeder** 2019-09-10 09:17 UTC
Labels: kind/bug, status/info-needed, severity/P1
