### ISSUE TITLE
RAM widget disappers when select Java-MySQL stack

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#2480] opened 2016-09-19 08:37 UTC
**Reproduction Steps:**
Open Workspaces -> Add workspace -> select Java-MySQL stack

**Expected behavior:**
User should be able set RAM for machine(s)

**Observed behavior:**
No RAM widget

**Che version:**   5.0.0-M2-SNAPSHOT
**OS and version:**  Ubuntu 16.04 LTS
**Docker version:** 1.12.1
**Che install:**  build from source code

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by ashumilova** [comment] 2016-09-20 06:17
Closing, as duplicate of https://github.com/eclipse/che/issues/2494

**Closed as completed by ashumilova** 2016-09-20 06:17 UTC
Labels: kind/bug
