### ISSUE TITLE
Che loading is stuck on activating github-auth-plugin in Firefox 82.0.1 on Hosted Che

### ISSUE THREAD

**Issue by alessandro-bugatti** [eclipse-che/che#18231] opened 2020-10-28 15:04 UTC
### Describe the bug
The editor doesn't show when opening a workspace using Firefox 82.0.x. The problem seems "Activating @eclipse-che/github-auth-plugin" that stucks forever, as it can see in the image below. The files are shown inside the left file panel, but they don't load when double click on them. Both Chrome or Edge work correctly. I tried to clear all the cookies, but it doesn't work anyway. I also tried using Firefox 81.0.2 in a virtual machine with Linux and it works correctly, when I updated to 82, it stopped working and it has the same behaviour as in Windows.
I followed a suggestion on Mattermost from @artem, updating `che-theia` to `next` instead of `latest`, but it doesn't work anyway.

### Che version

Che-Theia@c2396db using Theia@d295e4642
 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

Use Firefox 82.x to open a workspace on Openshift

### Expected behavior
The workspace seems loading, but it stucks forever on Activating @eclipse-che/github-auth-plugin

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`) 7.20.0
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Cattura](https://user-images.githubusercontent.com/12863422/97452482-1454e080-1935-11eb-9853-28ba007a9431.PNG)

**Comment by azatsarynnyy** [comment] 2020-10-28 21:15
Thank you @alessandro-bugatti for reporting it!

I'm able to reproduce it in FireFox 82.0

![image](https://user-images.githubusercontent.com/1636395/97497492-3c633480-1973-11eb-8abb-c2912b185005.png)

We'll look at it ASAP

**Comment by alessandro-bugatti** [comment] 2020-10-29 15:13
Hi, I have just updated to Firefox 82.0.2 on Windows and now it works flawlessy, maybe the problem was in Firefox, not in Che

![Cattura](https://user-images.githubusercontent.com/12863422/97593043-94e11300-1a01-11eb-8dcf-af5f7ca09a2f.PNG)

**Comment by azatsarynnyy** [comment] 2020-10-29 15:33
Thank you @alessandro-bugatti for checking it again!

I see they released FireFox 82.0.1 on October 27. And then another bugfix release (82.0.2) was on October 28.
https://www.mozilla.org/en-US/firefox/82.0.2/releasenotes/

In 82.0.2 there's only one bug is fixed - `WebSocket duplicate packets sent` https://bugzilla.mozilla.org/show_bug.cgi?id=1673340

I'm 99% sure that is the root cause of the issue described here.
So, I guess we can close this issue with a proposed workaround to upgrade FireFox installation to >= 82.0.2

**Closed as completed by azatsarynnyy** 2020-10-29 15:33 UTC
Labels: kind/bug, severity/P1, area/editor/theia
