### ISSUE TITLE
Workspace creation via factory url hangs when using chrome

### ISSUE THREAD

**Issue by johnmcollier** [eclipse-che/che#15188] opened 2019-11-14 01:15 UTC
### Describe the bug

When I go to create a workspace via the factory URL (`<che-url>/f?url=<devfile>`), I'm finding that it frequently hangs at the `Initializing workspace` stage and never progresses when on Chrome (I'm on Version 78.0.3904.87). If I use another browser like Firefox, it works fine. It doesn't _always_ hang on Chrome, but I'd say it hangs most of the time.

Looking at the cluster, I don't see any activity in the namespace, nor do I see anything in the logs of the Che server pod. In the Javascript console of Chrome I see:
```
[KEYCLOAK] Estimated time difference between browser and server is 0 seconds
app-cde81a752c.js:50227 You are using the ngTouch module. 
Angular Material already has mobile click, tap, and swipe support... 
ngTouch is not supported with Angular Material!
(anonymous) @ app-cde81a752c.js:50227
6app-cde81a752c.js:50227 Markup '<md-button flex></md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details.
(anonymous) @ app-cde81a752c.js:50227
app-cde81a752c.js:50227 Error: Invalid url provided
    at i.create (app-cde81a752c.js:133647)
    at i._connect (app-cde81a752c.js:133647)
    at new i (app-cde81a752c.js:133647)
    at e.$websocket (app-cde81a752c.js:133647)
    at e.value (app-cde81a752c.js:140269)
    at e.value (app-cde81a752c.js:140024)
    at app-cde81a752c.js:151808
    at c (app-cde81a752c.js:52596)
    at app-cde81a752c.js:52644
    at p.$digest (app-cde81a752c.js:53781) "Possibly unhandled rejection: {}"
(anonymous) @ app-cde81a752c.js:50227
2app-cde81a752c.js:50227 Markup '<md-button flex></md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details.
(anonymous) @ app-cde81a752c.js:50227
/api/organization/find?name=admin:1 Failed to load resource: the server responded with a status of 404 ()
app-cde81a752c.js:50227 TypeError: Cannot read property 'send' of undefined
    at e.value (app-cde81a752c.js:140364)
    at e.value (app-cde81a752c.js:140128)
    at e.value (app-cde81a752c.js:139997)
    at e.value (app-cde81a752c.js:152044)
    at e.value (app-cde81a752c.js:151887)
    at e.value (app-cde81a752c.js:137811)
    at e.value (app-cde81a752c.js:137755)
    at app-cde81a752c.js:137703
    at app-cde81a752c.js:56087
    at i (app-cde81a752c.js:41705)
(anonymous) @ app-cde81a752c.js:50227
app-cde81a752c.js:50227 TypeError: Cannot read property 'send' of undefined
    at e.value (app-cde81a752c.js:140364)
    at e.value (app-cde81a752c.js:140128)
    at e.value (app-cde81a752c.js:139997)
    at e.value (app-cde81a752c.js:152044)
    at e.value (app-cde81a752c.js:151887)
    at e.value (app-cde81a752c.js:137811)
    at e.value (app-cde81a752c.js:137755)
    at app-cde81a752c.js:137703
    at app-cde81a752c.js:56087
    at i (app-cde81a752c.js:41705) "Possibly unhandled rejection: {}"
(anonymous) @ app-cde81a752c.js:50227
```

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Install Che via Chectl
2. Create a workspace via a factory url on Chrome (like `che-che.9.1.2.3.nip.io/f?url=https://raw.githubusercontent.com/johnmcollier/devfiles/master/devfile_test.yaml`). My test devfile https://raw.githubusercontent.com/johnmcollier/devfiles/master/devfile_test.yaml can be used
3. Workspace creation will intermittently hang on the `Initializing workspace` step and never proceed
4. If you go back to the Che dashboard, a stopped workspace will show up.

### Expected behavior

Workspace creation via factory url works when on Chrome.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

```
^CJohns-MacBook-Pro-3:codewind-che-plugin johncollier$ oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.14-201908291507+ec04ac2-dirty", GitCommit:"ec04ac2", GitTreeState:"dirty", BuildDate:"2019-08-29T23:30:52Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-07-22T15:47:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
### Screenshots

<img width="1257" alt="Screen Shot 2019-11-13 at 8 14 40 PM" src="https://user-images.githubusercontent.com/6880023/68818213-413fb300-0652-11ea-8d38-83a549432560.png">

<img width="1257" alt="Screen Shot 2019-11-13 at 8 14 44 PM" src="https://user-images.githubusercontent.com/6880023/68818215-443aa380-0652-11ea-8903-fef00d0e0f24.png">

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

```
Johns-MacBook-Pro-3:codewind-che-plugin johncollier$ chectl version
chectl/0.0.20191113-next.7a9f9b2 darwin-x64 node-v10.17.0
```

**Comment by johnmcollier** [comment] 2019-11-14 01:24
I should also note that if I copy and paste the devfile via the new `Import devfile` tab, I don't hit this issue.

**Comment by tolusha** [comment] 2019-11-15 08:36
I've tried couples of time but wan't able to reproduce. 
Google Chrome | 78.0.3904.97 (Official Build) (64-bit)

**Comment by sleshchenko** [comment] 2020-03-26 13:02
@johnmcollier Could you try to reproduce it? It seems to work for me as well. http://che.openshift.io/f?url=https://raw.githubusercontent.com/johnmcollier/devfiles/master/devfile_test.yaml

**Comment by sleshchenko** [comment] 2020-03-26 13:04
I'm closing it since I can't reproduce it and the case when the user sees nothing when an exception occurs should be fixed in the scope of https://github.com/eclipse/che/issues/16453

@johnmcollier Feel free to reopen it if you still able to reproduce case described in the description.

**Closed as completed by sleshchenko** 2020-03-26 13:04 UTC
Labels: kind/bug, status/info-needed, area/dashboard
