### ISSUE TITLE
Theia IDE fails on OpenShift Origin

### ISSUE THREAD

**Issue by andy316x** [eclipse-che/che#13435] opened 2019-05-28 13:31 UTC
### Description
The Che 7 stack fails to start when using OpenShift Origin as the container orchestration platform. When selecting the Che 7 stack, the workspace hangs while waiting for the eclipse/che-theia container to start. 

### Reproduction Steps
- Run Eclipse Che in OpenShift Origin
- Select Workspaces > Add Workspace > Che 7 > CREATE & OPEN
- The workspace starts to initialise but then hangs waiting for the Theia container to initialise, eventually failing reporting Failed to run the workspace: "Server 'theia' in machine 'theia-idexih' not available.

**OS and version:**
OpenShift Origin v3.9.0
Eclipse Che v7.0.0-beta6 (however seems to be a problem for earlier versions too)

**Diagnostics:** 
The following can be seen in the workspace logs in Eclipse Che:

Starting Init Plugin Broker
Cleaning /plugins dir
Unified Che Plugin Broker
List of plugins and editors to install
- eclipse/che-machine-exec-plugin/0.0.1 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace machines.
- eclipse/che-theia/next - Eclipse Theia, get the latest release each day.
Starting Che plugins and editor processing
Starting VS Code and Theia plugins processing
All plugins have been successfully processed
MountVolume.SetUp succeeded for volume "che-workspace-token-tbcvx" 
MountVolume.SetUp succeeded for volume "pv0010" 
MountVolume.SetUp succeeded for volume "jwtproxy-config-volume" 
MountVolume.SetUp succeeded for volume "che-workspace-token-tbcvx" 
pulling image "eclipse/che-dev:nightly"
pulling image "eclipse/che-jwtproxy:latest"
Successfully pulled image "eclipse/che-jwtproxy:latest"
Created container
Started container
Successfully pulled image "eclipse/che-dev:nightly"
Created container
Started container
pulling image "eclipse/che-machine-exec"
Successfully pulled image "eclipse/che-machine-exec"
Created container
Started container
pulling image "eclipse/che-theia:next"
Successfully pulled image "eclipse/che-theia:next"
Created container
Started container
**Error: Failed to run the workspace: "Server 'theia' in machine 'theia-idexih' not available."**

Inspecting the OpenShift logs in the underlying container, Theia seems to have errored:

root INFO Theia app listening on http://0.0.0.0:3100 .
--

```
  | root INFO unzipping the plugin ProxyPluginDeployerEntry {
  | deployer:
  | PluginTheiaFileHandler { unpackedFolder: '/tmp/theia-unpacked' },
  | delegate:
  | PluginDeployerEntryImpl {
  | originId: 'local-dir:///default-theia-plugins',
  | pluginId: 'eclipse_che_ports_plugin.theia',
  | map: Map {},
  | changes: [],
  | acceptedTypes: [],
  | currentPath: '/default-theia-plugins/eclipse_che_ports_plugin.theia',
  | initPath: '/default-theia-plugins/eclipse_che_ports_plugin.theia',
  | resolved: true,
  | resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  | deployerName: 'PluginTheiaFileHandler' }
  | root INFO unzipping the plugin ProxyPluginDeployerEntry {
  | deployer:
  | PluginTheiaFileHandler { unpackedFolder: '/tmp/theia-unpacked' },
  | delegate:
  | PluginDeployerEntryImpl {
  | originId: 'local-dir:///default-theia-plugins',
  | pluginId: 'eclipse_che_theia_containers_plugin.theia',
  | map: Map {},
  | changes: [],
  | acceptedTypes: [],
  | currentPath:
  | '/default-theia-plugins/eclipse_che_theia_containers_plugin.theia',
  | initPath:
  | '/default-theia-plugins/eclipse_che_theia_containers_plugin.theia',
  | resolved: true,
  | resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  | deployerName: 'PluginTheiaFileHandler' }
  | root INFO unzipping the plugin ProxyPluginDeployerEntry {
  | deployer:
  | PluginTheiaFileHandler { unpackedFolder: '/tmp/theia-unpacked' },
  | delegate:
  | PluginDeployerEntryImpl {
  | originId: 'local-dir:///default-theia-plugins',
  | pluginId: 'eclipse_che_theia_factory_plugin.theia',
  | map: Map {},
  | changes: [],
  | acceptedTypes: [],
  | currentPath:
  | '/default-theia-plugins/eclipse_che_theia_factory_plugin.theia',
  | initPath:
  | '/default-theia-plugins/eclipse_che_theia_factory_plugin.theia',
  | resolved: true,
  | resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  | deployerName: 'PluginTheiaFileHandler' }
  | root INFO unzipping the plugin ProxyPluginDeployerEntry {
  | deployer:
  | PluginTheiaFileHandler { unpackedFolder: '/tmp/theia-unpacked' },
  | delegate:
  | PluginDeployerEntryImpl {
  | originId: 'local-dir:///default-theia-plugins',
  | pluginId: 'eclipse_che_welcome_plugin.theia',
  | map: Map {},
  | changes: [],
  | acceptedTypes: [],
  | currentPath: '/default-theia-plugins/eclipse_che_welcome_plugin.theia',
  | initPath: '/default-theia-plugins/eclipse_che_welcome_plugin.theia',
  | resolved: true,
  | resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  | deployerName: 'PluginTheiaFileHandler' }
  | root INFO unzipping the plugin ProxyPluginDeployerEntry {
  | deployer:
  | PluginTheiaFileHandler { unpackedFolder: '/tmp/theia-unpacked' },
  | delegate:
  | PluginDeployerEntryImpl {
  | originId: 'local-dir:///default-theia-plugins',
  | pluginId: 'task_plugin.theia',
  | map: Map {},
  | changes: [],
  | acceptedTypes: [],
  | currentPath: '/default-theia-plugins/task_plugin.theia',
  | initPath: '/default-theia-plugins/task_plugin.theia',
  | resolved: true,
  | resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  | deployerName: 'PluginTheiaFileHandler' }
  | root INFO unzipping the plugin ProxyPluginDeployerEntry {
  | deployer:
  | PluginTheiaFileHandler { unpackedFolder: '/tmp/theia-unpacked' },
  | delegate:
  | PluginDeployerEntryImpl {
  | originId: 'local-dir:///default-theia-plugins',
  | pluginId: 'theia_yeoman_plugin.theia',
  | map: Map {},
  | changes: [],
  | acceptedTypes: [],
  | currentPath: '/default-theia-plugins/theia_yeoman_plugin.theia',
  | initPath: '/default-theia-plugins/theia_yeoman_plugin.theia',
  | resolved: true,
  | resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  | deployerName: 'PluginTheiaFileHandler' }
  | root ERROR Uncaught Exception:  [object Object]
  | root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/theia-unpacked/eclipse_che_ports_plugin.theia
  | root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/theia-unpacked/eclipse_che_theia_containers_plugin.theia
  | root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/theia-unpacked/eclipse_che_theia_factory_plugin.theia
  | root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/theia-unpacked/eclipse_che_welcome_plugin.theia
  | root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/theia-unpacked/task_plugin.theia
  | root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/theia-unpacked/theia_yeoman_plugin.theia
  | root INFO Deploying backend plugin "@eclipse-che/ports-plugin@0.0.1" from "/tmp/theia-unpacked/eclipse_che_ports_plugin.theia/lib/ports-plugin.js"
  | root INFO Deploying backend plugin "@eclipse-che/theia-containers-plugin@0.0.2" from "/tmp/theia-unpacked/eclipse_che_theia_containers_plugin.theia/lib/containers-plugin.js"
  | root INFO Deploying backend plugin "@eclipse-che/theia-factory-plugin@0.0.1" from "/tmp/theia-unpacked/eclipse_che_theia_factory_plugin.theia/lib/factory-plugin.js"
  | root INFO Deploying backend plugin "@eclipse-che/welcome-plugin@0.0.1" from "/tmp/theia-unpacked/eclipse_che_welcome_plugin.theia/lib/welcome-plugin.js"
  | root INFO Deploying backend plugin "task-plugin@0.0.1" from "/tmp/theia-unpacked/task_plugin.theia/lib/task-plugin-backend.js"
  | root INFO Deploying backend plugin "@theia/yeoman-plugin@0.0.1-1539189859" from "/tmp/theia-unpacked/theia_yeoman_plugin.theia/lib/theia-yeoman-plugin-backend-plugin.js"
```

**Comment by RichardChester** [comment] 2019-06-11 10:17
I have the same issue

**Comment by andy316x** [comment] 2019-07-12 19:38
I experience this issue if running in multi-user mode, interestingly if I deploy Che in single-user mode Theia loads successfully, however it is then not able to create terminals. I am also using Che in AWS.

**Comment by sunix** [comment] 2019-07-15 16:09
@andy316x I am closing this issue as it looks duplicate of https://github.com/eclipse/che/issues/13690 and we have more information on it.

**Closed as completed by sunix** 2019-07-15 16:09 UTC
