### ISSUE TITLE
Problems in creating annotated workspaces

### ISSUE THREAD

**Issue by LookMumNoBackup** [eclipse-che/che#18560] opened 2020-12-08 14:35 UTC
### Describe the bug
Copy from this #18559 

We tried to setup a k8s cluster (in AWS) with Eclipse Che as described in official setup documentation. We failed to create workspaces which have user-defined k8s pod annotations (like proposed in this guide )

Is someone who is able to use this feature already? Can someone confirm that this feature is working and creating k8s pod annotations as specified?

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.22.2 linux-x64 node-v10.23.0

### Steps to reproduce

**Pre-condition** : Che Server is up and running within AWS EKS

1) Open browser
2) Login as user with admin privileges to Che Dashboard
3) Open following URL in same browser window
```
https://che-che.<Route53-Domain>/f?url=https://gist.githubusercontent.com/themr0c/ef8e59a162748a8be07e900b6401e6a8/raw/8802c20743cde712bbc822521463359a60d1f7a9/devfile.yaml&workspaceDeploymentAnnotations=ike.A1%3Dpreference-v1%2Cike.A%3Dtest
```
4) Look at a animation within window which shows that factory is about to create
![factory-creation-done](https://user-images.githubusercontent.com/75678636/101495575-fda89d00-3968-11eb-8c66-7871fffc9f19.PNG)
5) New workspace is created
6) Go to CLI and get complete description of the pod in which the workspace is running
[tag-issue-pod-description.txt](https://github.com/eclipse/che/files/5659754/tag-issue-pod-description.txt)

### Expected behavior
Found somewhere in the description the tags/labels which were specified in the URL

### Runtime
   - [x] kubernetes
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
```
chectl server:deploy --platform=k8s --installer=helm --domain=<ROUTE_53_DOMAIN> --multiuser
```
```
chectl/7.22.2 linux-x64 node-v10.23.0
```
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
Can not provide that easily as corporate cleaning procedure have to be performed for every file. If specific values/excerpts are needed I will provide them as soon as possible.

### Additional context
![factory-creation-done](https://user-images.githubusercontent.com/75678636/101495630-0c8f4f80-3969-11eb-917b-4aaa56892fdf.PNG)
[tag-issue-pod-description.txt](https://github.com/eclipse/che/files/5659754/tag-issue-pod-description.txt)

**Comment by skabashnyuk** [comment] 2020-12-08 14:55
I do have necessary annotations
<img width="1021" alt="Знімок екрана 2020-12-08 о 16 54 52" src="https://user-images.githubusercontent.com/1614429/101499634-2a16e600-3976-11eb-8e5d-893a697744b4.png">
how it looks like on your side?

**Comment by skabashnyuk** [comment] 2020-12-08 15:00
Please note that we are talking about `Deployment` annotations

**Comment by B166ER-2** [comment] 2020-12-08 16:19
@skabashnyuk many thanks for that detail. Indeed I was looking on the pod description first but I also checked the deployment description using following command

```
kubectl -n admin-che get deployments <DEPLOYMENT_ID> -o yaml
```

The content of the result is attached to this message. I was not able to find any hint of annotations provided before
[deployment2.txt](https://github.com/eclipse/che/files/5660417/deployment2.txt)

**Comment by skabashnyuk** [comment] 2020-12-09 07:36
@B166ER-2 can you get me a workspace json? from `https://che-server/api/workspace/workspacehd2w4hc3ydlhqtbx?token=usertoken` ?

**Comment by B166ER-2** [comment] 2020-12-09 08:34
@skabashnyuk sure ... JSON is attached
[api.txt](https://github.com/eclipse/che/files/5664511/api.txt)

**Comment by skabashnyuk** [comment] 2020-12-14 10:36
@B166ER-2 I was not able to reproduce this bug nighter 7.22.2 nor 7.23.-snapshot.
- `https://che-che.apps.cluster-devtools-041d.devtools-041d.example.opentlc.com/f?url=https://gist.githubusercontent.com/themr0c/ef8e59a162748a8be07e900b6401e6a8/raw/8802c20743cde712bbc822521463359a60d1f7a9/devfile.yaml&workspaceDeploymentAnnotations=ike.A1%3Dpreference-v1%2Cike.A%3Dtest`
<img width="1056" alt="Знімок екрана 2020-12-14 о 12 27 17" src="https://user-images.githubusercontent.com/1614429/102070876-68922200-3e08-11eb-86ad-bb9c5a889df7.png">

- `https://che-che.apps.cluster-devtools-041d.devtools-041d.example.opentlc.com/f?url=https://gist.githubusercontent.com/themr0c/ef8e59a162748a8be07e900b6401e6a8/raw/8802c20743cde712bbc822521463359a60d1f7a9/devfile.yaml&workspaceDeploymentLabels=ike.target%3Dpreference-v1%2Cike.session%3Dtest`
<img width="659" alt="Знімок екрана 2020-12-14 о 12 30 11" src="https://user-images.githubusercontent.com/1614429/102070887-6cbe3f80-3e08-11eb-8014-2d00ac6c1faf.png">


Can you confirm that you are using **vanilla** che-server 7.22.2 image like:
<img width="1651" alt="Знімок екрана 2020-12-14 о 12 34 16" src="https://user-images.githubusercontent.com/1614429/102071257-e5250080-3e08-11eb-890c-3ea08c7804d9.png">

**Comment by B166ER-2** [comment] 2021-01-11 14:45
sorry for the long break of communication ... my fault ... the deployment is absolutely vanilla. 
I got it working using the official documentation of che.

**Comment by skabashnyuk** [comment] 2021-01-11 15:12
>I got it working using the official documentation of che.

@B166ER-2  does that mean that we can close this issue?

**Comment by B166ER-2** [comment] 2021-01-11 16:08
> > I got it working using the official documentation of che.
> 
> @B166ER-2 does that mean that we can close this issue?

@skabashnyuk no ... I only wanted to emphasize that my setup which I used for reproduction of this issue was definitely a vanila one as I expect that the official documentation explains how to setup a valina che installation. The issue is still existing.

**Comment by skabashnyuk** [comment] 2021-01-12 09:31
@B166ER-2 can you check that on 7.24?

**Closed as completed** 2021-03-18 08:21 UTC
Labels: kind/bug, severity/P1, area/che-server, area/factory/server
