### ISSUE TITLE
Failed to run the workspace: "Server 'theia' in container 'theia-idead0' not available."

### ISSUE THREAD

**Issue by alexeykazakov** [eclipse-che/che#18360] opened 2020-11-12 21:46 UTC
I'm trying to start a workspace (tried nodejs and spring boot) but get the following error:

Error: Failed to run the workspace: "Server 'theia' in container 'theia-idead0' not available."

Logs:
https://gist.github.com/alexeykazakov/1f0621d99cf88ee0c07ad2009a4e823e
https://gist.github.com/alexeykazakov/b18284a2431703028c4b2762d6f8984c
https://gist.github.com/alexeykazakov/dfda63119cf48b356f485b7823c9a63c
https://gist.github.com/alexeykazakov/c5f6d45312094f82902e0f9a2608af5f
https://gist.github.com/alexeykazakov/cdca8cc10f596fa905164aacbbf27fde

Events:
https://gist.github.com/alexeykazakov/449b33551843fa051e02702bcc810557

### Che version
Che Operator 7.21.1 running on OCP 4.5
Configuration: https://github.com/codeready-toolchain/toolchain-infra/blob/master/config/operators/che/che_cluster.yaml

### Additional context
Maybe it's related to the recent change in the operator configuration: https://github.com/codeready-toolchain/toolchain-infra/pull/35

**Comment by alexeykazakov** [comment] 2020-11-12 22:19
Reverting single-host change fixed the problem at least for new users. My existing user is now in some broken state.

**Comment by ibuziuk** [comment] 2020-11-13 09:10
@alexeykazakov can not reproduce on OSD v4 with the following configuration - https://raw.githubusercontent.com/codeready-toolchain/toolchain-infra/master/config/operators/che/che_cluster.yaml

**Comment by sparkoo** [comment] 2020-11-13 09:16
@alexeykazakov do you have che-server logs ?

**Comment by sleshchenko** [comment] 2020-11-13 11:23
This PR would help a lot in discovering the cause but I did not manage to finalize it.
Platform team - if you have a chance to apply suggested changes and test it, would be really cool.

**Comment by alexeykazakov** [comment] 2020-11-13 14:59
When trying to reproduce then try deploy it without the single host thing first. Then set it to single host. Our setup is not a fresh installation as Ilya tried on OSD.

**Comment by alexeykazakov** [comment] 2020-11-17 04:45
I just installed a fresh CRW 2.5.0 operator and faced the same issue.

The logs from the operator pods:

```
2020-11-17 03:09:18,687[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 984]   - Workspace 'alkazako-osiotest:spring-boot-http-booster-y8atf' with id 'workspaceif7jc5fpsuvdl0nt' start failed
2020-11-17 04:33:06,757[nio-8080-exec-9]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 480]   - Starting workspace 'alkazako-osiotest/spring-boot-http-booster-y8atf' with id 'workspaceif7jc5fpsuvdl0nt' by user 'alkazako-osiotest'
2020-11-17 04:33:30,594[aceSharedPool-1]  [INFO ] [.i.k.KubernetesInternalRuntime 652]  - Debug workspace startup. Will watch the logs of 'workspaceif7jc5fpsuvdl0nt'
2020-11-17 04:36:55,149[aceSharedPool-1]  [WARN ] [.i.k.KubernetesInternalRuntime 255]  - Failed to start Kubernetes runtime of workspace workspaceif7jc5fpsuvdl0nt.
org.eclipse.che.api.workspace.server.spi.InfrastructureException: Server 'theia' in container 'theia-idebnv' not available.
	at org.eclipse.che.api.workspace.server.hc.ServerChecker$ServerCheckingTask.run(ServerChecker.java:122)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
2020-11-17 04:37:00,815[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 984]   - Workspace 'alkazako-osiotest:spring-boot-http-booster-y8atf' with id 'workspaceif7jc5fpsuvdl0nt' start failed
```

**Comment by ibuziuk** [comment] 2020-11-17 09:36
@alexeykazakov could you provide the logs from the che-server pod?

**Comment by alexeykazakov** [comment] 2020-11-17 15:35
Sorry, the logs above are from the Che server pod. Not from the operator pod as I said.

**Comment by ibuziuk** [comment] 2020-11-23 17:36
was able to reproduce this issue on the fresh OSD v4 cluster against CRW 2.5, funny enough that the same config seems to work just fine on `che-dev` OSD v4:

```
2020-11-23 17:18:10,824[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 984]   - Workspace 'ibuziuk:golang-kmi87' with id 'workspace3qpe01hj13071qjr' start failed
2020-11-23 17:31:01,696[nio-8080-exec-6]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 480]   - Starting workspace 'ibuziuk/golang-kmi87' with id 'workspace3qpe01hj13071qjr' by user 'ibuziuk'
2020-11-23 17:34:51,959[aceSharedPool-2]  [WARN ] [.i.k.KubernetesInternalRuntime 255]  - Failed to start Kubernetes runtime of workspace workspace3qpe01hj13071qjr.
org.eclipse.che.api.workspace.server.spi.InfrastructureException: Server 'theia' in container 'theia-idency' not available.
	at org.eclipse.che.api.workspace.server.hc.ServerChecker$ServerCheckingTask.run(ServerChecker.java:122)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
2020-11-23 17:34:52,334[aceSharedPool-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 984]   - Workspace 'ibuziuk:golang-kmi87' with id 'workspace3qpe01hj13071qjr' start failed
```

**Comment by ibuziuk** [comment] 2020-11-23 18:31
Not sure if this is related but there are different network-policies applied on the user namespaces:

- working (no networkpolicy objects in the <username>-code namespace)

- non-working

> NAME                              POD-SELECTOR   AGE
> allow-from-openshift-ingress      <none>         130m
> allow-from-openshift-monitoring   <none>         130m
> allow-same-namespace              <none>         130m

@sparkoo could it be the root cause?  maybe the default "flat" pod network is currently a requirment for enabling the 'single-host' ?

**Comment by alexeykazakov** [comment] 2020-11-23 20:38
You can see the network policies which are applied to all `<username>-code` user namespaces in Sandbox: https://github.com/codeready-toolchain/host-operator/blob/master/deploy/templates/nstemplatetiers/basic/ns_code.yaml#L72-L109

We can add a new network policy to allow che-server to reach them out there but I think the easiest solution would be to add `oc label namespace/codeready-workspaces-operator network.openshift.io/policy-group=ingress` label to the CRW operator namespace. The current Sandbox network policy allows traffic from such namespaces.
I've tested it in our crt-stage clusters and it worked.

But Che/CRW users in other environments may hit the same issue if they try to run workspaces in protected namespaces with similar network policies. So, it's worth documenting it if it's not already. Also, maybe Che operator should be smart enough to add required network policies to the workspace namespaces on fly...

**Comment by sparkoo** [comment] 2020-11-23 21:54
@ibuziuk @alexeykazakov I'm not very familiar with openshift network policies, but yes it looks like it may be a root cause. The traffic goes from the main Route and Traefik Service in `che` namespace, through `traefik` Pod, into workspace Services in workspace's namespace. So they must be reachable.

**Comment by ibuziuk** [comment] 2020-11-24 08:43
> I've tested it in our crt-stage clusters and it worked: https://github.com/codeready-toolchain/toolchain-infra/pull/44/files

@alexeykazakov Wouldn't the proper solution be adding the `allow-from-codeready-workspaces-operator` network policy to the code namespace similar to what is already done for other cases - https://github.com/codeready-toolchain/host-operator/blob/master/deploy/templates/nstemplatetiers/basic/ns_code.yaml

```
allow-from-openshift-ingress 130m
allow-from-openshift-monitoring 130m
allow-same-namespace 130m
```

This PR looks like a workaround for a particular Sandbox setup and it does not look like a good idea to fix it on the che subcription level - https://github.com/codeready-toolchain/toolchain-infra/pull/44/files

**Comment by ibuziuk** [comment] 2020-11-25 11:03
Closing, single-host docs limitations & requirements are planned to be documented as part of https://github.com/eclipse/che/issues/18453

**Closed as completed by ibuziuk** 2020-11-25 11:03 UTC
Labels: kind/bug, status/analyzing, severity/P1, area/che-server
