### ISSUE TITLE
[Language server] The Refactor -> Rename feature does not work for Golang language server

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10524] opened 2018-07-24 12:00 UTC
**Reproduction Steps:**
1. Create and start workspace from **Go** stack with **web-go-simple** project.
2. Open "**main.go**" file from the project.
3. Click on any variable and select **Refactoring**->**Rename**(Shift+F6) feature from context menu.
4. Change name of the variable and press **ENTER**.

**Expected behavior:** 
The variable name changed
 
**Observed behavior:**
The variable was not changed and there is "**Rename failed: gorename: can't find package containing /projects/ga/main.go**" error notification.
 
**Che version**: 6.9.0
**OS and version:** Fedora 28
**Che install:** OCP-single

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**screenshot:**
![eclipse che wksp-3mtr - google chrome_051](https://user-images.githubusercontent.com/7760565/43136403-4bcd1624-8f51-11e8-9f0d-739cf35a86e6.png)

![selection_125](https://user-images.githubusercontent.com/7760565/45554148-5c404880-b83e-11e8-9067-b50f69642cc7.png)

**Comment by eivantsov** [comment] 2018-10-31 13:03
The problem here seems to have been caused by the fact that project sources aren't in `${GOPATH}/src`. It is possible to define `GOPATH` to point to `/projects` and create a project in `src`. However, `bin/ pkg/ src/` will be treated like projects and displayed in project explorer as such.

**Comment by dkuleshov** [comment] 2018-11-12 10:40
Yeah, seems like golang language server delegates renaming to `gorename` tool which conforms to golang project structure ideology which in turn does not align with such in eclipse che. At the moment there is no possibility to separately configure the tool to use custom project path, while in the other hand it is also not possible to change eclipse che workspace file system structure the way the tool requires for its proper work.

After spending a lot time on investigation and fixing the issue, as a conclusion I believe that we unfortunately have just a few options: to wait until the tool/language server becomes more flexible, to switch to another language server that may not have such problem or to revise the approach we're using when we organize eclipse che workspace file system structure.

From my point of view, all options are doubtful so I'm closing this as "won't fix" until we have a reliable solution.

**Closed as completed** 2018-11-12 11:18 UTC
Labels: kind/bug, severity/P2
