### ISSUE TITLE
Create UBI based images for che-theia

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#13765] opened 2019-05-15 11:17 UTC
We need eventually move to [UBI images ](https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image)
With this issue we can start creating POC images for che-theia
Currently there are [ubi8/nodejs-10](https://access.redhat.com/containers/?tab=images&get-method=unauthenticated#/registry.access.redhat.com/ubi8/nodejs-10), so we can start POC using that image as base image.
I propose to start with:
- [ ] [`theia-dev`](https://github.com/eclipse/che-theia/tree/master/dockerfiles/theia-dev)
- [ ] [`theia`](https://github.com/eclipse/che-theia/tree/master/dockerfiles/theia)

**Comment by nickboldt** [comment] 2019-09-28 15:31
Work in progress started last week here:

https://github.com/redhat-developer/codeready-workspaces/tree/master/dependencies/che-theia

Current TODOs:

- [ ] theia-dev - do we need to build **generator/eclipse-che-theia-generator.tgz** ? or can we just get the sources and install the binary during theia build from npm (*@eclipse-che/theia-generator*), as we do for *@theia/generator-plugin* ?
- [ ] theia-dev why hardcoded version @theia/generator-plugin@0.0.1-1540209403 vs. using latest?

- [ ] theia-dev - find a RHEL 7 or EPEL 7 repo from which we can get libxkbfile-devel and libxkbfile rpms
- [ ] theia-dev - Collect the contents of these for use in Brew:
-- /home/theia-dev/.yarn-global/node_modules/ 
-- /usr/local/share/.cache/yarn/
--  /opt/app-root/src/.npm-global/

- [ ] theia - Figure out what the MONACO stuff is about
- [ ] theia - fully remove all build ARGs ; use template -> Dockerfile generation instead
- [ ] theia - collect all npm deps into a tarball for use in Brew
- [ ] theia - verify e2e tests can be disabled with --skip-test flag

**Comment by benoitf** [comment] 2019-09-30 13:25
generator was in a separated repository (ws-skeleton) and then published to npmjs

as it's now in che-theia repository, it should not be retrieved through npmjs

**Comment by benoitf** [comment] 2019-09-30 13:33
> why hardcoded version @theia/generator-plugin@0.0.1-1540209403 vs. using latest?

to be sure that the version used is working as expected.

**Comment by AndrienkoAleksandr** [comment] 2019-09-30 14:52
> Collect the contents of these for use in Brew:
. /home/theia-dev/.yarn-global/node_modules/
. /usr/local/share/.cache/yarn/
. /opt/app-root/src/.npm-global/

I think from time to time content this folders changes and become outdated. Also If you want these folders in the some another images I think multi-stage build could help.

Do you mean Brew from MacOS? I guess it doesn't work on the Linux..

**Comment by AndrienkoAleksandr** [comment] 2019-09-30 14:57
> Figure out what the MONACO_CDN_PREFIX and CDN_PREFIX stuff is about

To speed up che-theia loading we are caching che-theia scripts and push it to the CDN registry like artifact. Then on start theia browser downloads scripts from the closest CDN server, that why theia loading faster.

**Comment by nickboldt** [comment] 2019-09-30 14:59
> > why hardcoded version @theia/generator-plugin@0.0.1-1540209403 vs. using latest?
> 
> to be sure that the version used is working as expected.
> 
> also let say you run the build 2 months later, it may not work at all

Right but why a DIFFERENT version in che-theia/theia vs che-theia/theia-dev? 

theia-dev: @theia/generator-plugin@0.0.1-1540209403
theia:       @theia/generator-plugin@0.0.1-1562578105

Surely you want the same version in both? Seems like hardcoding this in the dockerfiles vs. in a package.json or yarn.lock is what's causing the mismatch (update one, forget the other) ?

**Comment by nickboldt** [comment] 2019-09-30 15:00
> To speed up che-theia loading we are caching che-theia scripts and push it to the CDN registry like artifact. Then on start theia browser downloads scripts from the closest CDN server, that why theia loading faster.

I'm not sure we can do that for the product unless we have a RH-approved repo where we're publishing. What's the full URL of the CDN we're using?

**Comment by nickboldt** [comment] 2019-09-30 15:01
> I think from time to time content these folders changes and become outdated. Also If you want these folders in the some another images I think multi-stage build could help.

No, I need to pull the contents of these folders so that I can push them into the Dockerfile build inside Brew. Brew can't see the outside world, so I need to tar up these node_modules and then push the tarball into pkgs.devel.redhat.com so we have a stored copy of the sources/binaries from which to build offline.

**Comment by nickboldt** [comment] 2019-09-30 15:03
> generator was in a separated repository (ws-skeleton) and then published to npmjs
> 
> as it's now in che-theia repository, it should not be retrieved through npmjs

Do you mean @eclipse-che/theia-generator or @theia/generator-plugin ?

If you mean @eclipse-che/theia-generator... should we **also** be building @theia/generator-plugin instead of installing it from npm?

**Comment by benoitf** [comment] 2019-09-30 15:14
@nickboldt 
> do we need to build generator/eclipse-che-theia-generator.tgz ?

yes it's part of the source code of this project.

> should we also be building @theia/generator-plugin instead of installing it from npm?

no, because the source code is external to this repository: https://github.com/eclipse/theia-generator-plugin

**Comment by nickboldt** [comment] 2019-09-30 15:40
If "it's in another repo" was a reason not to build something, then the whole che-theia repo wouldn't exist. :P 

I'm asking if it's better to use a specific binary, or to build from master. Since the version of the generator plugin is different in theia-dev vs. theia, I'd think at least we should standardize on a single version, if not using latest.

Would you agree? or is there some technical reason to have them different?

**Comment by benoitf** [comment] 2019-09-30 15:43
it should be the same version coming from npmjs for theia-generator-plugin in theia-dev and in theia

**Comment by nickboldt** [comment] 2019-09-30 19:04
@benoitf so you mean:

Instead of using
`@theia/generator-plugin@0.0.1-1562578105`
and
`@theia/generator-plugin@0.0.1-1540209403`

we should just pull the latest from npm ? or both should be using newer `1562578105` timestamp?

**Comment by benoitf** [comment] 2019-09-30 19:13
`1562578105` timestamp

**Comment by benoitf** [comment] 2019-09-30 19:15
latest may pull unwanted versions and is not tagged/ reproducible build

**Comment by nickboldt** [comment] 2019-10-04 04:22
I've got a working build of theia-dev in Brew, pushed to Quay.
* Sync/trigger job: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/crw-theia-dev_sync-github-to-pkgs.devel/configure
* Latest tags: https://quay.io/repository/crw/theia-dev-rhel8?tab=tags

**Comment by nickboldt** [comment] 2019-10-06 04:11
Sync/trigger job for theia: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/crw-theia_sync-github-to-pkgs.devel/ is now working.

Latest tags (built locally, pushed manually): https://quay.io/repository/crw/theia-rhel8?tag=latest&tab=tags

However the build is still dying in Brew because node-gyp is trying to download stuff:

```
2019-10-06 03:54:41,669 - atomic_reactor.plugins.imagebuilder - INFO - --> RUN if [ -z $GITHUB_TOKEN ]; then unset GITHUB_TOKEN; fi &&     yarn
2019-10-06 03:54:42,190 - atomic_reactor.plugins.imagebuilder - INFO - yarn install v1.17.3
2019-10-06 03:54:42,279 - atomic_reactor.plugins.imagebuilder - INFO - $ node-gyp install
2019-10-06 03:54:42,543 - atomic_reactor.plugins.imagebuilder - INFO - gyp http GET https://nodejs.org/download/release/v10.14.1/node-v10.14.1-headers.tar.gz
2019-10-06 03:54:42,591 - atomic_reactor.plugins.imagebuilder - INFO - gyp WARN install got an error, rolling back install
2019-10-06 03:54:42,596 - atomic_reactor.plugins.imagebuilder - INFO - gyp ERR! stack Error: connect ECONNREFUSED 104.20.22.46:443
2019-10-06 03:54:42,596 - atomic_reactor.plugins.imagebuilder - INFO - gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
2019-10-06 03:54:42,596 - atomic_reactor.plugins.imagebuilder - INFO - gyp ERR! System Linux 3.10.0-957.21.2.el7.x86_64
2019-10-06 03:54:42,596 - atomic_reactor.plugins.imagebuilder - INFO - gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install"
2019-10-06 03:54:42,596 - atomic_reactor.plugins.imagebuilder - INFO - gyp ERR! cwd /home/theia-dev/theia-source-code
2019-10-06 03:54:42,597 - atomic_reactor.plugins.imagebuilder - INFO - gyp ERR! node -v v10.14.1
2019-10-06 03:54:42,597 - atomic_reactor.plugins.imagebuilder - INFO - gyp ERR! node-gyp -v v3.8.0
2019-10-06 03:54:42,597 - atomic_reactor.plugins.imagebuilder - INFO - gyp ERR! not ok
2019-10-06 03:54:42,614 - atomic_reactor.plugins.imagebuilder - INFO - error Command failed with exit code 1.
```
--  https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/crw-theia_sync-github-to-pkgs.devel/5/console

**Comment by nickboldt** [comment] 2019-10-06 16:57
OK, got past the node-gyp download problem.

Next issue:

```
Couldn't find package "axios@0.18.1" required by "@eclipse-che/theia-plugin-ext@7.2.0" on the "npm" registry.
Couldn't find package "clean-webpack-plugin@^0.1.19" required by "@eclipse-che/theia-plugin-ext@7.2.0" on the "npm" registry.
Couldn't find package "@eclipse-che/api@^7.0.0-beta-4.0-80162ea6d2" required by "@eclipse-che/theia-preferences-provider-extension@7.2.0" on the "npm" registry.
Couldn't find package "@eclipse-che/api@latest" required by "@eclipse-che/che-theia-hosted-plugin-manager-extension@7.2.0" on the "npm" registry.
Couldn't find package "@eclipse-che/api@latest" required by "@eclipse-che/plugin@7.2.0" on the "npm" registry.
Couldn't find package "@eclipse-che/api@latest" required by "@eclipse-che/theia-dashboard-extension@7.2.0" on the "npm" registry.
Couldn't find package "@eclipse-che/api@latest" required by "@eclipse-che/theia-terminal@7.2.0" on the "npm" registry.
Couldn't find package "@eclipse-che/workspace-client@latest" required by "@eclipse-che/theia-plugin-ext@7.2.0" on the "npm" registry.
Couldn't find package "@eclipse-che/workspace-client@latest" required by "@eclipse-che/theia-terminal@7.2.0" on the "npm" registry.
Couldn't find package "html-webpack-plugin@^3.2.0" required by "@eclipse-che/theia-assembly@0.11.0" on the "npm" registry.
Couldn't find package "ini@^1.3.5" required by "@eclipse-che/theia-git-provisioner@7.2.0" on the "npm" registry.
Couldn't find package "js-yaml@3.13.1" required by "@eclipse-che/theia-plugin-ext@7.2.0" on the "npm" registry.
Couldn't find package "ts-loader@^4.1.0" required by "@eclipse-che/theia-plugin-ext@7.2.0" on the "npm" registry.
Couldn't find package "typescript-formatter@7.2.2" required by "@eclipse-che/theia-plugin-ext@7.2.0" on the "npm" registry.
Couldn't find package "typescript-formatter@7.2.2" required by "@eclipse-che/theia-remote@7.2.0" on the "npm" registry.
Couldn't find package "typescript-formatter@7.2.2" required by "@eclipse-che/theia-terminal@7.2.0" on the "npm" registry.
Couldn't find package "@types/js-yaml@3.11.2" required by "@eclipse-che/theia-plugin-ext@7.2.0" on the "npm" registry.
Couldn't find package "webpack@^4.20.2" required by "@eclipse-che/theia-plugin-ext@7.2.0" on the "npm" registry.
Couldn't find package "webpack-cli@^3.1.1" required by "@eclipse-che/theia-plugin-ext@7.2.0" on the "npm" registry.
Couldn't find package "xterm@3.9.2" required by "@eclipse-che/theia-terminal@7.2.0" on the "npm" registry.
```

**Comment by nickboldt** [comment] 2019-10-06 17:01
Also can we use a version other than @latest ? That's great for CI but terrible for products. :) If so, how do we override that, and where?

**Comment by benoitf** [comment] 2019-10-06 17:01
I think it's solved with yarn offline / cache

**Comment by nickboldt** [comment] 2019-10-06 17:03
when/where do I have to run yarn to perform the caching? and from what folder do I then need to tar up the results? I know it's the weekend ... but your answers are not helpful :(

**Comment by benoitf** [comment] 2019-10-06 19:38
the yarn cache folder: https://github.com/benoitf/che-theia-brew/blob/master/build.sh#L70
(or `yarn cache dir` command)

for yarn offline:
https://github.com/benoitf/che-theia-brew/blob/master/conf/theia-dev/ubi8-brew/setup-extra.env

it will append `--offline` on every yarn commands

**Comment by benoitf** [comment] 2019-10-08 15:23
I've reworked che-theia docker image builds:
 https://github.com/eclipse/che-theia/pull/474

Found this issue with offline mode:
https://github.com/eclipse/che/issues/14804

Here is a script to generate 'offline/ubi8 / brew compliant (hopefully) images'
https://github.com/benoitf/che-theia-brew

The build script is mostly composed of 3 parts:

1.  we clone che-theia repository (for now it’s my branch) and run yarn

2. then, theia-dev, we generate a dry-run and use TMP_BUILDER_NAME to build an image “online” with ubi8. Once it is built, we extract cache/downloaded stuff and create assets. Then we create “real image” for ubi8 (ubi8-brew) with the name CHE_THEIA_DEV_IMAGE_NAME=“quay.io/codeready-workspaces/che-theia-dev:next”  (configured at the top of the file)

3. then theia: again, dry run. then two builds: one for the builder target, one for the runtime target. Extract assets from builder and runtime, generate offline/ubi8-brew image and build it with CHE_THEIA_IMAGE_NAME=“quay.io/codeready-workspaces/che-theia:next”

**Comment by nickboldt** [comment] 2019-10-09 19:23
Thanks to Florent's hard work we have theia and updated theia-dev images now for CRW 2.0:

* quay.io/crw/theia-rhel8:2.0-3 931MB
* quay.io/crw/theia-dev-rhel8:2.0-46 288M

**Comment by l0rd** [comment] 2019-10-10 21:49
@nickboldt @benoitf is there still something missing or we can close this issue?

**Comment by nickboldt** [comment] 2019-10-11 03:22
Once Florent's code is in https://github.com/redhat-developer/codeready-workspaces-theia we can resolve this. 

Followup work in https://github.com/eclipse/che/issues/14797

**Comment by nickboldt** [comment] 2019-10-16 19:08
Code is live in https://github.com/redhat-developer/codeready-workspaces-theia but not synced with pkgs.devel repos yet

**Comment by nickboldt** [comment] 2019-10-30 22:20
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Pipelines/job/crw-theia_master/ builds theia-dev, theia, and the endpoint runtime binary, then triggers three brew builds and pushed them to brew. Resolving.

**Closed as completed by nickboldt** 2019-10-30 22:20 UTC
Labels: severity/P1, area/editor/theia
