### ISSUE TITLE
Update golang sidecar to use newer VSCode extension

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#16428] opened 2020-03-23 21:00 UTC
### Is your enhancement related to a problem? Please describe.
It would be nice to update https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/ms-vscode/go to use latest version 0.13.1. I tested this version https://raw.githubusercontent.com/AndrienkoAleksandr/che-plugin-registry/master/v3/plugins/ms-vscode/go/0.13.1/meta.yaml with che-machine-exec project and it works much better than 0.11.4

**Comment by ericwill** [comment] 2020-03-23 21:09
Looks like a duplicate of #16182. I see you are testing in a custom Dockerfile, did you have to make any changes to the sidecar container?

**Comment by AndrienkoAleksandr** [comment] 2020-03-24 07:24
> did you have to make any changes to the sidecar container

Interesting question... No I only applied some logs, for myself. But when you rebuild go dockerfile which uses a lot of `go get -u some-lib-repo`, any way you have chance to get not the same image, because go get -u grab 'latest ' package and since some time this latest package can be updated....

**Comment by ericwill** [comment] 2020-03-24 12:16
Interesting point about the image not always being the same, I didn't consider that. I'm going to close this one as a duplicate of #16182.

**Closed as completed by ericwill** 2020-03-24 12:16 UTC
Labels: kind/enhancement, area/languages
