### ISSUE TITLE
chectl: che.infra.kubernetes.namespace usage & how to create different namespace for each user

### ISSUE THREAD

**Issue by svkr2k** [eclipse-che/che#15440] opened 2019-12-10 07:52 UTC
* I started with che codebase tagged with v`7.5.1`. I set the value of `che.infra.kubernetes.namespace.allow_user_defined=true` in the file `assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties`.
* `che.infra.kubernetes.namespace.default=<username>-che`
* Created the che-server image
* Added the image to registry (ECR).
* Installed che using the following (used the che-server image from local ECR registry ):
`chectl server:start --platform=k8s --installer=helm --domain=mydomain.com --multiuser --tls --templates=./deploy --cheimage=<link-to-registry-image>/che-server:latest`

Then i created a workspace, I could see that the newly created workspace still gets listed under 'che' namespace ?

```
~/src/che-7.5.1$ sudo kubectl get pod --namespace che
NAME                                                          READY   STATUS              RESTARTS   AGE
che-6dc7f5bdb6-rjq7g                                          1/1     Running             0          11m
devfile-registry-66ccfbd48c-bt72s                             1/1     Running             0          11m
keycloak-8798c4c79-hlzpt                                      1/1     Running             0          11m
plugin-registry-678667956c-j6kqr                              1/1     Running             0          11m
postgres-565dc5956b-fsw9q                                     1/1     Running             0          11m
workspacerszr1uror3fbdtkv.che-jwtproxy-864cc8bc9c-ft4mw       1/1     Running             0          4m
workspacerszr1uror3fbdtkv.che-workspace-pod-dc6b78674-kx4vt   2/2     Running             0          4m
```

When i create a second workspace, the following error appears:
```
Error: Failed to run the workspace: "Failure executing: POST at: https://56.63.0.1/api/v1/namespaces/che/services. Message: services "my-rest-server" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=services, name=my-rest-server, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=services "my-rest-server" already exists, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={})."
```

I tested the same for `NodeJS 10` devfile also, this time the error message shown when 2nd workspace created was related to volume mounting error.

**Comment by svkr2k** [comment] 2019-12-10 07:56
@sleshchenko  @ibuziuk , @lkrejci, please help.

**Comment by sparkoo** [comment] 2019-12-10 08:34
@svkr2k editing `che.properties` don't have any effect as the value is overriden by helm chart https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/values.yaml#L65, but it should be default `<username>-che` so there is something wrong. 
 - Is the `cheWorkspacesNamespace` in your `deploy/kubernetes/helm/che/values.yaml` correct?
 - can you please check che deployment env variables for `CHE_INFRA_KUBERNETES_NAMESPACE` and `CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT`
 - please check `che` configmap for same variables

**Comment by svkr2k** [comment] 2019-12-10 08:48
`cheWorkspacesNamespace` in `deploy/kubernetes/helm/che/values.yaml` is:
`cheWorkspacesNamespace: "<username>-che"`

**Comment by svkr2k** [comment] 2019-12-10 09:00
Here are some env variables that i could see within the theia ide container:
`CHE_WORKSPACE_NAMESPACE=admin`
`CHE_WORKSPACE_NAME=wksp-cy1q`
`CHE_WORKSPACE_ID=workspacew105x6mavx71e0k7`

**Comment by sparkoo** [comment] 2019-12-10 10:16
I've reproduced it locally. The value set in configmap is `che`.
```
[~/dev/che] (b9256eb439 ✘)✹✭ λ kubectl describe cm che -n che | grep -A 2 NAMESPACE
CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT:
----
che
--
CHE_INFRA_KUBERNETES_NAMESPACE:
----
che
```
If I run helm command directly, it is correct. My bet is on chectl.

**Comment by sparkoo** [comment] 2019-12-10 10:25
this would be the issue https://github.com/che-incubator/chectl/blob/master/src/tasks/installers/helm.ts#L326

**Comment by svkr2k** [comment] 2019-12-11 02:45
Thank you, @sparkoo , you are right. I too noticed the the following line setting 'che' namespace for all workspaces:
https://github.com/che-incubator/chectl/blob/97b31fbf7cf0d5f21432ffc81c8d7fc33ef69f51/src/tasks/installers/helm.ts#L328

**Comment by sparkoo** [comment] 2019-12-11 06:11
@svkr2k yes, you can either
 - deploy directly with helm
 - deploy with chectl and update configmap vars
 - deploy with chectl and add deployment env vars to container

The doc what vars to set is here https://github.com/eclipse/che-docs/blob/master/src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc. You want _One namespace per user strategy_. And please be aware that `CHE_INFRA_KUBERNETES_NAMESPACE` is legacy variable and should be unset.

Let me know if you need further help with setting this.

**Comment by svkr2k** [comment] 2019-12-11 08:01
Thank you very much, @sparkoo .
I tried deploy directly with helm.

```helm upgrade --install che --force --namespace che --set global.cheDomain=xpressbeta.com --set 'global.cheWorkspacesNamespace=<username>-che' --set global.ingressDomain=xpressbeta.com --set cheimage=879521958254.dkr.ecr.us-east-1.amazonaws.com/testorg/che-server:latest -f /home/ubuntu/src/che-7.5.1/deploy/kubernetes/helm/che/values/tls.yaml -f /home/ubuntu/src/che-7.5.1/deploy/kubernetes/helm/che/values/multi-user.yaml /home/ubuntu/src/che-7.5.1/deploy/kubernetes/helm/che1/
Release "che" does not exist. Installing it now.
NAME:   che
E1211 07:57:50.038470    5953 portforward.go:372] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:38798->127.0.0.1:56966: write tcp4 127.0.0.1:38798->127.0.0.1:56966: write: broken pipe
LAST DEPLOYED: Wed Dec 11 07:57:49 2019
NAMESPACE: che
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME  AGE
che   1s

==> v1/Deployment
NAME              AGE
che               1s
devfile-registry  1s
keycloak          1s
plugin-registry   1s
postgres          1s

==> v1/PersistentVolumeClaim
NAME           AGE
keycloak-data  1s
keycloak-log   1s
postgres-data  1s

==> v1/Pod(related)
NAME                               AGE
che-6c96674bc7-4shzc               0s
devfile-registry-66ccfbd48c-z2mfv  0s
keycloak-8798c4c79-vcnb5           0s
plugin-registry-678667956c-jrx5w   0s
postgres-565dc5956b-sm8mt          0s

==> v1/Role
NAME                   AGE
che-endpoints-monitor  1s

==> v1/Service
NAME              AGE
che-host          1s
devfile-registry  1s
keycloak          1s
plugin-registry   1s
postgres          1s

==> v1/ServiceAccount
NAME          AGE
che           1s
che-keycloak  1s

==> v1beta1/ClusterRoleBinding
NAME                         AGE
che-che-clusterrole-binding  1s

==> v1beta1/Ingress
NAME              AGE
che-ingress       1s
devfile-registry  1s
keycloak-ingress  1s
plugin-registry   1s

==> v1beta1/RoleBinding
NAME                       AGE
che-keycloak-role-binding  1s
```

**Comment by svkr2k** [comment] 2019-12-17 11:29
Hi @sparkoo , thank you.
Could you please let me knoe the environment variable for "persistent volumes access mode" ?
Is it CHE_INFRA_KUBERNETES_PVC_ACCESS_MODE ?
I cant see this anywhere in che codebase?

**Comment by sparkoo** [comment] 2019-12-17 13:10
@svkr2k looks like you're missing one `_`, it should be `CHE_INFRA_KUBERNETES_PVC_ACCESS__MODE`

**Comment by svkr2k** [comment] 2019-12-17 17:01
Thank you, @sparkoo 
But, sorry, is this available in master branch or any other branch?

**Comment by svkr2k** [comment] 2019-12-17 19:32
Here are the latest changes:

```
$ kubectl describe cm che -n che | grep -A 2 NAMESPACE
CHE_INFRA_KUBERNETES_NAMESPACE:
----

CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT:
----
<username>-che
```

In `che.properties`:
```
che.infra.kubernetes.pvc.strategy=common
che.infra.kubernetes.pvc.access_mode=ReadWriteMany
che.infra.kubernetes.pvc.wait_bound=false
```

In `che-7.5.1/deploy/kubernetes/helm/che/templates/configmap.yaml`:
```
  CHE_INFRA_KUBERNETES_NAMESPACE: ""
  CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT: "<username>-che"
```

The following error is shown:
```
pod has unbound immediate PersistentVolumeClaims (repeated 2 times)
Error: Failed to run the workspace: "Plugins installation process failed. Error: Unrecoverable event occurred: 'FailedScheduling', 'pod has unbound immediate PersistentVolumeClaims (repeated 2 times)', 'workspacefhb83oznt9t0yt96.che-plugin-broker'"
```

**Comment by svkr2k** [comment] 2019-12-19 04:34
Updated the previous comment : https://github.com/eclipse/che/issues/15440#issuecomment-566714454

**Comment by svkr2k** [comment] 2019-12-19 04:37
Additional details:
```
$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                        STORAGECLASS   REASON   AGE
pvc-5bf1584a-2217-11ea-acba-029ec662a75d   1Gi        RWO            Delete           Bound    r1-che/claim-che-workspace   gp2                     13m
pvc-f63b8b0f-2216-11ea-acba-029ec662a75d   1Gi        RWO            Delete           Bound    che/postgres-data            gp2                     16m
pvc-f63b93f7-2216-11ea-acba-029ec662a75d   1Gi        RWO            Delete           Bound    che/keycloak-data            gp2                     16m
pvc-f63b9604-2216-11ea-acba-029ec662a75d   1Gi        RWO            Delete           Bound    che/keycloak-log             gp2                     16m```

**Comment by svkr2k** [comment] 2019-12-19 07:43
@sparkoo , @tolusha , your opinions please ...
thanks in advance.

**Comment by svkr2k** [comment] 2019-12-20 03:31
Hi @tolusha , it would be very helpful if this issue can be added to [sprint/current-sprint](https://github.com/eclipse/che/labels/sprint%2Fcurrent-sprint). I'm eagerly waiting for a solution for this. It would be nice if i can get some additional support on this.
I apologize for interrupting.

**Comment by sparkoo** [comment] 2019-12-20 06:31
@svkr2k I'm a bit lost here. We've identified an issue with chectl. Then you had issue with waiting for PVC and now issue with starting workspace (`services "my-rest-server" already exists`) ? Can we have this issue for chectl and create new issues for others?

Btw I'm getting 404 for the second plugin in your devfile in https://github.com/eclipse/che/issues/15440#issuecomment-566714454

**Comment by svkr2k** [comment] 2019-12-20 07:37
Sorry, @sparkoo , thank you for the heads up ! i had the other questions while trying to figure out a solution for the my goal, that is, "create one workspace per user". I shall go ahead and remove unncessary comments and shall move them to a separate issue if required.

**Comment by sparkoo** [comment] 2019-12-20 08:29
@svkr2k don't get me wrong. It's great that you've identified the problems and thank you for that. We just need to keep scope of one github issue clear, so it can be properly triaged and planned. If we find new issue during discussion, we should create new one so it can be again properly triaged.

To limit number of workspaces per user, there is `che.limits.user.workspaces.count` property https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties#L56

**Comment by sparkoo** [comment] 2020-02-03 17:10
fixed by https://github.com/che-incubator/chectl/pull/482

**Closed as completed by sparkoo** 2020-02-03 17:10 UTC
Labels: kind/bug, severity/P1, area/chectl, area/install
