### ISSUE TITLE
Support/Document an Easy to Use "Open in Che" button for GitHub/GitLab

### ISSUE THREAD

**Issue by murphye** [eclipse-che/che#16731] opened 2020-04-23 16:02 UTC
### Is your enhancement related to a problem? Please describe.
GitPod has a popular feature called "Open in GitPod" 
https://github.com/gitpod-io/gitpod

### Describe the solution you'd like
An equivalent "Open in Che" button. Here is a makeshift example using Che icon:

`[![Open in Che](https://www.eclipse.org/che/images/ico/32x32.png) Open in Che](https://che.openshift.io/dashboard/#/load-factory/?url=https://github.com/murphye/quarkus-quickstarts/tree/master/getting-started`

Demo:
https://github.com/murphye/quarkus-quickstarts/blob/master/getting-started/README.md

### Describe alternatives you've considered
None

### Additional context
GitPod has a shorter/simpler URL would would be less error prone:

`[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/<org>/<repo>)`

example:

`[![Open in Che](https://che.openshift.io/button/open-in-che.svg)](https://che.openshift.io/#https://github.com/<org>/<repo>)`

This shortened URL could simply redirect to the full URL (see demo example).

**Comment by murphye** [comment] 2020-04-23 16:14
Suggest alternative buttons as well, such as:

- Open in Che
- Open in CodeReady Workspaces
- Open in OpenShift

**Comment by benoitf** [comment] 2020-04-23 16:14
@murphye 
it's already available: 

[![Contribute](https://che.openshift.io/factory/resources/factory-contribute.svg)](https://che.openshift.io/f?url=https://github.com/murphye/quarkus-quickstarts)

or with markdown not rendered:
```markdown
[![Contribute](https://che.openshift.io/factory/resources/factory-contribute.svg)](https://che.openshift.io/f?url=https://github.com/murphye/quarkus-quickstarts)
```

**Comment by murphye** [comment] 2020-04-23 16:15
@benoitf Where is this documented? I did search and could not find it. Is there missing doc?

**Comment by murphye** [comment] 2020-04-23 16:25
Also, it would be nice if the button was more explicit. Having "Open with" would provide better context for what the button does.

**Comment by murphye** [comment] 2020-04-23 16:28
FYI, I found a doc:
https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/1.0/html/administration_guide/administering_workspaces#creating_factories

Under `8.21.7.10. Repository badging`

**Comment by benoitf** [comment] 2020-04-23 16:29
@themr0c do we have that in current docs ? or is it something that has been lost ?

**Comment by benoitf** [comment] 2020-04-23 16:33
@murphye ok basically we've a badge design and you're asking for a "button"

**Comment by murphye** [comment] 2020-04-23 16:35
I think so. See the GitPod button. Much more clear what it does:

<img width="158" alt="Screen Shot 2020-04-23 at 12 34 21 PM" src="https://user-images.githubusercontent.com/643097/80124809-ccf13000-855e-11ea-99f9-e32f368d15f2.png">

**Comment by benoitf** [comment] 2020-04-23 16:51
yes they have two options: badges and buttons

**Comment by murphye** [comment] 2020-04-23 16:59
Also interesting to note that CodeReady Workspaces has an alternate label/icon.

<img width="1272" alt="Screen Shot 2020-04-23 at 12 56 22 PM" src="https://user-images.githubusercontent.com/643097/80127109-de880700-8561-11ea-9c2b-a2a11b6ab957.png">

**Comment by themr0c** [comment] 2020-04-24 09:41
@benoitf All the factories docs has not been ported to che-7. For a while I understood that it was a che-6 specific feature. Seems it is not, and we will have to plan something new (including what is still relevant from the old bits).

**Comment by ibuziuk** [comment] 2020-04-27 12:00
looks like a good idea for documenting this feature explicitly in the che-docs  - https://www.eclipse.org/che/docs/che-7/introduction-to-eclipse-che/ setting P1 and assigning to the docs team cc: @rkratky

**Comment by l0rd** [comment] 2020-04-28 09:07
We should create a new badge and button. @beaumorley do you have any recommendation? Do you think you can help us with that?

**Comment by tomgeorge** [comment] 2020-08-05 18:59
Can this be worked on with the current "Developer Workspace" button or should we wait until we have an "Open in Che" button?

**Comment by gorkem** [comment] 2020-08-06 02:24
@tomgeorge What do you plan to work on ? Document updates? I see 3 items here.

1. Document update
2. Renewed badge/button
3. easier URL, remove error prone `f=url`

**Comment by benoitf** [comment] 2020-08-06 06:58
@tomgeorge you can use current button for the documentation.

**Comment by tomgeorge** [comment] 2020-08-06 14:21
@gorkem, for documentation, specifically.  Thanks @benoitf

**Comment by l0rd** [comment] 2020-08-12 16:28
@tomgeorge the PR got merged but I get a 404 right now:

<img width="557" alt="image" src="https://user-images.githubusercontent.com/606959/90041378-7fddc900-dcc9-11ea-8ee0-7402d0bbba1b.png">

I had a similar problem and I suspect that that's the cause https://github.com/eclipse/che-docs/pull/1455/files#r469386825

**Comment by tomgeorge** [comment] 2020-08-12 16:59
opened https://github.com/eclipse/che-docs/pull/1462 to fix the 404

**Comment by ibuziuk** [comment] 2021-01-19 09:49
@tomgeorge even though the PR got merged I still can not find the instructions under the `End-user Guide` ? is it expected cc: @themr0c

**Comment by ibuziuk** [comment] 2021-01-19 16:08
Ok, looks like the relevant documentation is here https://www.eclipse.org/che/docs/che-7/end-user-guide/workspaces-overview/#using-a-badge-to-link-to-workspaces_che 
Closing

**Closed as completed by ibuziuk** 2021-01-19 16:08 UTC
Labels: kind/task, severity/P1, area/doc
