### ISSUE TITLE
Workspace is not starting when enabling VSCode Editor

### ISSUE THREAD

**Issue by ChiragDosi** [eclipse-che/che#15576] opened 2019-12-26 13:53 UTC
Hello Everyone,

I am new to eclipse and i configured the eclipse from below link:

https://www.eclipse.org/che/docs/che-7/deploying-che-on-kubernetes-on-aws/

I want to create two workspaces one for backend code and one for frontend code, on frontend workspace i need to install VSCode Editor but when go to editors and switch on the toggle then applying configuration gives error.
![Screenshot 2019-12-25 at 11 49 27 PM](https://user-images.githubusercontent.com/33427501/71478307-eedae000-2814-11ea-9571-0e097ca5c55b.png)

I tried to disable the VSCode editor but still its not starting because che-theia plugin is turned on, but when i turn off both che-theia plugin and vscode then workspace starts. When i disable all plugins and turn on only VSCode Editor in editors then also its not working.

Kindly please let me know how i can use VSCode editor for my workspace.

Thanks & Regards

**Comment by tolusha** [comment] 2019-12-26 15:49
I guess you try to mount `/project` path twice.

**Comment by skabashnyuk** [comment] 2019-12-26 16:17
@ChiragDosi thanks for this report. Can you please provide a devfile to reproduce this bug?

**Comment by ChiragDosi** [comment] 2019-12-26 17:07
> I guess you try to mount `/project` path twice.

Thanks for the reply @tolusha, i had even tried to recreate the workspace but still getting the same error.

**Comment by ChiragDosi** [comment] 2019-12-26 17:09
> @ChiragDosi thanks for this report. Can you please provide a devfile to reproduce this bug?

@skabashnyuk thanks for the reply, kindly please check below the devfile configuration:
![Screenshot 2019-12-26 at 10 38 04 PM](https://user-images.githubusercontent.com/33427501/71484033-708c3700-2830-11ea-9b59-c6c5560ef58c.png)

**Comment by skabashnyuk** [comment] 2019-12-26 17:37
@ChiragDosi can you please
 - try to run this workspace with the same devfile but with removed completely cheEditor section. Just to make sure your installation works fine.
- Can you provide meta.yaml of cdr/code-server/latest ? Does it in sync with https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/eclipse/che-theia/7.6.0/meta.yaml#L59-L61 ?

**Comment by ChiragDosi** [comment] 2019-12-26 17:41
@skabashnyuk I tried your suggestion and when i removed the che editor section workspace is starting fine. Sorry as i am very new to Eclipse so can you please let me know where i can find the meta.yaml file ??

**Comment by skabashnyuk** [comment] 2019-12-26 19:19
>Sorry as i am very new to Eclipse so can you please let me know where i can find the meta.yaml file ??

- Are you running upstream che or customized version?
- ` cdr/code-server/latest` is a editor id. Line 17 in your devfile. I want to see it mata.yaml. If I'll know the way you install Che  I may provide your additional instructions on how to get it url. Byt default it deployed alongside with che-server

For example `che.openshift.io` uses this one `https://che-plugin-registry.openshift.io/v3/plugins/` as a plugin registry.  You can find Theia based editor definition here https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/eclipse/che-theia/7.6.0/meta.yaml

**Comment by ChiragDosi** [comment] 2019-12-27 06:47
@skabashnyuk i have installed and configured che using below link:

https://www.eclipse.org/che/docs/che-7/deploying-che-on-kubernetes-on-aws/#preparing-the-aws-system-for-installing-che_deploying-che-on-kubernetes-on-aws

Also where i can find the meta.yaml file ??

**Comment by skabashnyuk** [comment] 2019-12-27 09:05
@ChiragDosi that's strange. I can't find any reference `cdr/code-server/latest` in https://www.eclipse.org/che/docs/che-7/deploying-che-on-kubernetes-on-aws/#preparing-the-aws-system-for-installing-che_deploying-che-on-kubernetes-on-aws  why did you decide to add it?

**Comment by gazarenkov** [comment] 2019-12-28 13:46
@skabashnyuk 
it simple reproducible on che.osio when I try to put any accessible version of 'code-server (cdr publisher)' editor.
FWIW there are 3 versions currently available (latest, next, 2.1523-vsc1.38.1),
I believe that's where theirs metainfo hosted: https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/cdr/code-server

**Comment by skabashnyuk** [comment] 2019-12-30 13:02
looks like a known issue https://github.com/eclipse/che-plugin-registry/pull/285

**Comment by amisevsk** [comment] 2020-01-06 23:36
Should be resolved by https://github.com/eclipse/che-plugin-registry/pull/305, which should be included in 7.6.0, @ChiragDosi which Che version are you deploying and which version of the editor are you using in your workspace?

**Comment by ChiragDosi** [comment] 2020-01-08 15:29
Hello @amisevsk i am using below version of che
chectl/7.6.0 linux-x64 node-v10.18.0

**Comment by ChiragDosi** [comment] 2020-01-08 15:30
> @ChiragDosi that's strange. I can't find any reference `cdr/code-server/latest` in https://www.eclipse.org/che/docs/che-7/deploying-che-on-kubernetes-on-aws/#preparing-the-aws-system-for-installing-che_deploying-che-on-kubernetes-on-aws why did you decide to add it?

I found only this link to configure Eclipse with Kubernetes fo followed this, Kindly please let me know if i have done anything wrong as this is new for me.

**Comment by ChiragDosi** [comment] 2020-01-09 14:53
As i can see that its exporting config from s3 (as per the blog which i followed) and in the config file memory is defined to only 100 MB so now the issue is that when i am trying to validate the cluster after editing the memory to 2GB the cluster is not starting because its deleting previous AWS master instance and in config master ip is assigned to previous instance's ip so it keeps giving time out error because that previous instance is terminated. How can you i resolve this issue if anyone can help me out in this ?? Either we need to define the memory while creating cluster which i dont know how we can do that or we can edit the cluster without restarting the cluster.

**Comment by ChiragDosi** [comment] 2020-01-20 18:12
can anyone suggest please ?? as i have changed the configuration as well and increased the memory.

**Comment by skabashnyuk** [comment] 2020-04-02 06:32
As @amisevsk said https://github.com/eclipse/che/issues/15576#issuecomment-571363032 this should be fixed. Let me know if it's not working for you

**Closed as completed by skabashnyuk** 2020-04-02 06:32 UTC
Labels: kind/question, status/info-needed
