### ISSUE TITLE
eclipse/che-theia:next still contains @theia/cpp extension

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#14555] opened 2019-09-16 05:59 UTC
### Describe the bug

`eclipse/che-theia:next` still contains @theia/cpp extension that was excluded in this commit [1]

[1] https://github.com/eclipse/che-theia/commit/992a0595e15d35e02b07776ed21bff381ba6d5b7

### Steps to reproduce

1. `docker pull eclipse/che-theia:next` 
2. go into the container
3. 
```bash
$ ls /home/theia/node_modules/@theia/ | grep cpp
> cpp
```

### Expected behavior
`@theia/cpp` extension shouldn't be present

### Additional context
`eclipse/che-theia:latest` - doesn't contain the extension
if build   `eclipse/che-theia:next` locally then `@theia/cpp`  doesn't exist either

### Is needed for
https://github.com/eclipse/che/issues/13698

**Comment by tsmaeder** [comment] 2019-09-25 07:07
Raising priority: we can't release cpp support without this.

**Comment by benoitf** [comment] 2019-09-25 07:09
the issue is that the PR can't be merged as happy path is failing to unrelated issues
https://github.com/eclipse/che-theia/pull/441

**Comment by benoitf** [comment] 2019-09-25 07:10
https://github.com/eclipse/che-theia/pull/449 should unblock

**Comment by mmorhun** [comment] 2019-09-26 06:09
Done

**Closed as completed by mmorhun** 2019-09-26 06:09 UTC
Labels: kind/bug, severity/P1, area/editor/theia
