### ISSUE TITLE
[Language server] The Apache Camel server log file is displayed in the Project Explorer and has "project" status

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#10731] opened 2018-08-10 11:13 UTC
**Reproduction Steps:**
1. Create workspace from **Java** stack with any project.
2. Enable **Apache Camel** language server and start the workspace.
3. Open project and create "**camel.xml**" file.

**Actual result:**
 "**log-camel-lsp.out**" file of **Apache Camel** language server  is displayed in the **Project Explorer** and has "project" status.
 
**Che version**: 6.10.0
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screenshot:**
![selection_075](https://user-images.githubusercontent.com/7760565/43954880-ce4d0304-9ca6-11e8-98bd-ff69baaf8bc1.png)

**Screencast:**
![screencast-172 19 20 234-8080-2018 08 10-14-06-43](https://user-images.githubusercontent.com/7760565/43954884-d1804ffe-9ca6-11e8-8f20-6b3c74e594e6.gif)

**Comment by eivantsov** [comment] 2018-08-12 05:44
Closed as a duplicate of https://github.com/eclipse/che/issues/10586

@vparfonov it makes sense to take it to a sprint

**Closed as completed by eivantsov** 2018-08-12 05:44 UTC
Labels: kind/bug, severity/P2
