### ISSUE TITLE
Importing several private projects in a single devfile fails

### ISSUE THREAD

**Issue by rromannissen** [eclipse-che/che#18494] opened 2020-12-01 10:00 UTC
### Describe the bug

I have tried importing a devfile with multiple projects stored in private GitHub repositories using the /f?url= API. The result is that Che fails to clone the repositories without even prompting for the credentials. Only the password request for the last repository is prompted (without previously asking for the user):

![Screenshot from 2020-12-01 10-38-09](https://user-images.githubusercontent.com/15966456/100723957-a5025e80-33c2-11eb-8199-fd1eca009373.png)

After entering the right password, that last clone fails as well and the projects list ends up empty:

![Screenshot from 2020-12-01 10-49-22](https://user-images.githubusercontent.com/15966456/100724295-00cce780-33c3-11eb-9a8d-c292a6173a84.png)

The devfile used to reproduce this error is the following:

```
apiVersion: 1.0.0
metadata:
  name: order-management
projects:
- name: gateway
  source:
    type: git
    location: https://github.com/rromannissen/gateway-crw.git
    branch: master
- name: orders
  source:
    type: git
    location: https://github.com/rromannissen/orders-crw.git
    branch: master
- name: inventory
  source:
    type: git
    location: https://github.com/rromannissen/inventory-crw.git
    branch: master
- name: customers
  source:
    type: git
    location: https://github.com/rromannissen/customers-crw.git
    branch: master
```

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

Che-Theia@5e48d39 using Theia@e2098321a in https://che.openshift.io and Che-Theia@4587314 using Theia@eb1136b11 in CodeReady Workspaces in OCP 4.6.4.

### Steps to reproduce

The devfile used to reproduce this error is the following:

```
apiVersion: 1.0.0
metadata:
  name: order-management
projects:
- name: gateway
  source:
    type: git
    location: https://github.com/rromannissen/gateway-crw.git
    branch: master
- name: orders
  source:
    type: git
    location: https://github.com/rromannissen/orders-crw.git
    branch: master
- name: inventory
  source:
    type: git
    location: https://github.com/rromannissen/inventory-crw.git
    branch: master
- name: customers
  source:
    type: git
    location: https://github.com/rromannissen/customers-crw.git
    branch: master
```

Just import it using the /f?url= API.

### Expected behavior

Che asks for the credentials of each repository and executes the clone correctly for all projects.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

Reproduced in https://che.openshift.io and CodeReady Workspaces 2.5.0 in OCP 4.6.4.

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [x] OperatorHub
   - [ ] I don't know

OperatorHub for CodeReady Workspaces 2.5.0 in OCP 4.6.4. 

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify)
   - [ ] other: please specify

Reproduced in https://che.openshift.io and CodeReady Workspaces 2.5.0 in OCP 4.6.4.

**Comment by skabashnyuk** [comment] 2020-12-01 11:22
Yes. Looks like UX is not ideal. 
From a technical POV, you can mount GitHub personal access token as described here. https://www.eclipse.org/che/docs/che-7/end-user-guide/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/#mounting-a-git-credential-store-into-a-workspace-container_mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container

**Comment by skabashnyuk** [comment] 2020-12-01 11:25
or this way https://www.eclipse.org/che/docs/che-7/end-user-guide/version-control/#accessing-a-git-repository-via-ssh_version-control

**Comment by skabashnyuk** [comment] 2020-12-01 11:32
@l0rd @vinokurig @mshaposhnik 
please correct me if I'm wrong. In an ideal world, Theia could look in git.config/.ssh folder depending on git configuration and could initial necessary processes or correctly inform the user about expected actions. Or we could move that to the factory resolution step before Thia. I'm not sure what Is best. WDYT

**Comment by rromannissen** [comment] 2020-12-01 12:24
> Yes. Looks like UX is not ideal.
> From a technical POV, you can mount GitHub personal access token as described here. https://www.eclipse.org/che/docs/che-7/end-user-guide/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/#mounting-a-git-credential-store-into-a-workspace-container_mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container

As you said, that solves the problem from a technical POV, but that wouldn't be an option for developers without knowledge about Kubernetes. We are evaluating Che/CRW as the standard development platform for customers with several hundreds of developers with various levels of knowledge/experience with Kubernetes. In large companies, development flows are usually abstracted from the platform for developers, and since Che would be aimed to replace local development environments, Kubernetes knowledge shouldn't be a requirement to use it.

Having this implemented in the UI would greatly ease adoption for that kind of companies, as private repositories are the usual scenario there.

**Comment by ericwill** [comment] 2020-12-01 14:09
This should have been fixed (at least for HTTPS) in https://github.com/eclipse/che/issues/16401

We can investigate next sprint.

**Comment by skabashnyuk** [comment] 2020-12-02 08:56
@ericwill wdyt about https://github.com/eclipse/che/issues/18494#issuecomment-736468353? At which stage, we should validate the existence of ssh keys or git-config?

**Comment by l0rd** [comment] 2020-12-02 11:31
> @l0rd @vinokurig @mshaposhnik
> please correct me if I'm wrong. In an ideal world, Theia could look in git.config/.ssh folder depending on git configuration and could initial necessary processes or correctly inform the user about expected actions. Or we could move that to the factory resolution step before Thia. I'm not sure what Is best. WDYT

@skabashnyuk agreed. In Theia there should be a git authentication helper that looks at git config or ssh keys before the clone starts and makes things work if it find them. Prompt the user otherwise. But for GitHub that flow should already be possible if the admin adds GitHub as an identity provider in Keycloak. We have created an issue to [make it straightforward](https://github.com/eclipse/che/issues/18238).

@rromannissen a couple of considerations:

1) if you are using GitHub you may want to [enable GitHub authentication](https://www.eclipse.org/che/docs/che-7/administration-guide/configuring-authorization/#enabling-authentication-with-social-accounts-and-brokering_configuring-authorization). That will enable the VS Code GitHub authentication flow. Be aware that [we recently fixed a bug](https://github.com/eclipse/che-theia/pull/924) (will be included in CRW 2.5.1)

2) in a scenario with hundreds of Che/CRW users, I would want to provision the namespace for each of those users (including RAM/CPU quotas and LimitRanges of that namespace) before the user starts creating workspaces. Such a process will hopefully be automated (using [something like this](https://github.com/redhat-cop/namespace-configuration-operator) for instance) and secrets containing an automatically generated ssh key pair could be included in that same flow. With that flow, CRW/Che users should only upload the automatically generated public SSH key (sent to them via an email for example) on GitHub.

**Comment by ericwill** [comment] 2020-12-02 17:05
So I was under the impression that factories are gone, right? Doesn't that mean that:

> I have tried importing a devfile with multiple projects stored in private GitHub repositories using the **/f?url= API**.

is not supposed to work?

**Comment by l0rd** [comment] 2020-12-02 21:13
> factories are gone, right

@ericwill factories are not gone, it's just that it's not possible to manage factories from the dashboard anymore. The factory menu item has been removed and the corresponding API.

**Comment by ericwill** [comment] 2020-12-02 21:20
Ah, okay. So I investigated and it seems that the factory API portion of the workspace plugin in che-theia (`FactoryInitializer`) was removed (because there is no factory API anymore), which explains why this is failing. Currently we are checking credentials for cloning git repos, but if it's done via factory this check doesn't to happen.

I think this kind of answers your question @skabashnyuk.

I'll have someone from my team investigate further to see what our options are.

**Comment by sunix** [comment] 2020-12-28 11:06
I am having a look

**Comment by sunix** [comment] 2020-12-28 16:48
The problem is that the two `git clone` commands are executed in parallel.

I don't think it make sense to have the commands executed in sequential. Will probably ask the second one to wait for the result of the first one.

**Closed as completed** 2021-01-12 14:16 UTC
Labels: kind/bug, severity/P1, area/factory/server

**Comment by sunix** [comment] 2021-01-12 15:11
so finally implemented in https://github.com/eclipse/che-theia/pull/959:
- clone is still done in parallel but each prompt to the user is done in secquence.
- Only ask for credentials once if cloning several repos from the same host.
