### ISSUE TITLE
Support volumes for plugin components in devfile

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#14634] opened 2019-09-23 12:33 UTC
### Description
It is necessary to add an ability to set `volumes` for `chePlugin` component. For example it is needed to mount the `.m2` volume to the java plugin.

**Comment by svor** [comment] 2019-09-23 12:34
It is needed for https://github.com/eclipse/che/issues/13603

**Comment by svor** [comment] 2019-09-24 08:16
@skabashnyuk as for me devfile is better place to do that, where we can see whole configuration of workspace's containers and make changes in one place.

**Comment by skabashnyuk** [comment] 2019-09-24 08:29
>@skabashnyuk as for me devfile is better place to do that, where we can see whole configuration of workspace's containers and make changes in one place.

Apart from that, any other reasons?

CC @l0rd

**Comment by amisevsk** [comment] 2019-09-24 15:06
Related: PRs https://github.com/eclipse/che/pull/14539 and https://github.com/eclipse/che-plugin-broker/pull/74 are working on adding volumes to plugin `meta.yaml`s for issue https://github.com/eclipse/che/issues/13387.

**Comment by sleshchenko** [comment] 2019-09-25 08:32
Actually, volumes are already implemented for meta.yaml https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/eclipse/che-theia/next/meta.yaml#L59. And Oleksandr just works on ephemeral workspaces which are needed for another task.
So, @svor I think from maven plugin point of view it makes more sense to define it on `meta.yaml` level and then:
1. every user should not define it in each of their devfile.
2. I assume maven plugin expects maven volume in the exact path, it does not value that user should care about.

As about supporting volumes for plugin components - maybe it makes sense but at this stage we don't have any real-world purposes for them, so maybe we should delay this issue until we see any needs in it.

**Comment by metlos** [comment] 2019-11-06 11:40
Closing as duplicate of #13318.

**Closed as completed by metlos** 2019-11-06 11:40 UTC
Labels: kind/enhancement, severity/P1
