### ISSUE TITLE
Build of Che fails

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#7140] opened 2017-11-02 09:11 UTC
### Description
I tried to build Che today and it fails.
<details>
<summary>Logs</summary>

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.eclipse.che.plugin.dynamodule.DynaModuleListGeneratorMojoITest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.32 s <<< FAILURE! - in org.eclipse.che.plugin.dynamodule.DynaModuleListGeneratorMojoITest
[ERROR] compileGuiceListModule(org.eclipse.che.plugin.dynamodule.DynaModuleListGeneratorMojoITest)  Time elapsed: 0.025 s  <<< FAILURE!
java.lang.NoClassDefFoundError: org/eclipse/che/wsagent/server/WsAgentModule
        at org.eclipse.che.plugin.dynamodule.DynaModuleListGeneratorMojoITest.compileGuiceListModule(DynaModuleListGeneratorMojoITest.java:104)
Caused by: java.lang.ClassNotFoundException: org.eclipse.che.wsagent.server.WsAgentModule
        at org.eclipse.che.plugin.dynamodule.DynaModuleListGeneratorMojoITest.compileGuiceListModule(DynaModuleListGeneratorMojoITest.java:104)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   DynaModuleListGeneratorMojoITest.compileGuiceListModule:104 » NoClassDefFound ...
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.369 s
[INFO] Finished at: 2017-11-02T11:03:21+02:00
[INFO] Final Memory: 63M/1363M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (integration-test) on project che-core-dynamodule-maven-plugin: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/gaal/workspace/che/core/che-core-dynamodule-maven-plugin/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
</details>

**OS and version:**    

**Diagnostics:**

**Comment by benoitf** [comment] 2017-11-02 15:29
what was the `mvn` command line ?
m2 repository was existing one, empty one ?

**Comment by garagatyi** [comment] 2017-11-02 16:46
Mvn clean install
Regular ( non empty) state

**Comment by garagatyi** [comment] 2017-11-06 09:03
It is still reproducible today with the command `mvn clean install` and without cleaning `.m2`

**Comment by benoitf** [comment] 2017-11-06 09:07
it's hard to reproduce on my side (also on jenkins it's not reproduced as well)
what is your maven version ? and JDK ?

**Comment by garagatyi** [comment] 2017-11-06 09:09
```
$ mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T22:39:06+03:00)
Maven home: /opt/apache-maven-3.5.0
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.144-5.b01.fc25.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.12.9-200.fc25.x86_64", arch: "amd64", family: "unix"
```

**Comment by garagatyi** [comment] 2017-11-06 09:14
@benoitf It looks like modules in core should not be dependant on modules in wsagent. WDYT?

**Comment by RomanNikitenko** [comment] 2017-11-06 09:16
I can reproduce it on my machine too
``` $ mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T22:39:06+03:00)
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_131/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.11.5-200.fc25.x86_64", arch: "amd64", family: "unix"
```

**Comment by benoitf** [comment] 2017-11-06 09:17
ok I've almost same version of maven (3.5.2) and OracleJDK 8 151 (on macOS)

is that folder where you're compiling che has spaces ? or something different than on jenkins ci ?

**Comment by benoitf** [comment] 2017-11-06 09:19
@garagatyi AFAIK it's a `test` dependency to have a "real war" file, not a runtime dependency.

**Comment by garagatyi** [comment] 2017-11-06 09:20
IDK about specifics of Jenkins installation) 
My workdir is: `/home/gaal/workspace/che`
@benoitf even if it is a test dependency it looks like it might break graph of dependencies.

**Comment by benoitf** [comment] 2017-11-06 09:25
@garagatyi do you have same reactor order build than on
https://ci.codenvycorp.com/view/che6-ci/job/che-ci-che6/96/consoleFull ?

**Comment by benoitf** [comment] 2017-11-06 09:25
```
...
09:11:38 [INFO] Che Core :: Git Impl JGit
09:11:38 [INFO] Che Workspace Agent War Packaging
09:11:38 [INFO] Che Core :: API :: DynaModule maven plugin
...
```

**Comment by garagatyi** [comment] 2017-11-06 10:31
@benoitf yes, but wsagent packaging depends on plugins, so this is not a good practice to have such cyclic dependencies. Does it pass in offline mode?

**Comment by benoitf** [comment] 2017-11-06 10:36
AFAIK @garagatyi it's not cyclic (AFAIK maven would break the build if there is a cyclic dependency)
In offline mode it works as well as the graph of dependencies is correct.

**Comment by benoitf** [comment] 2017-11-06 10:38
We may think about creating a test war file as part of the test, but I'm not sure it's easy as well as it requires compilation of java code and build of the war file, etc

**Comment by garagatyi** [comment] 2017-11-06 10:39
It fails for me and @RomanNikitenko so I suppose it is buggy in any case.
And wsagent packaging depends on plugins but I don't see that plugins are in the reactor before wsagent packaging module. Can you elaborate on how this is supposed to work?

**Comment by benoitf** [comment] 2017-11-06 10:56
@garagatyi the ws-agent-core
https://github.com/eclipse/che/blob/master/wsagent/che-wsagent-core/pom.xml has no dependency on dynamodule plugin

it's used there by the plugin https://github.com/eclipse/che/blob/master/core/che-core-dynamodule-maven-plugin/pom.xml#L106-L112

and the plugin is used in assembly module when building the final wsagent war file
https://github.com/eclipse/che/blob/master/assembly/assembly-wsagent-war/pom.xml#L169-L171


so we have che-core-dynamodule-plugin depending on che-wsagent-core (two core dependencies)
and assembly depending on core parts

so there is no cyclic dependency, or strange behavior

**Comment by tolusha** [comment] 2017-11-06 12:23
I faced this issue too.

**Comment by RomanNikitenko** [comment] 2017-11-06 12:41
I tried to switch on maven 3.5.2 and java 1.8.152
```[roman@rnikitenko core]$ mvn --version
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T10:58:13+03:00)
Java version: 1.8.0_152, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_152/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.11.5-200.fc25.x86_64", arch: "amd64", family: "unix"
```

and build is still  

```Che Core :: API :: DynaModule maven plugin ......... FAILURE [  6.953 s]```

**Comment by skabashnyuk** [comment] 2017-11-06 12:58
I do have the same issue if che-wsagent-core downloaded from nexus, and I don't have it in the case when che-wsagent-core I build myself. Probably CI is working because of that too.

```
INFO] --- maven-dependency-plugin:3.0.1:copy (copy-dependencies) @ che-core-dynamodule-maven-plugin ---
[INFO] Configured Artifact: org.eclipse.che.core:che-wsagent-core:6.0.0-M2-SNAPSHOT:war
[INFO] Copying che-wsagent-core-6.0.0-M2-SNAPSHOT.war to /Users/sj/dev/src/codenvy/che/core/che-core-dynamodule-maven-plugin/target/local-repo/org/eclipse/che/core/che-wsagent-core/6.0.0-M2-SNAPSHOT/che-wsagent-core-6.0.0-M2-20171106.113405-25.war
[INFO]
````
Investigating. @benoitf  can you take a look how DynaModuleListGeneratorMojoTest.testWarFiles can find this war?

**Comment by benoitf** [comment] 2017-11-06 13:21
@skabashnyuk I will investigate that usecase but the original issue is `mvn clean install` meaning that all is build locally previously

**Comment by RomanNikitenko** [comment] 2017-11-06 13:30
```
[INFO] Che Parent ......................................... SUCCESS [  1.515 s]
[INFO] Che Core Parent .................................... SUCCESS [  0.046 s]
[INFO] Che Core :: Commons :: Parent ...................... SUCCESS [  0.056 s]
[INFO] Che Core :: Commons :: Annotations ................. SUCCESS [  2.821 s]
[INFO] Che Core :: Commons :: Java API extension classes .. SUCCESS [  5.434 s]
[INFO] Che Core :: API :: DTO ............................. SUCCESS [  6.964 s]
[INFO] Che Core :: Commons :: Json helpers ................ SUCCESS [  1.460 s]
[INFO] Che Core :: Commons :: Utilities for tests ......... SUCCESS [  2.103 s]
[INFO] Che Core :: Commons :: Dependency Injecting ........ SUCCESS [  3.365 s]
[INFO] Che Core :: Commons :: Scheduler service ........... SUCCESS [  2.104 s]
[INFO] Che Core :: API :: DTO Maven Plugin ................ SUCCESS [  1.466 s]
[INFO] Che Core :: API :: Core ............................ SUCCESS [ 15.282 s]
[INFO] Che Core :: Commons :: Auth ........................ SUCCESS [  0.331 s]
[INFO] Che Core :: Commons :: XML ......................... SUCCESS [  3.075 s]
[INFO] Che Core :: Commons :: Commons J2ee ................ SUCCESS [  1.653 s]
[INFO] Che Core :: Commons :: Mail sender ................. SUCCESS [  1.466 s]
[INFO] Che Core :: API :: TypeScript DTO maven plugin ..... SUCCESS [ 19.512 s]
[INFO] Che Agent Parent ................................... SUCCESS [  0.041 s]
[INFO] Che Core :: API :: Debug :: Shared ................. SUCCESS [  0.723 s]
[INFO] Che Core :: API :: Debug ........................... SUCCESS [  1.813 s]
[INFO] Che Core :: API :: Git :: Shared ................... SUCCESS [  0.521 s]
[INFO] Che Core :: API :: Model ........................... SUCCESS [  0.316 s]
[INFO] Che Master Parent .................................. SUCCESS [  0.026 s]
[INFO] Che Core :: API :: Workspace :: Shared ............. SUCCESS [  1.770 s]
[INFO] Che Core :: API :: Project Shared .................. SUCCESS [  1.733 s]
[INFO] Che Core :: DB ..................................... SUCCESS [  2.155 s]
[INFO] Che Core :: DB :: Vendor H2 ........................ SUCCESS [  0.271 s]
[INFO] Che Core :: SQL :: Schema .......................... SUCCESS [  0.067 s]
[INFO] Che Core :: API :: Account ......................... SUCCESS [  4.201 s]
[INFO] Che Core :: API :: Installer :: Shared ............. SUCCESS [  0.156 s]
[INFO] Che Core :: API :: Installer ....................... SUCCESS [  6.598 s]
[INFO] Che Core :: API :: System Shared ................... SUCCESS [  1.149 s]
[INFO] Che Core :: API :: System .......................... SUCCESS [  2.839 s]
[INFO] Che Core :: API :: SSH :: Shared ................... SUCCESS [  1.026 s]
[INFO] Che Core :: API :: User :: Shared .................. SUCCESS [  0.997 s]
[INFO] Che Core :: API :: User ............................ SUCCESS [  8.308 s]
[INFO] Che Core :: API :: SSH ............................. SUCCESS [  3.956 s]
[INFO] Che Core :: API :: Workspace ....................... SUCCESS [ 15.495 s]
[INFO] Che Core :: API :: Agent ........................... SUCCESS [  0.222 s]
[INFO] Che Core :: API :: Project ......................... SUCCESS [ 47.911 s]
[INFO] Che Core :: API :: Git ............................. SUCCESS [  5.217 s]
[INFO] Che Core :: API :: Language Server Shared .......... SUCCESS [  1.028 s]
[INFO] Che Core :: API :: Language Server Maven Plugin .... SUCCESS [  0.946 s]
[INFO] Che Core :: API :: Language Server ................. SUCCESS [ 10.768 s]
[INFO] Che Core :: API :: Authentication :: Shared ........ SUCCESS [  0.905 s]
[INFO] Che Core :: API :: OAuth ........................... SUCCESS [  1.660 s]
[INFO] Che Core :: SSH Key :: Server ...................... SUCCESS [  1.674 s]
[INFO] Che Core :: Git Impl JGit .......................... SUCCESS [  8.273 s]
[INFO] Che Workspace Agent War Packaging .................. SUCCESS [  1.387 s]
[INFO] Che Core :: API :: DynaModule maven plugin ......... FAILURE [  6.961 s]
[INFO] Che Core :: DB :: Vendor PostgreSQL ................ SKIPPED
[INFO] Che Core :: API :: Authentication .................. SKIPPED
```

**Comment by benoitf** [comment] 2017-11-06 13:40
@RomanNikitenko could you please list content of folder
```
$ ls core/che-core-dynamodule-maven-plugin/target/local-repo/org/eclipse/che/core/che-wsagent-core/6.0.0-M2-SNAPSHOT
```
when you're inside local clone folder of che ?

**Comment by RomanNikitenko** [comment] 2017-11-06 13:43
@benoitf 
```
[roman@rnikitenko che]$ ls core/che-core-dynamodule-maven-plugin/target/local-repo/org/eclipse/che/core/che-wsagent-core/6.0.0-M2-SNAPSHOT
che-wsagent-core-6.0.0-M2-SNAPSHOT.war
[roman@rnikitenko che]$
```
this one?

**Comment by benoitf** [comment] 2017-11-06 13:46
@RomanNikitenko yes this one thanks.

so in your case it's the expecting value. I've issue a fix when dependency is a snaphot one (issue of @skabashnyuk ) https://github.com/eclipse/che/pull/7206
but I would say in your case it won't fix the issue :-/

**Comment by benoitf** [comment] 2017-11-06 13:54
@RomanNikitenko @garagatyi @skabashnyuk 
BTW do you have the same error ?

@garagatyi error was in ITest while @skabashnyuk error was in testWarFiles inside the unit test

**Comment by skabashnyuk** [comment] 2017-11-06 13:59
https://github.com/eclipse/che/pull/7206 this fix my usecase.
Asked @garagatyi  to test his.

**Comment by benoitf** [comment] 2017-11-06 14:02
@skabashnyuk it seems it's another usecase so I would say it won't :-/ and I don't know how to reproduce it and the test from original error is not even linked to the che-wsagent-core package (only integration test is using it)

**Comment by garagatyi** [comment] 2017-11-06 14:07
@skabashnyuk @benoitf didn't help in my case

**Comment by benoitf** [comment] 2017-11-06 14:12
@garagatyi could you please do:
```
$ find target -name "MyDynamoduleTestModule.class"
```

in `core/che-core-dynamodule-maven-plugin` folder ?

**Comment by garagatyi** [comment] 2017-11-06 14:13
@benoitf @skabashnyuk [here](https://gist.github.com/garagatyi/1f8d19213716e84886c18d5f7cb8f231) is an output of `mvn clean install -rf :che-core-dynamodule-maven-plugin -X` on my machine.

**Comment by garagatyi** [comment] 2017-11-06 14:14
@benoitf 
<details>

```
✔  16:13 ~/workspace/che/core/che-core-dynamodule-maven-plugin [ avoid-timestamp-dependency-dynamodule | ⚑ 9 ] $ find target -name "MyDynamoduleTestModule.class"
target/test-projects/DynaModuleListGeneratorMojoTest_testWarFiles_project/classes/org/eclipse/che/dynamodule/MyDynamoduleTestModule.class
target/test-projects/DynaModuleListGeneratorMojoTest_testServiceLoaderGenerated_project/classes/org/eclipse/che/dynamodule/MyDynamoduleTestModule.class
target/test-projects/DynaModuleListGeneratorMojoTest_testModuleListGenerated_project/classes/org/eclipse/che/dynamodule/MyDynamoduleTestModule.class
✔  16:13 ~/workspace/che/core/che-core-dynamodule-maven-plugin [ avoid-timestamp-dependency-dynamodule | ⚑ 9 ] $ 
```
</details>

**Comment by benoitf** [comment] 2017-11-06 14:16
ok I see the problem now

**Comment by benoitf** [comment] 2017-11-06 14:18
I've added a commit on PR https://github.com/eclipse/che/pull/7206 that should fix your issue @garagatyi 

It's because your filesystem is not sorting by default with lexicographical order (while on my computer or on CI it is)

**Comment by benoitf** [comment] 2017-11-06 15:38
I'm closing the issue as I've merged PR that fix the current issue, feel free to reopen if you still have issue

**Closed as completed by benoitf** 2017-11-06 15:38 UTC
Labels: kind/bug, severity/blocker
