### ISSUE TITLE
Support snippets for VS Code extensions running in a Che Theia sidecar

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16502] opened 2020-03-31 16:21 UTC
### Describe the bug

In Java files, the code snippet (to generate try catch block) `try_catch` is not working

### Che version

 - [x] latest

### Steps to reproduce
1. Start a Java workspace with a Java project (any of the getting started)
2. Open a Java file
3. type `try` and `Ctrl+space` inside a method

### Expected behavior
Expected to have the `try_catch` like in VSCode:
![Selection_694](https://user-images.githubusercontent.com/650571/78050115-26a97480-737c-11ea-9666-87224fcedc61.png)

But had no `try_catch` code snippet :(
![Selection_695](https://user-images.githubusercontent.com/650571/78050280-5193c880-737c-11ea-8aab-9e0f05da57f7.png)

### Runtime
   - [x] Openshift 4.3 and che.openshift.io

**Comment by tsmaeder** [comment] 2020-04-01 08:19
FWIW, this works in Theia master with the latest built-ins.

**Comment by skabashnyuk** [comment] 2020-04-01 09:06
>FWIW, this works in Theia master with the latest built-ins.

@sunix can you test?

**Comment by sunix** [comment] 2020-04-01 09:11
> FWIW, this works in Theia master with the latest built-ins.

is Theia using the Red Hat Java vscode ext ?

**Comment by sunix** [comment] 2020-04-01 09:28
> @sunix can you test?

No I don't have Theia installed locally. I let the assignee test with Theia if it is needed.

**Comment by IveJ** [comment] 2020-04-01 10:20
Hi David,

Plz check che doc for specific details and try to upgrade as appropriately
or built your own custom image if necessary.

**Comment by sunix** [comment] 2020-04-25 12:15
Sorry guys but it is impossible to code without a minimum of snippet ... main is not working neither ....

**Comment by phaumer** [comment] 2020-05-28 17:09
I can confirm this bug as well. 

Code snippets that were defined via the VSIX package.json contributes.snippets array appear in Theia, but not Eclipse Che. For example the Red Hat Java VSIX defines two set of snippets. 
- One that is just listed in package.json does not work. 
- The other set that gets loaded via a VS Code CompletionItemProvider implementation does appear. 

Theia 1.0:
![image](https://user-images.githubusercontent.com/4391934/83171605-37037480-a0cb-11ea-99c2-95e8dd1f62b3.png)

Che 7.13.1
![image](https://user-images.githubusercontent.com/4391934/83171666-4e426200-a0cb-11ea-9659-1b22e85cb8cb.png)

**Comment by tsmaeder** [comment] 2020-07-16 12:17
Confirmed with vscode-java 0.62 in theia and vscode-java 0.63 in openshift.io.

**Comment by tsmaeder** [comment] 2020-07-16 13:12
The problem is that the package.json in vscode-java contributes snippets with a relative uri like so:

```
    "snippets": [
      {
        "language": "java",
        "path": "./snippets/java.json"
      }
    ],
```

The code in TheiaPluginScanner#readSnippets() constructs an URI from this like so:

```
uri: FileUri.create(path.join(pck.packagePath, contribution.path)).toString()
```
This file uri is supposed to refert to a location relative to where package.json of the vscode extension is located. This works fine when the package is installed in the same place as the Theia back end, but fails when the package is located in a sidecar container.

**Comment by tsmaeder** [comment] 2020-07-16 13:14
There are two ways we could fix this:

1. Leave the URI as it is, but bring the files to the container where they are expected (where the Theia back end is running)
2. Fix the generation of the URI: we already have a way of resolving sidecar-relative URI's.

My first aproach will be to fix the URI

**Comment by ArvinB** [comment] 2020-07-16 13:25
@tsmaeder I like your approach to fix the URI. Will you make this fix and how soon? We can assist by verifying.

**Comment by tsmaeder** [comment] 2020-07-17 08:36
I'm working on it.

**Comment by tsmaeder** [comment] 2020-07-17 09:31
Turns out the monaco-snippet-suggest-provider.ts uses the FileSystem class directly, not a Resource. Since our workaround is based on resource, it does not get applied. I guess the right thing to do would be to implement file system providers for plugin resources after https://github.com/eclipse-theia/theia/pull/7908/files is merged

**Comment by fbricon** [comment] 2020-07-20 13:58
the snippets defined in package.json are only used until the Language Server has started. After that, they're disabled and server-side snippets should take over. See https://github.com/redhat-developer/vscode-java/pull/1101

**Comment by PrasangAPrajapati** [comment] 2020-07-21 22:56
> There are two ways we could fix this:
> 
> 1. Leave the URI as it is, but bring the files to the container where they are expected (where the Theia back end is running)
> 2. Fix the generation of the URI: we already have a way of resolving sidecar-relative URI's.
> 
> My first aproach will be to fix the URI

In the 1st option, I want to know how can we get the full path where file has to be in order to resolve it ? I can see extension folder name has some unique string attach in between which is new every time. How can we get that from a different (sidecar) container ? for example: `ms-python.go.0.11.4.afbdfvxtsa.Go-0.11.4.vsix` where you can see auto-generated `afbdfvxtsa` in middle.

**Comment by tsmaeder** [comment] 2020-07-23 14:59
@PrasangAPrajapati no, that directory is random. And anyway...you'd have to copy it to the theia container somehow. I suggest waiting until we have the PR from @akosyakov merged and can fix it correctly. Hopefully some within 2 weeks.

**Comment by tsmaeder** [comment] 2020-08-03 14:41
A naive approach based on registering a vscode FileSystemProvider upon connection of a front end fails because snippet files are read before activation of the Java plugin. We'll have to do something more involved.

**Comment by benoitf** [comment] 2020-08-20 15:13
if this issue is also concerning upstream Eclipse Theia, please file an issue in upstream theia and link it back there.

**Comment by ArvinB** [comment] 2020-08-20 16:04
@benoitf We can test and do that. Thank you.

**Comment by nickboldt** [comment] 2021-01-08 21:48
doot doot doo... moving stuff to a more reasonable milestone... doot doot doo... paperwork makes the project better...

**Closed as completed** 2021-03-16 13:14 UTC
Labels: kind/bug, severity/P1, area/languages, new&noteworthy
