### ISSUE TITLE
Error: Failed to run the workspace: "Server 'theia' in container 'theia-idewbt' not available."

### ISSUE THREAD

**Issue by hari1992-web** [eclipse-che/che#16712] opened 2020-04-22 13:05 UTC
![Screenshot from 2020-04-22 18-28-46](https://user-images.githubusercontent.com/62592574/79985168-d54a5c00-84c7-11ea-83d4-d06000088633.png)
![Screenshot from 2020-04-22 18-34-11](https://user-images.githubusercontent.com/62592574/79985198-e1ceb480-84c7-11ea-8206-253f146f4abb.png)

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify)
   - [x] other: please specify

### Additional context

Press F5 or click here to try again.

Successfully assigned admin-che/workspacehm5h0it4rzshwgvd.che-plugin-broker to knode1

Pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.0.0"

Successfully pulled image "quay.io/eclipse/che-plugin-metadata-broker:v3.0.0"

Created container che-plugin-metadata-broker-v3-0-0

Started container che-plugin-metadata-broker-v3-0-0

Starting plugin metadata broker

List of plugins and editors to install
- redhat/java11/latest - Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support and more...
- eclipse/che-machine-exec-plugin/nightly - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse Che workspace containers.
- eclipse/che-theia/next - Eclipse Theia, get the latest release each day.

All plugin metadata has been successfully processed

Successfully assigned admin-che/workspacehm5h0it4rzshwgvd.gradle-574f9664fd-jwvwx to knode1

AttachVolume.Attach succeeded for volume "pvc-1faec432-5c9c-400b-ade9-aa047f317c65" 

Pulling image "quay.io/eclipse/che-jwtproxy:dbd0578"

Successfully pulled image "quay.io/eclipse/che-jwtproxy:dbd0578"

Created container verifier

Started container verifier

Pulling image "quay.io/eclipse/che-theia-endpoint-runtime-binary:next"

Successfully pulled image "quay.io/eclipse/che-theia-endpoint-runtime-binary:next"

Created container remote-runtime-injectorltb

Started container remote-runtime-injectorltb

Pulling image "quay.io/eclipse/che-plugin-artifacts-broker:v3.0.0"

Successfully pulled image "quay.io/eclipse/che-plugin-artifacts-broker:v3.0.0"

Created container che-plugin-artifacts-broker-v3-0-0

Started container che-plugin-artifacts-broker-v3-0-0

Starting plugin artifacts broker

Cleaning /plugins dir

Downloading plugin extensions

Downloading VS Code extension 1/2 for plugin 'redhat/java11/latest'

Downloading VS Code extension 2/2 for plugin 'redhat/java11/latest'

All plugin artifacts have been successfully downloaded

Pulling image "quay.io/eclipse/che-java11-gradle:7.11.0"

Successfully pulled image "quay.io/eclipse/che-java11-gradle:7.11.0"

Created container gradle

Started container gradle

Pulling image "quay.io/eclipse/che-sidecar-java:11-f76ca45"

Successfully pulled image "quay.io/eclipse/che-sidecar-java:11-f76ca45"

Created container vscode-java29g

Started container vscode-java29g

Pulling image "quay.io/eclipse/che-machine-exec:nightly"

Successfully pulled image "quay.io/eclipse/che-machine-exec:nightly"

Created container che-machine-exect2e

Started container che-machine-exect2e

Pulling image "quay.io/eclipse/che-theia:next"

Successfully pulled image "quay.io/eclipse/che-theia:next"

Created container theia-idewbt

Started container theia-idewbt

Error: Failed to run the workspace: "Server 'theia' in container 'theia-idewbt' not available."

**Comment by hari1992-web** [comment] 2020-04-22 13:06
Now iam facing error please any body know thanks in advance

**Comment by tolusha** [comment] 2020-04-22 14:28
There are already several issues with such an error.
It would be nice if you check them out and figure out if they are useful

**Comment by davidfestal** [comment] 2020-04-22 17:47
This might be a duplicate of issue https://github.com/eclipse/che/issues/16439

**Comment by hari1992-web** [comment] 2020-04-23 05:29
> This seems to be a duplicate of issue #16439 
i am unable to resolve that issue , I cant understand please any body help

**Comment by renatodelgaudio** [comment] 2020-04-23 15:42
Same issue here.
I have deployed the latest version of Eclipse Che 7.11, by using both chectl as well as the operator.
I have deployed it on Azure AKS, as well as on my bare metal home Kubernetes cluster.

Same outcome.
No matter what stack I choose, the startup always fails when it reach the point to start Theia.
I have tried multiple versions of Theia (7.10, latest, next).
Looking at the workspace pod status (kubectl get pods), when it reaches the status running (5/5 running, the Eclipse Che portal shows still the spinner of loading.

Looking at the logging of the theia container inside the pod ( e.g. kubectl logs -f workspacefhf4738h43 -c  theia-ide1ci) it shows no errors.  
Last logging message is INFO Deploy plugins list took: 7435.1 ms

After a while the log shows just the message "Received SIGTERM" and at the same time Eclipse Che portal shows the failure of launching the workspace.

**Comment by strongit** [comment] 2020-07-15 01:59
Same issue here.
#17391

Is there a solve way？

**Comment by haribabuboyapati** [comment] 2020-07-15 04:43
sudo chectl server:start --installer=helm --multiuser --platform=k8s --domain=172.17.250.1.nip.io --k8spodreadytimeout=300000 --k8spodwaittimeout=3000000 --workspace-pvc-storage-class-name=csi-hostpath-sc

use this command

**Comment by haribabuboyapati** [comment] 2020-07-15 04:48
how to plan this installed you are using local or cloud ???

**Comment by haribabuboyapati** [comment] 2020-07-15 04:49
please show me the installation command of eclipse che ???

**Comment by skabashnyuk** [comment] 2020-07-15 06:10
Closing as duplicate in favor of https://github.com/eclipse/che/issues/16439 and https://github.com/eclipse/che/issues/16451

**Closed as completed by skabashnyuk** 2020-07-15 06:10 UTC
Labels: kind/bug, area/editor/theia, status/duplicate

**Comment by skabashnyuk** [comment] 2020-07-15 08:39
According to the information from @tolusha  they made multiple
improvements in installation with tls that might fix this problem.
Our suggestion would be to try to test the latest release and let us know if this problem is still reproducible. In case if it
is reproducible please follow up the whole Github bug template
and let us know the necessary information on how to reproduce it.

**Comment by RenDhark-star** [comment] 2020-11-30 08:00
i got the same issue. Did anyone solve this?

**Comment by monaka** [comment] 2023-01-31 03:01
I got a similar issue and resolved.
In my case, my TLS certificate in `che` ConfigMap was out of date.
