### ISSUE TITLE
Build of Che nightly images failed on Codenvy CI 

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14569] opened 2019-09-17 09:00 UTC
### Describe the bug
Build of nightly images failed on Codenvy CI https://ci.codenvycorp.com/view/nightly-builds/job/all-che-docker-images-nightly/1162/console
```
Building remotely on ci-build-slave (skryzhny) in workspace /home/codenvy/workspace/all-che-docker-images-nightly
Cloning the remote Git repository
Cloning repository https://github.com/eclipse/che
ERROR: Failed to clean the workspace
java.io.IOException: Unable to delete '/home/codenvy/workspace/all-che-docker-images-nightly'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
...
Caused by: java.nio.file.FileSystemException: /home/codenvy/workspace/all-che-docker-images-nightly/dockerfiles/theia/e2e/logs/theia.log: Operation not permitted
```

`ci-build-slave` seems requires cleanup.

**Comment by l0rd** [comment] 2019-09-17 19:30
@dmytro-ndp @skryzhny I see that the nightly build job has run successfully since then. Does it mean that the issue has been fixed?

**Comment by dmytro-ndp** [comment] 2019-09-18 09:07
@skryzhny had already cleaned up *ci-build-slave* yesterday.

**Comment by skryzhny** [comment] 2019-09-18 10:04
It looks like cause not known, please investigate and fix properly.

**Comment by dmytro-ndp** [comment] 2019-09-18 10:26
@skryzhny: investigation requires access rights to add job config and slave, which I don't actually have.

**Comment by skryzhny** [comment] 2019-09-18 11:29
@dmytro-ndp so you are willing to fix this but only things that prevent you from fixing is luck of access?

**Comment by dmytro-ndp** [comment] 2019-09-18 11:55
You asked me to fix it, https://github.com/eclipse/che/issues/14569#issuecomment-532616349, but I can't do it at least because I don't have access rights. And, I can't promise to fix it even with access rights ;-)

**Comment by skryzhny** [comment] 2019-09-18 12:33
@dmytro-ndp you're set blocker for this issue, I'm assuming that you are interested in proper fixing this by preventing this from happening in the future. Am I right?

**Comment by dmytro-ndp** [comment] 2019-09-18 13:01
Yes, of course. And I am not along ;-)

**Comment by dmytro-ndp** [comment] 2019-09-18 15:25
@skryzhny: you are right, I and can propose a very simple fixup: to add `sudo rm -rf ${WORKSPACE}/dockerfiles` command to job's Post-build Actions.

**Comment by skryzhny** [comment] 2019-09-18 16:00
@dmytro-ndp you probably forgot that user has no `sudo`, so this won't work.

**Comment by dmytro-ndp** [comment] 2019-09-18 16:03
Aha, I forgot it. So, let's try to use `Delete workspace before build starts` option.

**Comment by benoitf** [comment] 2019-11-20 10:53
closing as it was not reproduced

**Closed as completed by benoitf** 2019-11-20 10:53 UTC
Labels: severity/blocker
