### ISSUE TITLE
PHP autocomplete doesn't work with latest Intelephense

### ISSUE THREAD

**Issue by SpicySpaceman** [eclipse-che/che#17493] opened 2020-07-27 17:29 UTC
### Describe the bug

Auto-completion is not working anymore/only working partially.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.15.0 (Che-Theia next https://github.com/eclipse/che-theia/commit/2f11124)

### Steps to reproduce
1. Set up a Symfony 5 project
2. Use the latest Intelephense version (1.5.3, also reproduced with 1.4.0)
3. Edit some PHP/SCSS files
4. In a controller if I want to write `Response` as return type, there will be suggestions for `R`, but if I type `Re`* or more the suggestions disappear. If I want to write `RediretResponse` there will be suggestions for `R`, but not for `Re`, but again for `Red` and every following letter.
Similar situation for CSS properties in a SCSS file. If I want to write `display`**, there are no suggestions at all, but after `display: i`, there will be suggestions for `inline-block` for example.
I tried it in Gitpod and VS Code and there were no issues.
See screenshots.

*This error message appears in the console after typing `Re` (see above):
```
errors.ts:26 Uncaught Error: Cannot read property 'Deprecated' of undefined

TypeError: Cannot read property 'Deprecated' of undefined
    at v (/tmp/vscode-unpacked/redhat.php-new.1.4.0.rinuousiea.vscode-intelephense-client-1.4.0.vsix/extension/lib/extension.js:1)
    at /tmp/vscode-unpacked/redhat.php-new.1.4.0.rinuousiea.vscode-intelephense-client-1.4.0.vsix/extension/lib/extension.js:1
    at R (/tmp/vscode-unpacked/redhat.php-new.1.4.0.rinuousiea.vscode-intelephense-client-1.4.0.vsix/extension/lib/extension.js:1)
    at Array.map (<anonymous>)
    at asCompletionResult (/tmp/vscode-unpacked/redhat.php-new.1.4.0.rinuousiea.vscode-intelephense-client-1.4.0.vsix/extension/lib/extension.js:1)
    at errors.ts:26
```

**This error message appears in the console when trying to type `display` in a SCSS file (see above):
```
errors.ts:26 Uncaught Error: Cannot read property 'Deprecated' of undefined

TypeError: Cannot read property 'Deprecated' of undefined
    at y (/default-theia-plugins/vscode-builtin-css-language-features/extension/client/dist/cssMain.js:1)
    at /default-theia-plugins/vscode-builtin-css-language-features/extension/client/dist/cssMain.js:1
    at C (/default-theia-plugins/vscode-builtin-css-language-features/extension/client/dist/cssMain.js:1)
    at Array.map (<anonymous>)
    at asCompletionResult (/default-theia-plugins/vscode-builtin-css-language-features/extension/client/dist/cssMain.js:1)
    at errors.ts:26
```

### Expected behavior

Suggestions and auto-completion should always work

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/10995998/88572411-612bd100-d03f-11ea-961f-dbfc5e7a059f.png)

![image](https://user-images.githubusercontent.com/10995998/88572444-6ee15680-d03f-11ea-97ca-2fc5afae7cf9.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [x] my computer
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by ericwill** [comment] 2020-07-27 19:17
Taking a look at the issue, I see you are using Intelephense version 1.5.3 and 1.4.0. Right now we only have 1.3.11 in the plugin registry. I can't say for sure, but it looks like there is some theia API missing.

Thanks for the bug report, we'll look into updating to Intelephense 1.5.3, including all the needed API to go with it.

**Comment by danidoedel** [comment] 2020-07-27 19:20
Thanks for taking a look @ericwill 
I tested it with Gitpod and it works fine there, they are using Intelephense 1.4.0 so I assume it might be something else.
But I would be happy if you could check updating it to 1.5.3. 
Also, the css issue should be unrelated to the Intelephense version.

**Comment by danidoedel** [comment] 2020-07-28 12:13
@l0rd Are you sure it is Intelephense only as it is also not working with CSS?

**Comment by l0rd** [comment] 2020-07-28 21:05
@danidoedel no I am not but things may be related and the original title wasn't explicit enough.

**Comment by ericwill** [comment] 2020-08-12 19:11
@danidoedel I tried reproducing the issue with a Symfony project and intelphense 1.5.3, but I was unable to reproduce the error. Can you share your devfile or a link to the project which reproduces the crash?

**Comment by danidoedel** [comment] 2020-08-12 19:13
@ericwill as the devfile and project are work related I can't share them, but I'll try to set something simple up to reproduce it.

**Comment by danidoedel** [comment] 2020-08-18 09:52
@ericwill I did some tests and found out the following:
- Intelephense 1.3.11 seems to work fine now
- Intelephense 1.5.4 doesn't seem to work for me

However if I create a workspace with this devfile: 
https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/php-symfony/devfile.yaml

And try to edit some SCSS file and type something like `display` I don't get any suggestion and this error in the console (same for the Intelephense issue, just with Intelephense instead of vscode-builtin-css):

```
Uncaught Error: Cannot read property 'Deprecated' of undefined

TypeError: Cannot read property 'Deprecated' of undefined
    at y (/default-theia-plugins/vscode-builtin-css-language-features/extension/client/dist/cssMain.js:1)
    at /default-theia-plugins/vscode-builtin-css-language-features/extension/client/dist/cssMain.js:1
    at C (/default-theia-plugins/vscode-builtin-css-language-features/extension/client/dist/cssMain.js:1)
    at Array.map (<anonymous>)
    at asCompletionResult (/default-theia-plugins/vscode-builtin-css-language-features/extension/client/dist/cssMain.js:1)
    at cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.19.3/min/vs/editor/editor.main.js:30
```

I hope you can reproduce it with these information and a fix might also solve the Intelephense issue.. hopfully ;)

**Comment by ericwill** [comment] 2020-08-19 20:56
> @ericwill I did some tests and found out the following:
> 
>     * Intelephense 1.3.11 seems to work fine now
> 
>     * Intelephense 1.5.4 doesn't seem to work for me
> 
> 
> However if I create a workspace with this devfile:
> https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/php-symfony/devfile.yaml
> 
> And try to edit some SCSS file and type something like `display` I don't get any suggestion and this error in the console (same for the Intelephense issue, just with Intelephense instead of vscode-builtin-css):
> 
> ```
> Uncaught Error: Cannot read property 'Deprecated' of undefined
> 
> TypeError: Cannot read property 'Deprecated' of undefined
>     at y (/default-theia-plugins/vscode-builtin-css-language-features/extension/client/dist/cssMain.js:1)
>     at /default-theia-plugins/vscode-builtin-css-language-features/extension/client/dist/cssMain.js:1
>     at C (/default-theia-plugins/vscode-builtin-css-language-features/extension/client/dist/cssMain.js:1)
>     at Array.map (<anonymous>)
>     at asCompletionResult (/default-theia-plugins/vscode-builtin-css-language-features/extension/client/dist/cssMain.js:1)
>     at cdn.jsdelivr.net/npm/@theia/monaco-editor-core@0.19.3/min/vs/editor/editor.main.js:30
> ```
> 
> I hope you can reproduce it with these information and a fix might also solve the Intelephense issue.. hopfully ;)

Sadly I still can't reproduce it. How have you deployed Che? Judging by the error, it might be worth it to try a more recent che-theia release, like 7.17 or 7.16.2.

**Comment by danidoedel** [comment] 2020-08-19 21:01
Currently we are running 7.17.1 on kubernetes, not sure how it was deployed though. I also tired it with che-theia next. 
Is there anything I could try out?

**Comment by danidoedel** [comment] 2020-09-08 06:53
@ericwill seems to be not just me: https://github.com/eclipse-theia/theia/issues/8475

**Comment by ericwill** [comment] 2020-09-18 15:11
> @ericwill seems to be not just me: [eclipse-theia/theia#8475](https://github.com/eclipse-theia/theia/issues/8475)

Looks like there is a PR open for that issue, maybe it will fix the PHP case as well. I'm also planning on updating Che's PHP plugin this sprint.

**Comment by ericwill** [comment] 2020-09-24 19:31
The theia PR has been merged, I would try testing this on Che 7.20 (when it's released) and see if the bug is still there.

**Comment by danidoedel** [comment] 2020-09-24 20:46
@ericwill I can confirm it is fixed with Che Theia next 👍

**Comment by ericwill** [comment] 2020-09-24 21:17
Perfect!

**Closed as completed by ericwill** 2020-09-24 21:17 UTC
Labels: kind/bug, severity/P1, area/languages, area/plugins
