### ISSUE TITLE
GithubFactoryParametersResolver unit-test failed

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#19468] opened 2021-03-31 08:39 UTC
## Summary
<GithubFactoryParametersResolverTest unit test fail>
0. version: 7.27.2

1. test file path: "che\wsmaster\che-core-api-factory-github\src\test\java\org\eclipse\che\api\factory\server\github\GithubEnterpriseFactoryParametersResolverTest.java"

2. failed unit-test name
- GithubFactoryParametersResolverTest.shouldGenerateDevfileForFactoryWithNoDevfile
- GithubFactoryParametersResolverTest.shouldReturnFactoryFromRepositoryWithDevfile
- GithubFactoryParametersResolverTest.shouldSetBranchIntoDevfileIfNotMatchesCurrent
- GithubFactoryParametersResolverTest.shouldSetDefaultProjectIntoDevfileIfNotSpecified

3. cause
it cannot create FactoryDTO. because "dtoInterface2Providers" ConcurrentHashMap is empty.
so unit-tests are failed.

``` JAVA
private <T> DtoProvider<T> getDtoProvider(Class<T> dtoInterface) {
    DtoProvider<?> dtoProvider = dtoInterface2Providers.get(dtoInterface);
    if (dtoProvider == null) {
      if (!dtoInterface.isInterface()) {
        throw new IllegalArgumentException(
            format("Only interfaces can be DTO, but %s is not an interface.", dtoInterface));
      }

      if (hasDtoAnnotation(dtoInterface)) {
        throw new IllegalArgumentException(
            format("Provider of implementation for DTO type %s is not found", dtoInterface));
      } else {
        throw new IllegalArgumentException(dtoInterface + " is not a DTO type");
      }
    }

    return (DtoProvider<T>) dtoProvider;
  }
```

**Comment by AndrienkoAleksandr** [comment] 2021-03-31 14:27
@mshaposhnik Could you help?

**Comment by mshaposhnik** [comment] 2021-03-31 14:39
Cannot reproduce it locally. Please make sure that module `che-core-api-factory-shared` is built before. 
BTW is Java version 11?

**Comment by jykim206** [comment] 2021-04-01 01:03
I am using Java version 11.
I checked "che-core-api-factory-shared" was built. and it was processed. thank you for your advice!
I'll close the issue

**Comment by jykim206** [comment] 2021-04-01 01:15
i have a further question. 
when "dtoInterface2Providers " is filled with "62" DTOs?

<DTOFactory.java>
private final Map<Class<?>, DtoProvider<?>> dtoInterface2Providers = new ConcurrentHashMap<>()

**Comment by skabashnyuk** [comment] 2021-04-01 06:17
>when "dtoInterface2Providers " is filled with "62" DTOs? 

@jykim206 can you please rephrase your question. Please give more context.

**Comment by jykim206** [comment] 2021-04-01 08:22
when executed the test, we can see "dtoInterface2Providers" ConcurrentHashMaphave 62 DTOs. i wanna know which things assign 62DTOs to dtoInterface2Providers  ConcurrentHashMap.

**Comment by skabashnyuk** [comment] 2021-04-01 12:06
>@skabashnyuk when executed the test, we can see "dtoInterface2Providers" ConcurrentHashMap have 62 DTOs. i wanna know which things assign 62DTOs to dtoInterface2Providers ConcurrentHashMap.


https://github.com/eclipse/che/blob/49597448e56beaf76ce3859f5c02b92b89c77bf4/core/che-core-api-dto/src/main/java/org/eclipse/che/dto/server/DtoFactory.java#L486-L488

**Comment by jykim206** [comment] 2021-04-02 00:09
Thank you for kind explanation! I'll close the issue.

**Closed as completed by jykim206** 2021-04-02 00:09 UTC
Labels: kind/question, severity/P2
