### ISSUE TITLE
Javadoc is duplicated

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#10049] opened 2018-06-14 11:55 UTC
When the workspace is restarted, javadoc is duplicated.
See steps to reproduce: 
1. Start the workspace with java project and wait when jdt.ls is started;
2. Go to Workspace menu and click Stop;
3. Wait when the workspace is stopped and start it again
4. When jd.ls will be ready, hover the mouse on some java element and than you'll see that the documentation is duplicated:
![screenshot from 2018-06-15 14-27-14](https://user-images.githubusercontent.com/1271546/41467897-5f4949b0-70a8-11e8-9638-56c851508426.png)
5. If restart the workspace again javadoc will be displayed 3 times and so on.

Or you can see the video how to reproduce it:
https://youtu.be/Zy6B-RcnYGQ

**Comment by svor** [comment] 2018-06-15 12:32
@tsmaeder I've updated the description

**Comment by vrubezhny** [comment] 2018-06-20 14:22
`org.eclipse.che.ide.editor.orion.client.OrionHoverRegistrant.registerHover(final JsArrayString contentTypes, final OrionHoverHandler handler)` is called on re-used editor instance every time after workspace is restarted and this method adds a new instance of hover calculation service. So, the hovers are calculated two, three times and so one depending on the number of workspace restarts.
I believe the same issue happens for Occurrences calculation - see `org.eclipse.che.ide.editor.orion.client.registerOccurrencesHandler(OrionServiceRegistryOverlay serviceRegistry, JsArrayString contentTypes, OrionOccurrencesHandler handler)`

**Comment by tsmaeder** [comment] 2018-06-21 07:06
Duplicate of https://github.com/eclipse/che/issues/10117

**Closed as completed by tsmaeder** 2018-06-21 07:06 UTC
Labels: kind/bug, target/branch
