### ISSUE TITLE
Build in Java with SpringBoot and MySQL failing

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#15911] opened 2020-02-04 07:57 UTC
### Describe the bug
The `maven build` task failing in Java with SpringBoot and MySQL default workspace. The command ends with `Killed` without any further description of what happened.
That means that project can not be built&run.

### Che version
 - [x] latest 7.9.0

### Steps to reproduce

1. Go to Workspaces -> Add Workspace
2. Create Java with SpringBoot and MySQL with default settings
3. Go to Terminal -> Run task... -> maven build -> Continue without scanning the task output
4. Watch the terminal output

### Expected behavior

The project should be built and run successfully.

### Runtime

- [x] Openshift (include output of `oc version`)

### Screenshots
![Screenshot from 2020-02-04 08-53-57](https://user-images.githubusercontent.com/29278800/73724740-4cbfe900-472c-11ea-8ef0-824d1db89a82.png)

### Installation method

- [x] chectl 

### Environment
  
- [x] Amazon

**Comment by l0rd** [comment] 2020-02-05 00:34
That looks like an Out Of Memory error at runtime (not build time). I am not sure if the process got killed by the kubelet or by the JVM. Can you try to get the workspace pod description after the failure `oc get description pod <workspace-pod-id>` ? In particular I would look for something like:

```
    State:          Terminated
      Reason:       OOMKilled
```

I am assuming that the same test was passing before. Would you be able to verify if what caused the problem is an update of the sample (i.e. using a previous version/commit of the sample works fine) or an updated of che (i.e. using che `v7.8.0` works fine)?

**Comment by JPinkney** [comment] 2020-02-25 14:09
A fix for this has been provided on the devfile-registry!: https://github.com/eclipse/che-devfile-registry/pull/198

**Closed as completed by JPinkney** 2020-02-25 14:09 UTC
Labels: kind/bug, severity/P2, area/samples
