### ISSUE TITLE
"Apache Camel" devfile debug task does not work

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#14003] opened 2019-07-24 13:43 UTC
### Describe the bug
Task "run and debug the services" from Apache Camel devfile does not work

### Che version

 - [x] nightly

### Steps to reproduce
1. Run workspace from Apache Camel devfile https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/apache-camel-springboot
2. set breakpoint somewhere where it should be hit
3. run "run and debug the services"
4. breakpoint don't get hit

### Expected behavior
breakpoint hit out of the box

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Installation method
   - [x] chectl 

### Environment
   - [x] my computer 
       - [x] Linux

**Comment by apupier** [comment] 2019-07-24 13:48
it is the only stack which seems to provide a debug task.
we can use some attach launch config (but it requires an extra step which is not trivial):
- open Debug view
- Add Configuration
- provide something like
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  "version": "0.2.0",
  "configurations": [
    {
      "type": "java",
      "name": "Debug (Attach)",
      "request": "launch",
      "mainClass": "${file}"
    },
    {
      "type": "java",
      "name": "Debug (Attach)-Application<fuse-rest-http-booster>",
      "request": "attach",
      "port": 5005,
      "projectName": "fuse-rest-http-booster"
    }
  ]
}
```
- launch the config

but unfortunately, it started to show a few thread sand then failed with:
```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2019-07-24 13:41:26.484 ERROR 309 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 
***************************
APPLICATION FAILED TO START
***************************
Description:
Embedded servlet container failed to start. Port 8080 was already in use.
Action:
Identify and stop the process that's listening on port 8080 or configure this application to listen on another port.
```

given that we can use [the CodeLens on  Application class](https://drive.google.com/open?id=1o9PYCv30_IrCT5XDH8mhQyvkt52M5F61), I would say that this command should be removed for now. if we are able to auto-connect the debugger, it will become interesting to have it

**Comment by amisevsk** [comment] 2019-07-24 14:52
The issue is one of naming, I believe. The task should be named something like "run the services with debugging enabled".

The task *works*, but it only starts the server listening on a JDPA port; you still need to configure the theia debug task, and I don't know if there's a devfile-based way to do that.

An additional issue is that when you start this task, Theia prompts you that "a new service is listening on port 5005". If you choose to expose this port, you **won't** be able to connect your debugger.

**Comment by slemeur** [comment] 2019-07-24 21:29
@amisevsk : Excellent suggestion to rename the task. I think we should to that as an immediate quick-fix. The user will still have to add the debug configuration for now. until we look at adding the debug config in the devfile indeed.

**Comment by slemeur** [comment] 2019-07-24 21:30
@apupier : Can you help on this issue?

**Comment by slemeur** [comment] 2019-07-24 22:10
I just catched the PR! Thanks @apupier !

**Comment by amisevsk** [comment] 2019-08-07 20:41
Closing as current apache camel [devfile](https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/apache-camel-springboot/devfile.yaml) contains a working setup for debugging (start remote application + connect remote debugger). 

There are some improvements still possible, as listed in https://github.com/eclipse/che-devfile-registry/pull/66#issuecomment-518114703

**Closed as completed by amisevsk** 2019-08-07 20:41 UTC
Labels: kind/bug, severity/P2, area/devfile-registry
