### ISSUE TITLE
Upgrade vscode-java plugin to 0.55+

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#15593] opened 2020-01-02 09:11 UTC
### Is your enhancement related to a problem? Please describe.

it includes _java.project.referencedLibraries_ feature which is required for VS Code Camel K 0.11+ to have Java language support on standlaone Camel K files

### Describe the solution you'd like

upgrade vscode java to 0.55+

**Comment by tsmaeder** [comment] 2020-01-08 14:17
Closing as duplicate of https://github.com/eclipse/che/issues/15560

**Closed as completed by tsmaeder** 2020-01-08 14:17 UTC
Labels: kind/enhancement, area/plugins
