### ISSUE TITLE
[Hosted Che] - Redirect loop when opening workspace (in Chrome 84 anonymous window)

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#17470] opened 2020-07-23 12:37 UTC
### Describe the bug
Trying to open workspace in che.openshift.io in Chrome 84 **anonymous** window ends up in redirect loop: https://youtu.be/jSncBeA1P0E
Weirdly enough I am not able to reproduce this in "normal" window nor in Firefox (normal/anonymous).
I've tried with multiple accounts provisioned on different clusters and the behavior was still the same.

@Katka92 was also able to reproduce this behavior.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Expected behavior
Workspace is opened

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
https://youtu.be/jSncBeA1P0E

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by ibuziuk** [comment] 2020-07-23 12:51
@rhopp @Katka92 could you provide the logs? is it reproducible on both stg and prod? is it smth similar to what we had in https://github.com/eclipse/che/issues/16384 ?

**Comment by rhopp** [comment] 2020-07-23 13:07
@ibuziuk 
> could you provide the logs?

Here are the browser console logs: https://pastebin.com/GPYkHki2 (I don't see anything suspicious there)
I also have `.har` recording of the network requests - I can share that with you privatly if you want (contains tokens etc.)
For server logs - You are better positioned to dive deep into them - my users I've tried this with are `rhopp@redhat.com`, `rhopp-osiotest2`, `rhopp-osiotest3`.

> is it reproducible on both stg and prod? 

Yes. Just tried this on prod-preview with my user `rhopp-preview` and it reproduces there as well (allways reproducible)

> is it smth similar to what we had in #16384

This issue indeed looks pretty same.

**Comment by ibuziuk** [comment] 2020-07-23 13:19
works for me against in incognito against `80.0.3987.149-1`

**Comment by rhopp** [comment] 2020-07-23 13:30
I have Version 84.0.4147.89 (Official Build) (64-bit) (as stated in description). @Katka92 What's your version?

**Comment by Katka92** [comment] 2020-07-23 13:36
I reproduced this issue with Chrome Version 84.0.4147.89 (Official Build) (64-bit)

**Comment by ibuziuk** [comment] 2020-07-23 13:46
Setting P2 for now
@mshaposhnik @sleshchenko folks maybe you are aware of any changes related to the SameSite ? looks like some variation of #16384  from the first glance

**Comment by monaka** [comment] 2020-09-15 22:19
Even though I'm not sure my report fits to this issue.

Recent Chrome reports issues related SameSite like this.
My chrome is Version 85.0.4183.108 (Official Build) (64-bit) on ChromeOS.

![image](https://user-images.githubusercontent.com/101795/93270670-92797f80-f7ec-11ea-9a4e-5fb8fdd9749d.png)

These are reported on both che.codeshift.io and my PizzaFactory instances.
My workspaces are started with no trouble even if issues are reported.

**Comment by monaka** [comment] 2020-09-15 22:27
And workspaces are raised on PizzaFactory instance even if the browser is incognito mode.
 
![image](https://user-images.githubusercontent.com/101795/93271331-f2245a80-f7ed-11ea-86fe-02390f23fb28.png)

**Comment by monaka** [comment] 2020-09-15 23:03
I tried to reproduce this issue on PizzaFactory instance. And I found an exception log shown on incognito mode only.
AFAIK, it doesn't use Keycloak on che.openshift.io. But I think the root issue is same. 

```
VM1377 keycloackLoader.js:28 Cannot load keycloak settings. This is normal for single-user mode. DOMException: Blocked a frame with origin "https://che-banco.camino.pizzafactory.jp" from accessing a cross-origin frame.
    at https://che-banco.camino.pizzafactory.jp/_app/keycloackLoader.js:21:51
    at new Promise (<anonymous>)
    at KeycloakLoader.loadKeycloakSettings (https://che-banco.camino.pizzafactory.jp/_app/keycloackLoader.js:19:16)
    at https://che-banco.camino.pizzafactory.jp/_app/loader.js:227:36
    at https://che-banco.camino.pizzafactory.jp/_app/loader.js:239:3
```

**Comment by ibuziuk** [comment] 2021-03-11 12:13
Closing since che.openshift.io EOL is March 1st
The issue is not reproducible against workspace.openshift.com

**Closed as completed by ibuziuk** 2021-03-11 12:13 UTC
Labels: kind/bug, severity/P2, area/hosted-che
