### ISSUE TITLE
Java Plugin not Being Started

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14944] opened 2019-10-21 14:53 UTC
### Describe the bug
Java LS server didn't start from the first time of workspace loading and required refreshing of browser's tab:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/K8S/job/Single-Che-master-check-E2E-Happy-path-tests-against-k8s/2581/ :
```
Language server validation
        ▼ ProjectTree.expandPathAndOpenFileInAssociatedWorkspace "petclinic/src/main/java/org/springframework/samples/petclinic"
        ▼ ProjectTree.expandItem "petclinic/src"
        ▼ ProjectTree.waitItemExpanded "petclinic/src"
        ▼ ProjectTree.expandItem "petclinic/src/main"
        ▼ ProjectTree.waitItemExpanded "petclinic/src/main"
        ▼ ProjectTree.expandItem "petclinic/src/main/java"
        ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java"
        ▼ ProjectTree.expandItem "petclinic/src/main/java/org"
        ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java/org"
        ▼ ProjectTree.expandItem "petclinic/src/main/java/org/springframework"
        ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java/org/springframework"
        ▼ ProjectTree.expandItem "petclinic/src/main/java/org/springframework/samples"
        ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java/org/springframework/samples"
        ▼ ProjectTree.expandItem "petclinic/src/main/java/org/springframework/samples/petclinic"
        ▼ ProjectTree.waitItemExpanded "petclinic/src/main/java/org/springframework/samples/petclinic"
        ▼ ProjectTree.clickOnItem "petclinic/src/main/java/org/springframework/samples/petclinic/PetClinicApplication.java"
        ▼ ProjectTree.waitItemSelected "petclinic/src/main/java/org/springframework/samples/petclinic/PetClinicApplication.java"
        ▼ Editor.waitEditorOpened "PetClinicApplication.java"
        ▼ Editor.waitTab "PetClinicApplication.java"
        ▼ Editor.selectTab "PetClinicApplication.java"
        ▼ Ide.closeAllNotifications
        ▼ Editor.waitTab "PetClinicApplication.java"
        ▼ Editor.clickOnTab "PetClinicApplication.java"
        ▼ Ide.closeAllNotifications
        ▼ Editor.waitTabFocused "PetClinicApplication.java"
        ▼ Ide.checkLsInitializationStart
        ▼ Ide.waitStatusBarContains "Starting Java Language Server"
        ▼ Ide.waitAndSwitchToIdeFrame
    1) Java LS initialization


  3 passing (7m)
  1 failing

  1) Language server validation
       Java LS initialization:
     TimeoutError: Waiting to be able to switch to frame
Wait timed out after 240002ms
      at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
```

### Workaround 
Refreshing browser's tab restores LS server initialization https://github.com/eclipse/che/blob/master/e2e/pageobjects/ide/Ide.ts#L220-L226.

### Screencast
https://youtu.be/KBL5ug1idEI

### Screenshot
![screenshot-Java_LS_initialization (3)](https://user-images.githubusercontent.com/1197777/67220304-3bc7c200-f432-11e9-9998-a448aeb0b3a3.png)

### Related issue
https://github.com/eclipse/che/issues/14283

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Logs and configs
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/K8S/job/Single-Che-master-check-E2E-Happy-path-tests-against-k8s/2581/artifact/logs-and-configs/

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
https://github.com/eclipse/che/blob/master/e2e/tests/e2e_happy_path/HappyPath.spec.ts

### Devfile
https://github.com/eclipse/che/blob/master/e2e/files/happy-path/happy-path-workspace.yaml

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl:next
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: CRW CCI

**Comment by svor** [comment] 2019-10-21 15:03
I can reproduce this problem with **cpptools** plugin as well
<details><summary>Logs from the plugin's container</summary><p>

```
Starting the deployer with the list of resolvers [ LocalDirectoryPluginDeployerResolver {},
--
  | GithubPluginDeployerResolver { unpackedFolder: '/tmp/github-remote' },
  | HttpPluginDeployerResolver { unpackedFolder: '/tmp/http-remote' },
  | VsCodePluginDeployerResolver { vscodeExtensionsFolder: '/tmp/vscode-extension-marketplace' } ]
  | Theia Endpoint 1/pid listening on port 2503
  | Found the list of default plugins ID on env: undefined
  | Found the list of plugins ID on env: local-dir:///plugins/sidecars/che_incubator_cpptools_latest
  | Found the list of default plugins ID from CLI: undefined
  | unzipping the VS Code extension 'che-incubator.cpptools.latest.bopllwcluv.cdt-gdb-vscode-0.0.90.vsix' to directory: /tmp/vscode-unpacked/che-incubator.cpptools.latest.bopllwcluv.cdt-gdb-vscode-0.0.90.vsix
  | unzipping the VS Code extension 'che-incubator.cpptools.latest.ioxhwpyluu.cdt-vscode-0.0.7.vsix' to directory: /tmp/vscode-unpacked/che-incubator.cpptools.latest.ioxhwpyluu.cdt-vscode-0.0.7.vsix
  | unzipping the VS Code extension 'che-incubator.cpptools.latest.vlwrkdfgfd.llvm-vs-code-extensions.vscode-clangd-0.0.16.vsix' to directory: /tmp/vscode-unpacked/che-incubator.cpptools.latest.vlwrkdfgfd.llvm-vs-code-extensions.vscode-clangd-0.0.16.vsix
  | PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/che-incubator.cpptools.latest.bopllwcluv.cdt-gdb-vscode-0.0.90.vsix
  | Resolving "che-incubator.cpptools.latest.bopllwcluv.cdt-gdb-vscode-0.0.90.vsix" as a VS Code extension...
  | Resolved "che-incubator.cpptools.latest.bopllwcluv.cdt-gdb-vscode-0.0.90.vsix" to a VS Code extension "cdt-gdb-vscode@0.0.90" with engines: { vscode: '^1.26.0' }
  | PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/che-incubator.cpptools.latest.ioxhwpyluu.cdt-vscode-0.0.7.vsix
  | Resolving "che-incubator.cpptools.latest.ioxhwpyluu.cdt-vscode-0.0.7.vsix" as a VS Code extension...
  | Resolved "che-incubator.cpptools.latest.ioxhwpyluu.cdt-vscode-0.0.7.vsix" to a VS Code extension "cdt-vscode@0.0.7" with engines: { vscode: '^1.30.0' }
  | PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/che-incubator.cpptools.latest.vlwrkdfgfd.llvm-vs-code-extensions.vscode-clangd-0.0.16.vsix
  | Resolving "che-incubator.cpptools.latest.vlwrkdfgfd.llvm-vs-code-extensions.vscode-clangd-0.0.16.vsix" as a VS Code extension...
  | Resolved "che-incubator.cpptools.latest.vlwrkdfgfd.llvm-vs-code-extensions.vscode-clangd-0.0.16.vsix" to a VS Code extension "vscode-clangd@0.0.16" with engines: { vscode: '^1.36.0' }
  | the accepted plugins are []
  | the acceptedFrontendPlugins plugins are []
  | the acceptedBackendPlugins plugins are [ PluginDeployerEntryImpl {
  | originId:
  | 'local-dir:///plugins/sidecars/che_incubator_cpptools_latest',
  | pluginId:
  | 'che-incubator.cpptools.latest.bopllwcluv.cdt-gdb-vscode-0.0.90.vsix',
  | map: Map { 'package.json' => [Object] },
  | changes:
  | [ 'PluginVsCodeFileHandler', 'PluginVsCodeDirectoryHandler' ],
  | acceptedTypes: [ 1 ],
  | currentPath:
  | '/tmp/vscode-unpacked/che-incubator.cpptools.latest.bopllwcluv.cdt-gdb-vscode-0.0.90.vsix/extension',
  | initPath:
  | '/plugins/sidecars/che_incubator_cpptools_latest/che-incubator.cpptools.latest.bopllwcluv.cdt-gdb-vscode-0.0.90.vsix',
  | resolved: true,
  | resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  | PluginDeployerEntryImpl {
  | originId:
  | 'local-dir:///plugins/sidecars/che_incubator_cpptools_latest',
  | pluginId:
  | 'che-incubator.cpptools.latest.ioxhwpyluu.cdt-vscode-0.0.7.vsix',
  | map: Map { 'package.json' => [Object] },
  | changes:
  | [ 'PluginVsCodeFileHandler', 'PluginVsCodeDirectoryHandler' ],
  | acceptedTypes: [ 1 ],
  | currentPath:
  | '/tmp/vscode-unpacked/che-incubator.cpptools.latest.ioxhwpyluu.cdt-vscode-0.0.7.vsix/extension',
  | initPath:
  | '/plugins/sidecars/che_incubator_cpptools_latest/che-incubator.cpptools.latest.ioxhwpyluu.cdt-vscode-0.0.7.vsix',
  | resolved: true,
  | resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  | PluginDeployerEntryImpl {
  | originId:
  | 'local-dir:///plugins/sidecars/che_incubator_cpptools_latest',
  | pluginId:
  | 'che-incubator.cpptools.latest.vlwrkdfgfd.llvm-vs-code-extensions.vscode-clangd-0.0.16.vsix',
  | map: Map { 'package.json' => [Object] },
  | changes:
  | [ 'PluginVsCodeFileHandler', 'PluginVsCodeDirectoryHandler' ],
  | acceptedTypes: [ 1 ],
  | currentPath:
  | '/tmp/vscode-unpacked/che-incubator.cpptools.latest.vlwrkdfgfd.llvm-vs-code-extensions.vscode-clangd-0.0.16.vsix/extension',
  | initPath:
  | '/plugins/sidecars/che_incubator_cpptools_latest/che-incubator.cpptools.latest.vlwrkdfgfd.llvm-vs-code-extensions.vscode-clangd-0.0.16.vsix',
  | resolved: true,
  | resolvedByName: 'LocalDirectoryPluginDeployerResolver' } ]
  | local path to deploy on remote instance [ '/tmp/vscode-unpacked/che-incubator.cpptools.latest.bopllwcluv.cdt-gdb-vscode-0.0.90.vsix/extension',
  | '/tmp/vscode-unpacked/che-incubator.cpptools.latest.ioxhwpyluu.cdt-vscode-0.0.7.vsix/extension',
  | '/tmp/vscode-unpacked/che-incubator.cpptools.latest.vlwrkdfgfd.llvm-vs-code-extensions.vscode-clangd-0.0.16.vsix/extension' ]
  | Deploying backend plugin "cdt-gdb-vscode@0.0.90" from "/tmp/vscode-unpacked/che-incubator.cpptools.latest.bopllwcluv.cdt-gdb-vscode-0.0.90.vsix/extension/out/extension"
  | Deploying backend plugin "cdt-vscode@0.0.7" from "/tmp/vscode-unpacked/che-incubator.cpptools.latest.ioxhwpyluu.cdt-vscode-0.0.7.vsix/extension/dist/extension.js"
  | Deploying backend plugin "vscode-clangd@0.0.16" from "/tmp/vscode-unpacked/che-incubator.cpptools.latest.vlwrkdfgfd.llvm-vs-code-extensions.vscode-clangd-0.0.16.vsix/extension/out/src/extension"
```
</p></details>

this problem is reproducible time to time

**Comment by AndrienkoAleksandr** [comment] 2019-10-21 15:05
Reproducible with php language remote plugin

**Comment by musienko-maxim** [comment] 2019-10-21 15:08
<details>
 <summary>Logs after first starting workspace and opening a maven project</summary>
 <pre>
Starting the deployer with the list of resolvers [ LocalDirectoryPluginDeployerResolver {},
  GithubPluginDeployerResolver { unpackedFolder: '/tmp/github-remote' },
  HttpPluginDeployerResolver { unpackedFolder: '/tmp/http-remote' },
  VsCodePluginDeployerResolver { vscodeExtensionsFolder: '/tmp/vscode-extension-marketplace' } ]
Theia Endpoint 19/pid listening on port 2503
Found the list of default plugins ID on env: undefined
Found the list of plugins ID on env: local-dir:///plugins/sidecars/redhat_java_latest
Found the list of default plugins ID from CLI: undefined
unzipping the VS Code extension 'redhat.java.latest.wqwczbcine.java-0.50.0-1825.vsix' to directory: /tmp/vscode-unpacked/redhat.java.latest.wqwczbcine.java-0.50.0-1825.vsix
unzipping the VS Code extension 'redhat.java.latest.xqqajxsbmd.vscode-java-debug-0.20.0.vsix' to directory: /tmp/vscode-unpacked/redhat.java.latest.xqqajxsbmd.vscode-java-debug-0.20.0.vsix
PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/redhat.java.latest.wqwczbcine.java-0.50.0-1825.vsix
Resolving "redhat.java.latest.wqwczbcine.java-0.50.0-1825.vsix" as a VS Code extension...
Resolved "redhat.java.latest.wqwczbcine.java-0.50.0-1825.vsix" to a VS Code extension "java@0.50.0" with engines: { vscode: '^1.36.0' }
PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/redhat.java.latest.xqqajxsbmd.vscode-java-debug-0.20.0.vsix
Resolving "redhat.java.latest.xqqajxsbmd.vscode-java-debug-0.20.0.vsix" as a VS Code extension...
Resolved "redhat.java.latest.xqqajxsbmd.vscode-java-debug-0.20.0.vsix" to a VS Code extension "vscode-java-debug@0.20.0" with engines: { vscode: '^1.32.0' }
the accepted plugins are []
the acceptedFrontendPlugins plugins are []
the acceptedBackendPlugins plugins are [ PluginDeployerEntryImpl {
    originId: 'local-dir:///plugins/sidecars/redhat_java_latest',
    pluginId: 'redhat.java.latest.wqwczbcine.java-0.50.0-1825.vsix',
    map: Map { 'package.json' => [Object] },
    changes:
     [ 'PluginVsCodeFileHandler', 'PluginVsCodeDirectoryHandler' ],
    acceptedTypes: [ 1 ],
    currentPath:
     '/tmp/vscode-unpacked/redhat.java.latest.wqwczbcine.java-0.50.0-1825.vsix/extension',
    initPath:
     '/plugins/sidecars/redhat_java_latest/redhat.java.latest.wqwczbcine.java-0.50.0-1825.vsix',
    resolved: true,
    resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  PluginDeployerEntryImpl {
    originId: 'local-dir:///plugins/sidecars/redhat_java_latest',
    pluginId:
     'redhat.java.latest.xqqajxsbmd.vscode-java-debug-0.20.0.vsix',
    map: Map { 'package.json' => [Object] },
    changes:
     [ 'PluginVsCodeFileHandler', 'PluginVsCodeDirectoryHandler' ],
    acceptedTypes: [ 1 ],
    currentPath:
 </pre>
</details>

**Comment by tsmaeder** [comment] 2019-10-22 11:45
It seems that plugin activation is not happening in this case. Couple of datapoints:

1. It works with vscode-java 0.50 in plain Theia
2. Activation via the route "workspaceContains" does not work when the files in question (pom.xml and gradle) are added after the ide starts
3. It seems activation via "language:java" is not happening in Che.

**Comment by tsmaeder** [comment] 2019-10-22 12:36
Changed title: Java commands are not registered, which indicates that the vscode-java extensions is never started. Also: plugin activation are not visible in the browser log.

**Comment by tsmaeder** [comment] 2019-10-22 14:58
I am having trouble reproducing now. However, one thing I noticed is that in the plugin host image output, the line 

```
PLUGIN_HOST(21): PluginManagerExtImpl/init()
```

Was missing when the initialization failed. The log comes from plugin-host-rpc.ts#135, and indirectly from PluginManagerExtImpl#$start(), which is in plugin-manager.ts#155. 
It seems like in HostedPluginSupport#startPlugins() not all plugin managers are found to call $start on them.

**Comment by tsmaeder** [comment] 2019-10-23 10:16
Further info: the $start message seems to be sent to the remote plugin manager, but I don't see the init message that should be displayed if $start is indeed executed.

**Comment by dmytro-ndp** [comment] 2019-10-24 09:29
The error has been fixed by PR https://github.com/eclipse/che-theia/pull/508

**Comment by dmytro-ndp** [comment] 2020-03-20 07:45
It has been reproduced in Eclipse Che 7.11.0-SNAPSHOT:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/1384/consoleFull
```
          ▼ Ide.checkLsInitializationStart
          ▼ Ide.waitStatusBarContains "Activating Language Support for Java"
Known flakiness has occurred https://github.com/eclipse/che/issues/14944
          ▼ DriverHelper.reloadPage
[1584668329.067][SEVERE]: Timed out receiving message from renderer: 0.100
          ▼ Ide.waitStatusBarContains "Activating Language Support for Java"
[1584668329.326][SEVERE]: Timed out receiving message from renderer: 0.100
    1) Java LS initialization


  3 passing (5m)
  1 failing

  1) Language server validation
       Java LS initialization:
     TimeoutError: Waiting for element to be located By(css selector, div[id='theia-statusBar'])
Wait timed out after 180010ms
```

**Comment by svor** [comment] 2020-03-20 09:42
could you provide logs from java-plugin container?

**Comment by dmytro-ndp** [comment] 2020-03-20 09:55
@svor: [here it is](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/1384/artifact/logs-and-configs/workspace-logs/vscode-javapq5.container.log):
```
Error while starting endpoint:  Error: No matching bindings found for serviceIdentifier: Symbol(EnvVariablesServer)
    at _validateActiveBindingCount (/remote-endpoint/node_modules/inversify/lib/planning/planner.js:62:23)
    at _getActiveBindings (/remote-endpoint/node_modules/inversify/lib/planning/planner.js:48:5)
    at _createSubRequests (/remote-endpoint/node_modules/inversify/lib/planning/planner.js:91:26)
    at /remote-endpoint/node_modules/inversify/lib/planning/planner.js:115:17
    at Array.forEach (<anonymous>)
    at /remote-endpoint/node_modules/inversify/lib/planning/planner.js:114:26
    at Array.forEach (<anonymous>)
    at _createSubRequests (/remote-endpoint/node_modules/inversify/lib/planning/planner.js:94:20)
    at /remote-endpoint/node_modules/inversify/lib/planning/planner.js:115:17
    at Array.forEach (<anonymous>)
```

**Comment by dmytro-ndp** [comment] 2020-03-20 12:10
@svor: issue has been reproduced both with TLS enabled and disabled.

**Comment by dmytro-ndp** [comment] 2020-03-20 12:44
@svor: this time the issue was caused by changes in PR https://github.com/eclipse/che-theia/pull/676

**Comment by svor** [comment] 2020-03-20 13:05
this issue is not about Java LS. The problem is about It is about plugin-remote-endpoint . If execute  `bash-5.0$ ./remote-endpoint/plugin-remote-endpoint` in some container which provides remote plugin it returns
```log
Error while starting endpoint:  Error: No matching bindings found for serviceIdentifier: Symbol(EnvVariablesServer)
    at _validateActiveBindingCount (/remote-endpoint/node_modules/inversify/lib/planning/planner.js:62:23)
    at _getActiveBindings (/remote-endpoint/node_modules/inversify/lib/planning/planner.js:48:5)
    at _createSubRequests (/remote-endpoint/node_modules/inversify/lib/planning/planner.js:91:26)
    at /remote-endpoint/node_modules/inversify/lib/planning/planner.js:115:17
    at Array.forEach (<anonymous>)
    at /remote-endpoint/node_modules/inversify/lib/planning/planner.js:114:26
    at Array.forEach (<anonymous>)
    at _createSubRequests (/remote-endpoint/node_modules/inversify/lib/planning/planner.js:94:20)
    at /remote-endpoint/node_modules/inversify/lib/planning/planner.js:115:17
    at Array.forEach (<anonymous>)
```

**Closed as completed** 2020-03-21 06:05 UTC
Labels: kind/bug, severity/blocker, e2e-test/failure, area/plugins
