### ISSUE TITLE
Icons are missing from VSCode Extensions in che plugins

### ISSUE THREAD

**Issue by mohitsuman** [eclipse-che/che#14632] opened 2019-09-23 11:12 UTC
### Describe the bug

When we install a VSCode plugin , OpenShift Connector , the following icons are missing:
1. Navigation Bar icon for the extensions
2. Extension Icon on the Activity Bar
3. Icons for the tree node

### Che version
`Che-Theia@3acccea`
Eclipse Che version: `7.1.0`

### Steps to reproduce
1. Run Eclipse Che using Che operator
2. Install OpenShift Connector from Che Plugins
3. Reload workspace
4. Go to Activity Bar for the installed extension

### Expected behavior
The icons should be displayed on the Activity bar, navigation bar and on the tree nodes as it is on VSCode editor.

### Screenshots
<img width="943" alt="Screenshot 2019-09-23 at 4 37 46 PM" src="https://user-images.githubusercontent.com/3133356/65421096-826cd100-de20-11e9-8bd1-a793be182912.png">

### Installation method
   - [ ] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x ] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
The extension does not fetch the `latest` version of OpenShift Connector. There is an issue already for this https://github.com/eclipse/che/issues/14605

**Comment by ibuziuk** [comment] 2019-09-23 18:23
@vparfonov I recall there was some similar issue for missing icons. Is it smth that `ide` team plan to handle?

**Comment by azatsarynnyy** [comment] 2019-09-24 07:25
Here's related issue https://github.com/eclipse/che/issues/13750 that was fixed in the PR https://github.com/eclipse/che-theia/pull/430.
I suppose it's fixed locally on minishift/minikube only but it still reproduced on hosted Che.
cc @mmorhun

**Comment by mmorhun** [comment] 2019-09-24 07:57
It is strange, because the fix should work. Maybe it wasn't included in 7.1 release.
@mohitsuman if it is not hard for you, could you please test the case again but with `next` version of Che Theia?

**Closed as completed** 2019-10-30 15:53 UTC
Labels: kind/bug, severity/P2
