### ISSUE TITLE
Add getter/setter generator for Java classes

### ISSUE THREAD

**Issue by siamaksade** [eclipse-che/che#9732] opened 2018-05-17 12:52 UTC
Generating getter and setters for Java classes is currently possible by typing `get` or `set` and then using the code assistance to suggest various `getXXX()` and `setXXX()` methods. While this is ok for Java classes with few fields, it's not usable for larger classes. There should be an option to generate getters/setters and a dialog window to choose (checkbox) the fields similar to other IDEs

![getter setter](https://user-images.githubusercontent.com/1174934/40178475-d843deb2-59e1-11e8-9ed7-2d20b94888c2.png)

**Comment by eivantsov** [comment] 2018-05-18 04:35
@tolusha @tsmaeder is there anything like that in lang tools backlog?

**Comment by wgbeckmann** [comment] 2018-06-28 05:36
My Developer Team wants to cancel developing with Eclipse Che caused by missing this feature. It is a must for a JAVA IDE. So this is more a Bug then an Enhancement.

**Comment by siamaksade** [comment] 2018-07-03 15:21
@eivantsov has this been discussed for the roadmap?

**Comment by lmorel3** [comment] 2018-07-09 16:30
Writing getters and setters makes me mad! So, I also think it's a must have (at least for Java) and it should be implemented in Che ;)

**Comment by eivantsov** [comment] 2018-07-09 16:35
I can only post my previous comment: https://github.com/eclipse/che/issues/9732#issuecomment-390091799

@tsmaeder @slemeur do you think this is a must have for a superb Java support?

**Comment by slemeur** [comment] 2018-07-12 07:49
Generate getters/setters should be available with the JDT.LS from code actions: https://github.com/redhat-developer/vscode-java/issues/263

@tsmaeder : do you confirm?

**Comment by tsmaeder** [comment] 2018-07-12 08:02
@slemeur there is a quick fix for generating getters and setters for unused fields from jdt.ls. So currently the workflow could be: add a field, warning appears, ctrl-enter and select "createGetter and setter".

**Comment by lmorel3** [comment] 2018-07-12 08:11
@tsmaeder why not adding a new entry in the context menu? Something like "Generate code" for e.g. Then, a popup appears, you choose "Generate getters and setters", etc. 

This behavior would be de facto similar as the one in Eclipse IDE, but simpler.

**Comment by siamaksade** [comment] 2018-07-12 08:48
@tsmaeder the workaround is not sufficient as the user has to repeat it for every single field, one-bye-one. The ask is to create a generate getter/setter dialog to generate for all selected fields as @lmorel3 mentioned

**Comment by slemeur** [comment] 2018-07-18 16:08
@vparfonov : Could you consider adding a dialog to handle that?

**Comment by gorkem** [comment] 2019-08-23 16:40
Closing as this is available on Che 7 and Che 6 is not under active development

**Closed as completed by gorkem** 2019-08-23 16:40 UTC
Labels: kind/enhancement
