### ISSUE TITLE
Autogenerate debugger configuration for CHE Theia with help Theia generator.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#12193] opened 2018-12-14 08:59 UTC
### Description
It would be nice to have ability  auto-generate valid debugger configuration for Theia inside CHE. This configuration should be stored to the .theia folder and it should contains in the arguments --port=3130, --hostname=0.0.0.0.
CHE Theia generator - https://github.com/ws-skeleton/che-theia-generator

**Comment by gorkem** [comment] 2019-08-23 23:25
Sounds like https://github.com/theia-ide/theia/issues/4016

**Comment by tsmaeder** [comment] 2019-09-23 09:20
Closing as duplicate of https://github.com/eclipse-theia/theia/issues/4016

**Closed as completed by tsmaeder** 2019-09-23 09:20 UTC
Labels: kind/enhancement
