### ISSUE TITLE
devfile should allow to set `env` to chePlugin

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#15258] opened 2019-11-20 17:16 UTC
### Is your enhancement related to a problem? Please describe.
It is not possible to set env variable to a container of a che plugin

### Describe the solution you'd like
it would be nice if we could have in a devfile something that looks like:

```yaml
  - id: redhat/java/latest
    memoryLimit: 1536M
    type: chePlugin
    alias: java
    env:
      - value: '-Dmaven.repo.local=/projects/local/m2repo'
        name: MAVEN_OPTS
```

**Comment by benoitf** [comment] 2019-11-20 17:34
AFAIK it's a duplicate of https://github.com/eclipse/che/issues/14970

**Closed as completed** 2019-11-20 17:35 UTC
Labels: kind/enhancement, status/duplicate

**Comment by sunix** [comment] 2019-11-22 16:25
actually duplicate of https://github.com/eclipse/che/issues/14343
