### ISSUE TITLE
Import an existing workspace

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2660] opened 2016-09-29 18:53 UTC
The `Workspaces>Add Workspace` has an text input field for workspace configurations instead of what is displayed in `Dashboard>Create Workspace` which are locations of the of the workspace configuration. Can we provide an additional tab into `Dashboard>Create Workspace` called `Manual Entry` and use this for `Workspaces>Add Workspace` too? 

Not sure why we don't just use a single page for both. The only difference is using an existing workspace to add new projects to or creating new projects in a new workspace. Could we select `Create new workspace from stack` instead of `Select existing workspace` using an argument in the `/dashboard/#/create-project` url path and remove `/dashboard/#/create-workspace`? If this is the direction we want to go I can rewrite this issue.

![che-import2](https://cloud.githubusercontent.com/assets/20580888/18967420/c5948cf6-864a-11e6-9e22-6ec22eafb6ad.jpg)

![che-import1](https://cloud.githubusercontent.com/assets/20580888/18967423/c7bc4ed8-864a-11e6-94c0-9c421de32263.jpg)

**Comment by ashumilova** [comment] 2016-09-30 07:38
@JamesDrummond yes, we have "workspace" and "workspace + project creation" screens. They differ. On the first one - manually you enter workspace config. On the second screen - "Git Repository", "GitHub", "Zip" - there we provide source of the project. But yes - we are going to simplify it.

**Comment by bmicklea** [comment] 2016-10-03 12:54
@ashumilova is there an existing epic or issue that this duplicates then?

**Comment by ashumilova** [comment] 2016-10-04 05:49
No issue yet, we wanted to finalize this one https://github.com/eclipse/che/issues/1769, to use it and to see how to improve projects creation in this context.

**Comment by bmicklea** [comment] 2016-10-04 15:17
@JamesDrummond I'm going to close this issue as a duplicate of #1769 since that issue makes the two workspace creation flows identical and so solves this problem.

**Closed as completed by bmicklea** 2016-10-04 15:17 UTC
Labels: kind/enhancement
