### ISSUE TITLE
Emtpy list of workspaces after being logged out

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#19106] opened 2021-02-19 09:53 UTC
### Describe the bug
After being logged out of a workspace because of a timeout, I clicked on the "workspaces" tab in the left sidebar. I am shown an empty list of workspace, even though I have three workspaces.

### Che version

 7.26.0

### Steps to reproduce
See description

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [x] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl server:update
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify
Firefox

### Eclipse Che Logs
This is seen in the browser console:
```
Uncaught (in promise) Error: Failed to request workspaces: 
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
    requestWorkspaces https://che-eclipse-che.10.20.30.61.nip.io/dashboard/client.js:1
    r https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:114
    f https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:33
    componentDidMount https://che-eclipse-che.10.20.30.61.nip.io/dashboard/5.b99a7afd5a788480f927.js:1
    ic https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:130
    ds https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:130
    unstable_runWithPriority https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:138
    Wo https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:130
    us https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:130
    Qc https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:130
    Ko https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:130
    unstable_runWithPriority https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:138
    Wo https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:130
    Ko https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:130
    N https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:138
    onmessage https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:138
    EventHandlerNonNull* https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:138
    s https://che-eclipse-che.10.20.30.61.nip.io/dashboard/client.js:1
    <anonymous> https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:130
    s https://che-eclipse-che.10.20.30.61.nip.io/dashboard/client.js:1
    <anonymous> https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:130
    s https://che-eclipse-che.10.20.30.61.nip.io/dashboard/client.js:1
    <anonymous> https://che-eclipse-che.10.20.30.61.nip.io/dashboard/vendor.a313ca360767839a01d0.js:25
    s https://che-eclipse-che.10.20.30.61.nip.io/dashboard/client.js:1
    2789 https://che-eclipse-che.10.20.30.61.nip.io/dashboard/client.js:1
    s https://che-eclipse-che.10.20.30.61.nip.io/dashboard/client.js:1
    n https://che-eclipse-che.10.20.30.61.nip.io/dashboard/client.js:1
    <anonymous> https://che-eclipse-che.10.20.30.61.nip.io/dashboard/client.js:1
    <anonymous> https://che-eclipse-che.10.20.30.61.nip.io/dashboard/client.js:1
client.js:1:7175
```

**Comment by tsmaeder** [comment] 2021-02-19 09:54
Refreshing the page fixes the problem

**Comment by amisevsk** [comment] 2021-02-19 15:54
I suspect this is a duplicate of https://github.com/eclipse/che/issues/19020, which was fixed yesterday but isn't available in 7.26 afaik.

**Comment by sleshchenko** [comment] 2021-02-22 10:40
I expect it to be fixed by https://github.com/eclipse/che-dashboard/pull/172(not merged yet) or https://github.com/eclipse/che-dashboard/pull/171 (merged, related to issue Angel shared).
It should be retested after these PRs

**Comment by sleshchenko** [comment] 2021-03-24 12:49
After I tried to wait until session is expired - I was redirected to login page after the first made operation. So, closing it but let us know if you still face the described issue.

**Closed as completed by sleshchenko** 2021-03-24 12:49 UTC
Labels: kind/bug, severity/P1, area/dashboard
