### ISSUE TITLE
Tasks are not ended properly

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#19821] opened 2021-05-18 14:17 UTC
### Describe the bug
When start a task from the My workspace view by quickly clicking many times on it, it is not ended properly (IDE doesn't show "✓", but still shows spinning wheel) and the next task execution can't be started. 

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Use this devfile to create a workspace:
```yaml
apiVersion: 1.0.0
metadata:
  name: test-workspace
components:
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    image: 'quay.io/eclipse/che-java11-maven:nightly'
    alias: maven
commands:
  - name: Click me many times
    actions:
      - type: exec
        command: echo 'Command was finished'
        component: maven
```
2. Try to click quickly many times on **Click me many times** from Workspace view
3. See that the task never finish and it is not possible to re-run it

### Expected behavior
Task should be finished properly 

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

https://user-images.githubusercontent.com/1271546/127866606-84582247-6687-4f3e-a5e7-cea5d4810a8a.mp4

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

**Comment by svor** [comment] 2021-07-28 11:55
downstream issue https://issues.redhat.com/browse/CRW-1782

**Comment by tsmaeder** [comment] 2021-08-02 13:57
So the issue is that we manage to create parallel instances of the same task, but we can never get rid of the second one and it doesn't get marked as finished?

**Comment by svor** [comment] 2021-08-12 09:50
https://github.com/eclipse-theia/theia/pull/9858 should fix the problem

**Comment by nickboldt** [comment] 2021-08-24 13:10
given PR was merged and 7.35.0 is live, can we verify this is fixed?

**Comment by tsmaeder** [comment] 2021-08-24 13:46
The PR was merged this morning.

**Comment by nickboldt** [comment] 2021-09-10 17:24
PR merged, but label = sprint/next... so I'm guessing this slips to 7.37.

**Comment by svor** [comment] 2021-09-17 08:11
Currently blocked by: Align che-theia with upstream changes #20366

**Closed as completed** 2021-10-13 20:12 UTC
Labels: kind/bug, sprint/current, severity/P1, area/plugins
