### ISSUE TITLE
"volumes" not Supported Anymore for Plugins

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#16029] opened 2020-02-13 15:02 UTC
We used to allow volumes to be mounted inside Che plugins. The Java stack used this to avoid downloading all maven dependencies twice (one in the maven container, once for the IDE plugin). 
This ability seems to have been lost.

**Comment by tsmaeder** [comment] 2020-02-13 15:31
We can argue whether this is a bug or an enhancement, but it used to work, at least in the pre-devfile days. Other issues like https://github.com/eclipse/che/issues/16018 seem to depend on this being possible.

**Comment by skabashnyuk** [comment] 2020-02-14 07:28
@tsmaeder thank you for this report. To avoid misunderstanding can you please follow the bug template rule and provide more context about this accident. At this moment I'm working with such a devfilehttps://github.com/skabashnyuk/che/blob/cheserverdevfile/devfile.yaml#L10-L12  and don't have the feeling that volumes are not supported or you talking about defining volumes in meta.yaml? I would really appreciate it if you provide more information to avoid guessing and properly assign this task. Thanks.

**Comment by tsmaeder** [comment] 2020-02-14 08:00
"inside Che plugins" is the important part there. It works for components of type "dockerfile", but not "chePlugin".

**Comment by skabashnyuk** [comment] 2020-02-14 08:15
>"inside Che plugins" is the important part there. It works for components of type "dockerfile", but not "chePlugin".

ok

>can you please follow the bug template

Pleeeezzeee.
![image](https://user-images.githubusercontent.com/1614429/74513313-94076000-4f0a-11ea-898c-c0cf1198681d.png)

**Comment by amisevsk** [comment] 2020-02-14 20:51
I could not reproduce this on nightly (or 7.8.0), using a new java-maven workspace:
```bash
oc get po workspace563o04vk1p1o2yo5.maven-7b7d676d68-9c8xr -o yaml | yq '.spec.containers[] | select(.name | test("vscode-java")) | .volumeMounts'
[
  {
    "mountPath": "/home/theia/.m2",
    "name": "m2",
    "subPath": "workspace563o04vk1p1o2yo5/m2/"
  },
#...
```

**Comment by sleshchenko** [comment] 2020-02-17 08:32
@tsmaeder Please elaborate more info when you fill in a new bug, it could save time.
Maybe a plugin version you use is an old one, like [redhat/java/0.55.1](https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/redhat/java/0.55.1/meta.yaml) has maven volume declared but [redhat/java/0.46.0](https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/redhat/java/0.46.0/meta.yaml) does not.

**Comment by tsmaeder** [comment] 2020-02-17 09:19
@amisevsk if you put "volumes" inside a che plugin component in a devfile, it gets flagged as an error in the editor. If you put it inside a "dockerfile" component, it is accepted.

**Comment by tsmaeder** [comment] 2020-02-17 09:21
> 
> Maybe a plugin version you use is an old one, like [redhat/java/0.55.1](https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/redhat/java/0.55.1/meta.yaml) has maven volume declared but [redhat/java/0.46.0](https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/redhat/java/0.46.0/meta.yaml) does not.

I'm talking about devfiles, not meat.yml

**Comment by sleshchenko** [comment] 2020-02-17 09:23
> I'm talking about devfiles, not meat.yml

Good to know. If you provide devfile content you use - I will help you to figure out that plugin version you use ;)

**Comment by tsmaeder** [comment] 2020-02-17 09:27
@sleshchenko  how to reproduce:

1. Open any devfile in the devfile editor
2. Go to any component that is a plugin
3. Try to add a "volumes" section
4. Observe: the editor complains that "volumes" is not allowed here.

**Comment by skabashnyuk** [comment] 2020-02-17 09:30
@tsmaeder This issue looks like a duplicate:


 - Support `volumes` for components of type kubernetes/openshift | https://github.com/eclipse/che/issues/15122
- devfile: che plugins (vscode) and che editors should accept volumes | https://github.com/eclipse/che/issues/15122

**Comment by tsmaeder** [comment] 2020-02-17 09:43
@skabashnyuk I guess, but I don't really understand what @metlos is asking for. I definitely don't want the volumes applied on _the same path_ in all components.

**Comment by skabashnyuk** [comment] 2020-02-17 09:46
> I guess, but I don't really understand what @metlos is asking for. I definitely don't want the volumes applied on the same path in all components.

I don't really understand what you are asking for.   It would be really nice if you exactly explain what do you want.

**Comment by tsmaeder** [comment] 2020-02-17 09:55
I want to be able to mount a volume at a path I chose (different for different components) in plugins and editors. Just like I now can in "dockerimage" components.

**Comment by skabashnyuk** [comment] 2020-02-17 10:09
Closing as duplicate of https://github.com/eclipse/che/issues/13318 . If you have any concerns about this new feature implementation please comment https://github.com/eclipse/che/issues/13318

**Closed as completed by skabashnyuk** 2020-02-17 10:09 UTC
Labels: kind/bug, status/info-needed, severity/P1, area/che-server
