### ISSUE TITLE
OpenShift Connector does not work on workspaces.openshift.com

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#20229] opened 2021-07-30 13:30 UTC
### Describe the bug
After enabling the OpenShift Connector plugin in devfile via

```
  - id: redhat/vscode-openshift-connector/latest
    type: chePlugin
    alias: openshift-connector
 ```

it is not possible to work with a plugin from workspace since the view is empty and does not list any projects
 

### Che version
CRW 2.9

### Steps to reproduce
Create a workspace with openshift-connector plugin enabled:

```
  - id: redhat/vscode-openshift-connector/latest
    type: chePlugin
    alias: openshift-connector
 ```

### Expected behavior
 openshift-connector plugin view lists projects

**Comment by nickboldt** [comment] 2021-07-30 13:33
Dupe of https://issues.redhat.com/browse/CRW-2071 ?

**Comment by ibuziuk** [comment] 2021-07-30 13:51
no, it does not look the same - on workspaces.openshift.com there are even no projects listed and the plugin is literally unusable:
![image](https://user-images.githubusercontent.com/1461122/127662960-60240e6d-4276-4640-9be7-80f1682db84d.png)

**Comment by ibuziuk** [comment] 2021-07-30 13:57
After a couple of restarts I was able to get the projects, but I still can not see resources like pods, services, routes etc. is it expected?

![image](https://user-images.githubusercontent.com/1461122/127663803-8323a661-7344-4c61-9947-1b59a7257068.png)

The plugin looks unusable atm

**Comment by edeandrea** [comment] 2021-07-30 14:00
What if you also have the `redhat/vscode-yaml/latest` plugin in your devfile? Or if you already have it, remove it?

I had seen this a while back where there was some version incompatibilities between the openshift connector plugin & the vscode-yaml plugin.

**Comment by ibuziuk** [comment] 2021-07-30 14:20
this does not seem to help much - it is still not clear how to list resources like pods, routes, scv with the OpenShift Connector

**Comment by svor** [comment] 2021-08-11 10:07
>After a couple of restarts, I was able to get the projects, but I still can not see resources like pods, services, routes etc. is it expected?

@vinokurig ^^

**Comment by vinokurig** [comment] 2021-08-17 10:00
https://github.com/eclipse-che/che-plugin-registry/pull/1028 fixes the problem for Eclipse Che and https://github.com/redhat-developer/codeready-workspaces/commit/9157c2f9ca1fe8f2106d6590fb222b7144e4bacc is the same fix for the downstream CRW. I still can reproduce the problem in the `workspaces.openshift.com` when I manually paste the authentication plugin reference to the devFile, so let's not close the issue until the fix is released and we could properly test it in the `workspaces.openshift.com`.

**Comment by ibuziuk** [comment] 2021-09-15 14:01
@vinokurig tried to verify the connector on staging 2.11 but got pretty much the same result
![image](https://user-images.githubusercontent.com/1461122/133447657-b39166be-409e-4f2d-aeb7-282b3a0ed6e5.png)

I can not see any namespaces, pods, svc etc. only cluster IP. is it expected?

**Comment by svor** [comment] 2021-09-16 07:09
@vinokurig will take a look once he gets back from PTO

**Comment by vinokurig** [comment] 2021-10-06 07:10
It works for me:
![screenshot-codeready-codeready-workspaces-operator apps sandbox-m2 ll9k p1 openshiftapps com-2021 10 06-09_48_54](https://user-images.githubusercontent.com/7668752/136153922-29b0843b-8460-4df9-b019-653a3e835c47.png)

@ibuziuk Looks like your browser blocks the authentication popup. If so you should allow showing the popup and restart the workspace. You should see a notification about that:
![screenshot-nimbus-capture-2021 10 06-10_07_36](https://user-images.githubusercontent.com/7668752/136156337-f524cc73-8a91-4800-85d4-20a9efe2c2c0.png)

**Closed as completed** 2021-10-19 09:24 UTC
Labels: kind/bug, sprint/current, severity/P1, area/plugins
