### ISSUE TITLE
The file watcher does not track events properly after defined cases

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#7092] opened 2017-10-30 15:57 UTC
### Step to reproduce
**Use-case with creating new package:** 
* Create a workspace base on Java stack. Open it and create the Spring project. Expand the project to org.eclipse.che.examples and select the package. 
* Project -> New -> Java Package -> type package like: com.somepackage (with dot)
**Actual result:** The just created package has not appeared in the Project explorer.
**Expected result** the package should displayed in Project explorer

**Use-case with deleting items from IDE:**
Precondition: use two browser windows #1 and #2
* Create a workspace base on Java stack. Open it and create the Spring project. in the browser #1. Expand the project. Open the READ.me file.
* Go to the just created workspace in the browser #2. Select and open the README file too. 
* Delete the file trough IDE

**Use-case with coloring files under git**
* Create for  the Spring project with wizard and change content a file.
**Expected result** the color of just edited in Project Explorer and opened tab file should be changed.
**Actual result:** The file in Project Explorer and tab remains the same

**Comment by RomanNikitenko** [comment] 2017-11-17 14:51
I've tested it on branch related to https://github.com/eclipse/che/pull/7380 and the issue is already fixed there.
So I'm closing the issue.

**Closed as completed** 2017-11-17 14:52 UTC
Labels: kind/bug, sprint/current
