### ISSUE TITLE
che-theia happy path tests failing since June 8

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17144] opened 2020-06-11 14:52 UTC
### Describe the bug

Even [no-op changes to the code base, like a .md file](https://github.com/eclipse/che-theia/pull/772), cause the happy path tests to fail. This means we cannot rely on these tests as a measure of quality.

They should be:

* fixed, or
* simplified to remove the parts that are flaky, or 
* disabled entirely if they can't be fixed or adjusted to remove the flaky bits.

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Submit a PR.
2. Wait for e2e tests to fail.
3. resubmit. repeat waiting/failing.

![image](https://user-images.githubusercontent.com/227597/84401626-7e145e00-abd1-11ea-8046-6e8378a519da.png)

Examples:

https://github.com/eclipse/che-theia/pull/772 (added an empty line to a .md file, should pass)
https://github.com/eclipse/che-theia/pull/770 (simply change that works locally, should not fail test)
https://github.com/eclipse/che-theia/pull/739 (used to pass a couple weeks ago, now failing)

### Expected behavior

Tests should accurately trap for failures, not be a source of failure themselves.

**Comment by sunix** [comment] 2020-06-11 15:05
We should at least know why it is failing but cannot access to https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/1379/ .... (one of the link in the job)

**Comment by nickboldt** [comment] 2020-06-11 15:22
```
10:50:04 [3/4] Linking dependencies...
10:50:04 warning " > tslint-language-service@0.9.9" has incorrect peer dependency "typescript@>= 2.3.1 < 3".
10:50:04 warning " > tslint-language-service@0.9.9" has incorrect peer dependency "tslint@>= 4 < 6".
10:50:04 warning " > ts-jest@22.4.3" has incorrect peer dependency "typescript@2.x".
10:50:04 warning "workspace-aggregator-a62c531f-a389-42f5-9aa6-6f5ed970a4a3 > @eclipse-che/che-theia-hosted-plugin-manager-extension > @theia/plugin-dev > @theia/plugin-ext > @theia/messages > react-perfect-scrollbar@1.5.8" has unmet peer dependency "react@>=16.3.3".
10:50:04 warning "workspace-aggregator-a62c531f-a389-42f5-9aa6-6f5ed970a4a3 > @eclipse-che/che-theia-hosted-plugin-manager-extension > @theia/plugin-dev > @theia/plugin-ext > @theia/messages > react-perfect-scrollbar@1.5.8" has unmet peer dependency "react-dom@>=16.3.3".
10:50:04 warning "workspace-aggregator-a62c531f-a389-42f5-9aa6-6f5ed970a4a3 > @eclipse-che/che-theia-hosted-plugin-manager-extension > @theia/plugin-dev > @theia/plugin-ext > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
10:50:04 warning "workspace-aggregator-a62c531f-a389-42f5-9aa6-6f5ed970a4a3 > @eclipse-che/che-theia-hosted-plugin-manager-extension > @theia/plugin-dev > @theia/plugin-ext > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
10:50:04 warning Workspaces can only be enabled in private projects.
10:50:15 [4/4] Building fresh packages...
10:50:19 error /mnt/hudson_workspace/workspace/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/node_modules/vscode-ripgrep: Command failed.
10:50:19 Exit code: 1
10:50:19 Command: node ./lib/postinstall.js
10:50:19 Arguments: 
10:50:19 Directory: /mnt/hudson_workspace/workspace/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/node_modules/vscode-ripgrep
10:50:19 Output:
10:50:19 Finding release for v11.0.1-2
10:50:19 GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v11.0.1-2
10:50:19 Deleting invalid download cache
10:50:19 Downloading ripgrep failed: Error: Request failed: 401
10:50:19     at ClientRequest.https.get.response (/mnt/hudson_workspace/workspace/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/node_modules/vscode-ripgrep/lib/download.js:106:24)
10:50:19     at Object.onceWrapper (events.js:277:13)
10:50:19     at ClientRequest.emit (events.js:189:13)
10:50:19     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
10:50:19     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
10:50:19     at TLSSocket.socketOnData (_http_client.js:442:20)
10:50:19     at TLSSocket.emit (events.js:189:13)
10:50:19     at addChunk (_stream_readable.js:284:12)
10:50:19     at readableAddChunk (_stream_readable.js:265:11)
10:50:19     at TLSSocket.Readable.push (_stream_readable.js:220:10)
10:50:19 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
10:50:28 Build step 'Execute shell' marked build as failure
```
-- https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/1379/console

(you just have to turn on your VPN if you want to see that server)

**Comment by dmytro-ndp** [comment] 2020-06-11 16:57
@nickboldt: thanks for reporting an issue.
Actually, the title doesn't look correctly, because Che-theia happy path tests had started failing few days ago - from 8th June:
![Screenshot from 2020-06-11 19-50-05](https://user-images.githubusercontent.com/1197777/84416411-d91f7280-ac1c-11ea-9b4d-bd85971e7c77.png)

**Comment by nickboldt** [comment] 2020-06-11 17:17
OK, then how about https://github.com/eclipse/che-devfile-registry/pull/242#pullrequestreview-429065548
? Seems that THOSE tests are also broken.

**Comment by ericwill** [comment] 2020-06-11 17:42
Regarding the devfile registry PR check, I spoke to Radim about it and he's opened #17135 to start.

**Comment by azatsarynnyy** [comment] 2020-06-16 06:50
if the problem is related to
`GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v11.0.1-2`
`Downloading ripgrep failed: Error: Request failed: 401`
it should be fixed by setting `GITHUB_TOKEN` env. var.

**Comment by tsmaeder** [comment] 2020-06-16 07:53
There is a theia issue that might be related: https://github.com/eclipse-theia/theia/issues/2091

**Comment by dmytro-ndp** [comment] 2020-06-17 08:02
Happy path PR check has been fixed https://github.com/eclipse/che-theia/pull/772#issuecomment-645209946
It was GITHUB_TOKEN problem. Thank you, @azatsarynnyy, for advice.

**Closed as completed by dmytro-ndp** 2020-06-17 08:02 UTC
Labels: kind/bug, status/in-progress, severity/P1, area/ci, area/qe, new&noteworthy
