### ISSUE TITLE
Che is always asking if changes made should be overwritten ...

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16751] opened 2020-04-25 12:54 UTC
### Describe the bug
Editing a file like devfile.yaml in this project: https://che.openshift.io/factory?url=https://github.com/sunix/record-preview-feature-java15

### Che version

 - [x] 7.11.0 on che.openshift.io

### Steps to reproduce
1. Run this devfile:
2. Edit the devfile.yaml in the project 
3. Constantly, Che is showing the popup which is making the development very hard 
![image](https://user-images.githubusercontent.com/650571/80280489-a836bd00-8704-11ea-921e-6861aa56c35c.png)

### Workaround
Issue can be helped by either increasing the auto-save interval or disabling auto-save in Theia.

**Comment by sunix** [comment] 2020-04-26 09:18
maybe it is because it is not ephemeral ....

**Comment by ibuziuk** [comment] 2020-04-27 10:59
> maybe it is because it is not ephemeral ....
does it happen only in the non-ephemeral mode?

**Comment by sunix** [comment] 2020-04-27 11:09
just tested it doesn't happen

**Comment by ibuziuk** [comment] 2020-04-27 11:33
> just tested it doesn't happen

does not happen at all? could you please provide more details and steps to repro in the issue description?

**Comment by sunix** [comment] 2020-04-27 11:33
trying to remove some workspaces ... maybe related to the storage and number of files in volumes ...

**Comment by sunix** [comment] 2020-04-27 11:39
OK I have remove some workspaces and it seems to be better
It looks like
- you save it
- the file is getting saved ... but take a while
- Because of the delay, Che thinks the changes is not related to the previous change ... but it does

**Comment by sunix** [comment] 2020-04-27 12:04
mh it's happening again .... even after removed all my workspaces ...

**Comment by ibuziuk** [comment] 2020-04-27 15:55
@sunix is it Hosted Che specific, or happens the very same way in the upstream?

**Comment by sunix** [comment] 2020-04-29 06:57
Hi @ibuziuk  I have the feeling that it is happening only on my machine ... I am setting p2 unless someone else is raising the problem...

**Comment by digiltd** [comment] 2020-06-25 10:10
I can confirm this happens with myself and colleagues. Seems ok for a bit then will start asking you to confirm overwriting the file. Sometimes closing the file tab and reopening the file fixes it temporarily.

**Comment by digiltd** [comment] 2020-06-25 10:12
Developing Magento 2, so a massive codebase, typically ~50,000 files.

**Comment by sunix** [comment] 2020-06-25 11:56
@ibuziuk I don't know how much people are affected. Could we monitor that. I think we should work on that and make that detection a bit more robust ... even on slow storage.

**Comment by amisevsk** [comment] 2020-07-28 17:24
I'm encountering this pretty constantly when trying to work on the Che docs. I'm using Hosted Che with persistent storage, so I suspect it's a Gluster issue.

**Comment by digiltd** [comment] 2020-07-30 13:45
>It's especially frustrating as the notification steals focus from the editor, so even after closing it you can't continue typing in the file.

i feel your pain

**Comment by sunix** [comment] 2020-07-30 13:51
what i do is disabling auto-save ... or setting 20 seconds ....

**Comment by amisevsk** [comment] 2020-07-30 16:50
@sunix good suggestion for the mean time -- I've added it to the issue description so that it's easier to find.

**Comment by sunix** [comment] 2020-08-20 10:56
so async storage could be a way to solve that one.

**Comment by amisevsk** [comment] 2020-08-20 21:16
Having used async storage a fair bit now, it seems to be a good workaround.

**Comment by vzhukovskii** [comment] 2020-08-26 12:02
Could be related: https://github.com/eclipse/che/issues/17704

**Comment by sunix** [comment] 2020-08-26 12:09
@amisevsk How do you enable async storage in che.openshift.io BTW?
![image](https://user-images.githubusercontent.com/650571/91301750-b75a7400-e7a5-11ea-8160-8bfc77541b2a.png)

**Comment by amisevsk** [comment] 2020-08-26 16:54
@sunix See: https://github.com/eclipse/che/issues/17590

I typically add it manually by adding
```yaml
attributes:
  asyncPersist: 'true'
  persistVolumes: 'false'
```
to my devfie.

**Comment by vzhukovskii** [comment] 2020-09-15 14:51
Will post result of investigation of this issue.

All the results are actual for the commit https://github.com/eclipse-theia/theia/commit/1e09b816511769eb206494c1bac1a595e95795f9, not for the Theia master head as Che-Theia hasn't been updated to use Theia's master head.

So, when user opens file in editor, Theia tries to get `fs.Stat` for the specific uri. Autosave mechanism automatically call method [to save the state of currently changed file](https://github.com/eclipse-theia/theia/blob/68386d9d05f397ef720df34f59b722b59177d1cc/packages/monaco/src/browser/monaco-editor-model.ts#L404) with passing current [FileStat](https://github.com/eclipse-theia/theia/blob/5de8eee9596ce22e005777bd5cdaa43ff251ae72/packages/filesystem/src/common/filesystem.ts#L269) object by calling the following method calls: [Resource.save](https://github.com/eclipse-theia/theia/blob/68386d9d05f397ef720df34f59b722b59177d1cc/packages/monaco/src/browser/monaco-editor-model.ts#L424) > [saveContents](https://github.com/eclipse-theia/theia/blob/e2df38527582adcf49941ff8f1ae4e4f6fbd66f7/packages/filesystem/src/browser/file-resource.ts#L108) > [doSaveContents](https://github.com/eclipse-theia/theia/blob/e2df38527582adcf49941ff8f1ae4e4f6fbd66f7/packages/filesystem/src/browser/file-resource.ts#L127) > [setContent](https://github.com/eclipse-theia/theia/blob/9aab1f7aaeacd76456d83c21685eb23d96b205b5/packages/filesystem/src/node/node-filesystem.ts#L89).

[setContent](https://github.com/eclipse-theia/theia/blob/9aab1f7aaeacd76456d83c21685eb23d96b205b5/packages/filesystem/src/node/node-filesystem.ts#L89-L110)'s method body located here.

Theia tries to obtain new `fs.Stat` object for the same `FileStat` by calling [doCreateFileStat](https://github.com/eclipse-theia/theia/blob/9aab1f7aaeacd76456d83c21685eb23d96b205b5/packages/filesystem/src/node/node-filesystem.ts#L523) and tries [to compare](https://github.com/eclipse-theia/theia/blob/9aab1f7aaeacd76456d83c21685eb23d96b205b5/packages/filesystem/src/node/node-filesystem.ts#L164) modification time and size with the last one, passed by the method chain call.

When there're many changes made in the same file for the short period of time we can observe such situation, provided by the following log:

_log for the `fs.Stat` object passed from the editor:_
```
2020-09-15 13:26:35.539 root INFO doCreateFileStat: uri = file:///projects/record-preview-feature-java15/devfile.yaml, stat = {
    "dev": 1048600,
    "mode": 33188,
    "nlink": 1,
    "uid": 1202920000,
    "gid": 0,
    "rdev": 0,
    "blksize": 131072,
    "ino": 13763576696610406000,
    "size": 1840,
    "blocks": 4,
    "atimeMs": 1600176395528.138,
    "mtimeMs": 1600176395535.138,
    "ctimeMs": 1600176395536.1377,
    "birthtimeMs": 1600176395536.1377,
    "atime": "2020-09-15T13:26:35.528Z",
    "mtime": "2020-09-15T13:26:35.535Z",
    "ctime": "2020-09-15T13:26:35.536Z",
    "birthtime": "2020-09-15T13:26:35.536Z"
}
```

_log for the new `fs.Stat` object to be compared:_
```
2020-09-15 13:26:37.036 root INFO doCreateFileStat: uri = file:///projects/record-preview-feature-java15/devfile.yaml, stat = {
    "dev": 1048600,
    "mode": 33188,
    "nlink": 1,
    "uid": 1202920000,
    "gid": 0,
    "rdev": 0,
    "blksize": 131072,
    "ino": 13763576696610406000,
    "size": 1840,
    "blocks": 4,
    "atimeMs": 1600176379374.7065,
    "mtimeMs": 1600176395535.6855,
    "ctimeMs": 1600176395536.6855,
    "birthtimeMs": 1600176395536.6855,
    "atime": "2020-09-15T13:26:19.375Z",
    "mtime": "2020-09-15T13:26:35.536Z",
    "ctime": "2020-09-15T13:26:35.537Z",
    "birthtime": "2020-09-15T13:26:35.537Z"
}
```

as you can see, `atimeMs`, `mtimeMs`, `ctimeMs` represents time in milliseconds with **_nanoseconds_**.

Theia transforms this `fs.Stat` into `FileStat` and takes modification time by calling [stat.mtime.getTime()](https://github.com/eclipse-theia/theia/blob/9aab1f7aaeacd76456d83c21685eb23d96b205b5/packages/filesystem/src/node/node-filesystem.ts#L527) which has time in milliseconds rounded by nanoseconds value. 

You can observe it in above logs:

```
"mtime": "2020-09-15T13:26:35.535Z" >>  1600176395535ms
```

against
```
"mtime": "2020-09-15T13:26:35.536Z" >> 1600176395536ms
```

As the result comparison these two values give us two different values for the modification time in [checkInSync](https://github.com/eclipse-theia/theia/blob/9aab1f7aaeacd76456d83c21685eb23d96b205b5/packages/filesystem/src/node/node-filesystem.ts#L164) method. Thats why method [isInSync](https://github.com/eclipse-theia/theia/blob/9aab1f7aaeacd76456d83c21685eb23d96b205b5/packages/filesystem/src/node/node-filesystem.ts#L157) [calls client dialogue](https://github.com/eclipse-theia/theia/blob/9aab1f7aaeacd76456d83c21685eb23d96b205b5/packages/filesystem/src/node/node-filesystem.ts#L161) to overwrite changes.

We can refer to slow i/o of glusterfs when there're a lot modifications come from outside to update the one file and sometimes we have inconsistent modification time for the file that differs in 1 millisecond.

As the possible solutions there're two variants how we can resolve this issue:

1. Fast and requires changes only in Che-Theia:
> To rebind [FileShouldOverwrite](https://github.com/eclipse-theia/theia/blob/135af5d94bf21c4cbb3afcce57601c75459d8b6a/packages/filesystem/src/browser/filesystem-frontend-module.ts#L44-L53) class to take into account that there is a such bias in modification time. By adding check if difference between two modification time is not bigger than 1 milliseconds.
 
2. Slow and requires changes in Theia upstream:
> To replace [lastModification: stat.mtime.getTime()](https://github.com/eclipse-theia/theia/blob/9aab1f7aaeacd76456d83c21685eb23d96b205b5/packages/filesystem/src/node/node-filesystem.ts#L527) with integer value of milliseconds, not taking into account value of nanoseconds. But from the other hand there're new FS Api has been merged recently and need to check how it reproduces on Theia's master head. Which is difficult to do at this moment.

**Comment by amisevsk** [comment] 2020-09-15 18:09
That's a great explanation @vzhukovskii, thanks.

**Comment by azatsarynnyy** [comment] 2020-09-16 08:57
Thank you @vzhukovskii for an excellent analysis!
If this can be reproduced in vanilla Theia then let's try to contribute it upstream first.

**Comment by vzhukovskii** [comment] 2020-09-16 11:43
> Thank you @vzhukovskii for an excellent analysis!
> If this can be reproduced in vanilla Theia then let's try to contribute it upstream first.

Got it

**Comment by azatsarynnyy** [comment] 2020-09-17 08:56
update:
We've decided to start with a quick fix in Che Theia https://github.com/eclipse/che-theia/pull/862
And propose a related patch in upstream Theia.

**Closed as completed** 2020-09-24 13:54 UTC
Labels: kind/bug, severity/P1, area/editor/theia
