### ISSUE TITLE
eclipseche+keycloak facing issue on kubernetes HTTP Status 401 – Unauthorized

### ISSUE THREAD

**Issue by hari1992-web** [eclipse-che/che#16664] opened 2020-04-20 06:09 UTC
Type Status Report

Message Authorization token is missing

Description The request has not been applied because it lacks valid authentication credentials for the target resource.
![Screenshot from 2020-04-20 11-35-47](https://user-images.githubusercontent.com/62592574/79719192-9f587c80-82fb-11ea-98d7-47591b9e2060.png)

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by ericwill** [comment] 2020-04-20 17:37
Can you please provide steps to reproduce the issue, as well as your version and deployment information about Che?

**Comment by l0rd** [comment] 2020-07-29 20:55
Closing this issue since there are no instruction to reproduce it. @hari1992-web feel free to provide detailed instructions to reproduce the problem and re-open this issue.

**Closed as completed by l0rd** 2020-07-29 20:55 UTC
Labels: kind/bug, status/info-needed, severity/P1
