### ISSUE TITLE
Theia doesn't update command's previewUrl on 2nd workspace start

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#14803] opened 2019-10-07 23:30 UTC
### Describe the bug
When workspace is started 2nd time, commands attributes are not updated. This happens for `previewUrl`. Preview url is dynamic attribute. It is different at each workspace startup, because randomly named kubernetes services/ingresses are created for it. Theia probably caches some values, which is problem here.

From attached screenshot you can see that in response for workspace, `previewUrl` is different than the one that Theia tries to open.

### Che version

 - [x] other: please specify
PreviewUrl in devfile is not merged yet. It is implemented in this task https://github.com/eclipse/che/issues/13945 and PR is currently open https://github.com/eclipse/che/pull/14713
I've prepared test server image `quay.io/mvala/che-server:previewurl`

### Steps to reproduce
1. Start workspace with command that has previewurl
1. Stop the workspace
1. Start the workspace again
1. Run the command with previewurl
1. Opened url does not exists because the ingress host is different

### Expected behavior
Commands should be updated with values received from the server.

### Runtime
   - [x] minikube

### Screenshots
![theia-previewurl2](https://user-images.githubusercontent.com/1160903/66356240-a37a0980-e96a-11e9-9d77-ee008915736f.png)

### Installation method
   - [x] helm

### Environment
   - [x] my computer
       - [x] Linux

### Additional context
Support for preview url in devfile task https://github.com/eclipse/che/issues/13945 + PR https://github.com/eclipse/che/pull/14713

**Comment by sparkoo** [comment] 2019-10-08 14:32
previewUrl might be replaced with ${server.<servername>} variable. I'm working on it in previewurl devfile support PR

**Comment by sparkoo** [comment] 2019-10-08 15:40
> previewUrl might be replaced with ${server.} variable. I'm working on it in previewurl devfile support PR

works fine. previewurl PR is updated https://github.com/eclipse/che/pull/14713

**Comment by l0rd** [comment] 2019-10-08 18:21
@sparkoo should we close this issue then?

**Comment by sparkoo** [comment] 2019-10-08 19:19
@l0rd I need to verify that with @RomanNikitenko. This might still be an issue.

**Comment by RomanNikitenko** [comment] 2019-10-09 07:07
@sparkoo 
I tested [your changes](https://github.com/eclipse/che/pull/14713) using `quay.io/mvala/che-server:previewurl` image.

I defined the configuration in `devfile`
```- name: run on 8081 and /hello path
  previewUrl:
    port: 8081
    path: "/hello"
  actions:
      -
        type: exec
        component: go-cli
        command: "go run main.go 8081 /hello"
        workdir: ${CHE_PROJECTS_ROOT}/dummy-http-server
```
and got the following configuration in `tasks.json` file:
```
           {
                "type": "che",
                "label": "run on 8081 and /hello path",
                "command": "go run main.go 8081 /hello",
                "target": {
                    "workingDir": "${CHE_PROJECTS_ROOT}/dummy-http-server",
                    "containerName": "go-cli"
                },
                "previewUrl": "${server.8081/tcp}/hello"
            },
```
We keep preview url as variable: ```${server.8081/tcp}/hello``` for a task configuration and resolve the variable in runtime at rendering widgets and so on
So, I don't see any problems at the moment for case when we use variable for `previewUrl` field.

thank you for `previewUrl` support from devfile!

**Comment by sparkoo** [comment] 2019-10-09 07:19
thanks @RomanNikitenko. I'm closing this one.

**Comment by sparkoo** [comment] 2019-10-11 00:03
I have to reopen this issue. Using server placeholders is not possible for kubernetes/openshift components with multiple containers. In scenario like this, command has no info where it will run and we can't construct proper server placeholder. So we have to construct full URL on server.
see https://github.com/eclipse/che/pull/14713#discussion_r333044893

**Comment by sparkoo** [comment] 2019-10-11 00:03
cc @RomanNikitenko @l0rd

**Comment by RomanNikitenko** [comment] 2019-10-11 06:33
@sparkoo 
thank you for info!

To be honest, I don't like idea to store runtime info (full URL, not variable) for a task in configuration file. Taking into account the new information we should revise how we can handle it on client side and I would say it's not a bug (maybe task?) as we didn't support full URL earlier.

**Comment by sparkoo** [comment] 2019-10-11 06:52
@RomanNikitenko yes. It can be "subtask" of previewurl task (https://github.com/eclipse/che/issues/13945)

**Comment by sparkoo** [comment] 2019-10-14 08:57
The issue is not related to just previewUrl. I've created more generic issue https://github.com/eclipse/che/issues/14876

**Closed as completed** 2019-10-24 10:48 UTC
Labels: kind/bug, status/analyzing, area/editor/theia
