### ISSUE TITLE
SSH view public key / delete key-pair does not work

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#14499] opened 2019-09-10 10:05 UTC
### Describe the bug
Once SSH key-pair is generated it is not possible to delete it or view the public key:

![Peek 2019-09-10 11-56](https://user-images.githubusercontent.com/1461122/64604257-1e7aef00-d3c2-11e9-811d-9b1cf1ad764c.gif)

Nothing happens after executing both commands

> SSH: view public key
> SSH: delete key-pair 

NOTE: the secrets for private keys have been generated:

![image](https://user-images.githubusercontent.com/1461122/64604622-c1336d80-d3c2-11e9-9825-6798efab07e2.png)

### Che version
`7.1.0`

### Steps to reproduce

- Create a workspace
- Generate Key-pair
- Restart Workspace 
- execute `SSH: view public key`
- ERROR: nothing happens
- execute `SSH: delete key-pair`
- ERROR: nothing happens

### Expected behavior
- execute `SSH: view public key`
- the public key is shown
- execute `SSH: delete key-pair `
- key-pair is deleted

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] Hosted Che

**Comment by ibuziuk** [comment] 2019-09-10 10:06
@vinokurig could you please take a look, this is quite a critical issue IMO

**Comment by Katka92** [comment] 2019-09-10 10:47
@ibuziuk I have the same problem, I can not view ssh public key or delete them. I've tried to restart worksapce and didn't help.

**Comment by vinokurig** [comment] 2019-09-10 15:01
@ibuziuk I cannot reproduce the issue on my minikube. Looks like it is an infrastructural problem.

**Comment by ibuziuk** [comment] 2019-09-10 15:03
@vinokurig yeah, but what sort of problem? how delete / show key is implemented from k8s / openshift perspective?

**Comment by ibuziuk** [comment] 2019-09-10 15:06
note, that generating key-pair works fine. the problem looks like specific to view / delete API e.g. maybe plugin can not find the key for some reason? how can I see the logs?

**Comment by l0rd** [comment] 2019-09-10 21:44
@vinokurig have you verified that it works on minishift/crc/ocp as well?

**Comment by gorkem** [comment] 2019-09-10 23:55
Duplicate of https://github.com/eclipse/che/issues/14332

**Comment by vinokurig** [comment] 2019-09-11 11:35
@l0rd 
> @vinokurig have you verified that it works on minishift/crc/ocp as well?

I've tried it on minishift and didn't reproduce the issue as well.

**Comment by Katka92** [comment] 2019-09-11 12:01
I can not reproduce that on Che running localy on minishift neither minikube. I can reproduce that on Rh-Che prod-preview where 7.1.0 is deployed.

**Comment by vinokurig** [comment] 2019-09-11 12:51
I cannot check it because I have an issue with login to che.openshift.io.

**Comment by l0rd** [comment] 2019-09-11 14:28
@ibuziuk shouldn't we close this one as a duplicate?

**Comment by vinokurig** [comment] 2019-09-16 08:21
Fixed by https://github.com/eclipse/che/pull/14557

**Closed as completed by vinokurig** 2019-09-16 08:21 UTC
Labels: kind/bug, status/analyzing
