### ISSUE TITLE
Workspace panel actions are not working

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#19441] opened 2021-03-29 08:38 UTC
### Describe the bug
I opened my usual self-hosting workspace this morning and ended up with an empty workspace. I saw no source in the explorer and I could not open any terminals in containers. After realizing I had no workspace roots open, I opened one by hand and my projects appeared. I could now open terminals in user containers, but not in any containers inside the "plugins" folder in the "my workspace" sidebar.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Start a workspace and try to use any action from the `Workspace` panel.
Also see: https://github.com/eclipse/che/issues/19441#issuecomment-809240864

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by tsmaeder** [comment] 2021-03-29 08:43
Correction: opening terminals does not work in _any_ container, it's just that I already had some open in that workspace.

**Comment by RomanNikitenko** [comment] 2021-03-29 09:08
I tested on the `dogfooding` instance for the `next` version of the `che-theia` editor.
I can not reproduce the problem.

We need more details and steps to reproduce for an investigation.

**Comment by azatsarynnyy** [comment] 2021-03-29 09:14
I suspect, the steps maybe something like:
- create a new **persisted** workspace with several projects where the multi-root mode is **off**
- turn the multi-root mode **on** and restart the workspace
- check the explorer

Maybe the problem is related to persisting/restoring the IDE state when one changes the multi-root mode across the sessions?

**Comment by benoitf** [comment] 2021-03-29 09:19
@tsmaeder please share console log of the browser when clicking on 'new terminal' icon

**Comment by tsmaeder** [comment] 2021-03-29 09:20
The browser log says:
```
Uncaught (in promise) Error: command 8 not found
    at Function.MessageFactory.replyErr (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:380)
    at /home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:246
    at processTicksAndRejections (/dashboard/internal/process/task_queues.js:97)
```

This looks like a command with arguments (aka "safe command") is not found when the front end is trying to execute the command.

**Comment by RomanNikitenko** [comment] 2021-03-29 09:20
I see.
Looks like the problem is actual for the `Workspace` panel.

**Comment by tsmaeder** [comment] 2021-03-29 09:23
Confirmed, the commands from the "F1" menu work, as well.

**Comment by benoitf** [comment] 2021-03-29 09:26
it can't be a side effect of https://github.com/eclipse-theia/theia/pull/9223 ?

**Comment by benoitf** [comment] 2021-03-29 09:29
I'm using quay.io/eclipse/che-theia:1caeb61 in my workspace and it works, trying with new images

**Comment by benoitf** [comment] 2021-03-29 09:32
so it doesn't work with `quay.io/eclipse/che-theia:c881e91` aka https://github.com/eclipse-che/che-theia/commit/c881e914b4944841a20f0d929664f382cffe4fbe but works with `quay.io/eclipse/che-theia:1caeb61` aka https://github.com/eclipse-che/che-theia/commit/1caeb61a17674360bdde1575000e4f0469d729c0

so I suspect regression is coming from upstream theia change

**Comment by azatsarynnyy** [comment] 2021-03-29 09:37
@RomanNikitenko could you please check it with the upstream commit before https://github.com/eclipse-theia/theia/pull/9223

**Comment by RomanNikitenko** [comment] 2021-03-29 09:48
Now I see that it's not related to a terminal functionality - the `Workspace` panel doesn't work for me at all!

**Comment by RomanNikitenko** [comment] 2021-03-29 10:35
For testing I used the PR: https://github.com/eclipse-che/che-theia/pull/1049
I pinned the `theia` commit: https://github.com/eclipse-theia/theia/commit/d9c0fabb4e657e7d1879a8067d119598cc00fb43
`Che-theia` commit: https://github.com/eclipse-che/che-theia/commit/abda623ed90a7e33b60bd812faa873158293d248

The `Workspace` panel works well for me.
You can use the images provided by `Happy Path` tests: https://github.com/eclipse-che/che-theia/pull/1049#issuecomment-809265993 for testing.

So, I believe the regression was caused by upstream changes after the commit: https://github.com/eclipse-theia/theia/commit/d9c0fabb4

**Comment by azatsarynnyy** [comment] 2021-03-29 11:35
Thanks @RomanNikitenko for checking it.
@tsmaeder could you please take a look at https://github.com/eclipse-theia/theia/pull/9223?
Maybe revert the commit, while investigating the issue.

**Comment by azatsarynnyy** [comment] 2021-03-29 11:37
I'm setting `blocker` as it prevents consuming the latest changes from the upstream Theia.

**Comment by tsmaeder** [comment] 2021-03-29 12:16
Not sure it's a blocker, technically, since there is a workaround. (use terminal menu and "Run Task..."

**Comment by tsmaeder** [comment] 2021-03-29 15:07
The above analysis is slightly wrong: the command that is converted to an "internal" command is not used when creating a "safe command". So the command conversion is only broken for commands that use the field `Command.id` instead of `Command.command`.

**Comment by tsmaeder** [comment] 2021-03-29 15:08
`Command.id` is deprecated, so the right fix is determined by whether we can remove the `id` field and make `command` mandatory (as it is in the vscode API):

**Comment by RomanNikitenko** [comment] 2021-03-30 15:09
@tsmaeder 
I guess we can close it

**Closed as completed** 2021-03-31 11:32 UTC
Labels: kind/bug, severity/blocker, sprint/current
