### ISSUE TITLE
Fail to start sample workspaces when using a custom TLS certificate

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#19309] opened 2021-03-17 10:41 UTC
### Describe the bug

Starting any getting started workspace fails with the following message.

<img width="557" alt="image" src="https://user-images.githubusercontent.com/606959/111454786-57adc100-8715-11eb-9e86-a7a283f5dd5a.png">

I have deployed Che on minikube. I am using a custom TLS certificate for Che endpoints. 

That means that I have:

- created a Kubernets tls secret with the key and certificate
- updated CheCluster setting both [`spec/k8s/tlsSecretName`](https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-the-che-installation/#checluster-custom-resource-k8s-settings_che) and [`/spec/server/cheHostTLSSecret`](https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-che-hostname/) to point to that secret
- add the CA certificate in configmap properly labelled (as described [here](https://www.eclipse.org/che/docs/che-7/installation-guide/importing-untrusted-tls-certificates/#_adding_new_ca_certificates_into_che))

### Che version

nightly

### Steps to reproduce

Deploy Che on minikube using chectl
Configure Che to use a custom certificate as described [here](https://che-incubator.github.io/2021/02/01/@mario.loriedo-using-mkcert-to-locally-trust-eclipse-che-tls-certificates-ffaafe76e5d0.html)
Start the Java maven sample

### Runtime
minikube

```
minikube version: v1.17.1
commit: 043bdca07e54ab6e4fc0457e3064048f34133d7e
```

### Installation method

```bash
$  chectl update next && \
   chectl server:deploy \
       -p minikube
```

### Environment

macOS

**Comment by l0rd** [comment] 2021-03-17 14:04
Related to https://github.com/eclipse/che/issues/19168

**Comment by l0rd** [comment] 2021-03-18 11:38
Looks like a duplicate of https://github.com/eclipse/che/issues/19120 but that got closed and I can still reproduce the problem using nightly. cc @vitaliy-guliy

**Comment by azatsarynnyy** [comment] 2021-03-18 11:53
I'm labeling it as `area/plugins` since the related functionality comes from the Workspace Plug-in.

**Comment by azatsarynnyy** [comment] 2021-03-18 11:57
I've noticed that only `*.crt` files are taken into account when reading it from the `/public-certs` folder:
https://github.com/eclipse/che-theia/blob/d4a190ebb3e5b42ad45f4190018b693e26055449/plugins/workspace-plugin/src/ca-cert.ts#L49
I believe it could be fixed by reading all the `*.pem` files as well, e.g. `/public-certs/custom-certs.rootCA.pem`.

**Comment by mmorhun** [comment] 2021-03-18 14:12
@azatsarynnyy I've run into the same problem, so created PR: https://github.com/eclipse/che-theia/pull/1038

**Comment by azatsarynnyy** [comment] 2021-03-18 14:57
Thanks @mmorhun!
@l0rd could you check if your issue is reproducible with the following che-theia version:
```yaml
components:
  - reference: https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1038/simple/che-theia-editor.yaml
    type: cheEditor
```
It's based on Mykola's PR

**Comment by vitaliy-guliy** [comment] 2021-03-18 15:02
> Looks like a duplicate of #19120 but that got closed and I can still reproduce the problem using nightly. cc @vitaliy-guliy

We should take into account all the certificates, that are in `/public-certs` directory.
Thanks to @mmorhun for the fixup.

**Comment by l0rd** [comment] 2021-03-19 00:20
Now it's hanging while trying to clone the project: I do not get any error but the project doesn't get cloned.

![Mar-19-2021 01-18-36-2](https://user-images.githubusercontent.com/606959/111714057-1ae6e480-8851-11eb-91f7-713ab6d8af28.gif)

**Comment by vitaliy-guliy** [comment] 2021-03-24 15:22
Should be working now

**Closed as completed by vitaliy-guliy** 2021-03-24 15:22 UTC
Labels: kind/bug, severity/P1, area/plugins
