### ISSUE TITLE
che-machine-exec 7.2.0 is required by the che 7.2.0?

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#14732] opened 2019-10-01 13:44 UTC
Just upgraded to che from 7.1.0 to 7.2.0, few questions about che-machine-exec:

1. should docker.io/eclipse/che-machine-exec have the corresponding tag 7.2.0?
2. should plugin registry have the meta.yaml for che-machine-exec 7.2.0?

**Comment by amisevsk** [comment] 2019-10-01 14:19
Hi @rbcminghou. To answer your questions:

- che-machine-exec has moved over to the quay.io repository: https://quay.io/repository/eclipse/che-machine-exec, which does contain the 7.2.0 tag. I believe we are working on deprecating the docker.io repo.
- When you upgraded to 7.2.0, did you also upgrade the plugin and devfile registries? Checking the current 7.2.0 release of che-plugin-registry, I see that there is a 7.2.0 version of che-machine-exec.

**Comment by nickboldt** [comment] 2019-10-01 18:40
I believe this is being caused by the new changes in the way I'm building the airgap version of the Che 7 plugin registry. 

For CRW we want to filter out all but the /latest/ folders but that means when you try to find `v3/plugins/eclipse/che-machine-exec-plugin/7.2.0/meta.yaml` you get 404'd as only `v3/plugins/eclipse/che-machine-exec-plugin/latest/meta.yaml` exists

**Comment by nickboldt** [comment] 2019-10-01 19:01
7.2.0 is the "default" in Che, when your devfile doesn't contain an editor;  could also fix the problem by adding
```
  - id: eclipse/che-theia/latest
    type: cheEditor
  - id: eclipse/che-machine-exec-plugin/latest
    type: chePlugin
```
into devfile to pull `/latest` instead of `/7.2.0`

**Comment by l0rd** [comment] 2019-10-01 22:30
@rbcminghou did we answer your questions? Can we close this issue?

**Comment by rbcminghou** [comment] 2019-10-01 22:52
Please close this issue.

**Closed as completed by rbcminghou** 2019-10-01 22:52 UTC
Labels: kind/question, status/info-needed
