### ISSUE TITLE
Git plugin does not work 

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#14846] opened 2019-10-10 16:02 UTC
### Describe the bug
_When try to use _'Source Control'_ tab it dosn't work. Also branch name is absent in the _'theia status bar'_._

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Open a workspace with a project VSC repository.
2. Click on the _Source Control_ tab.

### Expected behavior
- Should display info about git repo:
![git-plugin-che](https://user-images.githubusercontent.com/5408906/66585572-c1748380-eb8f-11e9-9165-ab5ac8e9aace.png)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![che-git-plugin-no-work](https://user-images.githubusercontent.com/5408906/66585679-f08af500-eb8f-11e9-9ed6-690b71e9f222.png)

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: CRW CCI

**Comment by tolusha** [comment] 2019-10-11 10:44
It works in Theia

**Comment by benoitf** [comment] 2019-10-11 10:47
@tolusha when you say "it works in theia" it's with vscode git extension and disabling native extension in theia as well, or just trying default example assembly ?

**Comment by tolusha** [comment] 2019-10-11 10:53
I've checked the default assembly

**Comment by benoitf** [comment] 2019-10-11 10:56
ok, BTW I've the root cause

**Comment by benoitf** [comment] 2019-10-11 11:06
@artaleks9 it's not checked by happy path ?

**Comment by benoitf** [comment] 2019-10-11 14:55
should be fixed now

**Comment by artaleks9** [comment] 2019-10-11 14:57
No, the 'happy-path' doesn't check it.
It was failed only one Java selenium test.

**Comment by artaleks9** [comment] 2019-10-12 12:50
I checked fixing up by running the single test on the _experimental job_ on my specific branch which up to date with a master branch. Looks like it works as expected, the test is success: 
https://ci.codenvycorp.com/view/qa-experimental/job/experimental-che-integration-tests-multiuser-master-ocp/324/Selenium_20tests_20report/

The issue will close after merge PR and verifying that everything works well:
https://github.com/eclipse/che/pull/14870

**Comment by dmytro-ndp** [comment] 2019-10-13 20:15
The issue hasn't reproduced recently https://github.com/eclipse/che/pull/14870#issuecomment-541396517

**Closed as completed by dmytro-ndp** 2019-10-13 20:15 UTC
Labels: kind/bug, severity/blocker, status/in-progress, e2e-test/failure, area/editor/theia
