### ISSUE TITLE
opening a Che 7 workspace from factory fails due to cors 

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#12788] opened 2019-02-27 22:36 UTC
Try creating a workspace with https://che.openshift.io/f?id=factorykfs97j9yp4c9wzwi 
Although workspace is created successfully an error on the browser console can be seen and 
the workspace is never opened

```
Failed to load resource: the server responded with a status of 503 (Service Unavailable)
loader.html:1 Access to XMLHttpRequest at 'https://routegvg4iz81-XXXXXXXX-che.8a09.starter-us-east-2.openshiftapps.com/jwt/auth' from origin 'https://che.openshift.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by PavelSosin** [comment] 2019-02-28 08:59
I just made next step toward installation of Che 7 beta on top of my local kubernetes cluster. I created secret from company certificate pre-installed on my laptop by IT team when it was delivered to me.   The next step, I suppose, will be ingress creation. Which type of ingress is suitable for Che7 in the personal evironment, see ((https://github.com/nginxinc/kubernetes-ingress/blob/master/docs/nginx-ingress-controllers.md))

**Comment by ibuziuk** [comment] 2019-02-28 13:47
@gorkem i believe it is related to long route exposure - https://github.com/openshiftio/openshift.io/issues/4695

**Comment by skabashnyuk** [comment] 2019-02-28 13:50
@gorkem I was able to reproduce it in some cases

![15 46 43](https://user-images.githubusercontent.com/1614429/53570828-1cf98000-3b70-11e9-8e4d-456cd23b96df.png)
Agree with @ibuziuk more likely this is routes issue.
Because one request to jwt proxy finished with successful redirection but next request returned 500 http error.

@PavelSosin are you statement is related to this issue?

**Comment by ibuziuk** [comment] 2019-02-28 15:00
@skabashnyuk do you think there could be some workaround for this?
page refresh does not seem to help 
![image](https://user-images.githubusercontent.com/1461122/53575465-e58bd300-3b71-11e9-8593-abae8ad5b2c8.png)

**Comment by ibuziuk** [comment] 2019-02-28 15:07
funny thing that when I directly navigate to jwt-proxy route it keeps returning 503 even in a couple of minutes after workspace startup

**Comment by skabashnyuk** [comment] 2019-02-28 15:08
>@skabashnyuk do you think there could be some workaround for this?

I don't think so.

**Comment by ibuziuk** [comment] 2019-02-28 15:12
I mean, is it expected that when all routes are exposed and accessible, page refresh would proceed with the redirect correctly?

**Comment by skabashnyuk** [comment] 2019-02-28 15:20
The issue is that the route becomes available and then gone. I think we can't guarantee in this case anything.

**Comment by ibuziuk** [comment] 2019-02-28 15:25
do you mean route flapping? AFAIK, on starter clusters there is only a problem related to the long route exposure (not route flapping)

**Comment by skabashnyuk** [comment] 2019-02-28 15:49
I reproduce it with route flapping.
1. A successful request to JWT proxy with a redirect as a result.
2. Next request JWT proxy - 503 service unavailable from OpenShift.

**Comment by nickboldt** [comment] 2019-07-31 20:56
This sounds like a problem we should fix in Che 7.1, if it's not already fixed in 7.0. If you agree please set a milestone and remove the triage label.

**Comment by skabashnyuk** [comment] 2019-08-01 07:28
Does anyone reproduce it since February? 
@ibuziuk wdyt?

**Comment by ibuziuk** [comment] 2019-08-01 07:33
AFAIK, this is route flapping (not CORS) related issue,which should be closed since it is infrastructure specic. Currently, there is no route flapping on OSO clusters used by che.openshift.io

**Closed as completed** 2019-08-01 07:34 UTC
