### ISSUE TITLE
Workspace creation errors on hosted che

### ISSUE THREAD

**Issue by bhps69** [eclipse-che/che#17872] opened 2020-09-15 14:29 UTC
### Is your task related to a problem? Please describe.

Iam a newbie to eclipse che, thought of just creating a simple project for practise. so createrd a workspace- first with spring boot only, then with spring boot + mysql , then spring boot+ mongo DB, then php+laravel+mysql, then php with mysql, then django. all one at a time, but for each one i got error- some times it is ""quota exceeded", sometimes"db already exists"? all these errors display after loading all the plugins - displayed in the console.

### Additional context

[error.docx](https://github.com/eclipse/che/files/5225594/error.docx)

**Comment by sparkoo** [comment] 2020-09-15 15:13
Your description is a bit confusing. Can you please describe exact steps how to reproduce? Also if possible, provide the logs of che-server and from workspace startup. You can run the workspace in debug mode to see more logging. Please upload the logs in some text format https://gist.github.com/ is perfect, I can't open the docx.

 - `quota exceeded` probably means that your cluster does not have enough resources to run the workspace. It may not free all the resources from previous runs yet.
 - `db already exists` I'm not sure about this one. Where and when does this error message appear? Might be some conflict from multiple workspaces runs.

**Comment by gorkem** [comment] 2020-09-15 15:19
@sparkoo It looks like this is on hosted che
@ibuziuk

**Comment by bhps69** [comment] 2020-09-15 17:38
The reproducing steps are-open the eclip Che link.  Click on workspace
which displays the"template" and"custom" tabbed options. Select custom and
select one of these-"spring boot" or "spring boot with MySql" or "spring
boot with MongoDB" or "PHP with MySql" or "php, laravel with MySql" or
"python with Django". In the console we can see the plugins and templates
are applied to the new project but atlast error will be displayed.

Software Engineer

Website : https://www.linkedin.com/in/phani-shekhar-bhandaru-33290614
 | email: phanibhandaru@gmail.com | Phone : +91-7036825170



This message is for the designated recipient only and may contain
privileged, proprietary, or otherwise private information. If you have
received it in error, please notify the sender immediately and delete the
original. Any other use of the email by you is prohibited.

**Comment by l0rd** [comment] 2020-10-12 09:41
@bhps69 I have followed the steps you provided:

- Open https://che.openshift.io/ on chrome
- Selected "Get Started" in the left menu bar
- Selected "Custom Workspace"
- Selected the devfile template "Java Spring Boot"

and my workspace got loaded successfully:

![image](https://user-images.githubusercontent.com/606959/95731150-70560e80-0c7f-11eb-9a50-b4a0f5e6b717.png)

I am closing this issue. Feel free to reopen it providing more details to help us reproduce your problem.

**Closed as completed by l0rd** 2020-10-12 09:41 UTC
Labels: kind/bug, status/info-needed, severity/P2
