### ISSUE TITLE
Invalid CRD openAPIV3Schema on OpenShift 3.11

### ISSUE THREAD

**Issue by vrushaliinamdar** [eclipse-che/che#15396] opened 2019-12-03 17:51 UTC
Hi,

I have built codewind-che-plugin on Power(ppc64le) from source. I would like validate it by installing che. 

However, I am getting below error:

```
# ./bin/chectl server:start --platform=openshift --installer=operator --che-operator-cr-yaml=codewind-checluster.yaml --che-operator-image=bivasibm/che-operator-ppc64le
  ✔ Verify Kubernetes API...OK (it's OpenShift)
  ✔ 👀  Looking for an already existing Che instance
    ✔ Verify if Che is deployed into namespace "che"...it is not
  ✔ ✈️  Openshift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if openshift is running...done.
 ›   Warning: Che will be deployed in Multi-User mode since Configured 'operator' installer which support only such.
  ❯ 🏃‍  Running the Che Operator
    ✔ Copying operator resources...done.
    ✔ Create Namespace (che)...It already exists.
    ✔ Create ServiceAccount che-operator in namespace che...It already exists.
    ✔ Create Role che-operator in namespace che...It already exists.
    ✔ Create ClusterRole che-operator...It already exists.
    ✔ Create RoleBinding che-operator in namespace che...It already exists.
    ✔ Create ClusterRoleBinding che-operator...It already exists.
    ✖ Create CRD checlusters.org.eclipse.che
      → **CustomResourceDefinition.apiextensions.k8s.io "checlusters.org.eclipse.che" is invalid: spec.validation.openAPIV3Schema: Invalid value**
```

System Details:
OS : Red Hat Enterprise Linux Server 7.7
ARCH : ppc64le
openshift v3.11.154
kubernetes v1.11.0+d4cacc0
chectl/0.0.2 linux-ppc64 node-v13.2.0

**Command executed:**

```
./bin/chectl server:start --platform=openshift --installer=operator --che-operator-cr-yaml=codewind-checluster.yaml --che-operator-image=bivasibm/che-operator-ppc64le
```

Contents of codewind-checluster.yaml can be found here 
[Che-installation-ppc64le.yaml.txt](https://github.com/eclipse/che/files/3917922/Che-installation-ppc64le.yaml.txt)

Please let me know if I am missing something.

Regards,
Vrushali

**Comment by l0rd** [comment] 2019-12-03 23:22
Thanks @vrushaliinamdar for reporting this

@davidfestal @tomgeorge I suspect that this can be a side effect of https://github.com/eclipse/che-operator/commit/431809f950f0863caf1bf6efd68a0b8561710e8e#diff-8161083b75e674994147f0f5c1e4507c. What do you think? Have you tested applying the CRD with OpenShift 3.11?

**Comment by l0rd** [comment] 2019-12-03 23:25
Anyway @vrushaliinamdar it looks like you are using a pretty old version of chectl. Can you try witha a recent version?

**Comment by davidfestal** [comment] 2019-12-04 10:00
@l0rd The commit https://github.com/eclipse/che-operator/commit/431809f950f0863caf1bf6efd68a0b8561710e8e#diff-8161083b75e674994147f0f5c1e4507c is quite old and we should have found this already in QE tests many times if really Openshift 3.11 didn't support OpenAPI v3 schemas.

Anyway, I tested again with the following fresh configuration:
```
$ minishift openshift version
openshift v3.11.0+f6acaf1-349
$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.164:8443
kubernetes v1.11.0+d4cacc0
$ chectl version
chectl/7.4.0 linux-x64 node-v10.17.0
```
And though the `chectl server:start` command failed, obviously for a network problem when trying to contact the Keycloak server, It correctly applied the CRD and all the components:
```
[david@timothee-linux-1 ~]$ chectl server:start --platform=minishift --installer=operator
  ✔ Verify Kubernetes API...OK (it's OpenShift)
  ✔ 👀  Looking for an already existing Che instance
    ✔ Verify if Che is deployed into namespace "che"...it is not
  ✔ ✈️  Minishift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if minishift is installed...done.
    ✔ Verify if minishift is running...done.
 ›   Warning: Che will be deployed in Multi-User mode since Configured 'operator' installer which support only such.
  ✔ 🏃‍  Running the Che Operator
    ✔ Copying operator resources...done.
    ✔ Create Namespace (che)...done.
    ✔ Create ServiceAccount che-operator in namespace che...done.
    ✔ Create Role che-operator in namespace che...done.
    ✔ Create ClusterRole che-operator...done.
    ✔ Create RoleBinding che-operator in namespace che...done.
    ✔ Create ClusterRoleBinding che-operator...done.
    ✔ Create CRD checlusters.org.eclipse.che...done.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment che-operator in namespace che...done.
    ✔ Create Che Cluster eclipse-che in namespace che...done.
  ❯ ✅  Post installation checklist
    ✔ PostgreSQL pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Keycloak pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Devfile registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Plugin registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ❯ Che pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✖ starting
        → ERR_TIMEOUT: Timeout set to pod ready timeout 130000
      Retrieving Che Server URL
      Che status check
Error: ERR_TIMEOUT: Timeout set to pod ready timeout 130000
    at KubeHelper.<anonymous> (/usr/local/lib/chectl/lib/api/kube.js:615:19)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/chectl/node_modules/tslib/tslib.js:107:62)
```

<details><summary>Additionally, I can chek I have the correct CRD in the cluster</summary>

```yaml
$ oc get crd checlusters.org.eclipse.che -o yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: 2019-12-04T09:31:59Z
  generation: 1
  name: checlusters.org.eclipse.che
  resourceVersion: "6489"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/checlusters.org.eclipse.che
  uid: eb96c945-1678-11ea-a844-525400fe35fd
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
  group: org.eclipse.che
  names:
    kind: CheCluster
    listKind: CheClusterList
    plural: checlusters
    singular: checluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            auth:
              description: Configuration settings related to the Authentication used
                by the Che installation.
              properties:
                externalIdentityProvider:
                  description: 'Instructs the operator on whether or not to deploy
                    a dedicated Identity Provider (Keycloak or RH SSO instance). By
                    default a dedicated Identity Provider server is deployed as part
                    of the Che installation. But if `externalIdentityProvider` is
                    `true`, then no dedicated identity provider will be deployed by
                    the operator and you might need to provide details about the external
                    identity provider you want to use. See also all the other fields
                    starting with: `identityProvider`.'
                  type: boolean
                identityProviderAdminUserName:
                  description: Overrides the name of the Identity Provider admin user.
                    Defaults to `admin`.
                  type: string
                identityProviderClientId:
                  description: Name of a Identity provider (Keycloak / RH SSO) `client-id`
                    that should be used for Che. This is useful to override it ONLY
                    if you use an external Identity Provider (see the `externalIdentityProvider`
                    field). If omitted or left blank, it will be set to the value
                    of the `flavour` field suffixed with `-public`.
                  type: string
                identityProviderImage:
                  description: Overrides the container image used in the Identity
                    Provider (Keycloak / RH SSO) deployment. This includes the image
                    tag. Omit it or leave it empty to use the defaut container image
                    provided by the operator.
                  type: string
                identityProviderImagePullPolicy:
                  description: Overrides the image pull policy used in the Identity
                    Provider (Keycloak / RH SSO) deployment. Default value is `Always`
                    for `nightly` or `latest` images, and `IfNotPresent` in other
                    cases.
                  type: string
                identityProviderPassword:
                  description: Overrides the password of Keycloak admin user. This
                    is useful to override it ONLY if you use an external Identity
                    Provider (see the `externalIdentityProvider` field). If omitted
                    or left blank, it will be set to an auto-generated password.
                  type: string
                identityProviderPostgresPassword:
                  description: Password for The Identity Provider (Keycloak / RH SSO)
                    to connect to the database. This is useful to override it ONLY
                    if you use an external Identity Provider (see the `externalIdentityProvider`
                    field). If omitted or left blank, it will be set to an auto-generated
                    password.
                  type: string
                identityProviderRealm:
                  description: Name of a Identity provider (Keycloak / RH SSO) realm
                    that should be used for Che. This is useful to override it ONLY
                    if you use an external Identity Provider (see the `externalIdentityProvider`
                    field). If omitted or left blank, it will be set to the value
                    of the `flavour` field.
                  type: string
                identityProviderURL:
                  description: Public URL of the Identity Provider server (Keycloak
                    / RH SSO server). You should set it ONLY if you use an external
                    Identity Provider (see the `externalIdentityProvider` field).
                    By default this will be automatically calculated and set by the
                    operator.
                  type: string
                oAuthClientName:
                  description: Name of the OpenShift `OAuthClient` resource used to
                    setup identity federation on the OpenShift side. Auto-generated
                    if left blank. See also the `OpenShiftoAuth` field.
                  type: string
                oAuthSecret:
                  description: Name of the secret set in the OpenShift `OAuthClient`
                    resource used to setup identity federation on the OpenShift side.
                    Auto-generated if left blank. See also the `OAuthClientName` field.
                  type: string
                openShiftoAuth:
                  description: 'Enables the integration of the identity provider (Keycloak
                    / RHSSO) with OpenShift OAuth. Enabled by defaumt on OpenShift.
                    This will allow users to directly login with their Openshift user
                    throug the Openshift login, and have their workspaces created
                    under personnal OpenShift namespaces. WARNING: the `kuebadmin`
                    user is NOT supported, and logging through it will NOT allow accessing
                    the Che Dashboard.'
                  type: boolean
                updateAdminPassword:
                  description: Forces the default `admin` Che user to update password
                    on first login. Defaults to `false`.
                  type: boolean
              type: object
            database:
              description: Configuration settings related to the database used by
                the Che installation.
              properties:
                chePostgresDb:
                  description: Postgres database name that the Che server uses to
                    connect to the DB. Defaults to `dbche`.
                  type: string
                chePostgresHostName:
                  description: Postgres Database hostname that the Che server uses
                    to connect to. Defaults to postgres. This value should be overridden
                    ONLY when using an external database (see field `externalDb`).
                    In the default case it will be automatically set by the operator.
                  type: string
                chePostgresPassword:
                  description: Postgres password that the Che server should use to
                    connect to the DB. If omitted or left blank, it will be set to
                    an auto-generated value.
                  type: string
                chePostgresPort:
                  description: Postgres Database port that the Che server uses to
                    connect to. Defaults to 5432. This value should be overridden
                    ONLY when using an external database (see field `externalDb`).
                    In the default case it will be automatically set by the operator.
                  type: string
                chePostgresUser:
                  description: Postgres user that the Che server should use to connect
                    to the DB. Defaults to `pgche`.
                  type: string
                externalDb:
                  description: 'Instructs the operator on whether or not to deploy
                    a dedicated database. By default a dedicated Postgres database
                    is deployed as part of the Che installation. But if `externalDb`
                    is `true`, then no dedicated database will be deployed by the
                    operator and you might need to provide connection details to the
                    external DB you want to use. See also all the fields starting
                    with: `chePostgres`.'
                  type: boolean
                postgresImage:
                  description: Overrides the container image used in the Postgres
                    database deployment. This includes the image tag. Omit it or leave
                    it empty to use the defaut container image provided by the operator.
                  type: string
                postgresImagePullPolicy:
                  description: Overrides the image pull policy used in the Postgres
                    database deployment. Default value is `Always` for `nightly` or
                    `latest` images, and `IfNotPresent` in other cases.
                  type: string
              type: object
            k8s:
              description: Configuration settings specific to Che installations made
                on upstream Kubernetes.
              properties:
                ingressClass:
                  description: 'Ingress class that will define the which controler
                    will manage ingresses. Defaults to `nginx`. NB: This drives the
                    `is kubernetes.io/ingress.class` annotation on Che-related ingresses.'
                  type: string
                ingressDomain:
                  description: 'Global ingress domain for a K8S cluster. This MUST
                    be explicitly specified: there are no defaults.'
                  type: string
                ingressStrategy:
                  description: Strategy for ingress creation. This can be `multi-host`
                    (host is explicitly provided in ingress), `single-host` (host
                    is provided, path-based rules) and `default-host.*`(no host is
                    provided, path-based rules). Defaults to `"multi-host`
                  type: string
                securityContextFsGroup:
                  description: FSGroup the Che pod and Workspace pods containers should
                    run in. Defaults to `1724`.
                  type: string
                securityContextRunAsUser:
                  description: ID of the user the Che pod and Workspace pods containers
                    should run as. Default to `1724`.
                  type: string
                tlsSecretName:
                  description: Name of a secret that will be used to setup ingress
                    TLS termination if TLS is enabled. See also the `tlsSupport` field.
                  type: string
              type: object
            server:
              description: General configuration settings related to the Che server
                and the plugin and devfile registries
              properties:
                airGapContainerRegistryHostname:
                  description: Optional hostname (or url) to an alternate container
                    registry to pull images from. This value overrides the container
                    registry hostname defined in all the default container images
                    involved in a Che deployment. This is particularly useful to install
                    Che in an air-gapped environment.
                  type: string
                airGapContainerRegistryOrganization:
                  description: Optional repository name of an alternate container
                    registry to pull images from. This value overrides the container
                    registry organization defined in all the default container images
                    involved in a Che deployment. This is particularly useful to install
                    Che in an air-gapped environment.
                  type: string
                cheDebug:
                  description: Enables the debug mode for Che server. Defaults to
                    `false`.
                  type: string
                cheFlavor:
                  description: Flavor of the installation. This is either `che` for
                    upstream Che installations, or `codeready` for CodeReady Workspaces
                    installation. In most cases the default value should not be overriden.
                  type: string
                cheHost:
                  description: Public hostname of the installed Che server. This will
                    be automatically set by the operator. In most cases the default
                    value set by the operator should not be overriden.
                  type: string
                cheImage:
                  description: Overrides the container image used in Che deployment.
                    This does NOT include the container image tag. Omit it or leave
                    it empty to use the defaut container image provided by the operator.
                  type: string
                cheImagePullPolicy:
                  description: Overrides the image pull policy used in Che deployment.
                    Default value is `Always` for `nightly` or `latest` images, and
                    `IfNotPresent` in other cases.
                  type: string
                cheImageTag:
                  description: Overrides the tag of the container image used in Che
                    deployment. Omit it or leave it empty to use the defaut image
                    tag provided by the operator.
                  type: string
                cheLogLevel:
                  description: 'Log level for the Che server: `INFO` or `DEBUG`. Defaults
                    to `INFO`.'
                  type: string
                cheWorkspaceClusterRole:
                  description: Custom cluster role bound to the user for the Che workspaces.
                    The default roles are used if this is omitted or left blank.
                  type: string
                customCheProperties:
                  additionalProperties:
                    type: string
                  description: Map of additional environment variables that will be
                    applied in the generated `che` config map to be used by the Che
                    server, in addition to the values already generated from other
                    fields of the `CheCluster` custom resource (CR). If `customCheProperties`
                    contains a property that would be normally generated in `che`
                    config map from other CR fields, then the value defined in the
                    `customCheProperties` will be used instead.
                  type: object
                devfileRegistryImage:
                  description: Overrides the container image used in the Devfile registry
                    deployment. This includes the image tag. Omit it or leave it empty
                    to use the defaut container image provided by the operator.
                  type: string
                devfileRegistryMemoryLimit:
                  description: Overrides the memory limit used in the Devfile registry
                    deployment. Defaults to 256Mi.
                  type: string
                devfileRegistryMemoryRequest:
                  description: Overrides the memory request used in the Devfile registry
                    deployment. Defaults to 16Mi.
                  type: string
                devfileRegistryPullPolicy:
                  description: Overrides the image pull policy used in the Devfile
                    registry deployment. Default value is `Always` for `nightly` or
                    `latest` images, and `IfNotPresent` in other cases.
                  type: string
                devfileRegistryUrl:
                  description: Public URL of the Devfile registry, that serves sample,
                    ready-to-use devfiles. You should set it ONLY if you use an external
                    devfile registry (see the `externalDevfileRegistry` field). By
                    default this will be automatically calculated by the operator.
                  type: string
                externalDevfileRegistry:
                  description: Instructs the operator on whether or not to deploy
                    a dedicated Devfile registry server. By default a dedicated devfile
                    registry server is started. But if `externalDevfileRegistry` is
                    `true`, then no such dedicated server will be started by the operator
                    and you will have to manually set the `devfileRegistryUrl` field
                  type: boolean
                externalPluginRegistry:
                  description: Instructs the operator on whether or not to deploy
                    a dedicated Plugin registry server. By default a dedicated plugin
                    registry server is started. But if `externalPluginRegistry` is
                    `true`, then no such dedicated server will be started by the operator
                    and you will have to manually set the `pluginRegistryUrl` field.
                  type: boolean
                nonProxyHosts:
                  description: List of hosts that should not use the configured proxy.
                    Use `|`` as delimiter, eg `localhost|my.host.com|123.42.12.32`
                    Only use when configuring a proxy is required (see also the `proxyURL`
                    field).
                  type: string
                pluginRegistryImage:
                  description: Overrides the container image used in the Plugin registry
                    deployment. This includes the image tag. Omit it or leave it empty
                    to use the defaut container image provided by the operator.
                  type: string
                pluginRegistryMemoryLimit:
                  description: Overrides the memory limit used in the Plugin registry
                    deployment. Defaults to 256Mi.
                  type: string
                pluginRegistryMemoryRequest:
                  description: Overrides the memory request used in the Plugin registry
                    deployment. Defaults to 16Mi.
                  type: string
                pluginRegistryPullPolicy:
                  description: Overrides the image pull policy used in the Plugin
                    registry deployment. Default value is `Always` for `nightly` or
                    `latest` images, and `IfNotPresent` in other cases.
                  type: string
                pluginRegistryUrl:
                  description: Public URL of the Plugin registry, that serves sample
                    ready-to-use devfiles. You should set it ONLY if you use an external
                    devfile registry (see the `externalPluginRegistry` field). By
                    default this will be automatically calculated by the operator.
                  type: string
                proxyPassword:
                  description: Password of the proxy server  Only use when proxy configuration
                    is required (see also the `proxyUser` field).
                  type: string
                proxyPort:
                  description: Port of the proxy server. Only use when configuring
                    a proxy is required (see also the `proxyURL` field).
                  type: string
                proxyURL:
                  description: URL (protocol+hostname) of the proxy server. This drives
                    the appropriate changes in the `JAVA_OPTS` and `https(s)_proxy`
                    variables in the Che server and workspaces containers. Only use
                    when configuring a proxy is required.
                  type: string
                proxyUser:
                  description: User name of the proxy server. Only use when configuring
                    a proxy is required (see also the `proxyURL` field).
                  type: string
                selfSignedCert:
                  description: Enables the support of OpenShift clusters whose router
                    uses self-signed certificates. When enabled, the operator retrieves
                    the default self-signed certificate of OpenShift routes and adds
                    it to the Java trust store of the Che server. This is usually
                    required when activating the `tlsSupport` field on demo OpenShift
                    clusters that have not been setup with a valid certificate for
                    the routes. This is disabled by default.
                  type: boolean
                serverMemoryLimit:
                  description: Overrides the memory limit used in the Che server deployment.
                    Defaults to 1Gi.
                  type: string
                serverMemoryRequest:
                  description: Overrides the memory request used in the Che server
                    deployment. Defaults to 512Mi.
                  type: string
                tlsSupport:
                  description: 'Instructs the operator to deploy Che in TLS mode,
                    ie with TLS routes or ingresses. This is disabled by default.
                    WARNING: Enabling TLS might require enabling the `selfSignedCert`
                    field also in some cases.'
                  type: boolean
              type: object
            storage:
              description: Configuration settings related to the persistent storage
                used by the Che installation.
              properties:
                postgresPVCStorageClassName:
                  description: Storage class for the Persistent Volume Claim dedicated
                    to the Postgres database. If omitted or left blank, default storage
                    class is used.
                  type: string
                preCreateSubPaths:
                  description: Instructs the Che server to launch a special pod to
                    pre-create a subpath in the Persistent Volumes. Defaults to `false`,
                    however it might need to enable it according to the configuration
                    of your K8S cluster.
                  type: boolean
                pvcClaimSize:
                  description: Size of the persistent volume claim for workspaces.
                    Defaults to `1Gi`
                  type: string
                pvcJobsImage:
                  description: Overrides the container image used to create sub-paths
                    in the Persistent Volumes. This includes the image tag. Omit it
                    or leave it empty to use the defaut container image provided by
                    the operator. See also the `preCreateSubPaths` field.
                  type: string
                pvcStrategy:
                  description: Persistent volume claim strategy for the Che server.
                    This Can be:`common` (all workspaces PVCs in one volume), `per-workspace`
                    (one PVC per workspace for all declared volumes) and `unique`
                    (one PVC per declared volume). Defaults to `common`.
                  type: string
                workspacePVCStorageClassName:
                  description: Storage class for the Persistent Volume Claims dedicated
                    to the Che workspaces. If omitted or left blank, default storage
                    class is used.
                  type: string
              type: object
          type: object
        status:
          properties:
            cheClusterRunning:
              description: Status of a Che installation. Can be `Available`, `Unavailable`,
                or `Available, Rolling Update in Progress`
              type: string
            cheURL:
              description: Public URL to the Che server
              type: string
            cheVersion:
              description: Current installed Che version
              type: string
            dbProvisioned:
              description: Indicates if or not a Postgres instance has been correctly
                provisioned
              type: boolean
            devfileRegistryURL:
              description: Public URL to the Devfile registry
              type: string
            helpLink:
              description: A URL that can point to some URL where to find help related
                to the current Operator status.
              type: string
            keycloakProvisioned:
              description: Indicates whether an Identity Provider instance (Keycloak
                / RH SSO) has been provisioned with realm, client and user
              type: boolean
            keycloakURL:
              description: Public URL to the Identity Provider server (Keycloak /
                RH SSO).
              type: string
            message:
              description: A human readable message indicating details about why the
                pod is in this condition.
              type: string
            openShiftoAuthProvisioned:
              description: Indicates whether an Identity Provider instance (Keycloak
                / RH SSO) has been configured to integrate with the OpenShift OAuth.
              type: boolean
            pluginRegistryURL:
              description: Public URL to the Plugin registry
              type: string
            reason:
              description: A brief CamelCase message indicating details about why
                the pod is in this state.
              type: string
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: CheCluster
    listKind: CheClusterList
    plural: checlusters
    singular: checluster
  conditions:
  - lastTransitionTime: 2019-12-04T09:31:59Z
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
```

</details>

I tend to think that there is something specific in the target environment that produces the error described in this issue.

**Comment by vrushaliinamdar** [comment] 2019-12-04 13:27
@l0rd @davidfestal  Thanks for the response. I will try with chectl/7.4.0 on ppc64le and get back to you.

**Comment by vrushaliinamdar** [comment] 2019-12-04 14:12
@l0rd @davidfestal I checked out and built the 7.4.x branch for chectl (). The build and tests were successful, however, when I execute the binary, it still displays the version as 0.0.2.

am I missing something?

```
chectl]# ./bin/run --help
Eclipse Che CLI

VERSION
  chectl/0.0.2 linux-ppc64 node-v10.15.3

USAGE
  $ chectl [COMMAND]

COMMANDS
  autocomplete  display autocomplete installation instructions
  devfile       generate and print a devfile to stdout given some Kubernetes resources and other Che workspaces features (project, language-support,
                commands etc...)
  help          display help for chectl
  server        control Che server
  update        update the chectl CLI
  workspace     control Che workspaces
```

**Comment by l0rd** [comment] 2019-12-04 23:04
@vrushaliinamdar we set the version when we do a release https://github.com/che-incubator/chectl/blob/master/.travis.yml#L28 otherwise on master branch we [don't update it](https://github.com/che-incubator/chectl/blob/master/package.json#L4). 

@benoitf what do you think about setting `next` as version in `package.json` in master branch?

**Comment by vrushaliinamdar** [comment] 2019-12-05 06:33
@l0rd @davidfestal any further suggestions for me ?

**Comment by vrushaliinamdar** [comment] 2019-12-09 09:02
@l0rd @davidfestal I have docker 1.13.1, openshift v3.11.154, kubernetes v1.11.0+d4cacc0 on the system on which I am trying to install Che.

does the docker version matter?

**Comment by l0rd** [comment] 2019-12-09 09:45
@vrushaliinamdar I thought that you solved your problem. As I mentioned in the comment above the version is always `0.0.2` when you clone and build chectl yourself. Can you provide the date of the latest 
 commit on your local chectl git repository? You can use the command `git log -1 --format=%cd` for example.  

No `docker` is not used/needed.

**Comment by vrushaliinamdar** [comment] 2019-12-10 12:43
@l0rd No, I am still facing the below issue while installing che.
```
✖ Create CRD checlusters.org.eclipse.che
      → **CustomResourceDefinition.apiextensions.k8s.io "checlusters.org.eclipse.che" is invalid: spec.validation.openAPIV3Schema: Invalid value**
```
The date of latest commit is:

chectl]# git log -1 --format=%cd
**Fri Nov 8 19:33:47 2019 +0100**


----------------------------------------------------------
]# ./bin/chectl server:start --platform=openshift --installer=operator --che-operator-cr-yaml=codewind-checluster.yaml --che-operator-image=bivasibm/che-operator-ppc64le
  ✔ Verify Kubernetes API...OK (it's OpenShift)
  ✔ 👀  Looking for an already existing Che instance
    ✔ Verify if Che is deployed into namespace "che"...it is not
  ✔ ✈️  Openshift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if openshift is running...done.
 ›   Warning: Che will be deployed in Multi-User mode since Configured 'operator' installer which support only such.
  ❯ 🏃‍  Running the Che Operator
    ✔ Copying operator resources...done.
    ✔ Create Namespace (che)...It already exists.
    ✔ Create ServiceAccount che-operator in namespace che...It already exists.
    ✔ Create Role che-operator in namespace che...It already exists.
    ✔ Create ClusterRole che-operator...It already exists.
    ✔ Create RoleBinding che-operator in namespace che...It already exists.
    ✔ Create ClusterRoleBinding che-operator...It already exists.
    ✖ Create CRD checlusters.org.eclipse.che
      → **CustomResourceDefinition.apiextensions.k8s.io "checlusters.org.eclipse.che" is invalid: spec.validation.openAPIV3Schema: Invalid value**

**Comment by vrushaliinamdar** [comment] 2019-12-12 06:58
@l0rd @davidfestal could you please help ?

**Comment by l0rd** [comment] 2019-12-12 09:57
@vrushaliinamdar please update your local git repo to a more recent version (git pull) and try again.

**Comment by davidfestal** [comment] 2019-12-12 11:08
@vrushaliinamdar 

If you don't use a released version of `chectl`, but build `chectl` yourself, then your `chectl` probably uses the [`master` version of the CRD](https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_crd.yaml)

In this case, the cause of your problem might be in this commit: https://github.com/eclipse/che-operator/commit/8ee9b4ea58c32560e520dc82b38b7e957bb4149a

And more precisely in lines: [27](https://github.com/eclipse/che-operator/blob/8ee9b4ea58c32560e520dc82b38b7e957bb4149a/deploy/crds/org_v1_che_crd.yaml#L27) and [502](https://github.com/eclipse/che-operator/blob/8ee9b4ea58c32560e520dc82b38b7e957bb4149a/deploy/crds/org_v1_che_crd.yaml#L502) of the CRD file.

It seems that the very last CRD has been erroneously generated by a too-much-recent release of the operator SDK, which added some fields at the root of the `OpenApiSchema` section, that are not supported by Openshift 3.11.

We'll test this further and keep you informed. However, in the meantime do you think you could use a released version of the `chectl` ? 
Another option, if you still need to build `chectl` yourself, is to modify the following line of its `package.json` file:

```
    "eclipse-che-operator": "git://github.com/eclipse/che-operator#master",
```
to 
```
    "eclipse-che-operator": "git://github.com/eclipse/che-operator#7.4.0",
```

**Comment by vrushaliinamdar** [comment] 2019-12-12 12:27
@l0rd Ok, I will fork latest version once again.

@davidfestal Since there is no chectl binary compatible with ppc64le is available. I need to build it from source itself.
I will try modifying `package.json` file and get back to you.

Thanks,
Vrushali

**Comment by vrushaliinamdar** [comment] 2019-12-13 09:06
@l0rd @davidfestal The installation went ahead and created CRD but, failing to download images for postgresql.

 chectl]# ./bin/run server:start --platform=openshift --installer=operator --che-operator-cr-yaml=codewind-checluster.yaml --che-operator-image=129.40.81.4:5000/che-operator-ppc64le
  ✔ Verify Kubernetes API...OK (it's OpenShift)
  ✔ 👀  Looking for an already existing Che instance
    ✔ Verify if Che is deployed into namespace "che"...it is not
  ✔ ✈️  Openshift preflight checklist
    ✔ Verify if oc is installed...done.
    ✔ Verify if openshift is running...done.
 ›   Warning: Che will be deployed in Multi-User mode since Configured 'operator' installer which support only such.
  ✔ 🏃‍  Running the Che Operator
    ✔ Copying operator resources...done.
    ✔ Create Namespace (che)...It already exists.
    ✔ Create ServiceAccount che-operator in namespace che...It already exists.
    ✔ Create Role che-operator in namespace che...It already exists.
    ✔ Create ClusterRole che-operator...It already exists.
    ✔ Create RoleBinding che-operator in namespace che...It already exists.
    ✔ Create ClusterRoleBinding che-operator...It already exists.
    ✔ Create CRD checlusters.org.eclipse.che...It already exists.
    ✔ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    ✔ Create deployment che-operator in namespace che...It already exists.
    ✔ Create Che Cluster eclipse-che in namespace che...done.
  ❯ ✅  Post installation checklist
    ❯ PostgreSQL pod bootstrap
      ✔ scheduling...done.
      ✖ downloading images
        → ERR_TIMEOUT: Timeout set to pod wait timeout 300000
        starting
      Keycloak pod bootstrap
      Devfile registry pod bootstrap
      Plugin registry pod bootstrap
      Che pod bootstrap
      Retrieving Che Server URL
      Che status check
Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000
    at KubeHelper.<anonymous> (~/chectl/src/api/kube.ts:525:11)
    at Generator.next (<anonymous>)
    at fulfilled (~/chectl/src/api/kube.ts:14:58)

Any suggestions?

**Comment by l0rd** [comment] 2019-12-13 09:33
@vrushaliinamdar you should have a look at the kubernetes events. I can see 2 possible causes for the error:
- kube cannot find the postgre image
- the image takes more then 5 minutes to download

**Comment by vrushaliinamdar** [comment] 2019-12-13 09:58
@l0rd I tried manually pulling the docker image - docker.io/ppc64le/postgres

**Comment by vrushaliinamdar** [comment] 2019-12-13 11:50
Hi @l0rd @davidfestal 
Same issue I have observed on x86 VM as well while installing Che. Even though I am not building anything from source and using all defaults.  Am I missing something?

**Comment by tolusha** [comment] 2019-12-16 09:42
I have the same problem.
```
minishift v1.34.2+83ebaab
chectl/0.0.20191212-next.7edebef linux-x64 node-v10.17.0
```

**Comment by tolusha** [comment] 2019-12-16 09:59
7.4.x binaries works fine

**Comment by davidfestal** [comment] 2019-12-16 11:07
As soon as you use a `chectl` that is not a released one, you will hit the invalid CRD error I analyzed here: https://github.com/eclipse/che/issues/15396#issuecomment-564961827.
Until we fix it on the master branch of the operator (which I'll do today)

**Comment by davidfestal** [comment] 2019-12-16 13:14
More details about the root cause can be found here: https://github.com/operator-framework/operator-sdk/issues/2118#issuecomment-549598512

**Comment by davidfestal** [comment] 2019-12-16 18:18
@vrushaliinamdar I merged the fix PR.
Could you please retry by simply building the last master chectl ?
Thanks !

**Comment by tolusha** [comment] 2019-12-17 10:25
I was able to install Eclipse Che with the latest changes.

**Closed as completed by tolusha** 2019-12-17 10:25 UTC
Labels: kind/bug, area/che-operator

**Comment by vrushaliinamdar** [comment] 2019-12-17 13:13
@davidfestal 
Tried installing che with latest chectl code. The installation is stuck at "postgresql - starting" phase.
When I checked the logs - I can see following error-

```
# oc logs postgres-c7b46b57d-6qchl -n che
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
fixing permissions on existing directory /var/lib/postgresql/data ... 
```

Any pointers on this issue?
