### ISSUE TITLE
error in cli output

### ISSUE THREAD

**Issue by riuvshin** [eclipse-che/che#3993] opened 2017-02-01 22:14 UTC
when I was running nightly server updates I've got following error in CLI output

```
[0;32mINFO:[0m (codenvy config): Generating codenvy configuration...
[mNotice: Compiled catalog for 1511be7f32f2.ec2.internal in environment production in 0.55 seconds[0m
[mNotice: Applied catalog in 0.09 seconds[0m
[0;32mINFO:[0m (codenvy config): Customizing docker-compose for running in a container
[0;32mINFO:[0m (codenvy start): Preflight checks
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
/scripts/base/library.sh: line 309: [: .: integer expression expected
         mem (1.5 GiB):           [0;32m[OK][0m
         disk (100 MB):           [0;32m[OK][0m
         port 80 (http):          [0;32m[AVAILABLE][0m
         port 443 (https):        [0;32m[AVAILABLE][0m
         port 2181 (zookeeper):   [0;32m[AVAILABLE][0m
         port 5000 (registry):    [0;32m[AVAILABLE][0m
         port 23750 (socat):      [0;32m[AVAILABLE][0m
         port 23751 (swarm):      [0;32m[AVAILABLE][0m
         port 32000 (jmx):        [0;32m[AVAILABLE][0m
         port 32001 (jmx):        [0;32m[AVAILABLE][0m
         port 8000 (debug):        [0;32m[AVAILABLE][0m
         port 9000 (lighttpd):    [0;32m[AVAILABLE][0m
         conn (browser => ws):    [0;32m[OK][0m
         conn (server => ws):     [0;32m[OK][0m

[0;32mINFO:[0m (codenvy start): Starting containers...
Creating codenvy_rsyslog_1
```

this is somehow related to version checks https://github.com/eclipse/che/blob/master/dockerfiles/base/scripts/base/library.sh#L309

@TylerJewell can you please take a look on this

**Comment by TylerJewell** [comment] 2017-02-01 23:11
I've tried running a whole series of tests and unable to reproduce so far.  I think this maybe was an image update issue somehow.

**Comment by riuvshin** [comment] 2017-02-01 23:12
@TylerJewell oki, let's close this and I will reopen if I will see it again, because Im not able to reproduce this  also

**Comment by benoitf** [comment] 2017-02-01 23:12
if you can use --trace option if you see it again

**Comment by riuvshin** [comment] 2017-02-06 13:12
Reproduced issue on stg
trace output
```
INFO: (codenvy config): Customizing docker-compose for running in a container
+++ printf 'INFO: %b %b\n' '(codenvy config): ' 'Customizing docker-compose for running in a container'
++ log 'INFO: (codenvy config):  Customizing docker-compose for running in a container'
++ [[ true = \t\r\u\e ]]
++ is_log
++ '[' true = true ']'
++ return 0
++ echo 'INFO: (codenvy config):  Customizing docker-compose for running in a container'
++ local_repo
++ '[' false = true ']'
++ return 1
++ local_assembly
++ '[' false = true ']'
++ return 1
++ cmd_config_post_action
++ has_docker_for_windows_client
++ [[ 172.30.11.129 = \1\0\.\0\.\7\5\.\2 ]]
++ return 1
++ local_repo
++ '[' false = true ']'
++ return 1
++ is_fast
++ '[' false = true ']'
++ return 1
++ skip_preflight
++ '[' false = true ']'
++ return 1
++ info start 'Preflight checks'
++ '[' -z x ']'
++ PRINT_COMMAND='(codenvy start): '
++ PRINT_STATEMENT='Preflight checks'
++ is_info
++ '[' true = true ']'
++ return 0
++ printf '\033[0;32mINFO:\033[0m %b%b\n' '(codenvy start): ' 'Preflight checks'
INFO: (codenvy start): Preflight checks
+++ printf 'INFO: %b %b\n' '(codenvy start): ' 'Preflight checks'
++ log 'INFO: (codenvy start):  Preflight checks'
++ [[ true = \t\r\u\e ]]
++ is_log
++ '[' true = true ']'
++ return 0
++ echo 'INFO: (codenvy start):  Preflight checks'
++ cmd_start_check_preflight
++ cmd_start_check_host_resources
+++ docker info
+++ grep 'Total Memory:'
++ HOST_RAM='Total Memory: 14.28 GiB'
+++ echo ' 14.28 GiB'
+++ xargs
++ HOST_RAM='14.28 GiB'
++ HOST_RAM=14.28
++ PREFLIGHT=
+++ less_than 14.28 1.5
+++ (( i=0 ))
+++ (( i<5 ))
+++ [[ 1 != 1 ]]
+++ (( i++  ))
+++ (( i<5 ))
+++ [[ 4 != . ]]
+++ '[' 4 -lt . ']'
/scripts/base/library.sh: line 309: [: .: integer expression expected
+++ return 1
++ text '         mem (1.5 GiB):           \033[0;32m[OK]\033[0m\n'
++ printf '         mem (1.5 GiB):           \033[0;32m[OK]\033[0m\n'
         mem (1.5 GiB):           [OK]
+++ printf '         mem (1.5 GiB):           \033[0;32m[OK]\033[0m\n'
++ log '         mem (1.5 GiB):           [OK]'
++ [[ true = \t\r\u\e ]]
++ is_log
++ '[' true = true ']'
++ return 0
++ echo '         mem (1.5 GiB):           [OK]'
+++ df /data
+++ grep /data
+++ cut -d ' ' -f 6
++ HOST_DISK=
+++ less_than '' 100000000
+++ (( i=0 ))
+++ (( i<0 ))
+++ return 1
++ text '         disk (100 MB):           \033[0;32m[OK]\033[0m\n'
++ printf '         disk (100 MB):           \033[0;32m[OK]\033[0m\n'
         disk (100 MB):           [OK]
+++ printf '         disk (100 MB):           \033[0;32m[OK]\033[0m\n'
++ log '         disk (100 MB):           [OK]'
++ [[ true = \t\r\u\e ]]
++ is_log
++ '[' true = true ']'
++ return 0
++ echo '         disk (100 MB):           [OK]'
++ [[ '' = \f\a\i\l ]]
++ cmd_start_check_ports
++ PORT_ARRAY=("80;port 80 (http):         " "443;port 443 (https):       " "2181;port 2181 (zookeeper):  " "5000;port 5000 (registry):   " "23750;port 23750 (socat):     " "23751;port 23751 (swarm):     " "32000;port 32000 (jmx):       " "32001;port 32001 (jmx):       ")
++ local PORT_ARRAY
++ debug_server
++ '[' false = true ']'
++ return 1
++ check_all_ports '80;port 80 (http):         ' '443;port 443 (https):       ' '2181;port 2181 (zookeeper):  ' '5000;port 5000 (registry):   ' '23750;port 23750 (socat):     ' '23751;port 23751 (swarm):     ' '32000;port 32000 (jmx):       ' '32001;port 32001 (jmx):       '
++ PORT_INTERNAL_ARRAY=("${@}")
++ declare -a PORT_INTERNAL_ARRAY
++ DOCKER_PORT_STRING=
++ HTTPD_PORT_STRING=
++ for index in '"${!PORT_INTERNAL_ARRAY[@]}"'
++ PORT=80
++ PORT_STRING='port 80 (http):         '
++ DOCKER_PORT_STRING+=' -p 80:80'
++ HTTPD_PORT_STRING+=' -p 80'
++ for index in '"${!PORT_INTERNAL_ARRAY[@]}"'
++ PORT=443
++ PORT_STRING='port 443 (https):       '
++ DOCKER_PORT_STRING+=' -p 443:443'
++ HTTPD_PORT_STRING+=' -p 443'
++ for index in '"${!PORT_INTERNAL_ARRAY[@]}"'
++ PORT=2181
++ PORT_STRING='port 2181 (zookeeper):  '
++ DOCKER_PORT_STRING+=' -p 2181:2181'
++ HTTPD_PORT_STRING+=' -p 2181'
++ for index in '"${!PORT_INTERNAL_ARRAY[@]}"'
++ PORT=5000
++ PORT_STRING='port 5000 (registry):   '
++ DOCKER_PORT_STRING+=' -p 5000:5000'
++ HTTPD_PORT_STRING+=' -p 5000'
++ for index in '"${!PORT_INTERNAL_ARRAY[@]}"'
++ PORT=23750
++ PORT_STRING='port 23750 (socat):     '
++ DOCKER_PORT_STRING+=' -p 23750:23750'
++ HTTPD_PORT_STRING+=' -p 23750'
++ for index in '"${!PORT_INTERNAL_ARRAY[@]}"'
++ PORT=23751
++ PORT_STRING='port 23751 (swarm):     '
++ DOCKER_PORT_STRING+=' -p 23751:23751'
++ HTTPD_PORT_STRING+=' -p 23751'
++ for index in '"${!PORT_INTERNAL_ARRAY[@]}"'
++ PORT=32000
++ PORT_STRING='port 32000 (jmx):       '
++ DOCKER_PORT_STRING+=' -p 32000:32000'
++ HTTPD_PORT_STRING+=' -p 32000'
++ for index in '"${!PORT_INTERNAL_ARRAY[@]}"'
++ PORT=32001
++ PORT_STRING='port 32001 (jmx):       '
++ DOCKER_PORT_STRING+=' -p 32001:32001'
++ HTTPD_PORT_STRING+=' -p 32001'
++ EXECUTION_STRING='docker run -it --rm  -p 80:80 -p 443:443 -p 2181:2181 -p 5000:5000 -p 23750:23750 -p 23751:23751 -p 32000:32000 -p 32001:32001 alpine:3.4                          sh -c "echo hi" > /dev/null 2>&1'
++ eval 'docker run -it --rm  -p 80:80 -p 443:443 -p 2181:2181 -p 5000:5000 -p 23750:23750 -p 23751:23751 -p 32000:32000 -p 32001:32001 alpine:3.4                          sh -c "echo hi" > /dev/null 2>&1'
+++ docker run -it --rm -p 80:80 -p 443:443 -p 2181:2181 -p 5000:5000 -p 23750:23750 -p 23751:23751 -p 32000:32000 -p 32001:32001 alpine:3.4 sh -c 'echo hi'
++ NETSTAT_EXIT=0
++ [[ 0 = 125 ]]
++ return 0
++ print_ports_as_ok '80;port 80 (http):         ' '443;port 443 (https):       ' '2181;port 2181 (zookeeper):  ' '5000;port 5000 (registry):   ' '23750;port 23750 (socat):     ' '23751;port 23751 (swarm):     ' '32000;port 32000 (jmx):       ' '32001;port 32001 (jmx):       '
++ PORT_INTERNAL_ARRAY=("${@}")
++ declare -a PORT_INTERNAL_ARRAY
++ for index in '"${!PORT_INTERNAL_ARRAY[@]}"'
++ PORT_STRING='port 80 (http):         '
++ text '         port 80 (http):          \033[0;32m[AVAILABLE]\033[0m\n'
++ printf '         port 80 (http):          \033[0;32m[AVAILABLE]\033[0m\n'
         port 80 (http):          [AVAILABLE]
+++ printf '         port 80 (http):          \033[0;32m[AVAILABLE]\033[0m\n'
++ log '         port 80 (http):          [AVAILABLE]'
++ [[ true = \t\r\u\e ]]
++ is_log
++ '[' true = true ']'
++ return 0
++ echo '         port 80 (http):          [AVAILABLE]'
++ for index in '"${!PORT_INTERNAL_ARRAY[@]}"'
++ PORT_STRING='port 443 (https):       '
++ text '         port 443 (https):        \033[0;32m[AVAILABLE]\033[0m\n'
++ printf '         port 443 (https):        \033[0;32m[AVAILABLE]\033[0m\n'
         port 443 (https):        [AVAILABLE]
+++ printf '         port 443 (https):        \033[0;32m[AVAILABLE]\033[0m\n'
++ log '         port 443 (https):        [AVAILABLE]'
++ [[ true = \t\r\u\e ]]
++ is_log
++ '[' true = true ']'
++ return 0
++ echo '         port 443 (https):        [AVAILABLE]'
++ for index in '"${!PORT_INTERNAL_ARRAY[@]}"'
++ PORT_STRING='port 2181 (zookeeper):  '
++ text '         port 2181 (zookeeper):   \033[0;32m[AVAILABLE]\033[0m\n'
++ printf '         port 2181 (zookeeper):   \033[0;32m[AVAILABLE]\033[0m\n'
         port 2181 (zookeeper):   [AVAILABLE]
+++ printf '         port 2181 (zookeeper):   \033[0;32m[AVAILABLE]\033[0m\n'
++ log '         port 2181 (zookeeper):   [AVAILABLE]'
++ [[ true = \t\r\u\e ]]
++ is_log
++ '[' true = true ']'
++ return 0
++ echo '         port 2181 (zookeeper):   [AVAILABLE]'
++ for index in '"${!PORT_INTERNAL_ARRAY[@]}"'
++ PORT_STRING='port 5000 (registry):   '
++ text '         port 5000 (registry):    \033[0;32m[AVAILABLE]\033[0m\n'
++ printf '         port 5000 (registry):    \033[0;32m[AVAILABLE]\033[0m\n'
         port 5000 (registry):    [AVAILABLE]
+++ printf '         port 5000 (registry):    \033[0;32m[AVAILABLE]\033[0m\n'
++ log '         port 5000 (registry):    [AVAILABLE]'
++ [[ true = \t\r\u\e ]]
++ is_log
++ '[' true = true ']'
++ return 0
++ echo '         port 5000 (registry):    [AVAILABLE]'
++ for index in '"${!PORT_INTERNAL_ARRAY[@]}"'
++ PORT_STRING='port 23750 (socat):     '
++ text '         port 23750 (socat):      \033[0;32m[AVAILABLE]\033[0m\n'
++ printf '         port 23750 (socat):      \033[0;32m[AVAILABLE]\033[0m\n'
         port 23750 (socat):      [AVAILABLE]
+++ printf '         port 23750 (socat):      \033[0;32m[AVAILABLE]\033[0m\n'
++ log '         port 23750 (socat):      [AVAILABLE]'
++ [[ true = \t\r\u\e ]]
++ is_log
++ '[' true = true ']'
++ return 0
++ echo '         port 23750 (socat):      [AVAILABLE]'
++ for index in '"${!PORT_INTERNAL_ARRAY[@]}"'
++ PORT_STRING='port 23751 (swarm):     '
++ text '         port 23751 (swarm):      \033[0;32m[AVAILABLE]\033[0m\n'
++ printf '         port 23751 (swarm):      \033[0;32m[AVAILABLE]\033[0m\n'
         port 23751 (swarm):      [AVAILABLE]
+++ printf '         port 23751 (swarm):      \033[0;32m[AVAILABLE]\033[0m\n'
++ log '         port 23751 (swarm):      [AVAILABLE]'
++ [[ true = \t\r\u\e ]]
++ is_log
++ '[' true = true ']'
++ return 0
++ echo '         port 23751 (swarm):      [AVAILABLE]'
++ for index in '"${!PORT_INTERNAL_ARRAY[@]}"'
++ PORT_STRING='port 32000 (jmx):       '
++ text '         port 32000 (jmx):        \033[0;32m[AVAILABLE]\033[0m\n'
++ printf '         port 32000 (jmx):        \033[0;32m[AVAILABLE]\033[0m\n'
         port 32000 (jmx):        [AVAILABLE]
+++ printf '         port 32000 (jmx):        \033[0;32m[AVAILABLE]\033[0m\n'
++ log '         port 32000 (jmx):        [AVAILABLE]'
++ [[ true = \t\r\u\e ]]
++ is_log
++ '[' true = true ']'
++ return 0
++ echo '         port 32000 (jmx):        [AVAILABLE]'
++ for index in '"${!PORT_INTERNAL_ARRAY[@]}"'
++ PORT_STRING='port 32001 (jmx):       '
++ text '         port 32001 (jmx):        \033[0;32m[AVAILABLE]\033[0m\n'
++ printf '         port 32001 (jmx):        \033[0;32m[AVAILABLE]\033[0m\n'
         port 32001 (jmx):        [AVAILABLE]
+++ printf '         port 32001 (jmx):        \033[0;32m[AVAILABLE]\033[0m\n'
++ log '         port 32001 (jmx):        [AVAILABLE]'
++ [[ true = \t\r\u\e ]]
++ is_log
++ '[' true = true ']'
++ return 0
++ echo '         port 32001 (jmx):        [AVAILABLE]'
++ cmd_start_check_agent_network
++ start_test_server
++ export AGENT_INTERNAL_PORT=80
++ AGENT_INTERNAL_PORT=80
++ export AGENT_EXTERNAL_PORT=32768
++ AGENT_EXTERNAL_PORT=32768
++ docker run -d -p 32768:80 --name fakeagent alpine:3.4 httpd -f -p 80 -h /etc/
+++ docker inspect '--format={{.NetworkSettings.IPAddress}}' fakeagent
++ export AGENT_INTERNAL_IP=172.17.0.2
++ AGENT_INTERNAL_IP=172.17.0.2
++ export AGENT_EXTERNAL_IP=172.30.11.129
++ AGENT_EXTERNAL_IP=172.30.11.129
++ PREFLIGHT=success
++ test1
+++ curl -I localhost:32768/alpine-release -s -o /data/cli.log --connect-timeout 5 --write-out '%{http_code}'
+++ NO_PROXY_CONFIG_FOR_CURL=("")
+++ local NO_PROXY_CONFIG_FOR_CURL
+++ [[ ! '' = '' ]]
+++ [[ ! '' = '' ]]
+++ has_curl
+++ hash curl
+++ return 0
++++ which curl
+++ log '/usr/bin/curl  "-I' localhost:32768/alpine-release -s -o /data/cli.log --connect-timeout 5 --write-out '%{http_code}"'
+++ [[ true = \t\r\u\e ]]
+++ is_log
+++ '[' true = true ']'
+++ return 0
+++ echo '/usr/bin/curl  "-I' localhost:32768/alpine-release -s -o /data/cli.log --connect-timeout 5 --write-out '%{http_code}"'
++++ which curl
+++ /usr/bin/curl -I localhost:32768/alpine-release -s -o /data/cli.log --connect-timeout 5 --write-out '%{http_code}'
++ HTTP_CODE=000
++ echo 28
++ check_http_code 000
++ '[' 000 = 200 ']'
++ return 1
++ return 1
++ test2
+++ curl -I 172.30.11.129:32768/alpine-release -s -o /data/cli.log --connect-timeout 5 --write-out '%{http_code}'
+++ NO_PROXY_CONFIG_FOR_CURL=("")
+++ local NO_PROXY_CONFIG_FOR_CURL
+++ [[ ! '' = '' ]]
+++ [[ ! '' = '' ]]
+++ has_curl
+++ hash curl
+++ return 0
++++ which curl
+++ log '/usr/bin/curl  "-I' 172.30.11.129:32768/alpine-release -s -o /data/cli.log --connect-timeout 5 --write-out '%{http_code}"'
+++ [[ true = \t\r\u\e ]]
+++ is_log
+++ '[' true = true ']'
+++ return 0
+++ echo '/usr/bin/curl  "-I' 172.30.11.129:32768/alpine-release -s -o /data/cli.log --connect-timeout 5 --write-out '%{http_code}"'
++++ which curl
+++ /usr/bin/curl -I 172.30.11.129:32768/alpine-release -s -o /data/cli.log --connect-timeout 5 --write-out '%{http_code}'
++ HTTP_CODE=200
++ check_http_code 200
++ '[' 200 = 200 ']'
++ return 0
++ return 0
++ text '         conn (browser => ws):    \033[0;32m[OK]\033[0m\n'
++ printf '         conn (browser => ws):    \033[0;32m[OK]\033[0m\n'
         conn (browser => ws):    [OK]
+++ printf '         conn (browser => ws):    \033[0;32m[OK]\033[0m\n'
++ log '         conn (browser => ws):    [OK]'
++ [[ true = \t\r\u\e ]]
++ is_log
++ '[' true = true ']'
++ return 0
++ echo '         conn (browser => ws):    [OK]'
++ test3
```

**Comment by riuvshin** [comment] 2017-02-06 13:14
whole trace of start command attached
[trace_start.zip](https://github.com/eclipse/che/files/754644/trace_start.zip)

**Comment by TylerJewell** [comment] 2017-02-06 14:42
I see the bug.   The less_than() method expects to always compare numbers of the same size - where the decimal will be in the same location.  So it can compare `1.543` and `5.234` ok, but it fails when you have `14.68` and `1.56` because of the decimal location.

**Comment by riuvshin** [comment] 2017-02-06 14:45
that's explains why we have this issue randomly, seems we just need to round floats and we are good

**Comment by TylerJewell** [comment] 2017-02-06 21:15
Thanks for finding a way to reproduce it.

**Comment by riuvshin** [comment] 2017-02-07 13:36
reopen since I've reverted commit

**Closed as completed** 2017-02-07 16:05 UTC
Labels: kind/bug, severity/P2
