### ISSUE TITLE
Unable to install Che on k8s platform using helm3 installer with chectl , throws JS Error: TypeError: request.abort is not a function

### ISSUE THREAD

**Issue by aaraodeo** [eclipse-che/che#17976] opened 2020-09-26 13:09 UTC
### Describe the bug
Unable to install Che on k8s platform using helm3 installer with chectl , throws JS Error: TypeError: request.abort is not a function

### Che version
7.19.1 

### Steps to reproduce

1) chectl server:delete --skip-kubernetes-health-check
No issue for above command
2) chectl server:start --cheimage=quay.io/eclipse/che-server:7.19.1 --installer=helm --platform=k8s --skip-kubernetes-health-check --domain=10.242.131.161.nip.io --self-signed-cert --k8spodreadytimeout=230000 --k8spodwaittimeout=600000 --cheboottimeout=80000

› Current Kubernetes context: 'kubernetes-admin@kubernetes'
 ›   Warning: "self-signed-cert" flag is deprecated and has no effect. Autodetection is used instead.
  ↓ Verify Kubernetes API [skipped]
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
  ✔ ✈️  Kubernetes preflight checklist
    ✔ Verify if kubectl is installed
    ↓ Verify remote kubernetes status [skipped]
    ✔ Check Kubernetes version: Found v1.12.10+1.0.10.el7.
    ✔ Verify domain is set...set to 10.242.131.161.nip.io.
    ↓ Check if cluster accessible [skipped]
  ✔ Start following logs
    ↓ Start following Operator logs [skipped]
    ✔ Start following Eclipse Che logs...done
    ✔ Start following Postgres logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plugin registry logs...done
    ✔ Start following Devfile registry logs...done
  ✔ Start following events
    ✔ Start following namespace events...done
 ›   Warning: Consider using the more reliable 'OLM' installer when deploying a stable release of Eclipse Che (--installer=olm).
  ❯ 🏃‍  Running Helm to install Eclipse Che
    ✔ Verify if helm is installed
    ✔ Check Helm Version: Found v3.3.4+ga61ce56
    ✔ Create Namespace (che)...does already exist.
    ❯ Check Eclipse Che TLS certificate...going to generate self-signed one
      ✔ Check Cert Manager deployment...already deployed
      ✔ Wait for cert-manager...ready
      ⠦ Check Cert Manager CA certificate...generating new one
        Set up Eclipse Che certificates issuer
        Request self-signed certificate
        Wait for self-signed certificate
        Retrieving Che self-signed CA certificate
      Check Cluster Role Binding
      Preparing Eclipse Che Helm Chart
      Updating Helm Chart dependencies
      Deploying Eclipse Che Helm Chart
/root/.local/share/chectl/client/7.19.1/lib/api/kube.js:153
                    request.abort();
                            ^
TypeError: request.abort is not a function
    at Timeout.setTimeout [as _onTimeout] (/root/.local/share/chectl/client/7.19.1/lib/api/kube.js:153:29)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

### Expected behavior
Che is installed successfully.

### Runtime
kubernetes 

kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10+1.0.14.el7", GitCommit:"51694421359f8938d25e9450fd8a3111307be90c", GitTreeState:"clean", BuildDate:"2020-07-22T14:54:41Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10+1.0.10.el7", GitCommit:"d5cce6424ede9dc4f24f6090525bfa539bddee99", GitTreeState:"clean", BuildDate:"2019-11-08T18:04:52Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

docker version
Client: Docker Engine - Community
 Version:           19.03.11-ol
 API version:       1.40
 Go version:        go1.14.4
 Git commit:        a9b9315
 Built:             Tue Jun 23 03:33:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11-ol
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.4
  Git commit:       a9b9315
  Built:            Tue Jun 23 03:31:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
  Default Registry: docker.io
 containerd:
  Version:          v1.2.0-rc.0-108-gc444666
  GitCommit:        c4446665cb9c30056f4998ed953e6d4ff22c7c39
 runc:
  Version:          1.0.0-rc5+dev
  GitCommit:        4bb1fe4ace1a32d3676bb98f5d3b6a4e32bf6c58
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

### Screenshots
N/A

### Installation method
    chectl
   
chectl version
chectl/7.19.1 linux-x64 node-v10.22.1

### Environment
   OS: Oracle Linux Server 7.8 64 bit, kernel: 4.14.35-1902.3.1.el7uek.x86_64
   Hardware: Virtual Machine with 12 GB Ram,  Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz, Disk space for "/" 53% used.

### Eclipse Che Logs
N/A

### Additional context
N/A

**Comment by tolusha** [comment] 2020-09-28 05:48
This issue has been fixed in master branch https://github.com/che-incubator/chectl/pull/879
But it exists in 7.19.x as well.

@aaraodeo 
thank you for pointing that out.

**Closed as completed** 2020-09-28 08:57 UTC
Labels: kind/bug

**Comment by aaraodeo** [comment] 2020-09-29 18:42
Which 7.19.x build this will be fixed? Is it fixed in nightly build?

**Comment by tolusha** [comment] 2020-09-30 06:58
It is fixed in nightly build and it will be fixed in 7.19.2 (expected this week)

**Comment by aaraodeo** [comment] 2020-10-01 15:49
Its not fixed in 7.19.2, i am getting same issue with following command:
chectl server:start --cheimage=quay.io/eclipse/che-server:7.19.2 --installer=helm --platform=k8s --skip-kubernetes-health-check --domain=10.242.131.161.nip.io --che-operator-cr-patch-yaml=patch.yaml --self-signed-cert

**Comment by aaraodeo** [comment] 2020-10-01 15:55
Not fixed in nightly build too, getting same error with following command:
 chectl server:start --cheimage=quay.io/eclipse/che-server:nightly --installer=helm --platform=k8s --skip-kubernetes-health-check --domain=10.242.131.161.nip.io --che-operator-cr-patch-yaml=patch.yaml --self-signed-cert

**Comment by tolusha** [comment] 2020-10-02 07:17
To deploy the nightly version of Eclipse Che use the latest version for chectl from the next channel: `chectl update next`
To deploy the stable version of Eclipse Che uses the stable version of chectl: `chectl update stable`
In both cases `--cheimage` flag is not needed

It confuses, I've created the issue [1] to enhance this process. 
https://github.com/eclipse/che/issues/18022

**Comment by aaraodeo** [comment] 2020-10-02 19:06
This is really getting confusing.
I experienced and as described in chectl server:start documentation (https://github.com/che-incubator/chectl)
If we do not give -cheimage its takes the default: quay.io/eclipse/che-server:nightly image.
I observed while using stable version of chectl. I had even updated chectl from version 7.19.0 to 7.19.1 using chectl stable update command.

For chectl on next channel if default is quay.io/eclipse/che-server:nightly image, its fine.
But for chectl on stable the default must be latest stable release but its not the case it is nightly build.
Also we do not have quay.io/eclipse/che-server:latest or quay.io/eclipse/che-server:stable image tag like we have for quay.io/eclipse/che-server:nightly, kindly confirm the same.

**Comment by aaraodeo** [comment] 2020-10-02 19:07
As the issue is not fixed in 7.19.2, can we keep it in open state, instead of closing it?

**Comment by tolusha** [comment] 2020-10-05 07:43
I can't reproduce it anymore.
Make sure you are using the latest 7.19.2 chectl. (`chectl update stable`)
If you are still experiencing the problem feel free to open the issue and provide stack trace and chectl command you used.

**Comment by aaraodeo** [comment] 2020-10-05 15:22
chectl version
chectl/7.19.2 linux-x64 node-v10.22.1

chectl server:start --cheimage=quay.io/eclipse/che-server:7.19.2 --installer=helm --platform=k8s --domain=10.242.131.161.nip.io  --skip-kubernetes-health-check
› Current Kubernetes context: 'kubernetes-admin@kubernetes'
  ↓ Verify Kubernetes API [skipped]
  ✔ 👀  Looking for an already existing Eclipse Che instance
    ✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
  ✔ ✈️  Kubernetes preflight checklist
    ✔ Verify if kubectl is installed
    ↓ Verify remote kubernetes status [skipped]
    ✔ Check Kubernetes version: Found v1.12.10+1.0.15.el7.
    ✔ Verify domain is set...set to 10.242.131.161.nip.io.
    ↓ Check if cluster accessible [skipped]
  ✔ Start following logs
    ↓ Start following Operator logs [skipped]
    ✔ Start following Eclipse Che logs...done
    ✔ Start following Postgres logs...done
    ✔ Start following Keycloak logs...done
    ✔ Start following Plugin registry logs...done
    ✔ Start following Devfile registry logs...done
  ✔ Start following events
    ✔ Start following namespace events...done
 ›   Warning: Consider using the more reliable 'OLM' installer when deploying a stable release of Eclipse Che (--installer=olm).
  ✔ 🏃‍  Running Helm to install Eclipse Che
    ✔ Verify if helm is installed
    ✔ Check Helm Version: Found v3.3.4+ga61ce56
    ✔ Create Namespace (che)...does already exist.
    ✔ Check Eclipse Che TLS certificate...self-signed TLS certificate secret found
    ✔ Check Cluster Role Binding...done.
    ✔ Preparing Eclipse Che Helm Chart...done.
    ✔ Updating Helm Chart dependencies...done.
    ✔ Deploying Eclipse Che Helm Chart...done.
  ✔ ✅  Post installation checklist
    ✔ Devfile registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Plugin registry pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Eclipse Che pod bootstrap
      ✔ scheduling...done.
      ✔ downloading images...done.
      ✔ starting...done.
    ✔ Retrieving Eclipse Che server URL... https://che-che.10.242.131.161.nip.io
    ✔ Eclipse Che status check
Command server:start has completed successfully.

kubectl get po -n che
NAME                                READY   STATUS    RESTARTS   AGE
che-6db6b48787-s754t                1/1     Running   0          16m
devfile-registry-59d4445cdc-87czm   1/1     Running   0      16m
plugin-registry-79cc64766c-4r6fd    1/1     Running   0       16m

kubectl get svc -n che
NAME               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
che-host           ClusterIP   10.99.249.123   <none>        8080/TCP,8087/TCP   16m
devfile-registry   ClusterIP   10.98.10.251    <none>        8080/TCP                  16m
plugin-registry    ClusterIP   10.97.9.160     <none>        8080/TCP                  16m

Installation went fine but i am unable to access https://che-che.10.242.131.161.nip.io outside cluster in a web-browser.

On the same master k8s node(10.242.131.161) where che is installed.

curl -k https://che-che.10.242.131.161.nip.io --no-proxy che-che.10.242.131.161.nip.io
curl: (7) Failed connect to che-che.10.242.131.161.nip.io:1080; Connection refused

This indicates some port mapping issue, i guess. Also kindly confirm if we need to configure a ingress-controller to access che ide outside cluster or the installation using helm installer is enough?

**Comment by aaraodeo** [comment] 2020-10-05 18:24
on repeated installation, after successfully installation i got the following issue too:

 curl -k  https://che-che.10.242.131.161.nip.io --noproxy che-che.10.242.131.161.nip.io
curl: (7) Failed connect to che-che.10.242.131.161.nip.io:443; Connection refused
[root@slc04lmm opt]# wget https://che-che.10.242.131.161.nip.io --no-proxy che-che.10.242.131.161.nip.io
--2020-10-05 11:23:05--  https://che-che.10.242.131.161.nip.io/
Resolving che-che.10.242.131.161.nip.io (che-che.10.242.131.161.nip.io)... 10.242.131.161
Connecting to che-che.10.242.131.161.nip.io (che-che.10.242.131.161.nip.io)|10.242.131.161|:443... failed: Connection refused.
--2020-10-05 11:23:05--  http://che-che.10.242.131.161.nip.io/
Connecting to che-che.10.242.131.161.nip.io (che-che.10.242.131.161.nip.io)|10.242.131.161|:80... failed: Connection refused.

**Comment by tolusha** [comment] 2020-10-06 06:57
@aaraodeo 
I confirm that che should be accessible outside the cluster.
