### ISSUE TITLE
[CHE6-branch] Terminal width doesn't adapt to the width of Che window

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#6837] opened 2017-10-19 12:43 UTC
### Description
On the following image, MC takes just a part of the screen width. 
![mc](https://user-images.githubusercontent.com/1851863/31771277-2915cad8-b4e4-11e7-8e3d-e3016674ed9f.png)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by tolusha** [comment] 2017-10-30 12:11
Unfortunately I can't reproduce the issue. Could you provide any steps?

**Comment by skabashnyuk** [comment] 2017-10-30 12:12
I've also had this issue on my Mac sometimes.

**Comment by mmorhun** [comment] 2017-11-03 14:46
I found how to reproduce it:
1. Open a workspace
2. Refresh browser tab
3. After refresh in the terminal will be two tabs: `dev-machine` and `Terminal`
4. Switch to the `Terminal` tab. It won't be resizable.

**Comment by AndrienkoAleksandr** [comment] 2017-11-03 14:59
Thank you @mmorhun . Finally we have steps to reproduce.

**Comment by vitaliy-guliy** [comment] 2017-11-20 10:01
Fixed with https://github.com/eclipse/che/pull/7396

**Closed as completed by vitaliy-guliy** 2017-11-20 10:01 UTC
Labels: kind/bug, severity/P1
