### ISSUE TITLE
Perform severity labels changes

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17997] opened 2020-09-30 12:24 UTC
### Is your task related to a problem? Please describe.
We have an intention to build our sprint priorities according to issues available in the issues like milestone + severity label.
We agreed that /blocker /P1 and /P2 is not enough to do that priorities, severity labels where designed mainly for bugs, at least it's described in https://github.com/eclipse/che/wiki/Labels#bug-severities on the wiki.

So, according to discussion that happened between @l0rd, @davidfestal, @benoitf we would need one more severity label, then we would have
blocker - Must be resolved immediately
P1 - Should be prioritized during sprint planning
P2 - Should be considered when planning sprints
P3 - There is no plan to fix bug/implement feature. Should not be considered to be taken into the next sprint

This issue is about getting a final agreement on the proposed changes and reflect wiki with the corresponding changes.

**Comment by l0rd** [comment] 2020-09-30 13:38
I would slightly change P1 and blocker definitions:

**blocker**: Put on hold your current task and fix that immediately
**P1**: Work on this next. Based on current sprint priorities it can be postponed to next sprint or included as unplanned work in current sprint.

And the other thing to consider is migration. When we create P3 label we should probably update P2 -> P3 and P1 -> P2.

**Comment by ericwill** [comment] 2020-10-19 15:04
IMHO we are mixing severity and priority, and this causes some issues when it comes to planning/assessing what to work on next.

## Severity
Describes how severe an issue is **completely ignoring any priority context**. Something that prevents Che from starting is by definition a `blocker`. An issue causing serious usability problems/regressions is by definition a `major` issue. Issue that have workarounds or aren't as severe are `minor`. Enhancements and feature requests have severity `enhancement`.

Now, severity can vary depending on the submitter of the bug. For example, a bug in a niche area of Che my be `minor` for me, but to a community member who relies on that area it could be a `major` or even a `blocker` issue.

**Severity is owned by the submitter.**

## Priority
Describes a user's or team's priority on that issue. Issues that must be fixed in the current sprint are deemed `critical`. Issues that should be fixed in the current sprint are deemed `P1`. Issues that can wait _n_ sprints but should be fixed eventually are deemed `P2`. Issues that we do not plan to work on can be marked as `help wanted`

This is assessed by individual contributors, or team leads. In the severity example above, maybe the user intends to fix the `blocker` issue. They can set `critical` for themselves, as they intend to fix it this sprint. But maybe I as a team lead working for Red Hat wouldn't set that priority as it's not a priority for my team.

Alternatively, maybe the user really wants an issue fixed, but cannot do it themselves. They can increase the priority on the issue, and maybe I as a team lead will consider taking the issue into my sprint, if the case to work on it is strong enough.

**Priority is owned by the submitter, or the person/team working on the issue.**

## Proposal
I propose we document the following in the wiki, and I am willing to do it.

### Severity Labels
| Label  | Description |
| ------------- | ------------- |
| `blocker`  | Blocks development or use of Che entirely.  |
| `major`  | A serious loss of function, usability, or a regression caused by recent work.  |
| `minor` | An issue that does not seriously interfere with day-to-day usage of Che, and/or an easy workaround is present |
| `enhancement` | Request for a new feature. Cases where functionality was expected, but is missing, can also be classified as a higher severity. |

### Priority Labels
| Label  | Description |
| ------------- | ------------- |
| `critical`  | Must fix in this sprint. Should be used sparingly.  |
| `P1`  | Very important that this issue is fixed in this sprint. Ideally all `P1` issues in a sprint plan should be fixed.  |
| `P2` | Of normal importance. |
| `help wanted` | A valid bug/request, but there are no plans to work on it. |

### Issue Triage
During issue triage, **the triager sets severity**. During prioritization/sprint planning, the **team lead sets priority**. Any user from the community can also set priority and either work on the bug themselves, or make the case to someone else about why their issue should be worked on.

**Comment by l0rd** [comment] 2020-10-21 08:41
@sleshchenko original problem was the lack of an extra priority label (blocker/P1/P2 was not enough).

@ericwill your proposal solves a different problem that deserves its own issue/discussion:

> we are mixing severity and priority, and this causes some issues when it comes to planning/assessing what to work on next

What are the issues caused by the fact that we do not do a distinction between severity and priority? Who has those issues? Can you open a distinct issue to provides those informations?

**Comment by ericwill** [comment] 2020-10-21 14:49
> @ericwill your proposal solves a different problem that deserves its own issue/discussion:
> 
> > we are mixing severity and priority, and this causes some issues when it comes to planning/assessing what to work on next
> 
> What are the issues caused by the fact that we do not do a distinction between severity and priority? Who is affected by those issues? Can you open a distinct issue to provides those informations?

Yes you're right it's best to have a separate discussion. I filed a new issue #18160

**Closed as completed** 2021-05-11 13:53 UTC
Labels: kind/task, severity/P1, lifecycle/frozen
