### ISSUE TITLE
chectl   operator installer  failed to deploy  to  Minikube

### ISSUE THREAD

**Issue by fredcsfaria** [eclipse-che/che#19807] opened 2021-05-16 15:05 UTC
### Describe the bug

Che  server:deploy   fails  to deploy on Minikube

> Current Kubernetes context: 'minikube'
  V Verify Kubernetes API...OK
  V ??  Looking for an already existing Eclipse Che instance
    V Verify if Eclipse Che is deployed into namespace "eclipse-cheop"...it is not
  > ??  Minikube preflight checklist
    V Verify if kubectl is installed
    V Verify if minikube is installed
    V Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    V Check Kubernetes version: Found v1.20.2.
    × Verify if minikube ingress addon is enabled
      → Unexpected token E in JSON at position 0
      Enable minikube ingress addon
      Retrieving minikube IP and domain for ingress URLs
      Checking minikube version
      Check if cluster accessible
 »   **Error: SyntaxError: Unexpected token E in JSON at position 0
 »   Command server:deploy failed.** 

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Expected behavior

The eclipse-che  should be deployed on Minikube namespace.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
    - [ ] Openshift (include output of `oc version`)
   - [X ] minikube (include output of `minikube version` and `kubectl version`)

C:\>minikube version
Enable colors error: Parâmetro incorreto.
minikube version: v1.20.0
commit: c61663e942ec43b20e8e70839dcca52e44cd85ae

C:\> kubectl version
    Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.1
6.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.1
5.5", Compiler:"gc", Platform:"linux/amd64"}
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

> Current Kubernetes context: 'minikube'
  V Verify Kubernetes API...OK
  V ??  Looking for an already existing Eclipse Che instance
    V Verify if Eclipse Che is deployed into namespace "eclipse-cheop"...it is not
  > ??  Minikube preflight checklist
    V Verify if kubectl is installed
    V Verify if minikube is installed
    V Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    V Check Kubernetes version: Found v1.20.2.
    × Verify if minikube ingress addon is enabled
      → Unexpected token E in JSON at position 0
      Enable minikube ingress addon
      Retrieving minikube IP and domain for ingress URLs
      Checking minikube version
      Check if cluster accessible
 »   Error: SyntaxError: Unexpected token E in JSON at position 0
 »   Command server:deploy failed. Error log: C:\Users\fcharles\AppData\Local\chectl\error.log Eclipse Che logs: C:\Users\fcharles\AppData\Local\Temp\chectl-logs\1621176

 

### Installation method
   - [X ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
          chectl server:deploy --installer operator -p minikube -n eclipse-cheop
     * provide an output of `chectl version` command
              >chectl version
                 chectl/7.30.1 win32-x64 node-v12.22.1
    
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ X] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

### Eclipse Che Logs

2021-05-16T14:56:22.202Z Error: SyntaxError: Unexpected token E in JSON at position 0
2021-05-16T14:56:22.202Z Command server:deploy failed. Error log: C:/Users/fcharles/AppData/Local/chectl/error.log Eclipse Che logs: C:/Users/fcharles/AppData/Local/Temp/chectl-logs/1621176978937
2021-05-16T14:56:22.202Z     at Object.error (C:/Users/fcharles/AppData/Local/chectl/client/7.30.1/node_modules/@oclif/errors/lib/index.js:26:15)
2021-05-16T14:56:22.202Z     at Deploy.error (C:/Users/fcharles/AppData/Local/chectl/client/7.30.1/node_modules/@oclif/command/lib/command.js:60:23)
2021-05-16T14:56:22.202Z     at Deploy.<anonymous> (C:/Users/fcharles/AppData/Local/chectl/client/7.30.1/lib/commands/server/deploy.js:253:22)
2021-05-16T14:56:22.202Z     at Generator.throw (<anonymous>)
2021-05-16T14:56:22.202Z     at rejected (C:/Users/fcharles/AppData/Local/chectl/client/7.30.1/node_modules/tslib/tslib.js:115:69)

**Comment by fredcsfaria** [comment] 2021-05-16 15:08
Steps to reproduce:
>chectl server:deploy --installer operator -p minikube -n eclipse-cheop

**Comment by flacatus** [comment] 2021-05-17 07:54
Hi @fredcsfaria !
I'm not able to reproduce your issue... I can deploy 7.30.1 normally in my local Windows 10.
I've installed minikube 1.20.0 using hyperv driver.

![image](https://user-images.githubusercontent.com/59865209/118451750-dc0cc800-b6f5-11eb-9248-9bd27b13f666.png)

**Comment by fredcsfaria** [comment] 2021-05-17 15:47
Hello @flacatus 

I am using  the stack Minikube,  Windows 7 and Virtual Box.    I  had already Che running before in that configuration  using early releases of Minikube/Kubectl.
 
![image](https://user-images.githubusercontent.com/52935549/118517010-3bc29d80-b70d-11eb-99e8-c17ee5b6fc59.png)

**Comment by flacatus** [comment] 2021-05-17 15:50
@fredcsfaria Can you try to run first `minikube addons enable ingress``and then install che, please?

**Comment by fredcsfaria** [comment] 2021-05-17 16:00
@flacatus  Sure.

![image](https://user-images.githubusercontent.com/52935549/118519745-c4dad400-b70f-11eb-8533-8cea7d0429c5.png)

**Comment by flacatus** [comment] 2021-05-17 16:05
Do you have powershell in W7? Can u try running as administrator?

**Comment by fredcsfaria** [comment] 2021-05-17 19:50
Sure. Power Shell as admin:

![image](https://user-images.githubusercontent.com/52935549/118547823-f4013d80-b72f-11eb-8e06-8b0bdde05a4a.png)

**Comment by tolusha** [comment] 2021-05-18 06:37
@flacatus 
did you use the same v1.20.0 minikube version ?

@fredcsfaria
What does this print? Accordingly to source code it fails on parsing the following output.
`minikube addons list -o json`

**Comment by fredcsfaria** [comment] 2021-05-18 17:02
@tolusha 
  would the issue to be due to the message  "Enable colors error" in the first line of output ?

**Comment by fredcsfaria** [comment] 2021-05-18 17:28
@tolusha 
  would the issue to be due to the message  "Enable colors error" in the first line of output ?  I dont know this parameter.
ps:Sorry, i had closed the issue  by mistake

![image](https://user-images.githubusercontent.com/52935549/118696725-f5d90880-b7e4-11eb-9a51-3606d8670fa3.png)

**Comment by tolusha** [comment] 2021-05-19 07:33
@fredcsfaria
yes, I guess that's the reason. 

@flacatus 
Are you aware how to configure a terminal to avoid such a message ?

**Comment by tolusha** [comment] 2021-06-07 07:35
I close this issue since it is not related to chectl it self.

**Closed as completed by tolusha** 2021-06-07 07:35 UTC
Labels: kind/bug, severity/P1, area/chectl
