### ISSUE TITLE
Not valid zip file when starting a Che 7 Java workspace

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12831] opened 2019-03-05 18:23 UTC
### Description

If I try to start a workspace with JDT LS (c.f. the workspce config attributes below) it fails with "not a valid zip file error"

```json
  "attributes": {
    "editor": "org.eclipse.che.editor.theia:1.0.0",
    "org.eclipse.che.vscode-redhat.java.memory_limit": "1024Mi",
    "sidecar.theia-ide.memory_limit": "512Mi",
    "plugins": "che-machine-exec-plugin:0.0.1,org.eclipse.che.vscode-redhat.java:0.38.0"
  }
```

![image](https://user-images.githubusercontent.com/606959/53826981-3f2d3c80-3f7a-11e9-8b47-ebac500c227f.png)

### Workaround

A second start of the workspace is successful

**Comment by l0rd** [comment] 2019-03-05 18:24
@garagatyi @tolusha are you aware of this issue?

**Comment by johnmcollier** [comment] 2019-03-05 19:05
I've been hitting this on Kube too with the latest images

**Comment by garagatyi** [comment] 2019-03-06 06:57
@l0rd duplicate of https://github.com/eclipse/che/issues/12762

**Closed as completed by garagatyi** 2019-03-06 06:57 UTC
Labels: kind/bug
