### ISSUE TITLE
Factory API doesn't work correctly

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#15439] opened 2019-12-10 04:11 UTC
### Describe the bug

We have an error message "Internal Server Error occurred" each time when trying to create a new factory which includes a devfile.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

7.6.0-SNAPSHOT

### Steps to reproduce
1. Open the swagger     <che-server>/swagger/
2. Then  /factory  POST (Create a new factory based on configuration)
3. Depends on Model Schema it supports devfile. 
    Paste this JSON:
```json
{
  "v": "4.0",
  "devfile":  {
    "apiVersion": "1.0.0",
    "metadata": {
      "generateName": "java-maven-"
    },
    "projects": [
      {
        "name": "console-java-simple",
        "source": {
          "type": "git",
          "location": "https://github.com/che-samples/console-java-simple.git",
          "branch": "java1.11"
        }
      }
    ],
    "components": [],
    "commands": []
  }
}
``` 
And try it out.

4. Receive an error message "Internal Server Error occurred, error time: 2019-12-10 ..."

### Expected behavior

The new factory will be created.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![Screenshot from 2019-12-10 05-49-20](https://user-images.githubusercontent.com/6310786/70494391-d4fe8500-1b13-11ea-917c-5f5203bb928a.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by olexii4** [comment] 2019-12-10 04:37
What about Factory API  GET /factory/workspace/{ws-id}?
Should it support workspace with devfile or not?

For now, it returns an error "Workspace created with Devfile can not be exported as Factory."
![Screenshot from 2019-12-10 06-35-58](https://user-images.githubusercontent.com/6310786/70496173-658a9480-1b17-11ea-8fd7-7d958abf4855.png)

@sleshchenko @skabashnyuk  WDYT?

**Comment by skabashnyuk** [comment] 2019-12-10 07:25
@olexii4 this expected behavior because devfile isn't adapted to the factory. https://github.com/eclipse/che/issues/12925

**Comment by olexii4** [comment] 2019-12-10 08:14
@skabashnyuk Ok. I just look into the Model Schema in the swagger:
![Screenshot from 2019-12-10 10-13-23](https://user-images.githubusercontent.com/6310786/70507767-bdd08f00-1b35-11ea-9d77-cfcfb2305e7e.png)
 So,  it is not finished yet.

**Comment by skabashnyuk** [comment] 2019-12-10 08:17
Closing as duplicate https://github.com/eclipse/che/issues/12925

**Closed as completed by skabashnyuk** 2019-12-10 08:17 UTC
Labels: status/analyzing
