### ISSUE TITLE
CHE CLI - nightly - errors - opensuse

### ISSUE THREAD

**Issue by akorneta** [eclipse-che/che#3855] opened 2017-01-23 15:25 UTC
how I run che

```
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock \
                    -v /home/tony/.che:/data \
                    -v /home/tony/.che/backup:/backup \
                    codenvy/che-cli:nightly $@
```

it fails with:

```
Status: Image is up to date for codenvy/che-cli:nightly
docker: Error response from daemon: oci runtime error: exec: "bin/install.sh": permission denied.
```
my env
OpenSuse 13.2
docker info:
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.12.1
Storage Driver: btrfs
 Build Version: Btrfs v4.5.3+20160516
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.16.7-53-desktop
Operating System: openSUSE 13.2 (Harlequin) (x86_64)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.43 GiB
Name: akorneta
ID: ADPP:JTHS:SSTP:TI5B:J3CV:TDMA:DVWV:C7KF:BEAY:PUIW:NMJL:72WS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

it was working last week

**Comment by TylerJewell** [comment] 2017-01-23 15:27
@akorneta - this may not be a bug.  Start by wiping all of your old images, and then rebuild nightly from master.  And then rerun.  

1. Build dockerfiles/base
2. Build dockerfiles/cli
3. Try running again.

**Comment by riuvshin** [comment] 2017-01-23 15:29
@TylerJewell we wiped all local images and pulled fresh from hub
 this is probably blocker issue, I can't reproduce this on mac. will test on ubuntu.

btw what is `install.sh` ? I never saw that script before.

**Comment by TylerJewell** [comment] 2017-01-23 15:30
I tested the latest nightly on fedora and centos and windows and mac this weekend, and wasn't having any issues.  Perhaps this is specif to opensuse?

**Comment by benoitf** [comment] 2017-01-23 15:35
BTW we don't have any install.sh

in the command I see "**codenvy**/che-cli:nightly $@" while the correct image name is "eclipse/che:nightly" (or eclipse/che-cli:nightly) (no codenvy at all)

**Comment by riuvshin** [comment] 2017-01-23 15:35
reproduced on ubuntu. I think this issue is actual for any linux. it seems issue comes from this PR https://github.com/eclipse/che/commit/c32d871f0272d18066c2623a7d52ac2277bb7472 it is the only place where I was able to find `install.sh`

**Comment by TylerJewell** [comment] 2017-01-23 15:36
Ohhhh - yeah, it's a syntax issue.  We should destroy `codenvy/che-cli` from dockerhub :)  @benoitf - how did you catch that?  My eyes glossed right over the name.

**Comment by riuvshin** [comment] 2017-01-23 15:38
strange... let us check, I wonder how we was able to pull codenvy/che-cli


original issue we had with codenvy not che, but we reproduced on che aswell

**Comment by benoitf** [comment] 2017-01-23 15:41
@TylerJewell well error was kinda strange as we've now `entrypoint.sh` almost everywhere now

**Comment by benoitf** [comment] 2017-01-23 15:43
@riuvshin  image is on dockerhub so we can pull that 6months old image ![image](https://cloud.githubusercontent.com/assets/436777/22210691/f3248c66-e18a-11e6-9d76-c1e45dd3ea12.png)

**Comment by riuvshin** [comment] 2017-01-23 15:46
we reproduced issue on codenvy, it is different issue. I closing this, sorry for this one

**Closed as completed by riuvshin** 2017-01-23 15:46 UTC
