### ISSUE TITLE
Unable to config keycloak if use https

### ISSUE THREAD

**Issue by LarryZhangy** [eclipse-che/che#9429] opened 2018-04-15 06:34 UTC
### Description
If config https to run che by use nightly image, it can't access keycloak  by run /scripts/keycloak_config.sh in keycloak pod， Because there is no https config in keycloak_config.sh

I can access https://keycloak-domaim/auth on chrome.

### Reproduction Steps
config keycloak by run job
```
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-configure-job
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-keycloak
        image: <my>/alphine:3.5
        command: ["sh", "-c", " adresses_length=0; until [ $adresses_length -gt 0 ]; do echo waiting for keycloak to be ready...; sleep 2; endpoints=`curl -s --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\"     https://kubernetes.default.svc/api/v1/namespaces/$POD_NAMESPACE/endpoints/keycloak`; adresses_length=`echo $endpoints | jq -r \".subsets[]?.addresses // [] | length\"`; done;"]
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      containers:
      - name: keycloak-configure-job
        image: eclipse/che-keycloak:nightly
        command: ["/scripts/keycloak_config.sh"]
        env:
          - name: HTTP_PROTOCOL
            value: "https"
          - name: KC_HOST
            value: <domain>
          - name: CHE_KEYCLOAK_ADMIN_REQUIRE_UPDATE_PASSWORD
            value: "true"
          - name: CHE_HOST
            value: <domain>
      serviceAccountName: che-keycloak
      restartPolicy: Never
  #backoffLimit: 4
```

**OS and version:**    

all image of che:   nightly

**Diagnostics:**

**Comment by LarryZhangy** [comment] 2018-04-15 06:35
@guydaichs

**Comment by guydaichs** [comment] 2018-04-15 07:46
There are a couple of issues with running KeyCloak with TLS:
1. Initial Che realm configuration (keycloak_config.sh) might fail due to [SSL enforcement on master realm](https://www.keycloak.org/docs/3.2/server_admin/topics/realms/ssl.html#_ssl_modes), if the pod's cluster IP is not in a certain range (10.0.x.x, 192.168.x.x, and 172..16.x.x). 
2. Che doesn't configure KeyCloak with a [TLS-terminating reverse proxy](https://www.keycloak.org/docs/2.5/server_installation/topics/clustering/load-balancer.html). As a result, the OIDC provider discovery fails, and you cannot login with KeyCloak. 
3. With multi-host configuration, you will also run into CORS issues. 

Essentially, running Multi-User Che with TLS is not yet supported (Single-User with TLS should work). I'll update the docs and values files to reflect this. 

To support this scenario, some changes need to be made to the KeyCloak configuration script, Ingress definitions and deployment orchestration. This issue should be added to https://github.com/eclipse/che/issues/5908. 

There is a nice reference for running [KeyCloak on k8s with Ingress TLS termination](https://github.com/kubernetes/charts/tree/master/incubator/keycloak). This is a very flexible chart, that relies on [wildfly CLI configuration](https://github.com/kubernetes/charts/tree/master/incubator/keycloak#wildfly-configuration). 

Currently, Che uses a simple KeyCloak configuration mechanism that is common to docker, OpenShift and Kubernetes infrastructures. Changes to this mechanism require a discussion with all relevant stakeholders. 

@skabashnyuk @akorneta @eivantsov @davidfestal @mshaposhnik - WDYT?

**Comment by eivantsov** [comment] 2018-04-24 10:43
@LarryZhangy @guydaichs if you change entrypoint in keycloak image and execute kc_realm_user.sh script, no rest calls will be initiated. 

I should probably issue a PR since we don't need Keycloak job, as just running a different entrypoint auto configures keycloak https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/charts/che-keycloak/templates/deployment.yaml#L48

**Comment by guydaichs** [comment] 2018-04-24 13:51
Sounds good to me. This will solve the initial configuration issue. Additionally, KeyCloak should be configured to [support Ingress as a TLS terminator](https://www.keycloak.org/docs/2.5/server_installation/topics/clustering/load-balancer.html).

**Comment by eivantsov** [comment] 2018-04-24 16:15
@guydaichs i wonder why it is not required for OpenShift routes that are HAProxy based. We just use Keycloak as is.

**Comment by eivantsov** [comment] 2018-04-24 18:11
@guydaichs @LarryZhangy I have issued a PR - works fine with http on MiniKube - realm and user provisioning happens in entrypoint, and no REST calls are made.

**Comment by arielbangiev** [comment] 2018-05-06 12:16
@eivantsov, @guydaichs, we tried to deploy Che to Kubernetes with multiuser and TLS after your merge of PR #9533.

The host of the Keycloak ingress looks something like this:
```
https://my-server.com/auth/
```

A valid certificate is served when accessing this url.

The PROTOCOL environment variable of the Keycloak pod is appropriately set to https, but the ```/auth/admin/master/console/index.html``` file contains links and scripts that have the http prefix:
```
    <link href="http://my-server.com/auth/resources/3.3.0.cr2/admin/keycloak/lib/patternfly/css/patternfly.css" rel="stylesheet" />
    <link href="http://my-server.com/auth/resources/3.3.0.cr2/admin/keycloak/node_modules/select2/select2.css" rel="stylesheet" />
```

Consequently, the Keycloak Administration Console doesn't load due to mixed content.

Can you please take a look?

**Comment by eivantsov** [comment] 2018-05-06 13:25
@arielbangiev `PROTOCOL` env is used only by the entrypoint script to configure realm and and client reidrectUris and webOrigins.

As far as I understand, automatic redirection to https should happen when tls is on - https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/charts/che-keycloak/templates/ingress.yaml#L16-L17

Does Keycloak fail to load because of this? What does browser dev console yells at?

**Comment by perspectivus1** [comment] 2018-05-07 07:02
@eivantsov, the Keycloak ingress is configured correctly -- it accepts https requests and forwards them to the Keycloak server. The issue is the generation of Keycloak Admin Console **client resources**. All links are generated using full path, including **protocol** and hostname.

The browser throws a mixed content error:
```
Mixed Content: The page at 'https://my-server.com/auth/admin/master/console/' was loaded over HTTPS, but requested an insecure favicon 'http://my-server.com/auth/resources/3.3.0.cr2/admin/keycloak/img/favicon.ico'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by eivantsov** [comment] 2018-05-07 07:54
@perspectivus1 I wonder why it works correctly on OpenShift. Routes are set to Allow or Redirect insecure traffic (both work).

**Comment by eivantsov** [comment] 2018-05-07 18:04
@annatech 

> I’m pretty sure that if the resource URLs obeyed the page protocol that there should be no issue running multi-user Eclipse Che / Keycloak under HTTPS on OpenShift.
Eclipse Che multi-user support https mode on OpenShift. It's tried and tested. That's why I ask myself and those you may have any ideas - why does it work with OpenShift routes and doesn't work with ingress?

![image](https://user-images.githubusercontent.com/5337267/39716873-3b3c3988-523a-11e8-8cfa-eb8566b1c9a8.png)

**Comment by dbengtson** [comment] 2018-05-11 03:53
@eivantsov 

Setting PROXY_ADDRESS_FORWARDING to true in the keycloak deployment fixed this issue for me in my GKE install.

**Comment by mjshashank** [comment] 2018-05-11 04:05
@dbengtson I seem to be facing a similar issue as described in #9674 . Where exactly does this change need to be made to fix it?

Note: Mine is a GKE installation as well.

**Comment by dbengtson** [comment] 2018-05-11 04:38
@mjshashank

In the [-env section for the keycloak deployment](https://github.com/eclipse/che/blob/f5b9275bb700269f7efcec98318c2d68385f9e6f/deploy/kubernetes/helm/che/charts/che-keycloak/templates/deployment.yaml#L58)
add this:
{{- if .Values.global.tls.enabled }}
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
{{- end }}

**Comment by mjshashank** [comment] 2018-05-11 04:44
@dbengtson I had just done that and it works. Thanks!

**Comment by eivantsov** [comment] 2018-09-10 07:35
Closed as fixed.

**Closed as completed by eivantsov** 2018-09-10 07:35 UTC
Labels: kind/question

**Comment by tony-engineering** [comment] 2020-03-03 10:23
@dbengtson thanks for the hint, that worked

**Comment by myasas** [comment] 2020-11-10 15:06
> @mjshashank
> 
> In the [-env section for the keycloak deployment](https://github.com/eclipse/che/blob/f5b9275bb700269f7efcec98318c2d68385f9e6f/deploy/kubernetes/helm/che/charts/che-keycloak/templates/deployment.yaml#L58)
> add this:
> {{- if .Values.global.tls.enabled }}
> - name: PROXY_ADDRESS_FORWARDING
> value: "true"
> {{- end }}

This is the fix for overcoming the issue !!!! (specially in a docker/kubernetes environment when you are using TLS in your ingress/route)

Thanks a lot @dbengtson !!!
