### ISSUE TITLE
Go devfile LS Not working without updating Go language server plugin to the experimental version.

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#16113] opened 2020-02-24 11:58 UTC
### Describe the bug
Go devfile is showing notification about updating the version of Go vsix plugin and a warning regarding development tools missing in the path installation.

### Che version
7.9.0-SNAPSHOT
 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
* Open a Go getting started devfile
* Open any .go script
* Next to the notifications in the bottom bar on a right side you will see a notification about missing development tools and outdated plugin

### Expected behavior
No errors/warnings are present

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`) 4.3, 4.2
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot_20200255_161009_closeup](https://user-images.githubusercontent.com/16451875/75261441-5698b180-57eb-11ea-8699-245f78260349.png)

![image](https://user-images.githubusercontent.com/16451875/75150606-1232e600-5705-11ea-94a0-a4cdbb60789d.png)

### Installation method
   - [x] chectl  `-a operator -p openshift --ssl --self-signed-cert`
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify) ocp42.codereadyqe.com
   - [ ] other: please specify

**Comment by ibuziuk** [comment] 2020-02-24 17:47
@ScrewTSW how this affects UX with Go, other than warning?

**Comment by tolusha** [comment] 2020-02-25 07:00
It is interesting to check Go LS features if they still work.

**Comment by ScrewTSW** [comment] 2020-02-25 12:14
strange... with next build of Che nightly, the warning has disappeared.

**Comment by ScrewTSW** [comment] 2020-02-25 12:22
@ibuziuk @tolusha No. The error highlighting and code completion only work once the `GO.vsix` plugin is updated. But even after updating the vsix plugin, the toolchain is saying that the binary is missing.

**Comment by ScrewTSW** [comment] 2020-02-25 14:00
Strange thing is that it's a one-time thing per deployment.
Once you do the update through theia, the stacks always work correctly - with the updated plugin the error highlighting and code completion works correctly.

**Comment by ibuziuk** [comment] 2020-02-25 14:14
Setting P1 after discussion with Tibor, looks like Go devfile is broken atm

**Comment by ScrewTSW** [comment] 2020-02-25 15:20
Pre update:
![Screenshot_20200225_161507](https://user-images.githubusercontent.com/16451875/75260883-8b583900-57ea-11ea-9967-26938efb5734.png)
![Screenshot_20200225_161009](https://user-images.githubusercontent.com/16451875/75260919-98752800-57ea-11ea-8530-ce269bab8ba0.png)
Update log:
```
Installing 1 tool at /go/bin
  gopls
Starting building the current package at /projects/src/github.com/golang/example/outyet
Not able to determine import path of current package by using cwd: /projects/src/github.com/golang/example/outyet and Go workspace: /projects/src
Starting building the current package at /projects/src/github.com/golang/example/outyet
Not able to determine import path of current package by using cwd: /projects/src/github.com/golang/example/outyet and Go workspace: /projects/src
Installing golang.org/x/tools/cmd/gopls FAILED
1 tools failed to install.
gopls:
Error: Command failed: /usr/local/go/bin/go get -u -v golang.org/x/tools/cmd/gopls
Fetching https://golang.org/x/tools/cmd/gopls?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/gopls?go-get=1: x509: certificate signed by unknown authority
package golang.org/x/tools/cmd/gopls: unrecognized import path "golang.org/x/tools/cmd/gopls" (https fetch: Get https://golang.org/x/tools/cmd/gopls?go-get=1: x509: certificate signed by unknown authority)
Fetching https://golang.org/x/tools/cmd/gopls?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/gopls?go-get=1: x509: certificate signed by unknown authority
package golang.org/x/tools/cmd/gopls: unrecognized import path "golang.org/x/tools/cmd/gopls" (https fetch: Get https://golang.org/x/tools/cmd/gopls?go-get=1: x509: certificate signed by unknown authority)
Installing golang.org/x/tools/cmd/gopls FAILED
1 tools failed to install.
gopls:
Error: Command failed: /usr/local/go/bin/go get -u -v golang.org/x/tools/cmd/gopls
Fetching https://golang.org/x/tools/cmd/gopls?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/gopls?go-get=1: x509: certificate signed by unknown authority
package golang.org/x/tools/cmd/gopls: unrecognized import path "golang.org/x/tools/cmd/gopls" (https fetch: Get https://golang.org/x/tools/cmd/gopls?go-get=1: x509: certificate signed by unknown authority)
Fetching https://golang.org/x/tools/cmd/gopls?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/gopls?go-get=1: x509: certificate signed by unknown authority
package golang.org/x/tools/cmd/gopls: unrecognized import path "golang.org/x/tools/cmd/gopls" (https fetch: Get https://golang.org/x/tools/cmd/gopls?go-get=1: x509: certificate signed by unknown authority)
Installing golang.org/x/tools/cmd/gopls FAILED
1 tools failed to install.
gopls:
Error: Command failed: /usr/local/go/bin/go get -u -v golang.org/x/tools/cmd/gopls
Fetching https://golang.org/x/tools/cmd/gopls?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/gopls?go-get=1: x509: certificate signed by unknown authority
package golang.org/x/tools/cmd/gopls: unrecognized import path "golang.org/x/tools/cmd/gopls" (https fetch: Get https://golang.org/x/tools/cmd/gopls?go-get=1: x509: certificate signed by unknown authority)
Fetching https://golang.org/x/tools/cmd/gopls?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/gopls?go-get=1: x509: certificate signed by unknown authority
package golang.org/x/tools/cmd/gopls: unrecognized import path "golang.org/x/tools/cmd/gopls" (https fetch: Get https://golang.org/x/tools/cmd/gopls?go-get=1: x509: certificate signed by unknown authority)
Installing golang.org/x/tools/cmd/gopls FAILED
1 tools failed to install.
gopls:
Error: Command failed: /usr/local/go/bin/go get -u -v golang.org/x/tools/cmd/gopls
Fetching https://golang.org/x/tools/cmd/gopls?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/gopls?go-get=1: x509: certificate signed by unknown authority
package golang.org/x/tools/cmd/gopls: unrecognized import path "golang.org/x/tools/cmd/gopls" (https fetch: Get https://golang.org/x/tools/cmd/gopls?go-get=1: x509: certificate signed by unknown authority)
Fetching https://golang.org/x/tools/cmd/gopls?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/gopls?go-get=1: x509: certificate signed by unknown authority
package golang.org/x/tools/cmd/gopls: unrecognized import path "golang.org/x/tools/cmd/gopls" (https fetch: Get https://golang.org/x/tools/cmd/gopls?go-get=1: x509: certificate signed by unknown authority)
/projects/src/github.com/golang/example/outyet>Finished running tool: /usr/local/go/bin/go build -o /tmp/vscode-goPfiPhe/go-code-check .
/projects/src/github.com/golang/example/outyet/main.go:20: syntax error: non-declaration statement outside function body
/projects/src/github.com/golang/example/outyet>Finished running tool: /usr/local/go/bin/go build -o /tmp/vscode-goPfiPhe/go-code-check .
/projects/src/github.com/golang/example/outyet/main.go:20: syntax error: non-declaration statement outside function body
```
After "Reload"
![Screenshot_20200225_161826](https://user-images.githubusercontent.com/16451875/75260968-b2166f80-57ea-11ea-8664-055a534cdd81.png)
![Screenshot_20200225_161736](https://user-images.githubusercontent.com/16451875/75260972-b2af0600-57ea-11ea-98fa-fdc1030bb1ae.png)

**Comment by JPinkney** [comment] 2020-02-25 15:51
I _thought_ a solution to this might be setting the che go plugin preference `go.useLanguageServer: true` in the devfile (it would get rid of the popup) but for some reason the golang language server features only work on the first go file opened (which is an issue in itself regardless)

**Comment by amisevsk** [comment] 2020-02-25 21:00
From my experience with this plugin on the vscode side, `gopls` leaves a *lot* to be desired but is required for module projects, so should be enabled by default in the plugin if possible.

Which analysis tools are missing? They should be added to the go sidecar, since `/go` is not persisted.

**Comment by ScrewTSW** [comment] 2020-02-26 08:46
@amisevsk I think it was refering to `gopls`.

**Comment by amisevsk** [comment] 2020-02-26 17:37
@ScrewTSW `gopls` is only required when the "experimental" language server is enabled; since the analysis tools popup appears before it's enabled, it suggests that something else is missing. If you get the notification again, it should output which analysis tools its installing.

Either way, I'm +1 on adding `gopls` to the golang sidecar.

**Comment by JPinkney** [comment] 2020-02-26 17:49
I just tried on che.openshift.io and it looks like the problem is that it's missing `golangci-lint`. I'm guessing this issue was introduced when the preference was changed in the devfile? https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/go/devfile.yaml#L19.

If I start a workspace and remove that preference the `Analysis Tools Missing` error doesn't pop up

**Comment by amisevsk** [comment] 2020-02-28 19:19
`golangci-lint` is installed, except the binary ends up in `/usr/local/go/src/bin` instead of `/usr/local/go/bin`, leaving it outside of the path. The script used to install it outputs to `./bin` for the current working directory.

**Comment by Katka92** [comment] 2020-03-11 14:15
Hi guys, is there any progress on that issue? This issue is still present in 7.10.0-SNAPSHOT.

**Comment by Ohrimenko1988** [comment] 2020-03-11 14:25
Can somebody describe what to do if notifications with update suggestions missed?
Do we have any way to update LS except notification confirmation?

**Comment by ScrewTSW** [comment] 2020-03-11 14:26
The notification appears with every workspace startup until the plugin is updated.

**Comment by Ohrimenko1988** [comment] 2020-03-11 14:27
@ScrewTSW Could you please describe steps for updating LS if update suggestions missed?

**Comment by ScrewTSW** [comment] 2020-03-12 15:26
@Ohrimenko1988 
* restart workspace
* open a .go file
* wait for LS initialization and notification pop-up:
![Screenshot_20200312_162253](https://user-images.githubusercontent.com/16451875/76537563-3bca6c00-647e-11ea-98d1-25865830ed13.png)
* click "Update"
* wait for installation, new notification will pop-up:
![Screenshot_20200312_162310](https://user-images.githubusercontent.com/16451875/76537578-4127b680-647e-11ea-90fe-0240c2247c5e.png)
* click "Reload"

**Comment by ScrewTSW** [comment] 2020-03-12 15:28
@amisevsk the `Go analysis tool missing` notification is not present anymore in 7.10.0 snapshot. Did not test for 7.9.x

**Comment by amisevsk** [comment] 2020-03-12 19:17
The fix for this issue would be to add it to the che-sidecar-go image (`go get gopls`) during the build. Then we could update the settings in the plugin to use the lang server, removing the prompt.

If you miss the prompt, nothing bad happens (provided all the regular tools are installed), but it will return if you try to work on a project that uses go modules.

**Comment by Ohrimenko1988** [comment] 2020-03-13 07:35
@amisevsk But the title of this issue "Go devfile Not working without updating Go language server to the experimental version." and according to this I suppose if you missed notification the Go language server will not work. Am I right?

**Comment by ScrewTSW** [comment] 2020-03-13 12:29
> @amisevsk But the title of this issue "Go devfile Not working without updating Go language server to the experimental version." and according to this I suppose if you missed notification the Go language server will not work. Am I right?

fixed the issue name

**Comment by ScrewTSW** [comment] 2020-03-13 13:27
@rhopp found out that the problem, and why after update the LS works across the same workspace type after deletion/restarts is that what fixes the language server is a simple user preference setting:
```
"go.useLanguageServer": true
```

**Comment by ericwill** [comment] 2020-03-13 14:11
> @rhopp found out that the problem, and why after update the LS works across the same workspace type after deletion/restarts is that what fixes the language server is a simple user preference setting:
> 
> ```
> "go.useLanguageServer": true
> ```
> 
> After setting that preference the golang devfile LS works correctly

So this is what's required to fix this issue, just the one setting? Or updating the Go LS plugin also needs to happen?

**Comment by ScrewTSW** [comment] 2020-03-13 14:20
> "go.useLanguageServer": true

I've created a new user, opened swagger and pushed
```
{
  "theia-user-preferences": "{\"application.confirmExit\":\"never\",\"workbench.iconTheme\":\"theia-file-icons\",\"go.useLanguageServer\":true}",
  "temporary": "false",
  "codenvy:created": "1584108807687"
}
```
to the preferences endpoint and then tried to open a new golang devfile.

the fix seems to be working even on newly created users that haven't been touched previously.

**Comment by ericwill** [comment] 2020-03-24 17:00
I believe the work here is done.

**Closed as completed by ericwill** 2020-03-24 17:00 UTC
Labels: kind/bug, severity/P1, area/languages

**Comment by MichalMaler** [comment] 2020-04-02 12:38
But the error highlighting isn't working yet. (Info from Tibor Dancs)
