### ISSUE TITLE
Add ability to use che-theia-generator to match with specific Theia version

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#13978] opened 2019-07-23 14:41 UTC
### Describe the bug
Currently we are using che-theia-generator with hard-coded latest configuration of the che-theia https://github.com/ws-skeleton/che-theia-generator/blob/master/src/templates/assembly-package.mst. But configuration generated in such way could be broken when we build che-theia with older theia branch(f.e. for theia v0.7.0). Hard-coded configuration could contains newer extension/s which we don't have in the older theia version and build of che-theia fail.

### Che version
 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by benoitf** [comment] 2019-07-23 14:53
AFAIK generator will be part of che-theia so it should ease that ?

**Comment by AndrienkoAleksandr** [comment] 2019-07-24 07:03
> AFAIK generator will be part of che-theia so it should ease that ?

I think yes.

**Comment by nickboldt** [comment] 2019-07-24 15:57
So... is this something that will be changed over from the ws-skeleton to the che-theia repo? Are we talking about a PoC now, and something fixed in che-theia upstream later? 

I'm confused what the issue is and what the solution will be. Also on priority. Need help w/ triage here.

**Comment by nickboldt** [comment] 2019-07-31 20:53
@slemeur if you think this needs to be in 7.2, then it's been triaged. removing the status/need-triage label

**Comment by evidolob** [comment] 2019-08-28 06:41
As now generator inside che-theia repository, there are nothing to do

**Closed as completed by evidolob** 2019-08-28 06:41 UTC
Labels: kind/enhancement, status/open-for-dev
