### ISSUE TITLE
`Error: failed to create subPath directory for volumeMount ` when creating a non ephemeral workspace

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#17545] opened 2020-07-31 12:29 UTC
Hello,
I am having these issue with hosted Che at the moment, with non ephemeral workspaces

```
Error when starting workspace
Unable to start workspace. Error when trying to start the workspace: Plugins installation process failed. Error: Unrecoverable event occurred: 'Failed', 'Error: failed to create subPath directory for volumeMount "claim-che-workspace" of container "che-plugin-metadata-broker-v3-2-0"', 'workspaceewczjlaabl3dway9.che-plugin-broker'
```
![image](https://user-images.githubusercontent.com/650571/89034755-e5c96880-d339-11ea-916e-6f0996ca2e26.png)

```
Successfully assigned sutan-1-che/workspaceewczjlaabl3dway9.che-plugin-broker to ip-172-31-65-51.us-east-2.compute.internal
pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.2.0"
Successfully pulled image "quay.io/eclipse/che-plugin-metadata-broker:v3.2.0"
Error: failed to create subPath directory for volumeMount "claim-che-workspace" of container "che-plugin-metadata-broker-v3-2-0"
```

![image](https://user-images.githubusercontent.com/650571/89034884-23c68c80-d33a-11ea-8b75-1cca01b2237b.png)

**Comment by ibuziuk** [comment] 2020-07-31 12:37
looks like you are starting from some factory, same issue from the getting started devfiles?

**Comment by ibuziuk** [comment] 2020-07-31 14:04
@sunix done the PVC cleanup for the account. is it still reproducible?

**Comment by ibuziuk** [comment] 2020-07-31 14:49
Closing. A separate issue for providing better UX - https://github.com/eclipse/che/issues/17546

**Closed as completed by ibuziuk** 2020-07-31 14:49 UTC
Labels: kind/bug, area/hosted-che
