### ISSUE TITLE
[Hosted Che] Unauthorized! Configured service account doesn't have access.

### ISSUE THREAD

**Issue by TheZoker** [eclipse-che/che#12366] opened 2019-01-09 14:36 UTC
I tried to run theia within che following these instructions:
https://docs.google.com/document/d/1hFXTwzIU3MnqcciXH9E7xyUtEJRUeUuJ-e0JlEhTKjo/mobilebasic

After doing everything exactly what the docs say, the "Loading" dialog takes forever. After waiting a long time, I tried to start the workspace again. But I get the following issue:

![screenshot_2019 01 09_15h28m07s_009_](https://user-images.githubusercontent.com/1368405/50905754-d1561000-1423-11e9-9747-5ca96d96d33d.png)

Here copy'n'paste:

> Failure executing: GET at: https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/api/v1/namespaces/zoker2-che/persistentvolumeclaims. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked.. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.

I also tried to install the theia stack with the same result. 

Does anyone know what went wrong here? I did not change any parameter or anything else...

**Comment by mohschmid** [comment] 2019-01-09 15:18
Same issue for me!

**Comment by hellanemrri** [comment] 2019-01-10 12:38
Same issue for me..???????

**Comment by bryantson** [comment] 2019-08-19 14:37
Same issue as well. Any update?

**Comment by sleshchenko** [comment] 2019-08-19 14:39
@bryantson Could you provide information about how did you deploy your Che? Chectl, operator, helm....? What were the arguments?

**Comment by bryantson** [comment] 2019-08-19 15:29
@sleshchenko The issue was encountered when I used https://che.openshift.io. I also did encountered the issue when I ran minishift previously.

**Comment by amisevsk** [comment] 2019-08-22 15:03
This is a che.openshift.io specific issue and seems to be related to how user accounts are provisioned there. 

I've created issue https://github.com/redhat-developer/rh-che/issues/1569 to track this, as it's not a Che-specific issue.

**Comment by davidwindell** [comment] 2019-08-22 21:01
I also have this issue on Rancher so I don't think it's platform specific

**Comment by puneethpk** [comment] 2019-10-07 06:09
Even i have the same issue..any fixes for this? or is it still open?

**Comment by l0rd** [comment] 2019-10-07 07:47
@puneethpk I beleive the original issue on che.openshift.io has been fixed. I am not able to reproduce it neither locally nor on an hosted instance of Che. Can you please provide some details that would help us reproduce it?

**Comment by amisevsk** [comment] 2019-10-07 11:56
@davidwindell @puneethpk Could you share details about your Che installations? The referenced error message is pretty specific to our production deployment. 

As a test, the output of `kubectl describe serviceaccount che` or similar would be helpfu (in addition to the usual version/deploy method/cluster info).

**Comment by davidwindell** [comment] 2019-10-07 15:03
I'm no longer able to reproduce it, can't recall when it was fixed but it might be when I started applying `cheWorkspacesNamespace` to my helm values.

**Comment by puneethpk** [comment] 2019-10-08 09:07
I have deployed it using yaml files in kubernetes cluster deployed in aws. This is the error log i get when i try to create a workspace.Che service account has all the access.
`The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password`

**Comment by hari1992-web** [comment] 2020-04-01 05:58
> I have deployed it using yaml files in kubernetes cluster deployed in aws. This is the error log i get when i try to create a workspace.Che service account has all the access.
> `The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password`

i am also facing same issue by using through yaml files , any solution please

**Comment by hari1992-web** [comment] 2020-04-01 05:59
Error: Failed to start the workspace: "Failure executing: POST at: https://10.96.0.1/api/v1/namespaces. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. namespaces is forbidden: User "system:serviceaccount:default:che" cannot create resource "namespaces" in API group "" at the cluster scope. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password."

**Comment by skabashnyuk** [comment] 2020-04-01 06:18
related to https://github.com/eclipse/che/issues/15946 
CC @ibuziuk

**Comment by hari1992-web** [comment] 2020-04-01 09:11
> related to #15946
> CC @ibuziuk

Its not helpful

**Comment by skabashnyuk** [comment] 2020-04-01 09:32
@hari1992-web this issue is might be related to https://github.com/eclipse/che/issues/15946 It's worth to check it again when https://github.com/eclipse/che/issues/15946 would be closed.

**Comment by hari1992-web** [comment] 2020-04-11 05:28
Press F5 or click here to try again.

Error: Failed to start the workspace: "Failure executing: GET at: https://10.96.0.1/api/v1/namespaces/che-che. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked. Unauthorized. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password."

**Comment by hari1992-web** [comment] 2020-04-11 05:28
Press F5 or click here to try again.

Error: Failed to start the workspace: "Failure executing: GET at: https://10.96.0.1/api/v1/namespaces/che-che. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked. Unauthorized. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password."

![Screenshot from 2020-04-11 10-55-48](https://user-images.githubusercontent.com/62592574/79036182-60337880-7be3-11ea-9af9-dab6ba068469.png)

**Comment by hari1992-web** [comment] 2020-04-11 06:04
Error: Error: Che TLS mode is turned on, but required "che-tls" secret is not pre-created in "che" namespace
![Screenshot from 2020-04-11 11-34-09](https://user-images.githubusercontent.com/62592574/79036690-65df8d00-7be8-11ea-847f-d1058bbd1104.png)    using chectl also its facing error

**Comment by ibuziuk** [comment] 2020-04-11 09:33
the original issue is che.openshift.io specific if you can still reproduce it on there, please provide details. Otherwise, please open a separate issue with details.

**Comment by hari1992-web** [comment] 2020-04-11 10:36
eclipse che+keycloak+postgres sql on kubernetes how to write yaml files and what is the procedure please explain any body knows ????????????????????????/

**Comment by sleshchenko** [comment] 2020-04-13 07:24
> eclipse che+keycloak+postgres sql on kubernetes how to write yaml files and what is the procedure please explain any body knows ????????????????????????/

@hari1992-web could you clarify what do you mean by writing yaml files? files for what? creating tls self-signed secret? BTW it does not seems a question related to this issue, please open a new issue with your question. Will try to help when understand which issues you face.

**Comment by hari1992-web** [comment] 2020-04-13 14:38
so I want to  install eclipse che  on kubernetes master machine through yaml files  what is procedure ???

**Comment by sleshchenko** [comment] 2020-04-14 07:27
@hari1992-web We don't support installing through yaml files, we only support helm or operator.
For sure you can run helm with --dry-run and --debug options and extract yamls files you'll be able to apply manually, but it may be error-prone and I don't recommend doing it until you deeply understand Che Deployment. What the problem with chectl? 
Please again, create a separate issue!

**Comment by ibuziuk** [comment] 2020-04-14 09:50
Looks like we had an issue with expired token on 1a and 1b. @skryzhny rotated the tokens and the issue should be fixed. 
@hari1992-web could you please confirm that https://github.com/eclipse/che/issues/12366#issuecomment-612333192 is no longer reproducible fo r you?

**Comment by hari1992-web** [comment] 2020-04-14 13:01
> @hari1992-web We don't support installing through yaml files, we only support helm or operator.
> For sure you can run helm with --dry-run and --debug options and extract yamls files you'll be able to apply manually, but it may be error-prone and I don't recommend doing it until you deeply understand Che Deployment. What the problem with chectl?
> Please again, create a separate issue!

ok I will use now with chectl and error will be posted please wait 
Thanks 
Advance

**Comment by hari1992-web** [comment] 2020-04-16 04:57
Readiness probe failed: HTTP probe failed with statuscode: 500
Back-off restarting failed container 
![Screenshot from 2020-04-16 10-26-13](https://user-images.githubusercontent.com/62592574/79416172-bed66900-7fcc-11ea-8624-4406425d33c5.png)  


facing this issue Iam using installating through chectl tool  
please any body know this issue
Thanks Advance

**Comment by nickboldt** [comment] 2020-06-22 19:40
1 month later, slip to backlog.

**Comment by ibuziuk** [comment] 2020-06-23 08:12
The original issue has been fixed. Closing

**Closed as completed by ibuziuk** 2020-06-23 08:12 UTC
Labels: kind/bug, severity/P1, area/hosted-che
