### ISSUE TITLE
[chectl] 'workspace:start' command is not compatible with the CRW route

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#14988] opened 2019-10-25 09:53 UTC
### Describe the bug
There is hardcoded route names 
https://github.com/che-incubator/chectl/blob/master/src/api/che.ts#L111 which fails start of workspace in CRW.

### Chectl version
next

### CRW version
2.0.0.Beta

### Steps to reproduce
Create test workspace in CRW using the command `chectl workspace:start --devfile=https://github.com/eclipse/che/blob/master/e2e/files/happy-path/happy-path-workspace.yaml --chenamespace=crw`

### Screenshots
![Screenshot from 2019-10-25 10-11-06](https://user-images.githubusercontent.com/1197777/67561649-e9ceb700-f725-11e9-9ee5-9c92ec5720a6.png)

### Reference
Downstream issue https://issues.jboss.org/browse/CRW-440

**Comment by ibuziuk** [comment] 2019-10-25 13:10
@dmytro-ndp if you do not mind I will close this one as a duplicate of https://github.com/eclipse/che/issues/14963

**Closed as completed** 2019-10-25 13:11 UTC
Labels: kind/bug, area/chectl
