### ISSUE TITLE
TestRunner plugin use wrong URL for launcning tests (regression)

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#4406] opened 2017-03-13 14:14 UTC
**Preconditions:** import the test project
[test-project.zip](https://github.com/eclipse/che/files/838429/test-project.zip)
**Reproduction Steps:** 
![anim](https://cloud.githubusercontent.com/assets/1640058/23858118/197b929e-0808-11e7-9ac3-db25a7395c20.gif)

**OS and version:**    Ubuntu 14.0 TLS, chrome browser

**Comment by dmytro-ndp** [comment] 2017-03-13 14:20
It may be caused by changes from https://github.com/eclipse/che/pull/4303.

**Comment by riuvshin** [comment] 2017-03-14 12:41
@vparfonov please take a look

**Comment by evidolob** [comment] 2017-04-03 14:38
Test run fails because Maven `build` and `test-compile` command is absent. Test plugin use one of it to compile project and after that run test, but if they absent hire are no way to compile project and test plugin cannot load test class.

**Comment by vparfonov** [comment] 2017-04-11 11:53
will be fixed in https://github.com/eclipse/che/issues/4683

**Closed as completed by vparfonov** 2017-04-11 11:53 UTC
Labels: kind/bug, sprint/current
