### ISSUE TITLE
Editor tabs are not restored after refreshing browser tab

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#15317] opened 2019-11-26 11:05 UTC
### Describe the bug
The selenium tests fails because **Editor** tabs are not restored after refreshing browser tab.
![screencast-che-eclipse-che 10 33 177 124 nip io-2019 11 26-13_58_51](https://user-images.githubusercontent.com/7760565/69630219-74704200-1055-11ea-95e0-e39a37550387.gif)

- ProjectStateAfterRefreshTest.checkRestoreStateOfProjectAfterRefreshTest failure on nightly build
https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-multiuser-master-ocp/850/Selenium_20tests_20report/failsafe-report.html#org.eclipse.che.selenium.workspaces.ProjectStateAfterRefreshTest
```
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitVisibility(SeleniumWebDriverHelper.java:151)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitVisibility(SeleniumWebDriverHelper.java:161)
	at org.eclipse.che.selenium.pageobject.theia.TheiaEditor.waitEditorTab(TheiaEditor.java:126)
	at org.eclipse.che.selenium.workspaces.ProjectStateAfterRefreshTest.checkFilesAreOpened(ProjectStateAfterRefreshTest.java:89)
	at org.eclipse.che.selenium.workspaces.ProjectStateAfterRefreshTest.checkRestoreStateOfProjectAfterRefreshTest(ProjectStateAfterRefreshTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//ul[@class='p-TabBar-content']//li[contains(@title, 'pom.xml')]"}
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 3.10.0-862.11.6.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
```
![org eclipse che selenium workspaces ProjectStateAfterRefreshTest checkRestoreStateOfProjectAfterRefreshTest_time-1574715575042-millis](https://user-images.githubusercontent.com/1197777/69624242-0031a080-104d-11ea-8ea0-5d551a5a9bc8.png)

- ProjectStateAfterRenameWorkspaceTest.checkProjectAfterRenameWs failure on nightly build:
https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-multiuser-master-ocp/850/Selenium_20tests_20report/failsafe-report.html#org.eclipse.che.selenium.workspaces.ProjectStateAfterRenameWorkspaceTest
```
Driver info: org.eclipse.che.selenium.core.SeleniumWebDriver
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:265)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitVisibility(SeleniumWebDriverHelper.java:151)
	at org.eclipse.che.selenium.core.webdriver.SeleniumWebDriverHelper.waitVisibility(SeleniumWebDriverHelper.java:161)
	at org.eclipse.che.selenium.pageobject.theia.TheiaEditor.waitEditorTab(TheiaEditor.java:126)
	at org.eclipse.che.selenium.workspaces.ProjectStateAfterRenameWorkspaceTest.checkFilesAreOpened(ProjectStateAfterRenameWorkspaceTest.java:109)
	at org.eclipse.che.selenium.workspaces.ProjectStateAfterRenameWorkspaceTest.checkProjectAfterRenameWs(ProjectStateAfterRenameWorkspaceTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//ul[@class='p-TabBar-content']//li[contains(@title, 'pom.xml')]"}
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 3.10.0-862.11.6.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
```
![org eclipse che selenium workspaces ProjectStateAfterRenameWorkspaceTest checkProjectAfterRenameWs_time-1574715617388-millis](https://user-images.githubusercontent.com/1197777/69624352-3707b680-104d-11ea-976b-613d40310f7e.png)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift 3.9 (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [x] other: Codenvy CI

**Comment by SkorikSergey** [comment] 2019-11-26 12:03
The selenium tests fails because 
![screencast-che-eclipse-che 10 33 177 124 nip io-2019 11 26-13_58_51](https://user-images.githubusercontent.com/7760565/69630219-74704200-1055-11ea-95e0-e39a37550387.gif)
Editor files tabs are not restored after refreshing browser tab.

**Comment by l0rd** [comment] 2019-11-26 23:09
Out of curiosity why do you need to refresh? This smells like a workaround for another issue. I am setting P2 because I don't consider refreshing the browser something a user should do so this issue doesn't have a big impact on users. 

Of course if that affects tests it should be fixed and priority raised. But I would prefer if we remove the refresh in the test case.

**Comment by dmytro-ndp** [comment] 2019-11-27 07:17
There are dedicated E2E tests, which check that tabs are being restored after refresh of browser tab. That beheviour was treated as important, so as it's quite usual situation when user has a lot of opened files, and from some reasons has lost connection to server, or workspace has stopped by timeout. And it's expected user would not need to find and reopen files after restoring access to his workspace.

**Comment by tolusha** [comment] 2019-11-27 07:43
@dmytro-ndp 
Is it used to work before?

**Comment by dmytro-ndp** [comment] 2019-11-27 08:16
Yes, it is.

**Comment by dmytro-ndp** [comment] 2019-11-27 08:26
@tolusha: looks like it doesn't work after restart of workspace https://github.com/eclipse/che/issues/14717

**Comment by dmytro-ndp** [comment] 2019-11-27 09:43
There is related problem appeared after refresh https://github.com/eclipse/che/issues/15332

**Comment by l0rd** [comment] 2019-11-27 13:17
Ok thanks for the explanation @dmytro-ndp. In this case, if it's not a workaround to bypass some other problem, I think we should fix this issue (and hopefully #15332 would address it).

**Comment by Katka92** [comment] 2019-12-11 08:22
The PR seems to be merged, but I can still reproduce on nightly Che.

**Comment by RomanNikitenko** [comment] 2019-12-11 08:57
I investigated the issue https://github.com/eclipse/che/issues/15332 and found that cause of the problem was related to task schema and validation system for tasks. It was fixed within the corresponding PRs to `theia` and `che-theia` projects.

I think here is another cause of the problem, so it's still relevant issue.

**Comment by azatsarynnyy** [comment] 2020-01-09 08:29
Closing as I cannot reproduce it anymore. Feel free to reopen if needed.

**Comment by SkorikSergey** [comment] 2020-01-14 13:57
This issue reproduces on 7.8.0-SNAPSHOT.

Screencast:
![screencast-che-eclipse-che 10 33 177 124 nip io-2020 01 14-15_53_56](https://user-images.githubusercontent.com/7760565/72350115-72863f00-36e6-11ea-8c50-5f3cd351cf30.gif)

**Comment by azatsarynnyy** [comment] 2020-01-14 14:17
Thanks @SkorikSergey for checking it!

**Closed as completed** 2020-01-30 15:08 UTC
Labels: kind/bug, severity/P2, area/editor/theia
