### ISSUE TITLE
Unexpected hang of CHE7 IDE after reopening browser tab 

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#14044] opened 2019-07-26 12:37 UTC
### Che version

- latest
 
### Steps to reproduce
- Create a workspace form the Dashbord go to the ws. Refresh tab
### Expected behavior
- The WS. should be opened

### Runtime
   - [x] kubernetes, 1.10.0
   - [x ] Openshift,  oc - 3.11
   - [x] minikube - 0.27.0
   
### Screenshots
![screencast-che-che 192 168 99 165 nip io-2019 07 26-15_31_21_2](https://user-images.githubusercontent.com/1640058/61951947-34bc1f80-afbb-11e9-8a48-2a0dff9f18d6.gif)

### Installation method
   - [x] chectl 
   

### Environment
        - [x] Linux - Fedora 28
 
### Additional context
Looks like browser try to consume `http://static.developers.redhat.com/` resource but it is not responds

**Comment by rhopp** [comment] 2019-07-26 13:53
I wasn't able to reproduce on `minikube version: v1.2.0`. 
I do see 404 to `static.developers.redhat.com/...` though.
@musienko-maxim Could you also try this on newer minikube, than 0.27.0 (Version from May 16, 2018)?

**Comment by rhopp** [comment] 2019-07-26 14:25
This looks like duplicate of https://github.com/eclipse/che/issues/14039. Closing it as such. Feel free to reopen, if you think it's not a duplicate.

**Closed as completed by rhopp** 2019-07-26 14:25 UTC
Labels: kind/bug, status/duplicate
