### ISSUE TITLE
failed to inject orion editor

### ISSUE THREAD

**Issue by nipobhsnro** [eclipse-che/che#3355] opened 2016-12-12 15:58 UTC
from issue no: 3118

@TylerJewell i have attached screen shot of console for the same:
![image](https://cloud.githubusercontent.com/assets/23380460/21105882/e65b60ee-c0b1-11e6-8754-4c652efb93d0.png)

**Comment by TylerJewell** [comment] 2016-12-12 18:54
@nipobhsnro - this is not going to be enough information for an engineer to reproduce. So it will be difficult for anyone to get involved without more specifics.

**Comment by TylerJewell** [comment] 2017-01-21 20:17
Closing due to no follow up info.

**Closed as completed by TylerJewell** 2017-01-21 20:17 UTC
Labels: kind/question
