### ISSUE TITLE
Improve login procedure for GitHub PullRequest Plugin

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#14217] opened 2019-08-13 14:43 UTC
### Is your enhancement related to a problem? Please describe.
At the moment we have ability to use GitHub Pull Requests for Visual Studio Code, in side Che Theia. In case you want to provide new PullRequest, plugin may request you to login with the OAuth.
Problem is in OAuth server hardcoded on plugin side and it point to VS Code server.
As workaround we provide document which allow setup OAuth token manually:

> 1. Authenticate: Run F1 => GitHub Pull Requests: Manually Provide Authentication Response command and paste the [GitHub token](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line). 
> 2. Select the repository permissions when generating the token. 

### Describe the solution you'd like
Most reasonable solution will be provide ability for setup OAuth server in plugin settings. For this we need to propose PR for original plugin repository. 

### Describe alternatives you've considered
Fork plugin and replace server url but I don't want consider it as solution. I just described it here to make solutions visible for other.

**Comment by vparfonov** [comment] 2019-11-04 14:53
We blocked at the moment with no ability use oAuth service in Che multi-user

**Comment by vinokurig** [comment] 2020-01-08 12:32
It is blocked by https://github.com/eclipse/che/issues/15621

**Comment by vinokurig** [comment] 2020-01-09 12:22
We can try to set GitHub token to the plugin's configuration: https://github.com/microsoft/vscode-pull-request-github/blob/8c1147440bab71e2de3323bb4932efe8aa84f85e/package.json#L55-L58

**Comment by sunix** [comment] 2020-06-05 14:36
hello @vinokurig any progress on this?

**Comment by vinokurig** [comment] 2020-06-09 13:06
@sunix, not yet it depends on https://github.com/eclipse-theia/theia/issues/7661

**Comment by sunix** [comment] 2020-06-26 07:12
@vinokurig can't we move forward without that?
Any other options?

**Comment by sunix** [comment] 2020-07-15 08:30
@ericwill @vinokurig any progress on that one?

**Comment by ericwill** [comment] 2020-07-15 16:13
> @ericwill @vinokurig any progress on that one?

We are currently working on other items, this one will have to wait a sprint or two.

**Comment by sunix** [comment] 2020-07-23 09:35
@vinokurig @ericwill 
What I suggest is that we patch `/home/theia/.theia/plugin-storage/global-storage.json` adding
```
"keychain: github.com": "the-github-token-retrieved-somewhere"
```
at startup of the plugin or in an entrypoint.

**Comment by vinokurig** [comment] 2020-07-23 12:01
This may help to save the login session between workspace restarts, but the initial issue is to make the first login procedure as smooth as possible right? For that we need to have the `vscode-git` plugin been updated to the latest version: https://github.com/eclipse/che/issues/16041 and then with the help of the `authentication` plugin API: https://github.com/eclipse/che/issues/14217 we can register the Che GitHub oauth provider for the github PR plugin.

**Comment by sunix** [comment] 2020-07-31 13:43
But if we already have the github token https://routelbdvdybb-ssunix-che.b542.starter-us-east-2a.openshiftapps.com/che-7/configuring-github-oauth/ ... can't we reuse it ?

**Comment by vinokurig** [comment] 2020-07-31 15:39
We already using it in the `github-oauth` plugin, but it works by calling it's own command from the command pallet. The native command which is registered by the github PR plugin and appears in the notification uses the `authentication API`.

**Comment by sunix** [comment] 2020-07-31 21:18
so we can just call that code or command from `github-oauth` in Che and add the token to "/home/theia/.theia/plugin-storage/global-storage.json" ... no ? why is it mandatory to override/register the `authentication API` if we know that it will take more than 6 months. A quick fix/workaround would be nice ... it's been a year this is here and new comers are trying to use the GHplugin but can't sign it ...

**Comment by vinokurig** [comment] 2020-08-03 08:44
@sunix 
> so we can just call that code or command from github-oauth in Che and add the token to /home/theia/.theia/plugin-storage/global-storage.json

We already do the similar approach. The problem is that the `github-oauth` opens a pop-up to login to GitHub and we don't call this command on the plugin start to not to show the pup-up on workspace start. We have a special command for that. At the same time we see a notification from the `github PR plugin` which wants us to use the `vscode-oauth`.
> why is it mandatory to override/register the authentication API

The latest version of the plugin [uses the `authentication API`](https://github.com/microsoft/vscode-pull-request-github/blob/e9eaebb742cf673e815a1a05946637d9d59d6d73/src/github/credentials.ts#L162) so anyway we need it, if we want to update the plugin.
> it's been a year this is here and new comers are trying to use the GHplugin but can't sign it ...

The workaround is [documented](https://www.eclipse.org/che/docs/che-7/version-control/#using-the-github-pull-requests-plug-in).

**Comment by sunix** [comment] 2020-08-03 10:58
The workaround is not acceptable if the user is getting into sign it with the GH pr that doesn't work with Che. How will the user magically find that documentation?
but why not just call `github-oauth` once, the first time at workspace start ?
My suggestion: if waiting for  https://github.com/eclipse-theia/theia/issues/7661 would takes more than 1 month we should find a way to help the user to set the token, to me `github-oauth` is a good workaround.
Definitely the workaround in the doc is not a good one as the user will never find that doc. Also token is lost after each restart of the workspace.

**Comment by sunix** [comment] 2020-08-03 11:13
Let's take it differently ... if you look at https://twitter.com/eclipse_che/status/1290225898998755330 how many new users do you think will be able to get signed in and create a PR out of it?
My guess: I would say 0%. 2% would create an issue, 98% would give up.

**Comment by vinokurig** [comment] 2020-10-09 12:53
Is fixed by https://github.com/eclipse/che-theia/pull/841

**Closed as completed by vinokurig** 2020-10-09 12:53 UTC
Labels: kind/enhancement, status/code-review, severity/P1, area/plugin-port
