### ISSUE TITLE
Code changes lost after workspace is restarted in Online Che IDE

### ISSUE THREAD

**Issue by Rahith-RR** [eclipse-che/che#17416] opened 2020-07-15 14:34 UTC
When i tried to change code in existing GitHub projects for my study purposes, if the IDE goes offline or the login session ends i am not able to get the changes done when i refresh page/re-login. It comes as fresh checkout from GitHub.
**I am Facing this issue in Online Che IDE**

**Comment by davidfestal** [comment] 2020-07-15 20:38
@Rahith-RR 2 things to test:
- Do you have the `Temporary Storage` option enabled on your workspace ? (you can see that on the Dashboard). If it's the case then it's quite expected.
- does it behave the same (changes lost) if you simply refresh your browser

**Comment by Rahith-RR** [comment] 2020-07-16 03:38
- Yes, @davidfestal , temperory storage is enabled. please see screenshot
- Changes are not lost by simply refreshing the page, but i have noted once that if the IDE goes offline the changes are lost after refreshing

![image](https://user-images.githubusercontent.com/67456372/87623633-75b8c100-c743-11ea-9a65-6e43e366b896.png)

**Comment by patlachance** [comment] 2020-07-16 06:21
@Rahith-RR temporary storage means data will be lost when the workspace is restarted as storage allocated to underneath ephemeral pod(s) won't be preserved. You may want to close this issue since it is not a bug.

**Comment by Rahith-RR** [comment] 2020-07-16 07:06
Ok @patlachance. Thank you for the info

**Closed as completed** 2020-07-16 07:06 UTC
Labels: kind/bug, status/info-needed, area/hosted-che
