### ISSUE TITLE
Debugging WSMaster seems to keep workspace container alive

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#9877] opened 2018-05-30 14:35 UTC
I've noticed that some containers stay behind when I do a "docker run -v /home/thomas/development/git/chedev/che:/repo -v /home/thomas/che:/data -v /var/run/docker.sock:/var/run/docker.sock eclipse/che:6.5.0 stop --fast". The output says "stopping containers" and "removing containers" without announcing any problems, but when I do a "docker ps" afterwards, the workspace containers is still running.
This seems to be happening when I am debugging WSMaster. I think it has started since I have rebased branch 5730_java_ls_poc on master.

**Comment by eivantsov** [comment] 2018-05-30 17:44
@tsmaeder maybe dropping `--fast` will force wsmaster to correctly stop all workspaces.

**Comment by tsmaeder** [comment] 2018-05-30 20:57
That may be,  but it worked with fast before.

**Comment by tsmaeder** [comment] 2018-05-30 21:16
That may be,  but it worked with fast before. Anyway, I don't think containers should be left running quietly in any case.

**Comment by eivantsov** [comment] 2018-05-31 03:57
```
INFO: (che action/graceful-stop): System going into status 'PREPARING_TO_SHUTDOWN' (was 'undefined')
INFO: (che action/graceful-stop): System going into status 'undefined' (was 'undefined')
INFO: (che action/graceful-stop): System going into status 'undefined' (was 'undefined')
INFO: (che action/graceful-stop): System going into status 'undefined' (was 'undefined')
INFO: (che action/graceful-stop): System going into status 'undefined' (was 'undefined')
INFO: (che action/graceful-stop): System going into status 'undefined' (was 'undefined')
INFO: (che action/graceful-stop): System going into status 'undefined' (was 'undefined')
INFO: (che action/graceful-stop): System going into status 'undefined' (was 'undefined')
INFO: (che action/graceful-stop): Success: System state 'READY_TO_SHUTDOWN'.
```
It's not related to `--fast` flag. Graceful stop is actually broken even though CLI log says everything is OK.

@skabashnyuk @mshaposhnik can this be cause by recent changes related to rolling and recreate update?

**Comment by mshaposhnik** [comment] 2018-05-31 08:10
Iverstigateg, cause is clear, issue to fix: https://github.com/eclipse/che/issues/9885

**Comment by mshaposhnik** [comment] 2018-05-31 11:46
Fixed in https://github.com/eclipse/che/pull/9887

**Comment by eivantsov** [comment] 2018-06-01 07:44
Yes. The issue is fixed.

**Closed as completed by eivantsov** 2018-06-01 07:44 UTC
Labels: kind/bug, severity/P1
