### ISSUE TITLE
Che Theia build fails on Hosted Che

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#16373] opened 2020-03-16 15:57 UTC
### Describe the bug
The build of Che Theia fails on Hosted Che.

### Steps to reproduce
1. Login to [Hosted Che](http://che.openshift.io/) and start a Workspace from the [Devfile](https://github.com/eclipse/che-theia/blob/master/devfiles/che-theia-all.devfile.yaml).
2. Follow the steps provided in Che Theia [CONTRIBUTING.md](https://github.com/eclipse/che-theia/blob/master/CONTRIBUTING.md).
3. [On step 4](https://github.com/eclipse/che-theia/blob/master/CONTRIBUTING.md#step-4-compile-che-theia), when compiling Che Theia, the build fails with the error
`
error An unexpected error occurred: "EEXIST: file already exists, mkdir '/projects/theia/node_modules/assert'".
`

Note, that each time the build fails with the link to a different subfolder of `/projects/theia/node_modules` folder.

Seems like some file system issue.

**Comment by benoitf** [comment] 2020-03-16 16:38
with persistent mode disabled ?
if it's with gluster AFAIK it's a very old known issue

**Comment by ibuziuk** [comment] 2020-03-16 17:27
Closing as duplicate of https://github.com/eclipse/che/issues/15673
Instructions for building che-theia on Hosted Che - https://github.com/eclipse/che/issues/15673#issuecomment-579735363
@azatsarynnyy feel free to reopen

**Closed as completed by ibuziuk** 2020-03-16 17:27 UTC
Labels: kind/bug

**Comment by azatsarynnyy** [comment] 2020-03-16 22:25
> with persistent mode disabled ?

@benoitf persistent mode is enabled. With disabled, the error is different:
```
error Could not write file "/projects/theia/yarn-error.log": "errmap.get is not a function or its return value is not iterable"
error An unexpected error occurred: "Unknown system error -122: Unknown system error -122, copyfile '/home/theia-dev/.cache/yarn/v4/npm-webpack-cli-2.0.12-64db876d044f03d8d6544281854b71a3a3c77dd3/node_modules/webpack-cli/.nyc_output/55da7ec72871d0ed6acb0d6ee8ac6e7f.json' -> '/projects/theia/node_modules/webpack-cli/.nyc_output/55da7ec72871d0ed6acb0d6ee8ac6e7f.json'".
```
