### ISSUE TITLE
Unable to start workspace for che dashboard

### ISSUE THREAD

**Issue by chopraaakash91** [eclipse-che/che#18478] opened 2020-11-28 06:25 UTC
I am trying to start a workspace for che-dashboard using the contributing doucment - https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#dashboard

I tried loading the workspace using the devfile - https://github.com/eclipse/che-dashboard/blob/master/devfile.yaml
But got the following error - 

Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin brokering process for workspace workspace4o77sb1hbhwsw8z0 failed with error: Failed to download plugin meta: failed to fetch plugin meta.yaml from URL 'https://che-plugin-registry.openshift.io/v3/plugins/che-incubator/typescript/1.30.2/meta.yaml': Downloading https://che-plugin-registry.openshift.io/v3/plugins/che-incubator/typescript/1.30.2/meta.yaml failed. Status code 404. Response body: 

Not Found

The requested URL was not found on this server.

**Comment by sleshchenko** [comment] 2020-11-30 08:28
It's caused by https://github.com/eclipse/che-plugin-registry/pull/672 and should be fixed by https://github.com/eclipse/che-dashboard/pull/110

**Comment by chopraaakash91** [comment] 2020-12-01 05:20
@sleshchenko Thanks for the update.

**Closed as completed** 2020-12-01 08:04 UTC
Labels: kind/bug, severity/P2, area/dashboard
