### ISSUE TITLE
"New Terminal" opens unresponive terminal window

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#13030] opened 2019-04-01 08:29 UTC
This is on minishift, installed per operator. 
1. Create a Che 7 workspace
2. In the "Containers" view, select the ws/dev container
3. Chose "Open Terminal" from the right click menu
4. Observe: a terminal window opens, but you cannot type anything in the window.

**Comment by tsmaeder** [comment] 2019-04-01 08:30
Tagging IDE2, please move if not appropriate.

**Comment by benoitf** [comment] 2019-04-01 11:20
duplicate of https://github.com/eclipse/che-theia/issues/117 ?

**Comment by AndrienkoAleksandr** [comment] 2019-04-10 15:14
Hello, @tsmaeder  I  can not reproduce this issue.
I tried to ways: 
- I compiled and deployed latest https://github.com/eclipse/che-operator to the latest minishift (v1.33.0+ba29431) and terminal works fine.
- I created minishift:
`minishift  start --cpus 4 --memory 16192 --disk-size 20g --vm-driver=virtualbox --docker-opt userland-proxy=false`
and I used chectl (chectl/0.0.2-66ce104 linux-x64 node-v10.4.1) with operator option:
`chectl server:start --installer=operator --platform=minishift`

In both cases terminal works.
Elaborate more information, please: 
- che-operator logs from openshift console
- define steps how you did install minishift
- browser info

**In case if you used Firefox than this issue is duplication** https://github.com/eclipse/che-theia/issues/117 **and should be closed**

**Comment by tsmaeder** [comment] 2019-04-11 07:27
My minishift says: minishift v1.33.0+ba29431
I have 
```
minishift config view
- docker-opt                         : [userland-proxy=false]
- memory                             : 10240
```
My vm driver is kvm

then run 
```
minishift start
chectl server:start --platform=minishift
```

**Comment by tsmaeder** [comment] 2019-04-11 07:34
This is firefox, yes.

**Comment by AndrienkoAleksandr** [comment] 2019-04-11 08:42
@tsmaeder is it work for you on the Google Chrome?

**Comment by AndrienkoAleksandr** [comment] 2019-04-24 08:44
Closed like duplication https://github.com/eclipse/che-theia/issues/117. @tsmaeder reopen issue if you can reproduce this issue on the Google Chrome.

**Closed as completed by AndrienkoAleksandr** 2019-04-24 08:44 UTC
Labels: kind/bug, status/info-needed
