### ISSUE TITLE
Cannot start eclipse/che:5.10.0 due to wrong version check

### ISSUE THREAD

**Issue by MarcelRosenberger** [eclipse-che/che#5140] opened 2017-05-19 14:12 UTC
When executing docker run with eclipse/che:5.10.0 or eclipse/che:latest the start process aborts with  WARN: Newer version '5.9.1' available

**Reproduction Steps:**
`# docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /eclipse-che:/data eclipse/che:5.10.0 start`

**Output:**
```
WARNING: No swap limit support
INFO: (che cli): 5.10.0 - using docker 17.05.0-ce / native
WARN: Newer version '5.9.1' available
```

My assumption is that there is an error in [startup_04_pre_cli_init.sh](https://github.com/eclipse/che/blob/master/dockerfiles/base/scripts/base/startup_04_pre_cli_init.sh) (line 291)
The function `less_than()` only works if the strings are the same length. Why is `version_lt()` not used instead?

Before:
line 291: `if less_than $BASE_VERSION $TAG; then`

After:
line 291: `if version_lt $BASE_VERSION $TAG; then`

**Comment by TylerJewell** [comment] 2017-05-19 14:25
Yikes - @benoitf - urgent bug.

You can add `--fast` in the meantime to skip this check.  The version check
is failing for versions with more than two digits.


Tyler Jewell // CEO // tyler@​codenvy.​com // 978.884.5355


On Fri, May 19, 2017 at 7:12 AM, MarcelRosenberger <notifications@github.com

**Comment by benoitf** [comment] 2017-05-19 14:32
@MarcelRosenberger it shouldn't abort the process. It's only a trace.
You may disable the check with `--skip:network` , `--fast`or `--offline`

`version_lt` was introduced later but yes it's a good replacement candidate.

**Comment by MarcelRosenberger** [comment] 2017-05-19 14:51
There was another issue  - gladly dedicated to my setup only. Port 8080 was already in use by another service which prevented che from starting.

The warning concerning the version-check was the last output I got, so I thought it was related to the failing start.

**Comment by benoitf** [comment] 2017-05-19 15:18
The issue is now fixed in current nightly with PR https://github.com/eclipse/che/pull/5141

**Closed as completed by benoitf** 2017-05-19 15:18 UTC
Labels: kind/bug, severity/P1
