### ISSUE TITLE
quarkus devfile v2 sample is broken

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20445] opened 2021-09-08 11:32 UTC
### Describe the bug

quarkus devfile v2 sample is broken
![Screenshot_20210908_143105](https://user-images.githubusercontent.com/5887312/132503878-7708a698-829e-494a-a499-fa06faf297ad.png)

### Che version

next (development version)

### Steps to reproduce

screenshot says more than enough

### Expected behavior

it works

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

**Comment by sparkoo** [comment] 2021-09-09 08:04
duplicate of https://github.com/eclipse/che/issues/20439 ?

**Comment by benoitf** [comment] 2021-09-09 08:11
dup of https://github.com/eclipse/che/issues/20439 (and it should be fixed now)

**Closed as completed by benoitf** 2021-09-09 08:11 UTC
Labels: kind/bug, severity/P1, area/plugins
