### ISSUE TITLE
Che unavailable and unable to delete with chectl on Kubernetes

### ISSUE THREAD

**Issue by SpontaneousDuck** [eclipse-che/che#17619] opened 2020-08-11 18:38 UTC
### Describe the bug
After deploying with `chectl server:start --platform k8s --domain 192.168.153.121.nip.io -m`, I am unable to access the site that `chectl` returns since the browser returns `ERR_CONNECTION_TIMED_OUT`. All the Kubernetes resources are up and running and I do not see any errors in the logs. If I then try to tear down the deployment with `chectl server:delete` I am unable to since `chectl` cannot connect to the deployment with the `E_CHECK_CHE_STATUS_FAIL` error.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Install latest `chectl`
2. Install an ingress as described [here](https://www.eclipse.org/che/docs/che-7/installing-che-on-bare-metal-using-kubespray/)
3. Run `chectl server:start --platform k8s --domain 192.168.153.121.nip.io -m`
4. Attempt to connect to the address returned.
5. Try to delete with `chectl server:delete`

### Expected behavior
I expect to be able to connect to the deployed che. The major problem is being unable to delete the deployment with `chectl` if it is unable to connect to the dashboard. I would like to be able to force a tear down if something is not working with my install and the tool is unable to connect.

### Runtime
   - [x] kubernetes v1.17.6
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Screenshot
Unable to run `chectl server:delete`
![image](https://user-images.githubusercontent.com/23267120/89935345-09b16780-dbe0-11ea-8c65-a66acf1845aa.png)

### Eclipse Che Logs
Che logs:
```
Using embedded assembly in /home/user/eclipse-che/.
Found a custom cert. Adding it to java trust store /home/user/cacerts based on /usr/local/openjdk-11/lib/security/cacerts
Trust this certificate? [no]:  Certificate was added to keystore
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
11-Aug-2020 17:08:32.066 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/8.5.56
11-Aug-2020 17:08:32.070 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jun 3 2020 20:18:30 UTC
11-Aug-2020 17:08:32.070 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 8.5.56.0
11-Aug-2020 17:08:32.071 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
11-Aug-2020 17:08:32.071 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.15.0-112-generic
11-Aug-2020 17:08:32.071 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
11-Aug-2020 17:08:32.071 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-11
11-Aug-2020 17:08:32.072 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.8+10
11-Aug-2020 17:08:32.072 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
11-Aug-2020 17:08:32.072 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /home/user/eclipse-che/tomcat
11-Aug-2020 17:08:32.072 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /home/user/eclipse-che/tomcat
11-Aug-2020 17:08:32.073 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
11-Aug-2020 17:08:32.073 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
11-Aug-2020 17:08:32.073 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
11-Aug-2020 17:08:32.073 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/home/user/eclipse-che//tomcat/conf/logging.properties
11-Aug-2020 17:08:32.073 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
11-Aug-2020 17:08:32.074 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:MaxRAMPercentage=85.0
11-Aug-2020 17:08:32.074 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dche.docker.network=bridge
11-Aug-2020 17:08:32.074 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.net.ssl.trustStore=/home/user/cacerts
11-Aug-2020 17:08:32.074 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.net.ssl.trustStorePassword=changeit
11-Aug-2020 17:08:32.074 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dport.http=8080
11-Aug-2020 17:08:32.074 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dche.home=/home/user/eclipse-che/
11-Aug-2020 17:08:32.074 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dche.logs.dir=/logs/
11-Aug-2020 17:08:32.074 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dche.logs.level=INFO
11-Aug-2020 17:08:32.074 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djuli-logback.configurationFile=file:/home/user/eclipse-che//tomcat/conf/tomcat-logger.xml
11-Aug-2020 17:08:32.074 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
11-Aug-2020 17:08:32.075 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
11-Aug-2020 17:08:32.075 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0022
11-Aug-2020 17:08:32.075 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dche.local.conf.dir=/home/user/eclipse-che//tomcat/conf/
11-Aug-2020 17:08:32.075 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
11-Aug-2020 17:08:32.075 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/home/user/eclipse-che//tomcat
11-Aug-2020 17:08:32.075 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/home/user/eclipse-che//tomcat
11-Aug-2020 17:08:32.075 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/home/user/eclipse-che//tomcat/temp
11-Aug-2020 17:08:32.103 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
11-Aug-2020 17:08:32.114 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
11-Aug-2020 17:08:32.126 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 474 ms
11-Aug-2020 17:08:32.164 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
11-Aug-2020 17:08:32.164 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.56
11-Aug-2020 17:08:32.187 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/swagger.war]
11-Aug-2020 17:08:32.443 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/swagger.war] has finished in [255] ms
11-Aug-2020 17:08:32.445 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/ROOT.war]
11-Aug-2020 17:08:33.958 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/ROOT.war] has finished in [1,513] ms
11-Aug-2020 17:08:33.959 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/api.war]
2020-08-11 17:08:37,082[ost-startStop-1]  [INFO ] [.e.c.c.d.JNDIDataSourceFactory 63]   - This=org.eclipse.che.core.db.postgresql.PostgreSQLJndiDataSourceFactory@2ca3c883 obj=ResourceRef[className=javax.sql.DataSource,factoryClassLocation=null,factoryClassName=org.apache.naming.factory.ResourceFactory,{type=scope,content=Shareable},{type=auth,content=Container},{type=singleton,content=true},{type=factory,content=org.eclipse.che.api.CommonJndiDataSourceFactory}] name=che Context=org.apache.naming.NamingContext@42b8af1e environment={}
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.assistedinject.FactoryProvider2$MethodHandleWrapper (file:/home/user/eclipse-che/tomcat/webapps/api/WEB-INF/lib/guice-assistedinject-4.2.2.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of com.google.inject.assistedinject.FactoryProvider2$MethodHandleWrapper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-08-11 17:08:38,798[ost-startStop-1]  [INFO ] [o.e.c.m.k.s.KeycloakSettings 92]     - Retrieving OpenId configuration from endpoint: https://keycloak-che.192.168.153.121.nip.io/auth/realms/che/.well-known/openid-configuration
2020-08-11 17:08:39,709[ost-startStop-1]  [INFO ] [o.e.c.m.k.s.KeycloakSettings 109]    - openid configuration = {issuer=https://keycloak-che.192.168.153.121.nip.io/auth/realms/che, authorization_endpoint=https://keycloak-che.192.168.153.121.nip.io/auth/realms/che/protocol/openid-connect/auth, token_endpoint=https://keycloak-che.192.168.153.121.nip.io/auth/realms/che/protocol/openid-connect/token, token_introspection_endpoint=https://keycloak-che.192.168.153.121.nip.io/auth/realms/che/protocol/openid-connect/token/introspect, userinfo_endpoint=https://keycloak-che.192.168.153.121.nip.io/auth/realms/che/protocol/openid-connect/userinfo, end_session_endpoint=https://keycloak-che.192.168.153.121.nip.io/auth/realms/che/protocol/openid-connect/logout, jwks_uri=https://keycloak-che.192.168.153.121.nip.io/auth/realms/che/protocol/openid-connect/certs, check_session_iframe=https://keycloak-che.192.168.153.121.nip.io/auth/realms/che/protocol/openid-connect/login-status-iframe.html, grant_types_supported=[authorization_code, implicit, refresh_token, password, client_credentials], response_types_supported=[code, none, id_token, token, id_token token, code id_token, code token, code id_token token], subject_types_supported=[public, pairwise], id_token_signing_alg_values_supported=[PS384, ES384, RS384, HS256, HS512, ES256, RS256, HS384, ES512, PS256, PS512, RS512], userinfo_signing_alg_values_supported=[PS384, ES384, RS384, HS256, HS512, ES256, RS256, HS384, ES512, PS256, PS512, RS512, none], request_object_signing_alg_values_supported=[PS384, ES384, RS384, ES256, RS256, ES512, PS256, PS512, RS512, none], response_modes_supported=[query, fragment, form_post], registration_endpoint=https://keycloak-che.192.168.153.121.nip.io/auth/realms/che/clients-registrations/openid-connect, token_endpoint_auth_methods_supported=[private_key_jwt, client_secret_basic, client_secret_post, client_secret_jwt], token_endpoint_auth_signing_alg_values_supported=[RS256], claims_supported=[aud, sub, iss, auth_time, name, given_name, family_name, preferred_username, email], claim_types_supported=[normal], claims_parameter_supported=false, scopes_supported=[openid, microprofile-jwt, web-origins, roles, phone, address, email, profile, offline_access], request_parameter_supported=true, request_uri_parameter_supported=true, code_challenge_methods_supported=[plain, S256], tls_client_certificate_bound_access_tokens=true, introspection_endpoint=https://keycloak-che.192.168.153.121.nip.io/auth/realms/che/protocol/openid-connect/token/introspect}
2020-08-11 17:08:40,408[ost-startStop-1]  [INFO ] [o.j.p.kubernetes.KUBE_PING 131]      - namespace che set; clustering enabled

-------------------------------------------------------------------
GMS: address=che-767647f6bd-qx4ww-16115, cluster=RemoteSubscriptionChannel, physical address=10.233.65.22:7800
-------------------------------------------------------------------
2020-08-11 17:08:43,495[ost-startStop-1]  [INFO ] [o.jgroups.protocols.pbcast.GMS 125]  - che-767647f6bd-qx4ww-16115: no members discovered after 3058 ms: creating cluster as coordinator
2020-08-11 17:08:43,527[ost-startStop-1]  [INFO ] [o.j.p.kubernetes.KUBE_PING 131]      - namespace che set; clustering enabled

-------------------------------------------------------------------
GMS: address=che-767647f6bd-qx4ww-33128, cluster=WorkspaceLocks, physical address=10.233.65.22:7801
-------------------------------------------------------------------
2020-08-11 17:08:46,569[ost-startStop-1]  [INFO ] [o.jgroups.protocols.pbcast.GMS 125]  - che-767647f6bd-qx4ww-33128: no members discovered after 3037 ms: creating cluster as coordinator
2020-08-11 17:08:46,586[ost-startStop-1]  [INFO ] [o.j.p.kubernetes.KUBE_PING 131]      - namespace che set; clustering enabled

-------------------------------------------------------------------
GMS: address=che-767647f6bd-qx4ww-13255, cluster=WorkspaceStateCache, physical address=10.233.65.22:7802
-------------------------------------------------------------------
2020-08-11 17:08:49,616[ost-startStop-1]  [INFO ] [o.jgroups.protocols.pbcast.GMS 125]  - che-767647f6bd-qx4ww-13255: no members discovered after 3026 ms: creating cluster as coordinator
2020-08-11 17:08:49,779[ost-startStop-1]  [INFO ] [o.f.c.i.d.DbSupportFactory 44]       - Database: jdbc:postgresql://postgres:5432/dbche (PostgreSQL 9.6)
2020-08-11 17:08:49,814[ost-startStop-1]  [INFO ] [o.f.c.i.util.VersionPrinter 44]      - Flyway 4.2.0 by Boxfuse
2020-08-11 17:08:49,820[ost-startStop-1]  [INFO ] [o.f.c.i.d.DbSupportFactory 44]       - Database: jdbc:postgresql://postgres:5432/dbche (PostgreSQL 9.6)
2020-08-11 17:08:49,854[ost-startStop-1]  [INFO ] [i.f.CustomSqlMigrationResolver 158]  - Searching for SQL scripts in locations [classpath:che-schema]
2020-08-11 17:08:49,901[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbValidate 44]       - Successfully validated 59 migrations (execution time 00:00.048s)
2020-08-11 17:08:49,915[ost-startStop-1]  [INFO ] [o.f.c.i.m.MetaDataTableImpl 44]      - Creating Metadata table: "public"."schema_version"
2020-08-11 17:08:49,944[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Current version of schema "public": << Empty Schema >>
2020-08-11 17:08:49,994[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 5.0.0.8.1 - 1__init.sql
2020-08-11 17:08:50,175[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 5.0.0.9.1 - 1__add_index_on_workspace_temporary.sql
2020-08-11 17:08:50,186[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 5.0.0.9.2 - 2__update_local_links_in_environments.sql
2020-08-11 17:08:50,196[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 5.2.0.1 - 1__increase_project_attributes_values_length.sql
2020-08-11 17:08:50,217[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 5.4.0.1 - 1__drop_user_to_account_relation.sql
2020-08-11 17:08:50,241[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 5.4.0.2 - 2__create_missed_account_indexes.sql
2020-08-11 17:08:50,260[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 5.6.0.1 - 1__add_exec_agent_where_terminal_agent_is_present.sql
2020-08-11 17:08:50,286[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 5.7.0.1 - 1__add_factory.sql
2020-08-11 17:08:50,348[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 5.7.0.2 - 2__remove_match_policy.sql
2020-08-11 17:08:50,365[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 5.8.0.1 - 1__add_foreigh_key_indexes.sql
2020-08-11 17:08:50,436[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 5.11.0.1 - 1__optimize_user_search.sql
2020-08-11 17:08:50,465[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 5.19.0.0.1 - 0.1__add_permissions.sql
2020-08-11 17:08:50,541[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 5.19.0.0.2 - 0.2__add_resources.sql
2020-08-11 17:08:50,567[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 5.19.0.0.3 - 0.3__add_organization.sql
2020-08-11 17:08:50,605[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.0.0.1 - 1__add_path_to_serverconf.sql
2020-08-11 17:08:50,611[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.0.0.2 - 2__rename_agents_to_installers.sql
2020-08-11 17:08:50,621[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.0.0.3 - 3__add_installer.sql
2020-08-11 17:08:50,646[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.0.0.3.1 - 3.1__remove_old_recipe_permissions.sql
2020-08-11 17:08:50,657[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.0.0.4 - 4__remove_old_recipe.sql
2020-08-11 17:08:50,672[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.0.0.5 - 5__add_machine_env.sql
2020-08-11 17:08:50,686[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.0.0.6 - 6__remove_snapshots.sql
2020-08-11 17:08:50,698[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.0.0.7 - 7__add_machine_volumes.sql
2020-08-11 17:08:50,713[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.0.0.8 - 8__add_serverconf_attributes.sql
2020-08-11 17:08:50,730[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.0.0.9 - 9__increase_externalmachine_env_value_length.sql
2020-08-11 17:08:50,737[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.0.0.10 - 10__move_dockerimage_recipe_location_to_content.sql
2020-08-11 17:08:50,746[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.0.0.11 - 11__increase_workspace_attributes_values_length.sql
2020-08-11 17:08:50,752[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.0.0.12 - 12__remove_stack_sources.sql
2020-08-11 17:08:50,759[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.3.0.1 - 1__add_fk_indexes.sql
2020-08-11 17:08:50,767[ost-startStop-1]  [WARN ] [o.f.c.i.dbsupport.JdbcTemplate 48]   - DB: identifier "che_index_factory_on_projects_loaded_action_value_action_entity_id" will be truncated to "che_index_factory_on_projects_loaded_action_value_action_entity" (SQL State: 42622 - Error Code: 0)
2020-08-11 17:08:50,778[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.3.0.1.1 - 1.1__add_fk_indexes.sql
2020-08-11 17:08:50,798[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.4.0.1 - 1__add_workspace_expirations.sql
2020-08-11 17:08:50,813[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.4.0.2 - 2__add_signature_key.sql
2020-08-11 17:08:50,861[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.4.0.3 - 3__add_k8s_runtimes.sql
2020-08-11 17:08:50,931[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.10.0.1 - 1__add_workspace_cfg_attributes.sql
2020-08-11 17:08:50,953[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.10.0.2 - 2__change_signature_key_pair_id.sql
2020-08-11 17:08:50,966[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.11.0.1 - 1__add_signature_key_constraints.sql
2020-08-11 17:08:50,991[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.12.0.1 - 1__rename_project_attributes_values_field.sql
2020-08-11 17:08:50,998[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.15.0.1 - 1__remove_not_null_constraint_from_env_name_fields.sql
2020-08-11 17:08:51,013[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.15.0.2 - 2__add_commands_to_k8s_runtime.sql
2020-08-11 17:08:51,051[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.16.0.1 - 1__increase_workspace_config_attributes_values_length.sql
2020-08-11 17:08:51,061[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.16.0.2 - 2__create_workspace_activity_table.sql
2020-08-11 17:08:51,110[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.16.0.3 - 3__bootstrap_ws_activity_data.sql
2020-08-11 17:08:51,122[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 6.17.0.1 - 1__convert_enums_to_strings.sql
2020-08-11 17:08:51,141[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 7.0.0.4.0.1 - 1__add_devfile.sql
2020-08-11 17:08:51,271[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 7.0.0.5.0.1 - 1__devfile_command_reference.sql
2020-08-11 17:08:51,282[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 7.0.0.6.0.1 - 1__add_devfile_component_prefs.sql
2020-08-11 17:08:51,296[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 7.0.0.7.0.1 - 1__add_registry_url_to_devfile_component.sql
2020-08-11 17:08:51,306[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 7.0.0.8.0.2.0.1 - 1__devfile_metadata.sql
2020-08-11 17:08:51,316[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 7.0.0.8.0.2.0.2 - 2__devfile_make_some_fields_optional.sql
2020-08-11 17:08:51,323[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 7.1.0.1 - 1__change_devfile_component_preferences_type.sql
2020-08-11 17:08:51,331[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 7.1.0.1.1 - 1.1__remove_stack_permissions.sql
2020-08-11 17:08:51,343[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 7.1.0.2 - 2__remove_stacks.sql
2020-08-11 17:08:51,359[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 7.2.0.1 - 1__remove_installers.sql
2020-08-11 17:08:51,372[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 7.4.0.1 - 1__add_devfile_source_sparse_checkout_dir.sql
2020-08-11 17:08:51,380[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 7.4.0.2 - 2__add_preview_url_to_devfile_command.sql
2020-08-11 17:08:51,390[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 7.6.0.1 - 1__drop_che_workspace_expiration.sql
2020-08-11 17:08:51,400[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 7.10.0.1 - 1__add_devfile_plugin_editor_component_cpu_limit_request.sql
2020-08-11 17:08:51,408[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 7.10.0.2 - 2__add_devfile_plugin_editor_component_ram_request.sql
2020-08-11 17:08:51,416[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 7.11.0.1 - 1__update_inconsistent_stopped_workspace_activities.sql
2020-08-11 17:08:51,424[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Migrating schema "public" to version 7.16.0.1 - 1__add_devfile_component_automount_workspace_secrets.sql
2020-08-11 17:08:51,430[ost-startStop-1]  [INFO ] [o.f.c.i.command.DbMigrate 44]        - Successfully applied 59 migrations to schema "public" (execution time 00:01.517s).
2020-08-11 17:08:52,480[ost-startStop-1]  [INFO ] [o.j.p.kubernetes.KUBE_PING 131]      - namespace che set; clustering enabled

-------------------------------------------------------------------
GMS: address=che-767647f6bd-qx4ww-44039, cluster=EclipseLinkCommandChannel, physical address=10.233.65.22:7803
-------------------------------------------------------------------
2020-08-11 17:08:55,507[ost-startStop-1]  [INFO ] [o.jgroups.protocols.pbcast.GMS 125]  - che-767647f6bd-qx4ww-44039: no members discovered after 3023 ms: creating cluster as coordinator
2020-08-11 17:08:55,574[ost-startStop-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 174]   - Configured factories for environments: '[kubernetes, no-environment]'
2020-08-11 17:08:55,574[ost-startStop-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 175]   - Registered infrastructure 'kubernetes'
2020-08-11 17:08:55,620[ost-startStop-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 661]   - Infrastructure is tracking 0 active runtimes
2020-08-11 17:08:55,657[ost-startStop-1]  [INFO ] [o.e.c.a.c.u.ApiInfoLogInformer 36]   - Eclipse Che Api Core: Build info '7.17.0' scmRevision '37b2ab9eac6bcad6e5da29f8dbd94f91882d28f5' implementationVersion '7.17.0'
2020-08-11 17:08:55,670[ost-startStop-1]  [WARN ] [p.s.AdminPermissionInitializer 69]   - Admin admin not found yet.
2020-08-11 17:08:55,719[ost-startStop-1]  [INFO ] [o.e.c.c.metrics.MetricsServer 46]    - Metrics server started at port 8087 successfully
11-Aug-2020 17:08:55.941 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/api.war] has finished in [21,982] ms
11-Aug-2020 17:08:55.942 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/home/user/eclipse-che/tomcat/webapps/dashboard]
11-Aug-2020 17:08:55.957 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
11-Aug-2020 17:08:55.959 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/home/user/eclipse-che/tomcat/webapps/dashboard] has finished in [17] ms
11-Aug-2020 17:08:55.959 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/home/user/eclipse-che/tomcat/webapps/workspace-loader]
11-Aug-2020 17:08:55.986 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/home/user/eclipse-che/tomcat/webapps/workspace-loader] has finished in [27] ms
11-Aug-2020 17:08:55.989 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]11-Aug-2020 17:08:55.998 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 23871 ms
```

**Comment by tolusha** [comment] 2020-08-12 06:28
Closed as duplicate of  https://github.com/eclipse/che/issues/17534

**Closed as completed by tolusha** 2020-08-12 06:28 UTC
Labels: kind/bug, severity/P2, area/chectl
