### ISSUE TITLE
Che@K8s with custom CA not working

### ISSUE THREAD

**Issue by gorootde** [eclipse-che/che#9531] opened 2018-04-24 15:10 UTC
### Description
If che is deployed on kubernetes (using TLS certificates that were signed by a non-public trusted authority), the bootstrapper will fail as it connects to a websocket endpoint that uses an untrusted certificate.

I am trying to use unencrypted connections inside the k8s cluster, while the ingress controller encrypts every connection to the outside.

The possible workaround is also blocked:
Configure `CHE_WEBSOCKET_ENDPOINT` so that the `ws://` protocol is used and the bootstrapper connects (K8s internally) unencrypted to the master. This does also not work as the browser uses the same configuration value to connect to the websocket. The browser needs to use the `wss://` protocol as the ingress controller encrypts the connection to the outside world. Result is that the browser uses `ws` which will fail as there is no unencrypted enpoint exposed.

### Reproduction Steps

1. Install Che on K8s using certificates signed by a non-officially trusted CA.
2. Fire up a workspace
3. Have a look in bootstrapper.log

**OS and version:**    
Che 6.3.0

**Diagnostics:**

**Comment by eivantsov** [comment] 2018-04-24 16:09
@gorootde you may edit Che deployment so that https and wss are used across values of certain envs like ws enpoints, che api, bootstrapper binary url etc.

However, that should have happened automatically, as long as you applied values in https folder.

**Comment by gorootde** [comment] 2018-04-24 16:40
@eivantsov I already did that. The root cause of these problems seems to be that the `CHE_WEBSOCKET_ENDPOINT` is used for both: Configuring the bootstrapper and the browser. The browser should use TLS (via Ingress) while the bootstrapper should use plain HTTP (cluster internally).

So either I find a way to configure the endpoint for browser and bootstrapper independent of each other, or I can only use cutstom workspace-images that already trust my CA.

**Comment by eivantsov** [comment] 2018-09-10 07:36
There's currentlly no automation to add self signed certs to Java trust store and root ca in workspace containers. Closing as duplicate of https://github.com/eclipse/che/issues/10910

**Closed as completed by eivantsov** 2018-09-10 07:36 UTC
Labels: kind/question
