### ISSUE TITLE
Eclipse Che no longer responding, message "Updating File"

### ISSUE THREAD

**Issue by didier1969** [eclipse-che/che#3396] opened 2016-12-15 09:51 UTC
Hello,
I installed Che on a KVM Ubuntu 16.04 machine, inside docker container. No problem at the beginning, but after a few days, Che becomes slow and even does not respond anymore. A message "Updating File" is shown.

The container contains one Workspace with Meteor, with one meteor project running inside. The biggest files are CSS files of 3-4 Mb

**Reproduction Steps:**

1. Create Meteor Workspace according to procedure described here : https://eclipse-che.readme.io/docs/get-started-with-meteor
2. Run meteor project 
3. Change any file
4. Let system sit for a couple days

**Observed behavior:**
Freezes and browser no longer responding

**Che version:**    5.0.0. Latest   
**OS and version:** Ubuntu 16.04 on KVM
**Docker version:** Docker version 1.12.3, build 6b644ec   
**Che install:**   Docker Container   

**Additional information:**
KVM Machine has GB RAM, 6 GB used. CPU is between 1-2% only.

**Comment by TylerJewell** [comment] 2016-12-15 14:20
1. Does rebooting Che resolve the issues?
2. Are there any logs in the chrome browser developer console?

**Comment by didier1969** [comment] 2016-12-15 16:26
Hello and thank you for your quick reply.
I restarted the server and after 25 minutes, the problem came again.
1) The KVM machine under Proxmox
![proxmox_kvm](https://cloud.githubusercontent.com/assets/2456309/21232090/c008eeda-c2ea-11e6-910b-9a04fa00884d.png)

2) The Google Chrome Dev console. I first thought that an extension diigolet could bring the issue. So Pic_1 is before disabling diigolet, Pic_2 after disabling it. 

![chrome_dev_1](https://cloud.githubusercontent.com/assets/2456309/21232328/77d8f500-c2eb-11e6-871a-3d04ea098325.png)
![chrome_dev_2](https://cloud.githubusercontent.com/assets/2456309/21232323/75fe6d8c-c2eb-11e6-84b2-19ee6b749e57.png)

Many thanks for your help.
Didier

**Comment by TylerJewell** [comment] 2016-12-15 16:49
Thanks for the additional diagnostics. We are going to treat this as a possible blocker / outage related issue.  We do not have any sort of timing or commitment we can offer, but it will get scheduled into our dev flow.

**Comment by bmicklea** [comment] 2016-12-15 17:03
@didier1969 are you able to reproduce this issue running Che in Docker native on Linux (outside the KVM)?

**Comment by JamesDrummond** [comment] 2016-12-20 15:32
We are currently having issues reproducing this issue. @didier1969 We need additional information to reproduce.

**Comment by TylerJewell** [comment] 2016-12-20 15:34
1. We have seen some inconsistency with this issue.  We have heard reports of this happening on native hosts, but it disappears before we can get a diagnostic log.

2. This may be issue related to natively running in a VM - but want to see if original poster can reliably reproduce in their VM.

**Comment by TylerJewell** [comment] 2016-12-29 16:59
@didier1969 - can you reconfirm that this issue is happening on our nightly release?  We are effectively GA ready with 5.0.0 release (1300 commits).  And we are trying to plan around 5.1.0 - and we need some more info on the state of this issue. There is a chance that the newly merged file system watchers solve your problem, so let's verify.

**Comment by didier1969** [comment] 2016-12-30 23:10
Hello Tyler,


Still happening with nightly release.


Please see the documents in attachment. Server is running if you want to see by yourself. Please simply advise when you want to connect.


Thanks for your help.


Best regards.


Didier Stadelmann

Creux-de-la-Quere 9

CH-2830 Courrendlin

________________________________

**Comment by TylerJewell** [comment] 2016-12-31 14:48
@didier1969 - ok, thank you for doing another test with our nightly package. @vparfonov - let's budget investigation time for this in the next sprint starting Thursday.

**Comment by svor** [comment] 2017-01-17 09:21
Can't reproduce

**Closed as completed by svor** 2017-01-17 09:21 UTC
Labels: kind/bug, status/info-needed, sprint/next, severity/P1
