### ISSUE TITLE
Do NOT push che-theia nightly image if it breaks Che happy path test

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#15690] opened 2020-01-14 13:27 UTC
### Is your enhancement related to a problem? Please describe.

Per CRW 2 retrospective discussions, we don't want to blindly pull latest theia as it can (has) broken happy path tests; need versioned tests (CRW 2.x lags behind Che 7.x so need two versions of happy path).

### Describe the solution you'd like

Need to write new check on nightly theia; if image check does not pass, do NOT push new image to quay.

**Comment by nickboldt** [comment] 2020-01-14 13:28
May be related to / duplicate of https://github.com/eclipse/che/issues/13258

**Comment by l0rd** [comment] 2020-01-15 03:29
The fix should be to NOT publish che-theia (not theia) image to prevent that Che PR check get broken. The head of che-theia master branch should continue to reference the head of theia master branch (we want to fix problems on theia master branch as soon as possible).

It's not a duplicate of #13258.  cc @rhopp @dmytro-ndp is there a duplicate of this issue?

Assigning to QE team but may be addressed by productization team as well (@nickboldt if you think you can address it please change the assignment).

**Comment by rhopp** [comment] 2020-01-22 09:08
Closing as duplicate of https://github.com/eclipse/che/issues/15291

**Closed as completed by rhopp** 2020-01-22 09:08 UTC
Labels: kind/enhancement, severity/P1, area/ci
