### ISSUE TITLE
Errors when a workspace starts up with several remote plugins

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#12762] opened 2019-02-26 09:51 UTC
### Description
 
Errors when a workspace starts up with several remote plugins

### Reproduction Steps

When I try to start a workspace with several remote plugins (java, go, ts, xml, yaml, node debug) I can observer several error (listed below).

**OS and version:**    
Minikube start command:
`minikube start --cpus 4 --memory 10240 --docker-opt userland-proxy=false  --extra-config=apiserver.authorization-mode=RBAC`
`minikube version: v0.28.2`

**Diagnostics:** 

- [ ] all plugins have been successfully processed
stream error: stream ID 1; HTTP_1_1_REQUIRED
Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspaceozixry8v80yfou5l failed with error: stream error: stream ID 1; HTTP_1_1_REQUIRED"

- [ ] Starting VS Code extensions processing
zip: not a valid zip file
Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspaceozixry8v80yfou5l failed with error: zip: not a valid zip file

- [ ] write /tmp/vscode-extension-broker817819086/plugin/extension/server/org.eclipse.lsp4xml-uber.jar: cannot allocate memory
Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspaceozixry8v80yfou5l failed with error: write /tmp/vscode-extension-broker817819086/plugin/extension/server/org.eclipse.lsp4xml-uber.jar: cannot allocate memory"

- [ ] Plugin installation timeout

**Comment by garagatyi** [comment] 2019-02-26 10:40
Can you provide workspace configuration to reproduce the issue?

**Comment by tolusha** [comment] 2019-02-27 09:49
```json
{
  "defaultEnv": "default",
  "environments": {
    "default": {
      "machines": {
        "ws/dev": {
          "attributes": {
            "memoryLimitBytes": "536870912"
          },
          "servers": {},
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [],
          "env": {}
        }
      },
      "recipe": {
        "type": "kubernetes",
        "content": "kind: List\nitems:\n - \n  apiVersion: v1\n  kind: Pod\n  metadata:\n   name: ws\n  spec:\n   containers:\n    - \n     image: 'eclipse/che-dev:6.18.1'\n     name: dev\n     resources:\n      limits:\n       memory: 512Mi\n",
        "contentType": "application/x-yaml"
      }
    }
  },
  "projects": [],
  "name": "wksp-nbt1",
  "attributes": {
    "editor": "org.eclipse.che.editor.theia:1.0.0",
    "plugins": "che-machine-exec-plugin:0.0.1,ms-vscode.node-debug2:1.31.6,ms-vscode.node-debug:1.32.1,ms-vscode.typescript:1.30.2,redhat.vscode-xml:0.3.0,redhat.vscode-yaml:0.3.0"
  },
  "commands": [],
  "links": []
}
```

**Comment by tolusha** [comment] 2019-02-27 09:51
it is also necessary to deploy plugin registry with all latest plugins

**Comment by garagatyi** [comment] 2019-02-27 10:17
@l0rd @ibuziuk Should OSIO-Che team include this issue into the upcoming sprint? Seems to be important and can block languages team

**Comment by l0rd** [comment] 2019-02-27 10:31
Yes it looks critical

**Comment by garagatyi** [comment] 2019-02-27 15:24
I reproduced this case:
```
* Starting VS Code extensions processing
  zip: not a valid zip file
  Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspaceozixry8v80yfou5l failed with error: zip: not a valid zip file
```
it is related to blocking brokers because of API rate limit on marketplace side.
Wasn't able to reproduce next cases:
```
* all plugins have been successfully processed
  stream error: stream ID 1; HTTP_1_1_REQUIRED
  Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspaceozixry8v80yfou5l failed with error: stream error: stream ID 1; HTTP_1_1_REQUIRED"

* write /tmp/vscode-extension-broker817819086/plugin/extension/server/org.eclipse.lsp4xml-uber.jar: cannot allocate memory
  Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspaceozixry8v80yfou5l failed with error: write /tmp/vscode-extension-broker817819086/plugin/extension/server/org.eclipse.lsp4xml-uber.jar: cannot allocate memory"
```
@tolusha how often do you see these cases? Any ideas how to reproduce them?

**Comment by tolusha** [comment] 2019-02-28 09:19
Unfortunately I wan't able to reproduce other errors. I always faced ` zip: not a valid zip file` issue. I guess once it is fixed and a new plugin broker is released I will try one more time.

**Comment by garagatyi** [comment] 2019-03-06 14:34
@tolusha `zip: not a valid zip file` issue should be tackled now - broker will retry to download extension or show pretty error message about rate limiting. Apart from that, it is possible that workspace start would timeout when retries and regular extensions downloads take too much time.

**Comment by garagatyi** [comment] 2019-03-07 11:52
Closing this issue since reproduced case is fixed. Feel free to reopen if other cases are reproduced

**Closed as completed by garagatyi** 2019-03-07 11:52 UTC
Labels: kind/bug
