### ISSUE TITLE
[regression] Devfile schema validation is broken for referenceContent actions

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#14024] opened 2019-07-25 11:28 UTC
### Describe the bug
When try to execute factory from python-django https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/python-django/devfile.yaml
the following validation error appears:
```
Devfile schema validation failed. 
Error: Exactly one of the following sets of problems must be resolved.: 
[(/commands/4/actions/0):The object must have a property whose name is "component".(/commands/4/actions/0):The object must have a property whose name is "command".
At least one of the following sets of problems must be resolved.: 
[(/commands/4/actions/0):The object must have a property whose name is "reference".(/commands/4/actions/0):The object must have a property whose name is "referenceContent".]]
```

### Che version

 - [ ] latest
 - [ x] nightly
 - [ ] other: please specify

### Steps to reproduce
Execute the factory with given devfile:
http://<che-host>/f?url=https://raw.githubusercontent.com/eclipse/che-devfile-registry/master/devfiles/python-django/devfile.yaml

### Expected behavior
Workspace should be created

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ x] my computer 
       - [ ] Windows
       - [ x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by amisevsk** [comment] 2019-07-25 13:43
Could not reproduce using `nightly-centos` on the dev-cluster.

**Comment by amisevsk** [comment] 2019-07-25 13:47
Update: rolled out *latest* nightly, and could reproduce now. Previous nightly worked without problem (deployed ~24 hours ago)

**Comment by amisevsk** [comment] 2019-07-25 14:04
So, latest `nightly` does not work, but the [previous nightly build](https://ci.codenvycorp.com/job/all-che-docker-images-nightly/1097/) does not reproduce this issue. 

For reference, working image is 

`eclipse/che-server@sha256:de5d3016692d961edfe9d3eafd0e5fbf39b3baa641ca1f02ca5c10578f5bb10b`

**Comment by amisevsk** [comment] 2019-07-25 14:27
The underlying issue seems to be failure to validate devfiles that use `referenceContent`, e.g. in python-django
``` json
  -
    name: debug
    actions:
    - type: vscode-launch
      referenceContent: >
        {
        "version": "0.2.0",
        "configurations": [
          {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "0.0.0.0",
            "pathMappings": [
              {
                  "localRoot": "${workspaceFolder}",
                  "remoteRoot": "${workspaceFolder}"
              }
            ]
          }]
        }
```

**Comment by tsmaeder** [comment] 2019-07-25 16:00
@amisevsk Since we enabled "referenceContent" for 7.0, I guess this needs to be fixed for 7.0, as well.

**Comment by amisevsk** [comment] 2019-07-25 16:37
Additional detail: only occurs using factory url (`/f?url=https://che-devfile-registry.prod-preview.openshift.io/devfiles/python-django/devfile.yaml`) and not using the same devfile in the "create workspace" UI.

**Comment by amisevsk** [comment] 2019-07-25 21:52
Looking again, this appears to be out-of-date che-server images; PR https://github.com/eclipse/che/pull/13957 enabled referenceContent recently. Without this PR, issue https://github.com/eclipse/che/issues/13925 precents starting the python-django workspace.

Closing as fixed in nightly / duplicate of https://github.com/eclipse/che/issues/13925

**Closed as completed by amisevsk** 2019-07-25 21:52 UTC
Labels: kind/bug
