### ISSUE TITLE
Unusable IDE after Refresh

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15041] opened 2019-10-31 09:23 UTC
### Describe the bug
I have the case 2-3 times a day that the IDE becomes completely unusable. I just have the state seen in the screenshot below and there is not way out of it except to restart either minishift, or sometimes ever the whole laptop.
When this happened just now, it was right after one of the regular refreshes described in https://github.com/eclipse/che/issues/14933

The browser log shows a lot of these errors:
```
app-ce60faadae.js:134113 WebSocket connection to 'ws://che-che.192.168.99.119.nip.io/api/websocket?token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJUOExKS3V1aWplZk5ITEJBb0g2T1B4cjJjVTkzNUlPTTVHeGRtUE1kQnRrIn0.eyJqdGkiOiJiMTkzOWU3NC0xNGI1LTQzOWEtYTkzYi0xOWUxMDNlYTMwMGUiLCJleHAiOjE1NzI0NjA4ODcsIm5iZiI6MCwiaWF0IjoxNTcyNDYwNTg3LCJpc3MiOiJodHRwOi8va2V5Y2xvYWstY2hlLjE5Mi4xNjguOTkuMTE5Lm5pcC5pby9hdXRoL3JlYWxtcy9jaGUiLCJhdWQiOlsiYnJva2VyIiwiYWNjb3VudCJdLCJzdWIiOiJkMzEwMDM4Ny1kNGRmLTQ5ZWMtYTMyOC0yMGUzODBlYWQ1ZjUiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJjaGUtcHVibGlj...mlmaWVkIjpmYWxzZSwibmFtZSI6ImFzZGYgYXNkZiIsInByZWZlcnJlZF91c2VybmFtZSI6InRob21hcyIsImdpdmVuX25hbWUiOiJhc2RmIiwiZmFtaWx5X25hbWUiOiJhc2RmIiwiZW1haWwiOiJmb29AYmFyLmNvbSJ9.o2r5V4SB71MMKtvLYLHPqDmYLdvoeFCLY5h9TGS-meU0qvcyQtSvICsfn5NzmX7iiyVe7F0NqyD5Ol7DX_z0kinU6DsWZ9AQgnhQ2-s3Xv4wvKkwp8YluscGNVzr5NQ7rKDrmKDVbQLRWD0o9hWn0lbtw5-F5i-SOdGHtAKV6h3dsfE-0rrC0Y7f61boVdtPczjSOCCJ6l_-tucT2BaX2WncC9jquBzichwg7yjgsgjedYcfhNhrfWKriP1H-DvbJSS4y-OEZ9iRrO6ZWI_Dx0lzKvMCZxOI849Fe7qsMMlSm60EljI_WMBZQgLGCMUc2s4InghwpWjTzcRKBc1j0w' failed: Unknown reason
n @ app-ce60faadae.js:134113
create @ app-ce60faadae.js:133646
i._connect @ app-ce60faadae.js:133646
i @ app-ce60faadae.js:133646
(anonymous) @ app-ce60faadae.js:133646
value @ app-ce60faadae.js:140198
value @ app-ce60faadae.js:139956
(anonymous) @ app-ce60faadae.js:151611
c @ app-ce60faadae.js:52595
(anonymous) @ app-ce60faadae.js:52643
$digest @ app-ce60faadae.js:53780
$apply @ app-ce60faadae.js:54168
(anonymous) @ app-ce60faadae.js:56094
i @ app-ce60faadae.js:41704
(anonymous) @ app-ce60faadae.js:41983
```

### Che version
 - [x] nightly

### Steps to reproduce
Do self-hosting according to che-theia/Contributing.md

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
    - [x]  minishift v1.34.0+f5db7cb

### Screenshots
![Screenshot from 2019-10-31 10-19-14](https://user-images.githubusercontent.com/13163770/67934342-03f61280-fbc8-11e9-82fc-fe8b8ccc5048.png)

### Installation method
   - [ ] chectl -p minishift -a operator

**Comment by tsmaeder** [comment] 2019-10-31 09:24
This is a serious bug since it wastes about an hour of my time per day restoring my development context.

I cannot switch to CRC because I was never able to get it running.

**Comment by ibuziuk** [comment] 2019-11-04 06:13
> I cannot switch to CRC because I was never able to get che running on crc. I have no sufficient quota for self-hosting on openshift.io.

che on crc works like a chram for me. PR with quotas updates on Hosted che is planned to be merged tomorrow

**Comment by tsmaeder** [comment] 2019-11-04 13:36
> che on crc works like a chram for me. 
 
I don't doubt that. Sucks to be me, though ;-)

**Comment by benoitf** [comment] 2019-11-21 09:15
this one is a dupe of https://github.com/eclipse/che/issues/14726

**Closed as completed** 2019-11-21 09:15 UTC
Labels: kind/bug, severity/P1, area/editor/theia, status/duplicate
