### ISSUE TITLE
Login using OpenShift 4.x OAuth doesn't work

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#13659] opened 2019-07-02 07:26 UTC
### Description
_There is deployed CHE on OCP 4.x by using OperatorHub and log into application with OAuth doesn't work. I assume this is related with the issue:_ https://issues.jboss.org/browse/KEYCLOAK-10169

**Reproduction Steps**
Test steps:
1. Install CHE by operator:
![eclipse-che-Details-Red-Hat-OpenShift-Container-Platform](https://user-images.githubusercontent.com/5408906/60491712-10b63880-9cb2-11e9-8fac-7d85412172ad.png)

2. Go to CHE login page, click on OpenShift v4 button::
![Log-in-to-Eclipse-Che](https://user-images.githubusercontent.com/5408906/60491673-f7ad8780-9cb1-11e9-8f82-6113211eb4c9.png)

3. Click on "Allow" button in OpenShift oAuth application page.
![Authorize-eclipse-che-openshift-identity-provider-nze9bt](https://user-images.githubusercontent.com/5408906/60492146-03e61480-9cb3-11e9-94bf-3987527c4a43.png)

4. Log into OCP as default cluster-admin user "kubeadmin".

**Expected behavior:**
* form to enter CHE profile info is opened
 
**Observed behavior:**
* page with error message:
![Log-in-to-Eclipse-Che-openshift-v-4](https://user-images.githubusercontent.com/5408906/60491937-8de1ad80-9cb2-11e9-992a-10f4440e0c0c.png)

**OS and version:**    
Che 7.0.0-RC-2.0

**Additional information:**
[keycloak-56f4fd9469-gxdbf-keycloak.log](https://github.com/eclipse/che/files/3348776/keycloak-56f4fd9469-gxdbf-keycloak.log)

![Keycloak-Admin-Console-openshift-v-4](https://user-images.githubusercontent.com/5408906/60492354-7bb43f00-9cb3-11e9-974d-6e706edce518.png)

![keycloak-56f4fd9469-gxdbf-Details-Red-Hat-OpenShift-Container-Platform](https://user-images.githubusercontent.com/5408906/60492399-938bc300-9cb3-11e9-83dc-997a9c16d3ab.png)

![keycloak-56f4fd9469-gxdbf-Details-Red-Hat-OpenShift-Container-Platform-yaml](https://user-images.githubusercontent.com/5408906/60492429-a0101b80-9cb3-11e9-970f-1de822e18387.png)

**Comment by SkorikSergey** [comment] 2019-07-02 13:01
This issue is reproduced if try to log into CHE as **kubeadmin** user. Logging under a regular user works as expected.

**Comment by davidfestal** [comment] 2019-07-02 13:17
I don't think it is expected to log into the Che Server as the Openshift **`kubeadmin`**.
@nickboldt @l0rd wdyt ? I assume this should be added to docs ?

@dmytro-ndp Do you know if logging to Che with Openshift OAuth under the **`kubeadmin`** user had been tested and was expected to work with CRW 1.2 and Openshift 3.11 ? I suspect it was not.

**Comment by dmytro-ndp** [comment] 2019-07-02 14:58
@davidfestal: login as a cluster admin is a USUAL use case, which is regularly tested with [Che against OKD 3.9](https://ci.codenvycorp.com/view/qa-nightly/job/che-multiuser-master-ocp-oauth-test/388/Selenium_20tests_20report/), and [CRW against OCP 3.11](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/pre-release/view/OCP%203.11/job/pre-release-e2e-tests-against-OCP3.11-with-OS-oauth/E2E_20tests_20report/failsafe-report.html#com.redhat.codeready.selenium.ocpoauth.LoginExistedUserWithOpenShiftOAuthTest), and it's expected to work correctly with kubeadmin on OCP 4 as well.

**Comment by nickboldt** [comment] 2019-07-02 21:05
Why are we still using resources to test Openshift 3.9? That's EOL and unsupported. 

We only support 3.11 + 4.latest + 4.(latest-1).

**Comment by nickboldt** [comment] 2019-07-02 21:07
@davidfestal We don't support CRW on pure K8s (only Che on K8s is community-supported), so I'd use the Openshift system:admin user rather than the kubeadmin one.

**Comment by nickboldt** [comment] 2019-07-02 21:08
Related downstream issue: https://issues.jboss.org/browse/CRW-202

**Comment by dmytro-ndp** [comment] 2019-07-02 21:23
@nickboldt: FYI: the issue is about deployment to OCP 4.x instance which doesn't have *system:admin* user by default, but *kubeadmin* with cluster admin right.

**Comment by davidfestal** [comment] 2019-07-03 10:29
> @davidfestal: login as a cluster admin is a USUAL use case, which is regularly tested with Che against OKD 3.9, and CRW against OCP 3.11, and it's expected to work correctly with kubeadmin on OCP 4 as well.

@dmytro-ndp I don't see any usage of the `kubeadmin` user to log into Che through the Openshift identity provider in the tests you pointed me to. They use either the selenium tests `DefaultTestUser` or a new user whose name is `"user" + currentTimeInMillisec`.

In Openshift 4.1, the `kubeadmin` user is a temporary admin user provided at start to connect to your cluster until you define proper cluster OAuth configuration that would provide real users, as show in this screen capture:

![image](https://user-images.githubusercontent.com/686586/60584548-d8842800-9d8d-11e9-9bb9-c721bd065bc1.png)
 
That seems quite expected to me that you cannot connect to Che through OAuth with such a specific user, temporary and admin-ony user, since this user doesn't even seem to be part of the Openshift OAuth integration.

**Comment by davidfestal** [comment] 2019-07-03 10:39
> @davidfestal  We don't support CRW on pure K8s (only Che on K8s is  community-supported), so I'd use the Openshift system:admin user rather  than the kubeadmin one.

> @nickboldt: FYI: the issue is about deployment to OCP 4.x instance which doesn't have system:admin user by default, but kubeadmin with cluster admin rights.

@dmytro-ndp @nickboldt I still don't understand what the problem is here.
`kubeadmin` is the default temporary admin user provided in OS 4.1 clusters, and we don't have any problem with that, except the fact that this *special* user cannot be used to login into Che, which of course seems obvious. Normal use of OS 4 would be to setup some sort of identity provider in the OS 4 cluster OAuth [configuration](https://console-openshift-console.apps.crw.codereadyqe.com/k8s/cluster/config.openshift.io~v1~OAuth/cluster/yaml), such as a simple `htpasswd` provider. As soon as this is done, **real OAuth users** are available and can be used to connect to Che through Openshift OAuth.
This is already working correctly, as @SkorikSergey mentioned in comment https://github.com/eclipse/che/issues/13659#issuecomment-507666386

**Comment by davidfestal** [comment] 2019-07-03 13:51
@dmytro-ndp If your purpose is to test that a user with cluster admin privileges can still start a workspace (cf issues [CRW-122](https://issues.jboss.org/browse/CRW-122) and [12670](https://github.com/eclipse/che/issues/12670) ) **also on Openshift 4.x**, then you would have to:
- create a real user (through htpasswd for example)
- assign the cluster admin role to it (through a service account + cluster role binding in its namespace I assume).

But using `kubeadmin` or some sort of internal system user is probably not the way to go to test this schenario.

**Comment by dmytro-ndp** [comment] 2019-07-03 14:59
@davidfestal: OpenShift OAuth works with user with cluster-admin rights, which @SkorikSergey had been added to available OCP 4 instance.
Anyway, we will be testing it with regular user and user with cluster-admin right.
So, we can close the issue and don't forget to mention in documentation, that Che doesn't work with **kubeadmin** user.

**Comment by davidfestal** [comment] 2019-07-03 15:05
@dmytro-ndp Great ! Thanks for your confirmation: one issue less !

**Closed as completed by davidfestal** 2019-07-03 15:05 UTC
Labels: kind/bug, severity/blocker
