### ISSUE TITLE
Openshift connector and Che: the extension is not keeping the state after workspace restart.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#15270] opened 2019-11-21 09:57 UTC
### Describe the bug
When using the openshift connector, the state is lost after restart.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Start a workspace with the openshift connector plugin + a nodejs project
2. Login to a remote openshift cluster from the openshift connector panel
3. Create some project / component to the nodejs project, push
4. Restart the workspace
5. User is not connected anymore, and after reloaded, the component has no context although .odo folder is still present in the nodejs project.

### Runtime
   - [x] Openshift 4.2

### Installation method
   - [x] che-operator (operator hub)

**Comment by tsmaeder** [comment] 2019-11-21 15:39
@sunix are you using persistent storage or ephemeral? Is the state preserved when you use the extension in VS Code?

**Comment by sunix** [comment] 2019-11-21 16:47
Persistent storage. Yes it works on VS Code

**Comment by azatsarynnyy** [comment] 2019-11-26 10:35
It's because of kubeconfig isn't persisted between workspace restarts. Should be fixed by https://github.com/eclipse/che/issues/14877

**Comment by sunix** [comment] 2019-12-05 10:54
@azatsarynnyy i don't see how these are related: https://github.com/eclipse/che/issues/14877 is about chectl

**Comment by azatsarynnyy** [comment] 2019-12-05 14:19
If I understand it right, the solution `#2 `, proposed in #14877, should fix that problem partly. When access to a cluster is set up with `chectl workspace:inject`.

**Comment by azatsarynnyy** [comment] 2020-02-06 16:15
relabeled to `area/plugins` as it's related to OpenShift Connector plugin

**Comment by sunix** [comment] 2020-02-07 08:57
> If I understand it right, the solution `#2 `, proposed in #14877, should fix that problem partly. When access to a cluster is set up with `chectl workspace:inject`.

Most of the end users won't use chectl. I don't see why we are talking about solutions that works for less then 5% of our users.

**Comment by vinokurig** [comment] 2020-02-10 10:12
According to https://github.com/eclipse/che/issues/15270#issuecomment-558568637, we need a way to  store `kubeconfig`. This requires architectural decision and may have impact on the platform side. cc @l0rd @benoitf

**Comment by sunix** [comment] 2020-02-10 19:25
what about having a single `home` volume (per user) that would be used by all the workspaces of the connected user ?

**Comment by sunix** [comment] 2020-02-11 09:25
The label [status/info-needed](https://github.com/eclipse/che/labels?utf8=%E2%9C%93&q=info-needed) is to be used when

> More information is needed before the issue can move into the “analyzing” state for engineering.

So maybe we should assigned that to another team, but someone should start analyzing for the best solution/implementation.

**Comment by tsmaeder** [comment] 2020-02-12 10:50
Note that any VS Code extension can save state to a directory provided by the API, so the only general fix is to preserve that directory between workspace runs.

**Comment by vinokurig** [comment] 2020-04-23 11:27
Is not actual since https://github.com/eclipse/che/issues/15261 is applied

**Comment by vinokurig** [comment] 2020-04-24 13:19
Can not reproduce the bug. Looks like since we have the [auto login feature](https://github.com/eclipse/che/issues/15261), it is not relevant any more. Here is my steps to reproduce: 
![video-convert (1)](https://user-images.githubusercontent.com/7668752/80216665-15841880-8647-11ea-84f5-5a3a4445151c.gif)

**Comment by sunix** [comment] 2020-06-23 14:39
Hey sorry, @vinokurig autologin is for login in the current openshift cluster. What if we log in another cluster?

**Comment by nickboldt** [comment] 2020-07-06 19:09
is this on track for Che 7.16? We'd like this to work OOTB in CRW 2.3.

**Comment by sunix** [comment] 2020-07-16 08:28
also ... has autologin https://github.com/eclipse/che/issues/15261 been moved to CRW?

**Comment by vinokurig** [comment] 2020-07-17 13:08
@sunix 
> also ... has autologin #15261 been moved to CRW?

It should work for CRW.

**Comment by vinokurig** [comment] 2020-07-17 13:14
The only possible solution to keep the plugin state between workspace restarts is to have an additional PVC, like the `/projects` folder mount. @skabashnyuk WDYT?

**Comment by sunix** [comment] 2020-07-17 13:38
@vinokurig yep so which folder(s) would you turn into volumes ?

**Comment by vinokurig** [comment] 2020-07-17 13:43
It think it should be a new folder somewhere in `root`, don't know the name yet :)

**Comment by skabashnyuk** [comment] 2020-07-20 12:23
keeping the state of workspace between restarts in a volume sounds good to me

**Comment by tsmaeder** [comment] 2020-07-20 13:46
Note that we sometimes run multiple copies of VS Code extensions in various containers (VSCode YAML, for example). This could lead to the plugins overwriting each other's state. So if this is going to be a general fix, we should follow up by doing something about that: IMO, running multiple copies of the same plugin is wrong anyway: we needed it because we could not remotely call plugin API. Now that we can, we should refactor our plugins and prevent multiple copies of the same plugin.

**Comment by vinokurig** [comment] 2020-07-23 08:36
The `openshift-connector` plugin uses the `openshift-client` tool under the hood, so the login state is kept in the `config` of the `openshift-client` tool, not in the plugin state. I've added a volume mount to the `openshift-connector` plugin which will save the `config` of the `openshift-client` tool, so the the login session will be saved between workspace restarts.

**Closed as completed** 2020-07-23 13:03 UTC
Labels: status/analyzing, severity/P1, area/plugins
