### ISSUE TITLE
Customize Theia "Getting Started"

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#11790] opened 2018-10-31 10:08 UTC
### Description

When che-theia is loaded it currently has no file opened and no "Getting started" page is shown in the editor panel:

![image](https://user-images.githubusercontent.com/606959/47780991-eebc7e80-dcfc-11e8-902a-bb2d75e5e101.png)

We should show and customize the upstream "Theia Getting Started extension" (https://github.com/theia-ide/theia/pull/3149) with a Che logo.

**Comment by l0rd** [comment] 2018-10-31 10:08
cc @slemeur

**Comment by benoitf** [comment] 2018-10-31 10:14
it's kind of duplicate of https://github.com/theia-ide/theia/pull/3149

**Comment by l0rd** [comment] 2018-10-31 10:55
Thank you @benoitf I have changed the issue to customize it for Che then...

**Comment by l0rd** [comment] 2018-10-31 10:57
@slemeur for now the customization is as simple as "add a Che logo". Please add your input.

**Comment by slemeur** [comment] 2018-10-31 15:38
OK, adding the logo sounds enough for me in term of "branding". 

Other questions:
- What recent workspace will show in the context of Che? I think it should show the latest used workspaces. 
- I think the getting started should also have a "New..." section which allow the developer to quickly create a new file, a new project or import from github or a repository.
- I would also love that we remind all the keyboard shortcut that are associated with those actions.
- I think it's important to remind the user about how to get the command palette.

Also, by default, when we start a workspace (for the first time - ie not resuming from a previous state), it would be nice if we could unfold the "Files" panel and open the readme.md if it exist.

**Comment by gorkem** [comment] 2019-08-24 02:49
@slemeur I think this is done already but feel free to reopen if anything missing

**Closed as completed by gorkem** 2019-08-24 02:49 UTC
Labels: kind/enhancement
