### ISSUE TITLE
Docker image not updated in an existing workspace

### ISSUE THREAD

**Issue by dcdh** [eclipse-che/che#4667] opened 2017-04-02 22:06 UTC
Hello,

I'have created a workspace with a custom docker image for my dev machine. However I had to build and deploy in my registry a new latest one to fix an issue.

Now I need to update this image in my current workspace but I can't find a way to replace the current version in my workspace by this new one.

I have relaunched my workspace but it is not working. I have changed the value in my recipe by a *fake* one to force the update of the workspace but it was not loaded.

Is there a way to update the current docker image used in my workspace ?

**Reproduction Steps:**
Create a workspace;
Build and deploy a new version;
Relaunch the workspace.

**OS and version:**    Linux, 5.6.0 

**Diagnostics:** 
I guess docker images are not checked when the workspace is restarted. It also apply for the workspace recipe.

**Comment by TylerJewell** [comment] 2017-04-03 12:43
It is correct, and expected behavior, that Docker images are not rechecked
when restarting a workspace. Allowing a Docker image to be altered in
between workspace sessions would lead to immutable characteristics that
could cause unintended behaviors.

Your choices:
1. You can create a new envrionment (in the dashboard) for a single
workspace.  Each environment can have a different runtime.  So your new
environment could use the new image.  But please note that you need to
configure the system to force pull an image if it's using the same name.
Che will cache image names locally near the Docker daemon, and the default
behavior will not have it check a registry for a newer version if it is
using the same name and tag.  So it's preferred that you reference a
different tag or a digest, which is SHA256 unique.

2. You can create an entirely new workspace as well.

Please note that if you are using default behaviors, we snapshot the
workspace when it is stopped. This creates a new image orphaned from the
original image you used when starting the workspace.  When the workspace is
restarted, it is started from this orphaned image to guarantee consistency
from the previous run.  You can disable this behavior and ot always have a
starting workspace come from the originating image.


Tyler Jewell // CEO // tyler@​codenvy.​com // 978.884.5355

**Comment by bmicklea** [comment] 2017-04-10 14:03
Closing as resolved, if there are more questions please re-open.

**Closed as completed by bmicklea** 2017-04-10 14:03 UTC
Labels: kind/question
