### ISSUE TITLE
Investigate the session unexpectedly deleted when running selenium tests on CI job

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#7887] opened 2017-12-14 15:39 UTC
### Description
* When the test suite is running on the CI job, sometimes there is failing test  'GitCompareTest' by reason: **_"session deleted because of page crash"_** 
* Need to investigate it and fix up

**See the report:**
![page-crash](https://user-images.githubusercontent.com/5408906/33999896-71573bce-e0f4-11e7-91b2-2fa667d34ebe.png)

**Che version:** 6.0.0-M4
**OS and version:** Fedora 25
**Docker version:** 17.06
**API docker version:** 1.30
**Che install:** Docker container

**Additional information:**
* Related selenium test: _GitCompareTest_
* Problem can be reliably reproduced, doesn't happen randomly: [No]

**Update**: Similar error can be found here at [org.eclipse.che.selenium.git.PullRequestPluginTest.checkGitHubUserPage(PullRequestPluginTest.java:240)](https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/57/consoleText)

**Related issue:** https://github.com/eclipse/che/issues/8100

**Comment by dmytro-ndp** [comment] 2017-12-26 19:52
Similar error can be found here at at [org.eclipse.che.selenium.git.PullRequestPluginTest.checkGitHubUserPage(PullRequestPluginTest.java:240)](https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/57/consoleText)

**Comment by musienko-maxim** [comment] 2018-01-11 13:47
So, the problem can be reproduced not only on CI infrastructure. This can happen on host machine when we click on Open on github button of Pull Request widget. But in this case crashing tab happens some later. I try to capture exceptions from client (Browser) during crashing, after analyzing this info i suspect that reason of failing may be particular features  X- graphics in the docker container. Another things which indirectly indicates this - this problem is not reproduced with native browser.

**Additional info:**
Browser exceptions:
```vendor-73784b1bca.js:20280 GET http://172.30.3.7:8080/api/keycloak/settings 404 ()
send @ vendor-73784b1bca.js:20280
ajax @ vendor-73784b1bca.js:19816
Q.(anonymous function) @ vendor-73784b1bca.js:19961
(anonymous) @ app-076a571a2a.js:125
(anonymous) @ app-076a571a2a.js:124
c @ vendor-73784b1bca.js:14749
fireWith @ vendor-73784b1bca.js:14861
ready @ vendor-73784b1bca.js:15067
a @ vendor-73784b1bca.js:15083
app-076a571a2a.js:141 Keycloak initialization failed with error:  {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
(anonymous) @ app-076a571a2a.js:141
Promise rejected (async)
(anonymous) @ app-076a571a2a.js:127
c @ vendor-73784b1bca.js:14749
fireWith @ vendor-73784b1bca.js:14861
ready @ vendor-73784b1bca.js:15067
a @ vendor-73784b1bca.js:15083
vendor-73784b1bca.js:33381 You are using the ngTouch module.
Angular Material already has mobile click, tap, and swipe support...
ngTouch is not supported with Angular Material!
(anonymous) @ vendor-73784b1bca.js:33381
e @ vendor-73784b1bca.js:75483
i @ vendor-73784b1bca.js:25384
(anonymous) @ vendor-73784b1bca.js:25205
o @ vendor-73784b1bca.js:21201
et @ vendor-73784b1bca.js:25205
s @ vendor-73784b1bca.js:22537
u.test.Pr.resumeBootstrap @ vendor-73784b1bca.js:22566
(anonymous) @ app-076a571a2a.js:143
Promise resolved (async)
(anonymous) @ app-076a571a2a.js:142
c @ vendor-73784b1bca.js:14749
fireWith @ vendor-73784b1bca.js:14861
ready @ vendor-73784b1bca.js:15067
a @ vendor-73784b1bca.js:15083
5vendor-73784b1bca.js:33381 Markup '<md-button flex></md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details.
(anonymous) @ vendor-73784b1bca.js:33381
l @ vendor-73784b1bca.js:78813
compile @ vendor-73784b1bca.js:78683
U @ vendor-73784b1bca.js:28982
I @ vendor-73784b1bca.js:28515
I @ vendor-73784b1bca.js:28527
I @ vendor-73784b1bca.js:28527
I @ vendor-73784b1bca.js:28527
I @ vendor-73784b1bca.js:28527
I @ vendor-73784b1bca.js:28527
I @ vendor-73784b1bca.js:28527
I @ vendor-73784b1bca.js:28527
(anonymous) @ vendor-73784b1bca.js:29404
l @ vendor-73784b1bca.js:35653
(anonymous) @ vendor-73784b1bca.js:35669
$eval @ vendor-73784b1bca.js:36913
$digest @ vendor-73784b1bca.js:36731
$apply @ vendor-73784b1bca.js:37021
(anonymous) @ vendor-73784b1bca.js:22540
i @ vendor-73784b1bca.js:25384
s @ vendor-73784b1bca.js:22538
u.test.Pr.resumeBootstrap @ vendor-73784b1bca.js:22566
(anonymous) @ app-076a571a2a.js:143
Promise resolved (async)
(anonymous) @ app-076a571a2a.js:142
c @ vendor-73784b1bca.js:14749
fireWith @ vendor-73784b1bca.js:14861
ready @ vendor-73784b1bca.js:15067
a @ vendor-73784b1bca.js:15083 
```

**Comment by musienko-maxim** [comment] 2018-01-15 14:42
So the problem looks like small size of /dev/shm  (default value: 64 M) but after investigation - i clarified that test can use more than 100 MB. I try to add into compose shm_size: 1g (after that smm size will be 1Gb). In manual mode the problem was resolved. I think this should fix the problem. For approving this one - we should launch some full selenium cycles. If this won't reproduce - the solution will be correct.

**Comment by musienko-maxim** [comment] 2018-01-16 08:23
After full selenium cycle the test passed properly: https://ci.codenvycorp.com/view/qa-experimental/job/experimental-che-integration-tests-master-docker/62/Selenium_tests_report/. I think we can merge this changes and close the issues

**Closed as completed** 2018-01-16 10:16 UTC
Labels: kind/task, sprint/current, severity/P2, e2e-test/failure
