### ISSUE TITLE
[Language server] Unexpected exceptions in the dev-machine console after initialization LS for GO lang

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#9796] opened 2018-05-24 11:10 UTC
### Steps to reproduce:
1) Create a workspace with next configuration:
```json
{
  "defaultEnv": "default",
  "environments": {
    "default": {
      "machines": {
        "gols": {
          "attributes": {
            "memoryLimitBytes": "1073741824"
          },
          "servers": {
            "golsp": {
              "attributes": {
                "languageRegexes": "[ {\"languageId\":\"golang\", \"regex\":\".*\\\\.go$\"}]",
                "internal": "true",
                "id": "go-ls",
                "type": "ls"
              },
              "port": "5555",
              "protocol": "tcp"
            }
          },
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [
            "org.eclipse.che.terminal"
          ],
          "env": {
            "CHE_MACHINE_NAME": "gols"
          }
        },
        "dev-machine": {
          "attributes": {},
          "servers": {},
          "volumes": {},
          "installers": [
            "org.eclipse.che.exec",
            "org.eclipse.che.terminal",
            "org.eclipse.che.ws-agent"
          ],
          "env": {
            "CHE_MACHINE_NAME": "dev-machine"
          }
        }
      },
      "recipe": {
        "type": "compose",
        "content": "services:\n dev-machine:\n  image: eclipse/ubuntu_jdk8\n  mem_limit: 2147483648\n  depends_on:\n   - gols\n gols:\n  image: eivantsov/go-lang\n  mem_limit: 1073741824\n",
        "contentType": "application/x-yaml"
      }
    }
  },
  "name": "golang",
  "projects": [
    {
      "name": "web-go-simple",
      "attributes": {
        "contribute_to_branch": [
          "master"
        ]
      },
      "links": [],
      "type": "blank",
      "source": {
        "location": "https://github.com/che-samples/web-go-simple",
        "type": "git",
        "parameters": {}
      },
      "path": "/web-go-simple",
      "description": "",
      "problems": [],
      "mixins": [
        "pullrequest"
      ]
    }
  ],
  "commands": [],
  "links": []
}
```
2) After workspace creation, open the `main.go file`, open `dev-machine` console. 
------
**Expected result:** The LS should start without errors
**Actual result:**  There are exceptions like:
![selection_001](https://user-images.githubusercontent.com/1640058/40482003-e68fa148-5f5b-11e8-9add-8cb9160e5c25.png)
**OS and version:**   Fedora 28, Chrome browser, 66.0.3, CHE on docker infra., ver. 6.6.0 SNAPSHOT, rev. 6c0f87c29aa0c433

**Comment by tsmaeder** [comment] 2018-05-28 10:26
Note that this is in all likelihood a bug in the go language server. Dynamic registration is opt-in, the LS has to check client capablilites and not assume dynamic capabilities are implemented.

**Comment by dkuleshov** [comment] 2018-05-29 13:07
As @tsmaeder mentioned in another discussion it might be quite possible that https://github.com/eclipse/che/issues/9781 is caused by this bug.

**Comment by dkuleshov** [comment] 2018-06-04 13:19
> As @tsmaeder mentioned in another discussion it might be quite possible that #9781 is caused by this bug.

False assumption.

**Comment by musienko-maxim** [comment] 2018-06-19 07:38
After fixing the go LS worked properly. But currently the LS with configuration that is described above the LS is not initialized. Also we have problem with Ls  that is launched under installer. In this case, exceptions in the dev-machine console still actual.

**Comment by vparfonov** [comment] 2018-09-12 06:28
need to check after merging jdt.ls branch and updating lsp4j

**Comment by SkorikSergey** [comment] 2019-07-04 13:11
Not relevant anymore. Closing.

**Closed as completed by SkorikSergey** 2019-07-04 13:11 UTC
Labels: kind/bug, severity/P2
