### ISSUE TITLE
Nit: lag when filtering plugins by name means characters are ignored

### ISSUE THREAD

**Issue by sympatheticmoose** [eclipse-che/che#18745] opened 2021-01-06 14:01 UTC
### Describe the bug
If you type relatively quickly in the filter for plugins, some input is ignored - in particular the first character. Not suggesting an urgent issue, but a UX papercut that would be nice to resolve.

### Che version
CRW 2.5.1 / Che-Theia@aa4f001 using Theia@eb1136b11

### Steps to reproduce

1. Create any workspace
2. Open the plugins view (cmd + shift + j)
3. Type a value such as openshift quickly

### Screenshots

https://user-images.githubusercontent.com/19860021/103776313-2931ac80-5027-11eb-93c0-45fd7cd2ff3b.mov

**Comment by ericwill** [comment] 2021-01-06 14:05
Looks like a duplicate of #17196

**Closed as completed** 2021-01-06 14:14 UTC
Labels: kind/bug, status/duplicate
