### ISSUE TITLE
che plugins view should have proper icons for each plugins/extensions

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13693] opened 2019-06-05 09:08 UTC
### Description
At the moment all the plugins are shown with the eclipse che logo. We have to make the right changes (registry or picking from vscode marketplace) to display the right icons
![Selection_275](https://user-images.githubusercontent.com/650571/58944494-3e2ac780-8782-11e9-91b2-f9bed10f8c46.png)

**Comment by vitaliy-guliy** [comment] 2019-10-11 09:19
There is a proposal pull request to plugin registry with icons for each plugin https://github.com/eclipse/che-plugin-registry/pull/221
But it's only first a step and have to be finished.

**Comment by nickboldt** [comment] 2020-01-29 13:54
Closing dupe of https://github.com/eclipse/che/issues/14510

**Closed as completed by nickboldt** 2020-01-29 13:54 UTC
Labels: kind/enhancement, area/editor/theia
