### ISSUE TITLE
che.openshift.io account in broken state

### ISSUE THREAD

**Issue by dneary** [eclipse-che/che#15885] opened 2020-01-30 22:38 UTC
When trying to connect to che.openshift.io, I am directed to (re)activate my account. My che.openshift.io account lapsed and was apparently cleaned up a couple of months ago.

Since then, every time I connect to che.openshift.io, I am redirected to https://sso.redhat.com/auth/realms/redhat-external/broker/rhd-sso/endpoint and when I connect with my username and password, I get to an openshift.io console (screenshot below) with an error message "There was an error processing request for access. Please try again by visiting: <a href='https://manage.openshift.com/openshiftio'>https://manage.openshift.com/openshiftio</a>. Contact us if you continue to see the issue." The Che loading screen displays the message "Creating your OpenShift account" for several minutes, then shows an error 401.

My guess is that my account has been left in some kind of intermediate state, and  I cannot reactivate it because some namespace, volume, or other resource still exists.

![Screenshot from 2020-01-30 17-38-14](https://user-images.githubusercontent.com/467525/73496771-54c40580-4387-11ea-98bc-54b9e225eea3.png)

![Screenshot from 2020-01-30 17-38-07](https://user-images.githubusercontent.com/467525/73496786-5beb1380-4387-11ea-9a08-0984ab289d6a.png)

**Comment by alexeykazakov** [comment] 2020-02-13 18:12
@dneary I see two users in the same email in manage.openshift.com
It often causes issues with logging. Try to login with your username instead of email. It should help.

**Comment by ibuziuk** [comment] 2020-02-17 09:55
@dneary could you please give it a go? @alexeykazakov I believe we need a known issue section in our FAQ if this type of problem is the expected one

**Comment by dneary** [comment] 2020-02-27 20:13
Just back from PTO. How can I find out my username? I am asked for my Red Hat username or email address to log in.

**Comment by alexeykazakov** [comment] 2020-02-27 20:20
Try to login using `dneary` as your username.

**Comment by ibuziuk** [comment] 2020-03-03 17:44
@dneary any news?

**Comment by ibuziuk** [comment] 2020-06-23 08:13
@dneary closing feel free to reopen

**Comment by dneary** [comment] 2020-07-22 21:11
Sorry @ibuziuk I neglected to come back to this.

Yes, I still have the problem. I would like to take off and nuke it from orbit, if that works. I don't know how to log in with just username, I get taken to the SSO page for Red Hat Developer automatically.

**Comment by dneary** [comment] 2020-07-22 21:55
With some assistance, I verified that with my username dneary and the same password, my account was correctly provisioned. However, when I log in with dneary@redhat.com, it is still broken. Is it possible to delete/merge the two dneary@redhat.com accounts to fix the issue permanently? Thanks!

**Comment by ibuziuk** [comment] 2020-07-23 05:47
> However, when I log in with dneary@redhat.com, it is still broken. Is it possible to delete/merge the two dneary@redhat.com accounts to fix the issue permanently? Thanks!

@alexeykazakov any recommendations? this issue with multiple accounts for red hatters is a pretty common problem (@benoitf had the same situation). The common solution is just to use the username for login and the leave the second account will be in a broken state permanently?

**Comment by benoitf** [comment] 2020-07-23 05:52
one issue with login with username instead of email address is that browsing other websites (like issues.redhat.com, etc) is failing as I'm not seen anymore as red hat employee then I'm missing issues. So I need to always login/logout

**Comment by alexeykazakov** [comment] 2020-07-24 02:57
@dneary can you try to login using your email again?

**Comment by alexeykazakov** [comment] 2020-07-24 03:02
@benoitf and you too please?

**Comment by benoitf** [comment] 2020-07-24 07:28
@alexeykazakov I tried with email address login but it's still failing

![login](https://user-images.githubusercontent.com/436777/88369276-f30db280-cd8f-11ea-9236-53388783f5d7.gif)

**Comment by dneary** [comment] 2020-07-26 22:44
Works for me now! Thank you.

**Comment by sunix** [comment] 2020-07-27 07:59
hello @alexeykazakov 
I also have sutan-1 working but not sutan@redhat.com ...
Do we have a procedure if that kind of issue happens with other people? or should that be creating and commenting this gh issue?

**Comment by ibuziuk** [comment] 2020-07-27 13:53
we discussed with Alexey that we do need a section in the FAQ / Troubleshooting
 https://www.eclipse.org/che/docs/che-7/hosted-che/#troubleshooting

**Comment by ibuziuk** [comment] 2020-07-30 09:23
@alexeykazakov had a chat with @benoitf today and he claimed that the issue is resolved for his account. Could you please send the Troubleshooting instructions to https://www.eclipse.org/che/docs/che-7/hosted-che/#troubleshooting / https://github.com/eclipse/che-docs and I believe we can close the issue

**Comment by ibuziuk** [comment] 2020-07-30 16:07
@alexeykazakov than lets at very add this as the Known Issue section

**Comment by dneary** [comment] 2020-07-30 19:09
Can I close this issue, or do you want to leave it open until you document that?

**Comment by ibuziuk** [comment] 2020-08-04 09:27
@dneary yeah, let's close once it is documented as a known issue

**Comment by ibuziuk** [comment] 2020-09-11 12:55
@alexeykazakov will appreciate if you can follow up on this issue and provide the valid instructions to the Known Issues section - ] https://github.com/eclipse/che-docs/blob/master/src/main/pages/che-7/overview/ref_hosted-che-faq-and-troubleshooting.adoc#frequently-asked-questions-faqs-and-troubleshooting

**Comment by robstryker** [comment] 2020-10-13 12:35
I am experiencing this issue. Logging in with rstryker@redhat.com provides the error workflow listed above. However, logging in with just "rstryker" does not work. I am not sure the user exists. I executed a password reset but didn't receive an email anywhere.

**Comment by ibuziuk** [comment] 2020-10-13 13:38
@alexeykazakov could you please take a look ^

**Comment by mistapotta** [comment] 2020-12-10 23:27
@alexeykazakov can you please look into my account?  Username mistapotta, Email mistapotta@gmail.com. I too am having the issue logging in.  Thank you!

**Comment by ibuziuk** [comment] 2021-03-11 12:06
Closing since che.openshift.io has been shut down in favor of workspaces.openshift.com
More details about the new service can be found in the official documentation - https://www.eclipse.org/che/docs/che-7/hosted-che/hosted-che/

**Closed as completed by ibuziuk** 2021-03-11 12:06 UTC
Labels: kind/bug, status/analyzing, severity/P1, area/hosted-che
