### ISSUE TITLE
Sometimes, after performing commands in the terminal, notifications don't appear 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#15761] opened 2020-01-21 09:56 UTC
### Describe the bug
From time to time we can see that after performing commands in the terminal notifications with status of these commands don't appear.
We detected this problem by automated tests and for now, can't share any additional information. We will add it as quickly as possible.

### Che version

 - [ ] latest
 - [ x ] nightly
 - [ ] other: please specify

### Steps to reproduce

- Create workspace from the "Cpp" stack with default project.
- Go to the workspace and launch predefined "build" command
- Pay attention that sometimes the "Task build has exited with code 0." notification doesn't appear

 
### Expected behavior
The "Task build has exited with code 0." notification appears after all launches

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by l0rd** [comment] 2020-01-21 21:32
closing this issue as duplicate of #15769  because #15769 has more info

**Closed as completed by l0rd** 2020-01-21 21:32 UTC
Labels: kind/bug
