### ISSUE TITLE
[area/doc] Navigation bar cannot be scrolled

### ISSUE THREAD

**Issue by zeibura** [eclipse-che/che#14568] opened 2019-09-17 08:30 UTC
### Describe the bug
The navigation bar on https://www.eclipse.org/che/docs/che-7/ falls off the bottom of the screen as soon as any part of it is expanded and cannot be scrolled down.

### Che version
Doc version 7

### Steps to reproduce
1. Open Che v7 doc (https://www.eclipse.org/che/docs/che-7/introduction-to-eclipse-che/)
2. Expand any item on the navigation bar
3. Observe result - navigation bar falls off the bottom of the screen and cannot be scrolled down by any means (dragging or scrolling)

### Expected behavior
Navigation bar can be scrolled down

### Runtime
n/a
### Screenshots
n/a
### Installation method
n/a

### Environment
Win7 64bit
Same result observed on Firefox, Chrome and Internet Explorer

### Additional context
n/a

**Comment by l0rd** [comment] 2019-09-17 19:33
@rkratky @themr0c do you think that we may be able to fix this?

**Comment by themr0c** [comment] 2019-09-18 08:48
That's a duplicate of https://github.com/eclipse/che/issues/14294. We are aware of that issue, but current priority for our team is set on creating new content. I'll try to have a look hopefully soon.

**Comment by zeibura** [comment] 2019-09-18 11:14
If this is going to take time to fix, then I would propose a workaround where we would add links to the other Che4z pages to the Release Information page (which is currently the only one that can be opened from the navbar). Does that sound okay?

**Comment by rkratky** [comment] 2019-09-18 16:02
I'm aware of the problem. I don't have a short-term fix ready -- we need to fix the website theme.

**Comment by themr0c** [comment] 2019-09-19 08:19
I am closing this issue to keep only https://github.com/eclipse/che/issues/14294 open.

**Closed as completed by themr0c** 2019-09-19 08:19 UTC
Labels: kind/enhancement, severity/P2
