### ISSUE TITLE
ssh: delete key pair not working

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#14332] opened 2019-08-25 10:58 UTC
### Describe the bug

When creating a new workspace with git projects added, they don't get cloned upon workspace creation:
```
Looking for git in: git
Using git 2.20.1 from git
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
trying to delete a key that was generated, it's not working
```
>ssh: delete key pair
```
Deleted it manually via k8s secretes and tried to generate a new one but i can't anymore
### Che version

 - [ ] latest
 - [ ] nightly
 - [X] other: please specify
```
Che-Theia@e358e2f using Theia@e358e2f
Built 8/14/2019, 7:53:02 AM
List of extensions:
@theia/core 0.8.0
@theia/output 0.8.0
@theia/process 0.8.0
@theia/filesystem 0.8.0
@theia/variable-resolver 0.8.0
@theia/workspace 0.8.0
@theia/languages 0.8.0
@theia/editor 0.8.0
@theia/callhierarchy 0.8.0
@theia/console 0.8.0
@theia/json 0.8.0
@theia/userstorage 0.8.0
@theia/preferences 0.8.0
@theia/navigator 0.8.0
@theia/markers 0.8.0
@theia/terminal 0.8.0
@theia/task 0.8.0
@theia/cpp 0.8.0
@theia/debug 0.8.0
@theia/debug-nodejs 0.8.0
@theia/editorconfig 0.8.0
@theia/file-search 0.8.0
@theia/keymaps 0.8.0
@theia/merge-conflicts 0.8.0
@theia/messages 0.8.0
@theia/mini-browser 0.8.0
@theia/outline-view 0.8.0
@theia/scm 0.8.0
@theia/search-in-workspace 0.8.0
@theia/plugin-ext 0.8.0
@theia/plugin-dev 0.8.0
@theia/plugin-ext-vscode 0.8.0
@theia/preview 0.8.0
@theia/textmate-grammars 0.8.0
@eclipse-che/theia-remote 0.0.1
@eclipse-che/theia-plugin-ext 0.0.1
@eclipse-che/theia-terminal 0.0.1
@eclipse-che/theia-user-preferences-synchronizer 0.0.1
@eclipse-che/che-theia-hosted-plugin-manager-extension 0.0.1
@eclipse-che/theia-dashboard-extension 0.0.1
@eclipse-che/theia-activity-tracker 1.0.0
@eclipse-che/theia-about 0.0.1
@eclipse-che/theia-preferences-provider-extension 0.0.1
```

### Steps to reproduce

A newly deployed che environment today
followed the steps of https://www.eclipse.org/che/docs/che-7/version-control/
>ssh: delete key pair (nothing happens clicking it)

### Runtime
   - [X] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-21T15:34:43Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T17:06:39Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}
```

### Installation method
   - [X] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know
```
chectl/7.0.0 linux-x64 node-v10.16.2
```

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [X] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [X] other (please specify) 
   - [ ] other: please specify

Private cloud

**Comment by SDAdham** [comment] 2019-08-25 12:29
I tried both methods, generating ssh key for all hosts and particular host, and nothing works, always get:
```
Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

**Comment by gorkem** [comment] 2019-08-25 14:44
I think it is because of the known_hosts is not updated by the IDE. Can you do the initial git clone from the command line and see if git works afterwards ?

**Comment by SDAdham** [comment] 2019-08-25 15:37
Yes, i did try that, same problem

**Comment by SDAdham** [comment] 2019-08-25 15:38
Is ssh delete key generally works? Or is it buggy?

**Comment by gorkem** [comment] 2019-08-25 16:50
Delete has worked for me but you may want to restart your workspace after adding/removing ssh keys. Che keeps SSH keys as k8s secrets and mounts them to the proper path so path to the key will not be removed until the restart.

**Comment by ibuziuk** [comment] 2019-08-26 08:14
@vinokurig could you please confirm that restart is required for deleting ssh? should we add a similar warning as we currently have for ssh key generation (e.g. ssh keys will be removed after workspace restart)?

**Comment by SDAdham** [comment] 2019-08-26 08:54
Restart doesnt fix anything, infact clicking delete ssh key doesnt do anything as well

**Comment by gorkem** [comment] 2019-08-26 13:17
@vparfonov can you check if this is a regression?

**Comment by ibuziuk** [comment] 2019-08-26 17:34
Vitalli is on PTO, @azatsarynnyy could you please take a look?

**Comment by azatsarynnyy** [comment] 2019-08-28 08:40
I believe the issue is caused by the missing entry for a remote host in `known_hosts` file.
@SDAdham could you please try the following steps, with ssh key pair already generated:
- open a terminal into `theia-ide` container
- update the `known_hosts` with the following command:
`ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts`
- try to clone a repo again

Make sure that `github.com` in the command is replaced with the required host if needed.

**Comment by gorkem** [comment] 2019-08-30 02:42
@azatsarynnyy All the calls to delete/view ssh keys are failing at the moment. Here is what I see from the logs 

```
root ERROR Request getAllSshKey failed with error: Request failed with status code 403 
root ERROR [hosted-plugin: 44] Promise rejection not handled in one second: Error: Request getAllSshKey failed with message: Request failed with status code 403
root ERROR [hosted-plugin: 44] With stack trace: Error: Request 'getAllSshKey' failed
    at Proxy.<anonymous> (https://static.developers.redhat.com/che/theia_artifacts/theia.fb4ce1ef4bb91a367691.js:1:1787832)
    at e.<anonymous> (https://static.developers.redhat.com/che/theia_artifacts/theia.fb4ce1ef4bb91a367691.js:1:2947499)
    at https://static.developers.redhat.com/che/theia_artifacts/theia.fb4ce1ef4bb91a367691.js:1:2946670
    at Object.next (https://static.developers.redhat.com/che/theia_artifacts/theia.fb4ce1ef4bb91a367691.js:1:2946775)
    at https://static.developers.redhat.com/che/theia_artifacts/theia.fb4ce1ef4bb91a367691.js:1:2945688
    at new Promise (<anonymous>)
    at r (https://static.developers.redhat.com/che/theia_artifacts/theia.fb4ce1ef4bb91a367691.js:1:2945465)
    at e.$getAll (https://static.developers.redhat.com/che/theia_artifacts/theia.fb4ce1ef4bb91a367691.js:1:2947413)
    at e.doInvokeHandler (https://static.developers.redhat.com/che/theia_artifacts/theia.fb4ce1ef4bb91a367691.js:1:827569)
    at e.invokeHandler (https://static.developers.redhat.com/che/theia_artifacts/theia.fb4ce1ef4bb91a367691.js:1:827297)
```

**Comment by gorkem** [comment] 2019-08-30 02:43
I am elevating the severity of the issue.

**Comment by SDAdham** [comment] 2019-08-30 03:45
@azatsarynnyy I'll try your suggestion soon, I am deploying a new environment now

**Comment by azatsarynnyy** [comment] 2019-08-30 21:52
Some notes after investigating an issue of deleting a key pair.

Looks odd that request for generating a key pair is always successful but fetching a key is failed.
WebSocket messages from browser's console:
```
{"kind":"data","id":14,"content":"{\"jsonrpc\":\"2.0\",\"id\":11,\"method\":\"getAllSshKey\",\"params\":\"vcs\"}"}

{"kind":"data","id":14,"content":"{\"jsonrpc\":\"2.0\",\"id\":11,\"error\":{\"code\":-32603,\"message\":\"Request getAllSshKey failed with message: Request failed with status code 403\"}}"}

```
`SSH: delete key pair...` and `SSH: view public key...` commands rely on the `getAllSshKey` API call which is the reason for failing these commands.

Note, not reproducible on minikube but on hosted Che only.

**Comment by ibuziuk** [comment] 2019-09-05 11:02
@azatsarynnyy according to the issue reporter the issue was reproduced on k8s environment. Why do you think it is Hosted Che specific?

**Comment by azatsarynnyy** [comment] 2019-09-05 14:00
@ibuziuk I mean that I cannot reproduce the issue of deleting key pair in Che running on minikube but it's reproducible on che.openshift.io

BTW, the keys verification issue should be fixed by the PR https://github.com/eclipse/che/pull/14418

**Comment by ibuziuk** [comment] 2019-09-05 14:02
@azatsarynnyy but che.openshift.io is still RC 1.1 - I'm not sure it is fair to compare it with master ;-)

**Comment by gorkem** [comment] 2019-09-11 23:52
This is not hosted Che specific. I think this is an issue on any multi-user Che installation but for me it is reproducible on every Openshift 4.x cluster.

**Closed as completed** 2019-09-16 08:20 UTC
Labels: kind/bug, status/in-progress, severity/P1

**Comment by SDAdham** [comment] 2019-09-17 09:43
@vinokurig : is this issue fixed? And do you know when I can get the fix?

**Comment by vinokurig** [comment] 2019-09-17 09:47
@SDAdham It is fixed, It must be applied in the `eclipse/che-server:nightly` docker image

**Comment by SDAdham** [comment] 2019-09-17 10:08
@vinokurig : the image of my che's container is `eclipse/che-server:7.1.0` but for my development pods
```
quay.io/eclipse/che-php-7:nightly
docker.io/eclipse/che-machine-exec:7.1.0
docker.io/eclipse/che-theia:7.1.0
docker.io/eclipse/che-remote-plugin-php7:7.1.0
docker.io/eclipse/che-remote-plugin-php7:7.1.0
```
None of them could get this fix any sooner, right?

**Comment by vinokurig** [comment] 2019-09-17 10:17
Unfortunately no
